### PR TITLE
rkt: update to 1.1.0.

### PR DESCRIPTION
**Pull request by thypon**
can't build: libressl bug.

### CODE REVIEW

**Comment by ebfe** [comment]
CMS disabled.  https://www.mail-archive.com/tech@openbsd.org/msg19675.html

**Comment by ebfe** [comment]
A patch like this

```diff
--- a/scripts/sign-file.c
+++ b/scripts/sign-file.c
@@ -39,7 +39,7 @@
  * signing with anything other than SHA1 - so we're stuck with that if such is
  * the case.
  */
-#if OPENSSL_VERSION_NUMBER < 0x10000000L
+#if (OPENSSL_VERSION_NUMBER < 0x10000000L || LIBRESSL_VERSION_NUMBER)
 #define USE_PKCS7
 #endif
 #ifndef USE_PKCS7
```

might work if we can sneak it into the build process.

**Comment by thypon** [comment]
I don't get why this bug isn't present in our linux kernels?

**Comment by ebfe** [comment]
> I don't get why this bug isn't present in our linux kernels?
Because CONFIG_MODULE_SIG is not set in the config.

**Pull request closed without merging**
