### PR TITLE
frp: update to 0.16.1.

### PR DESCRIPTION
**Pull request by cr6git**

### CODE REVIEW

**Comment by cr6git** [comment]
[69e2e0d](https://github.com/voidlinux/void-packages/commit/69e2e0d3a3a238c72fcf4933e9b68a57f27108ba)

**Comment by ebfe** [comment]
Why close? That was a revbump not an update

**Comment by cr6git** [comment]
@ebfe Damn! :hushed: I could've sworn that you updated it... well, sometimes I feel like my eyes are not functioning properly. :confounded:

**Comment by cr6git** [comment]
Could you make the change? I don't want to bother you opening a new PR just for that...

**Comment by ebfe** [comment]
Please make a new PR.

**Pull request closed without merging**
