### PR TITLE
New package: create_ap-0.4.3

### PR DESCRIPTION
**Pull request by drkhsh**

### CODE REVIEW

**Comment by xtraeme** [comment]
This is just a script... is there a need for a pkg? you can download, extract this into ~ and exec it.

**Comment by drkhsh** [comment]
@xtraeme yeah, i would really like it :smile: i mean, there are many programs written in shell?

**Comment by Vaelatern** [comment]
Very few in the repositories, but normally because shell is so portable it almost belongs in dotfiles.

**Comment by drkhsh** [comment]
@Vaelatern nevertheless, I think it would fit as package

**Comment by Vaelatern** [comment]
To repeat what @xtraeme asked, why should it be a package beyond "it can be"?

**Comment by drkhsh** [comment]
@Vaelatern it is packaged in a lot of distros and it is "cleaner" as package

**Comment by drkhsh** [comment]
So will this be merged or should I close the PR?

**Comment by Vaelatern** [comment]
I don't think this will be merged. It isn't in many official distro repositories. The final call is for @xtraeme to make, but if not in 2 days then it's a no.

**Comment by drkhsh** [comment]
@Vaelatern OK. It is in the official Arch repos.

**Comment by Vaelatern** [comment]
Yes, it is in their Community repo (not the AUR, the more maintained one).

**Comment by chneukirchen** [comment]
It could be useful in hrmpf, so :+1: from me.

**Comment by drkhsh** [comment]
I think that this won't be merged, so i will close it. 😞

**Comment by Vaelatern** [comment]
@chneukirchen You could just do the download in hrmpf's creation, I suppose...

**Pull request closed without merging**
