### PR TITLE
New package: git-annex-5.20150113_1

### PR DESCRIPTION
**Pull request by oholiab**
This has got the tahoe-lafs special remote missing but it has pretty much all the other functionality and I've been using it for a week or so with no problems at all.

### CODE REVIEW

**Comment by chneukirchen** [comment]
I think it would be better to use a sandbox to build, look into the pandoc template.

**Comment by oholiab** [comment]
Okay, I'll give it a go :) I know next to nothing about the haskell ecosystem so would you mind if I hit you up for help if I get stuck?

**Comment by oholiab** [comment]
Couple of things definitely need doing here then (after chats on IRC):
1. It doesn't need bind as a dep, just bind-utils. Misunderstanding on my part.
2. While I'm at it I'll talk to the author to try and get some more ideas of where I can trade out for more lightweight dependencies
3. Do the build in a cabal sandbox

**Comment by xtraeme** [comment]
Stalled for a month... feel free to resubmit it, thanks.

**Pull request closed without merging**
