### PR TITLE
New package: asl-1.41r8

### PR DESCRIPTION
**Pull request by allan**

### CODE REVIEW

**Comment by allan** [comment]
gah, doesn't work anymore...  will fix later.  please don't merge yet.

**Comment by Vaelatern** [comment]
Can you trigger a travis build with a rebase?

**Comment by the-maldridge** [comment]
This does not build.  As I do not read German, I am not troubleshooting further.

https://travis-ci.org/the-maldridge/void-packages/builds/246410534

**Comment by allan** [comment]
nobody will ever need this package including me.

**Pull request closed without merging**
