### PR TITLE
Cron alternatives

### PR DESCRIPTION
**Pull request by Vaelatern**
@xtraeme but note that all but `fcron` can't be installed at the same time at present.

### CODE REVIEW

**Comment by ebfe** [comment]
This might be a good opportunity to fix the file clashes between all the crons.

    cronie and dcron conflict for
    /usr/bin/crond
    /usr/bin/crontab
    /usr/share/man/man1/crontab.1
    /usr/share/man/man8/crond.8
   
    cronie and scron conflict for
    /etc/crontab
    /usr/bin/crond
    
    dcron and scron conflict for
    /usr/bin/crond

Alternatives for /etc/sv doesn't make a lot of sense if the packages overwrite their binaries.

**Comment by Vaelatern** [comment]
I agree fully. I'll make the changes in separate commits to easily drop if xtraeme doesn't like them, to be squashed before comitting.

**Comment by Vaelatern** [comment]
Not sure what to do about `/etc/crontab`

**Comment by chneukirchen** [comment]
Leave `/etc/crontab` for the users to create.

**Comment by Vaelatern** [comment]
Saying remove it in both packages that have it. Okay.

**Comment by Vaelatern** [comment]
Action taken. Alternatives group should be fully implemented. Should only be one commit per template, unless it's important to show these changes.

**Comment by Vaelatern** [comment]
@xtraeme @chneukirchen ready for review.

**Comment by xtraeme** [comment]
The `replaces` var needs to be removed.

**Comment by Vaelatern** [comment]
Commits added.

**Comment by Vaelatern** [comment]
@xtraeme Ready again for review.

**Comment by xtraeme** [comment]
@Vaelatern looks good, thanks :+1:

**Pull request closed without merging**
