### PR TITLE
[NOMERGE] go: update to 1.10

### PR DESCRIPTION
**Pull request by abenson**

### CODE REVIEW

**Comment by the-maldridge** [comment]
NOMERGE until I've had a chance to confirm this isn't going to break our monitoring.

**Comment by Vaelatern** [comment]
and nomerge until all go pkgs are revbumped for this.

**Comment by ebfe** [comment]
-1, ships useless cache files as is

**Comment by chneukirchen** [comment]
Is setting GOCACHE good enough?

**Comment by abenson** [comment]
It disables building the cache, that was the instruction from my research
on it

On Feb 23, 2018 09:12, "Leаh Neukirchen" <notifications@github.com> wrote:

Is setting GOCACHE good enough?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/voidlinux/void-packages/pull/11818#issuecomment-368018213>,
or mute the thread

**Comment by abenson** [comment]
Nevermind Only for that build, i think it'll need to be applied to all, so
maybe a change to the go build style?

Sorry, I'm in meetings all day

**Comment by abenson** [comment]
Nevermind, it doesn't seem to include cache in the built packages

--
AndrewB
Knowing is Half the Battle.

**Comment by ebfe** [comment]
Just from the commit count: you are missing some revbumps.

**Comment by ebfe** [comment]
You didn't check these actually build? At least kubernetes seems broken.

**Comment by abenson** [comment]
I didn't mean to push at that time, I'm still fixing the ones that didn't build.

**Comment by ebfe** [comment]
Please use the upstream fix for kubernetes fc37221db5d08eb9553273ad6202a2557cfde131, otherwise +1

**Comment by abenson** [comment]
Used the upstream patch for Kubernetes. 

Also tested the packages that had been updated

**Comment by ebfe** [comment]
ping @the-maldridge

**Comment by the-maldridge** [comment]
LGTM

**Comment by ebfe** [comment]
c965885b6dc7087722b1c28d67e401bbc96914c1

**Pull request closed without merging**
