### PR TITLE
pam: fix i686 build + cross

### PR DESCRIPTION
**Pull request by pullmoll**
Builds with binary-bootstrap i686 again. It failed when I tried to build it locally in a `./xbps-src binary-bootstrap i686` environment.

### CODE REVIEW

**Comment by pullmoll** [comment]
Hmm.. I'll look into fixing cross as well.

**Comment by pullmoll** [comment]
This may be too much hackery for @xtraeme 's taste. Perhaps some of you have a better fix using exsting `$XBPS_...` variables?

**Comment by xtraeme** [comment]
I'm not sure about these changes... can you provide a build log?

**Comment by pullmoll** [comment]
I guess you need a build log with failing for i686. I'll create one - brb.

**Comment by pullmoll** [comment]
Here is [a build log](http://sprunge.us/fgaO). It fails when trying to link `padout`.

**Comment by pullmoll** [comment]
Ouch! Sorry, this patch is probably not necessary.
I tried without ccache and distcc and now it built correctly

**Comment by pullmoll** [comment]
Works after disabling ccache + distcc thus closing.

**Pull request closed without merging**
