### PR TITLE
New package: python-stormssh-0.6.9

### PR DESCRIPTION
**Pull request by diogoleal**

### CODE REVIEW

**Comment by asergi** [comment]
`stormssh` is Python 3 compatibile. See `python-Babel` as example.

**Comment by diogoleal** [comment]
@asergi, I made the changes you suggested.

**Comment by asergi** [comment]
Please apply this: https://gist.github.com/asergi/bba8591dbb06fac8174836a078112dac

**Comment by diogoleal** [comment]
Changed!

**Pull request merged**
