### PR TITLE
New Package: Processing-2.2.1

### PR DESCRIPTION
**Pull request by diogoleal**
For Issue #985 Package Request: processing #985

### CODE REVIEW

**Comment by beefcurtains** [comment]
Why is this downloading binaries for a GPL'ed program?

**Comment by diogoleal** [comment]
Why processing is developed in Java and after your question, I finding how other distros 
created processing packages and  I see that most use the binary in java. 

But I can compile the processing, if you prefer.

**Comment by xtraeme** [comment]
@diogoleal please add only the relevant commits for this package, create a branch and then push from that branch.

Cheers :+1:

**Comment by xtraeme** [comment]
@diogoleal Please also follow the commit rules explained in CONTRIBUTING.md.

Thanks

**Comment by xtraeme** [comment]
font-hanozono? wtf

**Comment by diogoleal** [comment]
Sorry, it went along with the commit.
I'll close this pull request and fix the problem in the build.

**Pull request closed without merging**
