### PR TITLE
linux4.5: enable CAN subsystem on x86_64/i386 

### PR DESCRIPTION
**Pull request by floGik**
The Controller Area Network subsystem is heavily used in automotive applications. Having these modules readily available to modprobe after a clean install is a clear advantage for automotive software developers. Debian, for example, has them. Build is successful on x86_64 without user interaction, i386 contains the same changes so should build as well. ARM doesn't need these changes as the upstream ARM kernel configs already contain most of the CAN subsystem by default.

### CODE REVIEW

**Comment by Vaelatern** [comment]
I'd recommend a shorter commit message... `e` works and is within the git standard of about 50 characters for a commit message (looks a little prettier on tools for dealing with git).

**Comment by floGik** [comment]
@Vaelatern thanks for the hint, changed it accordingly. :)

**Comment by xtraeme** [comment]
- revision must be bumped

**Comment by Vaelatern** [comment]
Also, commit message, not title of PR ;) `git commit --amend`

**Comment by floGik** [comment]
@xtraeme can you give me a hint on what i have to do here? i haven't done this before and `xbump` tells me everything is up to date. 

@Vaelatern okay, changed the commit message :) sorry i'm so new

**Comment by Vaelatern** [comment]
@floGik `xrevbump linux4.5`

**Comment by floGik** [comment]
@Vaelatern thank you so much. Did that.

**Comment by Vaelatern** [comment]
Rebase on top of master, 1 commit containing all the changes.

**Comment by floGik** [comment]
@Vaelatern the latest commit now contains the changes and the revbump. i hope i'm getting closer.

**Comment by Vaelatern** [comment]
I would recommend running the command `git rebase --interactive HEAD~6` and then, after "squashing" all of your commits down to one commit, (there will be some sort of instructions), running `git rebase upstream/master` (I am assuming that when you run `git remote -v` it shows void-packages as `upstream`, if not, change the `upstream` in that command to refer to void-packages) and force pushing that to this branch.

All told you want exactly 1 commit in this PR, with the totality of the changes within it.

**Comment by floGik** [comment]
@Vaelatern updated, all changes are one commit now. Sorry I'm generating so much work.

**Pull request merged**
