### PR TITLE
eclipse-ecj: provide architecture dependant binaries.

### PR DESCRIPTION
**Pull request by Gottox**

### CODE REVIEW

**Comment by Vaelatern** [comment]
What is the state of this PR?

**Comment by Gottox** [comment]
We need a gcj on musl to make this work.

**Comment by pullmoll** [comment]
With gcc6 we now have gcj for musl. Curious to see if it actually works.

**Comment by the-maldridge** [comment]
@Gottox is this a PR you are interested in actually rebasing and merging, it currently wins the "oldest open PR" award.

**Comment by Gottox** [comment]
as gcj will go away in future gcc releases this is obsolete.

**Pull request closed without merging**
