### PR TITLE
gcc: gcc-go conflicts with go

### PR DESCRIPTION
**Pull request by ebfe**
$ xbps-query -o /usr/bin/go
    gcc-6.2.1_2: /usr/bin/go (regular file)
    go-1.7.3_1: /usr/bin/go (regular file)

### CODE REVIEW

**Comment by chneukirchen** [comment]
Also go.1, and gofmt, gofmt.1, and i'd prefer renaming over a conflict.

**Comment by ebfe** [comment]
/usr/lib/gcc/x86_64-unknown-linux-gnu/6.2/cgo
/usr/lib/libnetgo.a
/usr/lib/libgolibbegin.a

Rename /usr/bin/go to `?`

**Comment by chneukirchen** [comment]
`gcc-go`, `gcc-gofmt`?

**Comment by ebfe** [comment]
This is getting ugly...
```
$ strace -e exec -f go fmt
[...]
[pid 14740] execve("/usr/bin/gofmt", ["/usr/bin/gofmt", "-l", "-w", "main.go"], [/* 54 vars */]) = 0
[...]
```

**Comment by chneukirchen** [comment]
Then keep the conflict, Arch does too.

**Comment by pullmoll** [comment]
BTW: Perhaps someone finds the cause why linking go fails for musl. I disabled go for musl, because I could fix the compiling errors, but not the linking stage.

**Comment by thypon** [comment]
why not having alternatives?

**Comment by chneukirchen** [comment]
We could make a `gcc-go-tools` which conflicts with `go`... I think it could be useful to have `gccgo` installed in parallel to go.

**Comment by ebfe** [comment]
Feel free to take over the PR

**Comment by chneukirchen** [comment]
Adopted.

@pullmoll gccgo doesn't work on musl anyway due to lack of setcontext etc.

**Pull request closed without merging**
