### PR TITLE
[RFC] xbps-src: handle changelog metadata field

### PR DESCRIPTION
**Pull request by ebfe**
#3355, depends on voidlinux/xbps#169. Not sure if I updated everything that's necessary, also needs some kind of version check to determine if xbps-create accepts `--changelog`.

### CODE REVIEW

**Comment by xtraeme** [comment]
I'd wait until 0.52 is released and then increasing the min xbps version required in xbps-src should dtrt.

**Comment by xtraeme** [comment]
Looks ok btw :+1:

**Comment by Vaelatern** [comment]
Can you also add a note in the Manual about this variable, so when this PR is merged the documentation is updated as well?

**Comment by Vaelatern** [comment]
This OK?

**Pull request closed without merging**
