### PR TITLE
New package: python-xlrd-1.0.0

### PR DESCRIPTION
**Pull request by diogoleal**

### CODE REVIEW

**Comment by Vaelatern** [comment]
Is this a dependency for something else?

**Comment by crocket** [comment]
Extract data from Excel spreadsheets (.xls and .xlsx, versions 2.0 onwards) on any platform. Pure Python (2.6, 2.7, 3.2+). Strong support for Excel dates. Unicode-aware.

**Comment by asergi** [comment]
https://github.com/voidlinux/void-packages/pull/4610#issuecomment-310798234

**Comment by asergi** [comment]
Obsolete. Feel free to resubmit it.

**Pull request closed without merging**
