### PR TITLE
New package: wyrd-1.4.6

### PR DESCRIPTION
**Pull request by Vaelatern**
nopie because a linked library complained.

### CODE REVIEW

**Comment by dominikh** [comment]
Please fix the cross-compilation issues if possible, or set nocross=yes (or only_for_archs, if it's not a cross-compile issue but doesn't build on ARM in general.)

**Comment by Vaelatern** [comment]
I'm trying to figure out how to fix them. ocaml is a bit foreign to me.

**Comment by Vaelatern** [comment]
The issue is in a tool called "ocamlmklib" which does not seem to find a custom `ld`.

**Comment by Vaelatern** [comment]
Fixed with added nocross

**Comment by dominikh** [comment]
`conf_files="/etc/wyrdrc"` has to be added. I'll do it myself when merging, to avoid a roundtrip.

**Comment by dominikh** [comment]
Merged as cb879cc3c235f266f43540f928180adfcc85789b.

**Pull request closed without merging**
