### PR TITLE
ghc: update to 7.10.1

### PR DESCRIPTION
**Pull request by pullmoll**

### CODE REVIEW

**Comment by xtraeme** [comment]
See #1238

**Comment by pullmoll** [comment]
I see and hadn't thought of that. I'll try to get void for cubietruck done. Perhaps it's possible to build a ghc-x86_64 cross-compiler on armv7hf itself.

**Comment by chneukirchen** [comment]
I'd wait for ghc 7.10.2.

**Comment by pullmoll** [comment]
I'll leave this to @chneukirchen.

**Pull request closed without merging**
