### PR TITLE
New package: libmwaw-0.3.7

### PR DESCRIPTION
**Pull request by bra1nwave**
https://github.com/voidlinux/void-packages/issues/3716

### CODE REVIEW

**Comment by pullmoll** [comment]
The merge is wrong. Always do `git pull --rebase` to avoid merging unrelated changes into your PR.
FWIW in my fork I once did `git remote add upstream git://github.com/voidlinux/void-packages.git` and now always do `git pull --rebase upstream master` to sync to master.

**Comment by pullmoll** [comment]
Try with `git rebase -i 1ec6e9bae157f0a56439273f931a14124fe465c8` to squash your commits into one. Then use `git push -f`.

**Comment by bra1nwave** [comment]
Thank you very much for your help!
Now it should be fine :)

**Comment by pullmoll** [comment]
And now there's one thing left to do. Remove the empty line before your addition in `common/shlibs`, then do `git commit --amend` and `git push -f` again.

**Comment by bra1nwave** [comment]
OK, done.

**Comment by pullmoll** [comment]
Looks good now. Let's wait for travis-ci and I'll merge it.

**Pull request merged**
