### PR TITLE
openrazer-meta: update to 2.3.0

### PR DESCRIPTION
**Pull request by z3ntu**
Also move the python3-six dependency to the python3-pyudev package as I have missed that when I created the packages.

### CODE REVIEW

**Comment by maxice8** [comment]
there are some extra changes that can be imported from #13144

**Comment by pullmoll** [comment]
5fed77212bd7c6a9d9e5989ef733e6ec6f4e9d66 or is there anything else? In that case please open a new PR.

**Comment by z3ntu** [comment]
Yes, I created #13761 with them

**Comment by z3ntu** [comment]
Btw @maxice8 if you want to take over updating openrazer in the void repos, I can gladly give that over to you as updating the packages in the VM is rather annoying and I seem to have quite a few problems with void in the VM.

**Comment by maxice8** [comment]
On Mon, Apr 23, 2018 at 08:04:31AM +0000, Luca Weiss wrote:
> Btw @maxice8 if you want to take over updating openrazer in the void repos, I
> can gladly give that over to you as updating the packages in the VM is rather
> annoying and I seem to have quite a few problems with void in the VM.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

Sure, but you don't really need a VM for Void Linux i used to update packages from Exherbo without chroots, just installed xbps-src and statically linked xbps into my $HOME, was quite a fun workflow.

**Pull request closed without merging**
