### PR TITLE
new package: i3-gaps

### PR DESCRIPTION
**Pull request by skrzyp**
Not an option or subpackage, because Airblader's fork gone too far and might be considered as different codebase.

### CODE REVIEW

**Comment by skrzyp** [comment]
nevermind, screw that shit…

**Comment by Duncaen** [comment]
https://github.com/u202e/void-templates/blob/master/i3-gaps-git/template

**Comment by skrzyp** [comment]
And I'm not sure if we built vanilla version of patched one, because every time I try to build it with xbps-src at home, it outputs vanilla builds, but when I do this manually, everythimg goes well.

@Airblader should check his branching on this repo, this is a complete mess.

**Comment by Airblader** [comment]
> because Airblader's fork gone too far and might be considered as different codebase

I don't agree with that, but it's your call. 

> @Airblader should check his branching on this repo, this is a complete mess.

Can you be more specific as to what is "a mess"? I have two branches and I regularly merge vanilla in there. No rebases or other funny business. Pretty standard git stuff.

**Comment by Airblader** [comment]
My suspicion without looking into this since I don't use void is that you're checking out the wrong branch. The branching is explained in the Readme, it just has to be read.

**Comment by gregf** [comment]
@skrzyp yeah I believe what @Airblader said is correct. You just didn't read the README. The master branch is just vanilla i3 from what I can tell. You need to checkout either i3-gaps or gaps-next branch.

**Comment by Duncaen** [comment]
If i test it manually, the branch `gaps-next` is cloned, that should be correct, maybe just use a more specific clone to checkout the right branch and make it a little bit faster.
```
git clone --depth 1 --single-branch --branch gaps git://github.com/Airblader/i3.git
```

**Comment by skrzyp** [comment]
```
[i3] CC src/xcursor.c
[i3] CC src/version.c
[i3] CC src/commands.c
[i3] CC src/config_directives.c
In file included from ../i3-gaps-4.11/src/ipc.c:13:0:
../i3-gaps-4.11/src/ipc.c: In function 'handle_get_version':
include/yajl_utils.h:17:50: error: expected expression before ')' token
 #define y(x, ...) yajl_gen_##x(gen, ##__VA_ARGS__)
                                                  ^
../i3-gaps-4.11/src/ipc.c:862:5: note: in expansion of macro 'y'
     y(integer, MAJOR_VERSION);
     ^
include/yajl_utils.h:17:50: error: expected expression before ')' token
 #define y(x, ...) yajl_gen_##x(gen, ##__VA_ARGS__)
                                                  ^
../i3-gaps-4.11/src/ipc.c:865:5: note: in expansion of macro 'y'
     y(integer, MINOR_VERSION);
     ^
src/i3.mk:40: recipe for target 'src/ipc.o' failed
make: *** [src/ipc.o] Error 1
make: *** Waiting for unfinished jobs....
=> ERROR: i3-gaps-4.11_1: failed to run do_build() at line 8.
```

This is what I get when I force `git` to use `gaps` branch by default.
Also, `git` throws an `command not found` error on ARM's in Travis, no idea why.

**Comment by skrzyp** [comment]
So, it seems like so-called upstream ( @Airblader ) is doing something wrong with i3's internal version system on non-master branches. I've got the same error on release tarball too.

**Comment by Airblader** [comment]
You need the git tags. That's also true for vanilla i3. Also I'm going to unwatch this issue because I don't want to deal with the douchebag tone here. If you guys can't be friendly, figure it out yourself.

**Comment by skrzyp** [comment]
Pinning for specific tag, like `4.11` builds an "vanilla" build in a result.
So… is there a way to build an -gaps branch synced with latest upstream release?

**Comment by skrzyp** [comment]
I've tried this way, but it fails when you directly specify branch while cloning.
This repo is a giant mystery for me…

**Comment by xtraeme** [comment]
@Airblader is just right. There's no issue in the i3-gaps git repository. You just need to figure how to fetch the correct branch.

**Pull request closed without merging**
