### PR TITLE
broadcom-wl-dkms: add linux-4.7.patch

### PR DESCRIPTION
**Pull request by cavalier911**
This pull request resolves kernel module wl failing to build for linux-4.7 discussed in issue #4708

### CODE REVIEW

**Comment by Vaelatern** [comment]
Please don't close and re-open pull requests. It is never necessary.

**Comment by Vaelatern** [comment]
Only one PR, please, unless you are told otherwise. Unrelated features, such as if you fixed something in `firefox` and added a new spotify client, should go in separate PRs. If you wanted to package something, and it depended on a different package not yet in Void, you would put both of those package additions in the **same** PR.

**Comment by cavalier911** [comment]
@Vaelatern 
Sorry, my local branch required `git reset --hard` and `git push origin master --force` which deleted the broadcom-wl-dkms commit and closed #4742 pull request. My intent was to send a replacement PR for broadcom-wl-dkms and a separate PR for vivaldi which I added later.
Do I need to create a new branch for each separate pull request?

**Comment by Vaelatern** [comment]
That is the way it is done, yes. Cheap branching is a strength of git.

**Comment by Vaelatern** [comment]
This PR can not be reviewed or accepted due to the mixed nature of its intentions.

**Comment by Vaelatern** [comment]
25ff298

**Pull request closed without merging**
