### PR TITLE
dotherside: shlibs update

### PR DESCRIPTION
**Pull request by gangsterakato**

### CODE REVIEW

**Comment by Vaelatern** [comment]
Rebuild of dotherside needed too (revbump)

**Comment by Gottox** [comment]
updating shlibs is only needed when a the so version has changed.

**Comment by gangsterakato** [comment]
@Gottox, since the update of the package I got the error `could not load: libDOtherSide.so` when trying to open a program compiled with `dotherside`.

When renaming the library from from libDOtherSide.so.0.0.0 to libDOtherSide.so it works.
What can be done in this case?

**Comment by Gottox** [comment]
looks like an ldopen issue. this may be fixed by patchng the depending program.

**Comment by gangsterakato** [comment]
@Gottox, the fact is that the program worked well with the last version, without any configuration.

**Comment by Gottox** [comment]
which one was it?

**Pull request closed without merging**
