### PR TITLE
tint2: update to 0.14.6

### PR DESCRIPTION
**Pull request by cr6git**

### CODE REVIEW

**Comment by cr6git** [comment]
Oupss!! 
Sorry, I just omitted the "$" before {homepage}.

**Comment by Vaelatern** [comment]
You seem to be contributing regularly.
Please learn to have just one commit per PR by squashing commits and pushing with --force.
I'll leave this PR open for you to test.

**Comment by cr6git** [comment]
I don't know... 
I give up.

**Comment by Vaelatern** [comment]
It's alright, it's confusing if you've never done it.
But closing and re-opening PRs is never the correct way to do this.
The correct way from command line git is something like: `git rebase --interactive HEAD~3` and following the instructions, then (assuming that https://github.com/voidlinux/void-packages is `upstream`) do something like: `git rebase upstream/master`

**Comment by cr6git** [comment]
@Vaelatern I don't use git from the command line, I'm using the github Web interface. 

Do you know where is _the button_ for this function (squashing commits) ?? 

I am stuck here... :disappointed:

**Pull request closed without merging**
