### PR TITLE
WIP: docker: update to 1.13.1, add new dependencies

### PR DESCRIPTION
**Pull request by ackalker**
This update adds new runtime dependencies on `docker-runc`, `docker-containerd` and `docker-proxy`. and a new buildtime dependency, `go-md2man` for building the man pages.

Note: the `docker-*` dependencies have to be exact commit-pinned versions, according to https://github.com/docker/docker/blob/v1.13.1/hack/dockerfile/install-binaries.sh and https://github.com/docker/docker/blob/v1.13.1/hack/dockerfile/binaries-commits .

Please advise on how we should check (and maintain) these dependency versions.

### CODE REVIEW

**Comment by pullmoll** [comment]
> Please advise on how we should check (and maintain) these dependency versions.

Perhaps add a script to docker which fetches [binaries-commits](https://github.com/docker/docker/blob/v1.13.1/hack/dockerfile/binaries-commits) and emits a sed script to update the package templates, i.e. `docker-commits.sh`:
```
#!/bin/bash
# Fetch git revisions for docker modules and emit a sed script.
# Optional parameter: docker version number
VER=$1
[ -z "$VER" ] && VER="1.13.1"
URL=https://raw.githubusercontent.com/docker/docker/v${VER}/hack/dockerfile/binaries-commits

curl -s $URL | while read LINE; do
        [ -z "$LINE" -o "${LINE:0:1}" = "#" ] && continue
        NAME=${LINE%=*}
        HASH=${LINE#*=}
        unset pkg
        case "$NAME" in
                TOMLV_*)      pkg="docker-tomlv" ;;
                RUNC_*)       pkg="docker-runc" ;;
                CONTAINERD_*) pkg="docker-containerd" ;;
                TINI_*)       pkg="docker-tini" ;;
                LIBNETWORK_*) pkg="docker-libnetwork" ;;
                VNDR_*)       pkg="docker-vndr" ;;
                BINDATA_*)    pkg="docker" ;;
                *)            echo "unknown name: $NAME"
                              exit 1
        esac
        [ -z "$pkg" ] && continue
        echo "# update hash for $pkg"
        echo "sed -i ../$pkg/template \\"
        echo "  -e 's;\\(_githash\\)=.*;\1=${HASH,,};'"
        echo
done
```
Of course you would remove the `pkg="..."` for packages which do not exist or are wrong.
Or you don't care and let sed fail for these :)

**Comment by ackalker** [comment]
@pullmoll Thanks! I will look into it.

**Comment by pullmoll** [comment]
I think you could also `sed` the template's version date.
```
DATE=$(date +%Y%m%d)
…
        echo "sed -i ../$pkg/template \\"
        echo "  -e 's;\\(_githash\\)=.*;\\1=${HASH,,};' \\"
        echo "  -e 's;\\(version\\)=\\(.*\\)\\.2017*;\\1=\\2.${DATE};'"
```

**Comment by roman-neuhauser** [comment]
any idea why, contrary to travis-ci, this fails to build for x86_64 on my machine?  `linux-headers` in `makedepends` changes nothing.

```
roman@dagon ~/wc/void-packages pr/5820 0 1035 0 . git show -s master        
commit 3ee97f76666221dd8c2444eab74fb0c9c304a28d
Author: Enno Boland <gottox@voidlinux.eu>
Date:   Sun Mar 12 12:39:03 2017 +0100

    cachefilesd: update to 0.10.10.

roman@dagon ~/wc/void-packages pr/5820 0 1036 0 . git log --oneline master..
1635e37c20 docker: update to 1.13.1
cf8eab86f2 New package: docker-proxy-0.8.0.dev.2.20161019
539f57f8d7 New package: docker-containerd-0.2.3.20170126
56db596dce New package: docker-runc-1.0.0.rc2.20170129
107de897e7 New package: go-md2man-1.0.5

roman@dagon ~/wc/void-packages pr/5820 0 1037 0 . ./xbps-src -f clean docker
=> Using `/home/roman/wc/void-packages/hostdir/binpkgs/pr/5820' as local repository.
=> docker-1.13.1_1: cleaning build directory...

roman@dagon ~/wc/void-packages pr/5820 0 1038 0 . ./xbps-src -f pkg docker  
=> Using `/home/roman/wc/void-packages/hostdir/binpkgs/pr/5820' as local repository.
[*] Updating `https://repo.voidlinux.eu/current/musl/x86_64-repodata' ...
ERROR: [reposync] failed to fetch file `https://repo.voidlinux.eu/current/musl/x86_64-repodata': Not Found
[*] Updating `https://repo.voidlinux.eu/current/musl/nonfree/x86_64-repodata' ...
ERROR: [reposync] failed to fetch file `https://repo.voidlinux.eu/current/musl/nonfree/x86_64-repodata': Not Found
[*] Updating `https://repo.voidlinux.eu/current/x86_64-repodata' ...
x86_64-repodata: 1224KB [avg rate: 734KB/s]
[*] Updating `https://repo.voidlinux.eu/current/nonfree/x86_64-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/aarch64/x86_64-repodata' ...
ERROR: [reposync] failed to fetch file `https://repo.voidlinux.eu/current/aarch64/x86_64-repodata': Not Found
[*] Updating `https://repo.voidlinux.eu/current/multilib/x86_64-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/multilib/nonfree/x86_64-repodata' ...
=> docker-1.13.1_1: removing autodeps, please wait...
=> docker-1.13.1_1: building ...
   [host] go-md2man-1.0.5_1: found (/host/binpkgs/pr/5820)
   [host] go-1.8_1: found (https://repo.voidlinux.eu/current)
   [target] libbtrfs-devel-4.10_1: found (https://repo.voidlinux.eu/current)
   [target] sqlite-devel-3.17.0_1: found (https://repo.voidlinux.eu/current)
   [target] device-mapper-devel-2.02.168_1: found (https://repo.voidlinux.eu/current)
   [target] libseccomp-devel-2.3.2_1: found (https://repo.voidlinux.eu/current)
   [runtime] docker-runc>=0: found docker-runc-1.0.0.rc2.20170129_1 (/host/binpkgs/pr/5820)
   [runtime] docker-containerd>=0: found docker-containerd-0.2.3.20170126_1 (/host/binpkgs/pr/5820)
   [runtime] docker-proxy>=0: found docker-proxy-0.8.0.dev.2.20161019_1 (/host/binpkgs/pr/5820)
   [runtime] iptables>=0: found iptables-1.6.1_1 (https://repo.voidlinux.eu/current)
   [runtime] xz>=0: found xz-5.2.3_1 (https://repo.voidlinux.eu/current)
   [runtime] git>=0: found git-2.12.0_1 (https://repo.voidlinux.eu/current)
=> docker-1.13.1_1: installing host dependency 'go-md2man-1.0.5_1' ...
=> docker-1.13.1_1: installing host dependency 'go-1.8_1' ...
=> docker-1.13.1_1: installing target dependency 'libbtrfs-devel-4.10_1' ...
=> docker-1.13.1_1: installing target dependency 'sqlite-devel-3.17.0_1' ...
=> docker-1.13.1_1: installing target dependency 'device-mapper-devel-2.02.168_1' ...
=> docker-1.13.1_1: installing target dependency 'libseccomp-devel-2.3.2_1' ...
=> docker-1.13.1_1: running do-fetch hook: 00-distfiles ...
=> docker-1.13.1_1: running do-extract hook: 00-distfiles ...
=> docker-1.13.1_1: extracting distfile(s), please wait...
=> docker-1.13.1_1: running post-extract hook: 00-patches ...
=> docker-1.13.1_1: running pre-configure hook: 00-gnu-configure-asneeded ...
=> docker-1.13.1_1: running pre-configure hook: 01-override-config ...
=> docker-1.13.1_1: running pre-configure hook: 02-script-wrapper ...
=> docker-1.13.1_1: running pre-build hook: 02-script-wrapper ...
=> docker-1.13.1_1: running do_build ...
# WARNING! I don't seem to be running in a Docker container.
# The result of this command might be an incorrect build, and will not be
# officially supported.
#
# Try this instead: make all
#

---> Making bundle: dynbinary (in bundles/1.13.1/dynbinary)
Building: bundles/1.13.1/dynbinary-client/docker-1.13.1
Created binary: bundles/1.13.1/dynbinary-client/docker-1.13.1
Building: bundles/1.13.1/dynbinary-daemon/dockerd-1.13.1
# github.com/docker/docker/daemon/graphdriver/btrfs
In file included from _build-docker-xbps/src/github.com/docker/docker/daemon/graphdriver/btrfs/btrfs.go:9:0:
/usr/include/btrfs/ctree.h:37:25: fatal error: linux/sizes.h: No such file or directory
 #include <linux/sizes.h>
                         ^
compilation terminated.
# pkg-config --cflags libseccomp libseccomp
pkg-config: exec: "pkg-config": executable file not found in $PATH
=> ERROR: docker-1.13.1_1: failed to run do_build() at line 30.

roman@dagon ~/wc/void-packages pr/5820 0 1039 1 . 
```

**Comment by ebfe** [comment]
hostmakedepends+="pkg-config"

linux/sizes.h no longer exists in the 4.10 linux-headers package

**Comment by ebfe** [comment]
Correction: linux4.10-headers has it, but kernel-libc-headers is the relevant package,

**Comment by rngd** [comment]
hello @ebfe, adding pkg-config to hostmakedepends does not fix the sizes.h error:

```
---> Making bundle: dynbinary (in bundles/1.13.1/dynbinary)
Building: bundles/1.13.1/dynbinary-client/docker-1.13.1
Created binary: bundles/1.13.1/dynbinary-client/docker-1.13.1
Building: bundles/1.13.1/dynbinary-daemon/dockerd-1.13.1
# github.com/docker/docker/daemon/graphdriver/btrfs
In file included from _build-docker-xbps/src/github.com/docker/docker/daemon/graphdriver/btrfs/btrfs.go:9:0:
/usr/include/btrfs/ctree.h:37:25: fatal error: linux/sizes.h: No such file or directory
 #include <linux/sizes.h>
                         ^
compilation terminated.
=> ERROR: docker-1.13.1_1: failed to run do_build() at line 30.


roman@dagon ~/wc/void-packages pr/5820 :M 0 1054 1 . git di
diff --git a/srcpkgs/docker/template b/srcpkgs/docker/template
index 33b1cef4ed..90088b403a 100644
--- a/srcpkgs/docker/template
+++ b/srcpkgs/docker/template
@@ -3,7 +3,7 @@ pkgname=docker
 version=1.13.1
 revision=1
 build_style=go
-hostmakedepends="go-md2man"
+hostmakedepends="go-md2man pkg-config"
 makedepends="libbtrfs-devel sqlite-devel device-mapper-devel libseccomp-devel"
 short_desc="Pack, ship and run any application as a lightweight container"
 maintainer="Juan RP <xtraeme@voidlinux.eu>"
roman@dagon ~/wc/void-packages pr/5820 :M 0 1055 0 . 
```

**Comment by ebfe** [comment]
No, but it fixes the subsequent `pkg-config: exec: "pkg-config": executable file not found in $PATH`

**Comment by ebfe** [comment]
2f189373655e716aac3bf09e5ed250a4dfc5343d, rebasing on top of master and adding hostmakedepends+="pkg-config" should fix the build.

**Comment by roman-neuhauser** [comment]
yeah, the packages build after rebasing on top of 2f18937 and with pkg-config in hostmakedepends, thanks!

**Comment by ackalker** [comment]
@thypon Could you please tell me why you committed your change to `master` without informing me? The PR was clearly marked WIP for a reason. Now I'm stuck with a monster of a merge conflict to fix.

In particular, I would like to know:

* Why bundle `docker-runc`, `docker-containerd` and `docker-proxy` instead of have them as subpackages? Use of (patched) `hack/dockerfile/install-binaries.sh` requires network access (`git clone`) inside of `do_build` build step (not always desirable).
* Why drop generating man pages using `md2man`?
* I was still working on a solution for the `dockerd` logging problem, I might have needed to change `files/docker/log/run` to implement it.

**Comment by thypon** [comment]
This PR seems stucked.

1. it is KISS and accomplishes what would need a lot of helper subpackages that could change in the future. Furthermore, it streamlines the development.
2. Nobody drops `md2man`. I updated `docker` from scratch with minimal changes on top of the old version, and `md2man` wasn't even a package.
3. I'm not diminishing your work. Feel free to continue with your PR rebasing on top of the current `master`.

IMHO it is better if we split this effort into three steps:

1. a md2man package
2. the md2man Docker support
3. Docker split into sub-packages (i would argue this is not needed at all)

**Comment by ackalker** [comment]
@thypon I agree with you on all points. It would have been nice though if you had given me a heads up on your intent to push your changes.

**Comment by ebfe** [comment]
This PR is obsolete since 87e421d6319de6a75b96154eda5247d8ea5c787e?

**Comment by thypon** [comment]
It is, actually. Closing this for now.

**Pull request closed without merging**
