### PR TITLE
Update kdeframeworks to 5.45.0

### PR DESCRIPTION
**Pull request by Hoshpak**

### CODE REVIEW

**Comment by Hoshpak** [comment]
It's great that this change was merged, it will make things much easier in the future. Since creating this PR and testing that each package builds was a lot of work and I don't see an easy way to automatically amend all commits with this change, I'd rather leave the change out of this PR. It could either be a separate PR or be included with the next update of the frameworks packages.

**Comment by maxice8** [comment]
On Mon, Apr 23, 2018 at 01:31:55AM -0700, Helmut Pozimski wrote:
> It's great that this change was merged, it will make things much easier in the
> future. Since creating this PR and testing that each package builds was a lot
> of work and I don't see an easy way to automatically amend all commits with
> this change, I'd rather leave the change out of this PR. It could either be a
> separate PR or be included with the next update of the frameworks packages.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

if you want i can do it, should be semi easy to automate.

**Comment by Hoshpak** [comment]
Sure, feel free to try. I wouldn't have time right now anyway.

**Comment by maxice8** [comment]
There we go https://github.com/maxice8/void-packages/tree/update-kdeframeworks

i believe you can merge or if it fails you can just reset your branch to latest `master` on void-packages and just import the commits.

**Comment by Hoshpak** [comment]
Thanks a lot, I pushed the changed commits to update the PR.

**Comment by maxice8** [comment]
alright, thanks.

**Comment by Chocimier** [comment]
5.47.0 is out, will you care to update PR? If not quite, I can do that.

**Comment by Hoshpak** [comment]
I you have the time to do it, please got for it. Compiling all packages for the relevant architectures, fixing newly introduced issues (especially with cross-compiling) etc. takes a lot of time which I don't have right now.

**Pull request closed without merging**
