### PR TITLE
buku: add missing dependency python3-requests

### PR DESCRIPTION
**Pull request by cr6void**
This fixes [#6054](https://github.com/voidlinux/void-packages/issues/6054).

### CODE REVIEW

**Comment by Vaelatern** [comment]
A revision bump is necessary.

**Comment by cr6void** [comment]
Excuse-me!! Fixed.

**Comment by cr6void** [comment]
@Vaelatern it's OK for you or I missed something ? Thanks.

**Comment by Duncaen** [comment]
The commit message.

**Comment by cr6void** [comment]
@Duncaen I'm really sorry, I don't know how to change the commit message...

I think I should do a new PR.

**Pull request closed without merging**
