### PR TITLE
linux4.16: update to 4.16.10

### PR DESCRIPTION
**Pull request by abenson**

### CODE REVIEW

**Comment by misuchiru03** [comment]
This has been tested *working* on an HP Envy x360 with Ryzen5 2500u APU with Radeon Vega 8 (Raven Ridge) graphics.  This has, so far, been the only missing link to making Void's graphics load at all (past the kernel loading text).

**Comment by cr6git** [comment]
4.16.10 is out.

**Comment by abenson** [comment]
I'll update and repush, thanks.

**Comment by cr6git** [comment]
@abenson it would have been a good idea to enable RTSX. [#14249](https://github.com/voidlinux/void-packages/pull/14249)

**Pull request merged**
