### PR TITLE
sigil: add necessary python3 dependency; fix cross

### PR DESCRIPTION
**Pull request by jannisch**
The application throws a ton of errors before startup and then crashes without this python3 package being installed.

### CODE REVIEW

**Comment by jannisch** [comment]
Might the failed build show a common issue? I wonder why `qmake` can't be found although I only added a runtime dependency.

**Comment by Duncaen** [comment]
I guess it did not cross compile before, because support for cross compiling was added to the qt5 stuff recently.
`qt5-qmake` needs to be a `hostmakedepends`.

**Comment by jannisch** [comment]
Thanks for the info, hope it builds now!

**Comment by pullmoll** [comment]
For cross builds you probably need to add a statement like this:
```
if [ -n "$CROSS_BUILD" ]; then
        hostmakedepends+=" qt5-host-tools qt5-tools-devel qt5-svg-devel"
        hostmakedepends+=" qt5-webkit-devel qt5-xmlpatterns-devel qt5-multimedia-devel"
        hostmakedepends+=" qt5-sensors-devel qt5-declarative-devel qt5-location-devel"
        hostmakedepends+=" qt5-webchannel-devel"
fi
```

**Comment by jannisch** [comment]
Really didn't expect those issues, will need some time...

**Comment by pullmoll** [comment]
Wild guess: The linker giving errors for missing symbols when cross compiling may be a case of `gcc-6.3.0` eliminating unused code. You could try, if `CXXFLAGS="-fno-lifetime-dse"` in the global section helps.

**Comment by jannisch** [comment]
Unfortunately that does not work (I hope _global_ means at the end of the template, tried it in `configure_args` as well)

I could not find anything similar in the [Arch PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/sigil) or in the [Gentoo ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/app-text/sigil/sigil-0.9.6.ebuild) as well 😞

**Comment by pullmoll** [comment]
Arch doesn't try to cross compile sigil, neither does gentoo AFAICT.
I'll take a closer look and come back to you.

**Comment by jannisch** [comment]
Oops that's obvious for Arch...
Thank you!

**Comment by pullmoll** [comment]
Just adding `python3-devel` to the list of `hostmakedepends+="…"` inside the `if` statement solves cross building, i.e.
```
if [ -n "$CROSS_BUILD" ]; then
        hostmakedepends+=" qt5-host-tools qt5-tools-devel qt5-svg-devel"
        hostmakedepends+=" qt5-webkit-devel qt5-xmlpatterns-devel qt5-multimedia-devel"
        hostmakedepends+=" qt5-sensors-devel qt5-declarative-devel qt5-location-devel"
        hostmakedepends+=" qt5-webchannel-devel python3-devel"
fi
```

**Comment by jannisch** [comment]
That's it 😃

**Pull request merged**
