### PR TITLE
New package: quodlibet-3.4.0

### PR DESCRIPTION
**Pull request by jarbowski**

### CODE REVIEW

**Comment by xtraeme** [comment]
- This package is missing `noarch=yes`
- This package is missing runtime dependencies

**Comment by jarbowski** [comment]
It isn't missing noarch=yes
And according to Arch pkgbuild, only some optional dependencies are missing: gst-libav, zeitgeist (only x86 in Void), libgpod, cddb-py, python2-musicbrainz2, kakasi.
I've added python-inotify and libkeybinder2.

**Comment by xtraeme** [comment]
Last time I merged one of your pkgs had to loose almost 1h fixing the pkg.

**Comment by jarbowski** [comment]
Sorry for that, it won't happen again. I think everything is okay now, it works well on my box.

**Pull request closed without merging**
