### PR TITLE
New package: neovim-0.1.0.

### PR DESCRIPTION
**Pull request by stpx**

### CODE REVIEW

**Comment by pullmoll** [comment]
I think there should perhaps be a FindLUA.cmake script in this package which checks the common versions and their varying locations, no?

IIRC I've seen, and patched, such a script in some other package to also look for lua5.2 or lua52.

**Comment by xtraeme** [comment]
The alternatives framework can be useful for this case, the lua pkgs should set bin/lua and bin/luac as alternatives.

**Comment by pullmoll** [comment]
xbps-alternatives works for binaries only, or does it? Otherwise `lua52.pc` could be an alternative for `lua.pc` and both `pkg-config` and `cmake` should find the installed version.

**Comment by xtraeme** [comment]
With alternatives you can symlink anything, any file or directory.

See srcpkgs/ex-vi as example.

**Comment by pullmoll** [comment]
I really should take the time to RTFS and understand xbps-alternatives. *sigh*

**Comment by stpx** [comment]
Adding `-DLUA_PRG=/usr/bin/lua5.2` to `configure_args` appears to work.... I know very little about lua.

**Comment by stpx** [comment]
Cross-compile is broken... And the last time I tried to compile for `x86_64-musl` it failed, but the was a few months ago.

**Comment by stpx** [comment]
I think `armv*` builds are getting hung up from: building `lua*-lpeg` for the target arch, then for host arch. That shouldn't be a problem on the actual build server, right?

**Comment by stpx** [comment]
The `armv*-musl` builds are failing because of `LuaJIT`.  Good enough to merge?

**Comment by pullmoll** [comment]
:+1:

**Pull request merged**
