### PR TITLE
New package: shake.

### PR DESCRIPTION
**Pull request by CasperVector**
short_desc="Defragmenter that runs in userspace while the system is used"

### CODE REVIEW

**Comment by CasperVector** [comment]
It seems that this package uses `error()` from `error.h`, and is therefore unsupported on musl.  However, I do not quite understand why help2man complains about `can't get '--help' info` on aarch64 and armv7hf.

**Comment by Vaelatern** [comment]
Cross building means it can't run cross-built binaries.
It's a flaw unconsidered by those who rely on help2man

**Comment by CasperVector** [comment]
Now I see...

**Comment by CasperVector** [comment]
Now I see...

**Comment by Vaelatern** [comment]
Straightforward fix is to rely on the pkg as a host pkg on cross build and have help2man do its magic on them.

**Comment by newbluemoon** [comment]
Just had the same thought as @Vaelatern :) but you also have to make cmake use the host binary, e.g.:

```
if [ -n "$CROSS_BUILD" ]; then
	hostmakedepends+=" shake"

	post_extract() {
		sed -i -e 's;get_target_property (HELP2MAN_COMMAND ${command} LOCATION);set(HELP2MAN_COMMAND ${command});' \
		 CMakeLists.txt
	}
fi
```

**Comment by CasperVector** [comment]
Thanks for the advice; template updated accordingly, cross-built successfully on my machine.

**Comment by CasperVector** [comment]
Added `$broken` specifically for `-musl` architectures.

**Comment by Vaelatern** [comment]
See how I amended the commit message before merging.

**Comment by CasperVector** [comment]
Oops, I see.  All remaining templates updated now.

**Pull request merged**
