### PR TITLE
Change distfile location for kdeframeworks packages

### PR DESCRIPTION
**Pull request by Hoshpak**
This is to address #6514 . Change the distfiles URLs for the kdeframeworks packages from stable to Attic on the KDE mirror. No rebuild/revbump needed.

### CODE REVIEW

**Comment by Vaelatern** [comment]
I'll have to check if the attic also has the most recent versions, or if it's just the older versions

**Comment by Hoshpak** [comment]
The directory contains only the versions that were removed from the stable directory, currently these are frameworks versions up to 5.29. If these packages would be updated in the near future, one would have to revert the URLs back to the stable directory. If you think it's better to leave it as it currently is, I don't mind closing this pull request and leaving it unchanged. My only concern was that possibly necessary rebuilds of the packages will inevitably fail if the URLs are not changed and since KDE 5 seems pretty much to be stuck, I wouldn't expect updates to these packages in the near future.

**Comment by ebfe** [comment]
@Vaelatern ping

**Comment by yopito** [comment]
will be unecessary if #6052 is merged.

**Comment by Hoshpak** [comment]
Lukcily made obsolete by #6052 having been merged.

**Pull request closed without merging**
