### PR TITLE
Update libgit2 to 0.25.1

### PR DESCRIPTION
**Pull request by SevereOverfl0w**

### CODE REVIEW

**Comment by chneukirchen** [comment]
Needs a respin for new cargo now.

**Comment by SevereOverfl0w** [comment]
I have rebased against master.

**Comment by Vaelatern** [comment]
Looks like `libgit2-glib` expects to find functions it can't anymore.

**Comment by asergi** [comment]
#5498

**Comment by SevereOverfl0w** [comment]
Closing in favour of #5498, hadn't seen that when making my commit (and it also appears to be identical).

**Comment by chneukirchen** [comment]
Neither adresses libgit2-glib?

**Comment by SevereOverfl0w** [comment]
@chneukirchen I don't believe there is currently an update to libgit2-glib (according to https://github.com/GNOME/libgit2-glib). There has been _some_ recent activity, so I would guess that it's in the pipeline.

It may now be possible to build from master (which wasn't possible 8 days ago), so that may be one way around it.

**Comment by chneukirchen** [comment]
Nothing uses this library, if it is unmaintained we can also drop it?
cc @xtraeme

**Comment by SevereOverfl0w** [comment]
libgit2-glib has been updated to 0.25.0, so presumably can now be updated as part of this PR. Will try and find some time to take it on soon.

**Comment by SevereOverfl0w** [comment]
Oops, someone has beaten me to it!

**Pull request closed without merging**
