### PR TITLE
rxvt-unicode: updated to 9.22

### PR DESCRIPTION
**Pull request by Vaelatern**

### CODE REVIEW

**Comment by Vaelatern** [comment]
I can't think of a better way to say `rxvt clone supporting Xft fonts and Unicode` and xlint fails on just that line.

**Comment by 7185** [comment]
How about `An rxvt clone supporting Xft fonts and Unicode`?

**Comment by chneukirchen** [comment]
First off, you don't need to fix xlint things just when you want to bump a revision.

Second, I propose "Terminal emulator supporting Xft fonts and Unicode", so people would actually find it...

**Comment by xtraeme** [comment]
+1

**Comment by Vaelatern** [comment]
Description changed to @chneukirchen's suggestion.

**Pull request merged**
