### PR TITLE
New package: firefox-esr-i18n-52.5.0

### PR DESCRIPTION
**Pull request by Chocimier**

### CODE REVIEW

**Comment by Gottox** [comment]
To clarify: firefox-i18n does not work for ff-esr anymore?

**Comment by Chocimier** [comment]
Not checked, as firefox-i18n-* depend on firefox, which conflicts with firefox-esr.

**Comment by Gottox** [comment]
but firefox-esr provides firefox, so this dependency is satisfied.

**Comment by Gottox** [comment]
Ah, no, it does not. This is an error.

**Comment by Chocimier** [comment]
Anyway, 52 refuses to load and use translation of 56.

**Comment by asergi** [comment]
Merged manually in 0fec68021d9dc19d1a96f989b189146932c25bd4 (removed nonexistent `firefox-esr-i18n-be` and `firefox-esr-i18n-my`).

**Pull request closed without merging**
