### PR TITLE
Add alternatives group for cc to clang and gcc

### LINKED ISSUE #12578: clang package missing "cc" executable
### System

```console
$ xuname
-bash: xuname: command not found

$ uname -a
Linux vagrant 4.12.13_1 #1 SMP PREEMPT Thu Sep 14 13:15:00 UTC 2017 x86_64 GNU/Linux

* package:  clang
  *affected package(s) including the version*: clang-6.0.0_1

### Expected behavior

I expect the clang package to provide a `cc` executable in `$PATH`, so that many C, C++, Rust, and other projects that prefer to invoke the compiler as a generic "cc" name can work.

### Actual behavior

The clang package does not install a `cc` executable, resulting in many systems language projects builds failing.

### Steps to reproduce the behavior

1. Install clang.
2. Attempt to run `cc`.

As a workaround, users can manually create a `cc` shim, or just dump clang for gcc, which funnily enough does provide a `cc` shim.

### LINKED ISSUE #12579: rust package fails to find clang compiler
### System

```console
$ xuname
-bash: xuname: command not found
$ uname -a
Linux vagrant 4.12.13_1 #1 SMP PREEMPT Thu Sep 14 13:15:00 UTC 2017 x86_64 GNU/Linux
```

* package:  rust
  *affected package(s) including the version*: rust-1.24.0_1 clang-6.0.0_1

### Expected behavior

When I attempt to compile a `helloworld.rs` script, then the Rust compiler sees the available clang compiler and uses it to build a `helloworld` executable.

### Actual behavior

Rust complains that it cannot find `cc` for linking.

### Steps to reproduce the behavior

1. Install the "rust" package.
2. Install the "clang" package.
3. Attempt to compile a Rust application.

This issue appears to be due to #12578.

As a workaround, I'm dumping clang for gcc, which does provide a `cc` executable that Rust then sees on `$PATH`.

### PR DESCRIPTION
**Pull request by jnbr**
closes #12578, closes #12579

### CODE REVIEW

**Comment by maxice8** [comment]
@chneukirchen we have a taker.

**Comment by maxice8** [comment]
add the closes to the commits so that they are sure to closes the issues.

**Comment by jnbr** [comment]
> add the closes to the commits so that they are sure to closes the issues.

Thanks for the hint. Actually, it's fine to do it from a pull request, doesn't have to be a commit message, my syntax was wrong though.

**Comment by Vaelatern** [comment]
Also gcc installs a `cc` symlink. That might need changing.

**Comment by Vaelatern** [comment]
@newbluemoon we don't nitpick on this issue. Whatever people do, people do.

**Comment by jnbr** [comment]
@newbluemoon thanks for letting me know, you're right. We will eventually see, what will happen.

Let's stay on topic here.

**Comment by Vaelatern** [comment]
I like this. No other objections have been raised.

**Comment by newbluemoon** [comment]
@Vaelatern Didn’t mean to be nitpicking, sorry if it appeared this way. It just seemed to me there was a slight misunderstanding and @jnbr might be interested to know. But I’ll shut up about this now, because you’re right. ;)

**Pull request merged**
