### PR TITLE
New package: perl-Svsh-1.002000.

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by pullmoll** [comment]
None of these packages are noarch=yes? I can't imagine that's true.

**Comment by maxice8** [comment]
That is true, big oversight by me.

I'll fix this when I get home at midnight GMT -3.

My notebook HDD gave up so I can't work on Voidlinux from my uni anymore.

**Comment by pullmoll** [comment]
NP. I just wanted to work on the pile of PRs again, from older to newer, and this was the next one.

**Comment by maxice8** [comment]
On Tue, Feb 06, 2018 at 08:02:54PM +0000, Jürgen Buchmüller wrote:
> None of these packages are noarch=yes? I can't imagine that's true.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/voidlinux/void-packages/pull/11089#issuecomment-363547530

it is done

**Pull request closed without merging**
