### PR TITLE
New package: iwd-0.2.

### PR DESCRIPTION
**Pull request by maxice8**
as requested on the forums, it is quite nifty.

### CODE REVIEW

**Comment by maxice8** [comment]
usage examples.

```
[iwd]# known-networks list
                                 Known Networks                                
--------------------------------------------------------------------------------
 Name                            Security   Last connected     Last seen        
--------------------------------------------------------------------------------
 memes                           psk        May 14,  7:10 PM   May 14,  7:10 PM 
```

```
[iwd]# device list
                                    Devices                                    
--------------------------------------------------------------------------------
  Name                Address             State          Adapter   
--------------------------------------------------------------------------------
  wlp1s0              f8:da:0c:94:a9:8d   connected      phy0      
```

**Comment by maxice8** [comment]
```
[iwd]# device wlp1s0 get-networks 
                               Available networks                             *
--------------------------------------------------------------------------------
    Network name                    Security  Signal
--------------------------------------------------------------------------------
    NAIARA                          psk       ****
    Onix                            psk       ****
    Brwlan                          psk       ****
    TP-Link                         psk       ****
    OTICASCAROL                     psk       ****
    Ti                              psk       ****
    ULTRAPOPULAR SAO JOAO           psk       ****
    MERCUSYS_CCD8                   psk       ****
    SARAH                           psk       ****
    VIVO-58C4                       psk       ****
    Dailin                          psk       ****
    CONVIDADOS MONTREAL MAGAZINE    psk       ****
    ECA                             psk       ****
    Barbara                         psk       ****
    Milena                          psk       ****
  > memes                           psk       ****  
```

**Comment by Johnnynator** [comment]
https://raw.githubusercontent.com/alpinelinux/aports/8b7e48dcaf6a2049edeffaa957db618e923b78ab/main/linux-headers/0002-libc-compat.h-prevent-redefinition-of-struct-ethhdr.patch
Alpine has this patch for ethhdr. I will check locally if I can get iwd compilled with it.

**Comment by Johnnynator** [comment]
Nice iwd acknowledges that only GLIBC has execinfo but later just forgets it and complains that `__iwd_backtrace_print` is not supported. It feels like they weren't sure if they want to support not GLIBC systems or not.

**Comment by Johnnynator** [comment]
finished. I will open a PR for `kernel-libc-headers` once I have that patch done
https://github.com/Johnnynator/void-packages/commit/194138b78172b11c4fa87aceef8c71652d6933af

**Comment by Gottox** [comment]
iwd can't build against a shared ell yet, can't it?

**Comment by Johnnynator** [comment]
@maxice8 You can include the musl patch if you want, it should be final now.
https://github.com/Johnnynator/void-packages/commit/662275d8a36a5482f3f67df1b5d5fdd0f14b6e2f

**Comment by maxice8** [comment]
@Gottox no clue

@Johnnynator added

**Pull request merged**
