### PR TITLE
weston: add egl patches

### PR DESCRIPTION
**Pull request by Sir-Boops**
These patches are needed for nvidia support, i haven't tested them on a non nvidia system

### CODE REVIEW

**Comment by the-maldridge** [comment]
Are these patches still relevant?

**Comment by Sir-Boops** [comment]
I've not seen any movement upstream so yes they are. And I've now also tested these patches on a non nvidia system and they don't effect it.

**Comment by Duncaen** [comment]
I dont think we should import patches that large, it bloats the repository.

**Comment by asergi** [comment]
What @Duncaen said. Also, it's not sure these patches will be accepted upstream.
So, @the-maldridge revert it.

**Comment by the-maldridge** [comment]
I very much dispute the bloat comment, but I've reverted the patch anyway.

**Pull request closed without merging**
