### PR TITLE
new package: mac-3.99

### PR DESCRIPTION
**Pull request by tonkazoid**

### CODE REVIEW

**Comment by dicktyr** [comment]
thank you! :}
(I was preparing to do it myself)

it's useful (for queries) to include "Monkey's Audio" in the description

    Monkey's Audio (APE) codec and decompressor

**Comment by tonkazoid** [comment]
> it's useful (for queries) to include "Monkey's Audio" in the description

Yes, i'll add it.

Another thing i don't like is the version number + _ubs=u4-b5-s7. Should i change it to something like 3.99:u4:b5:s7 and then ${version//:/-} for url, wrksrc etc? Or other tips to handle this?

**Comment by dicktyr** [comment]
sorry, I don't know
I'm just getting started with void-packages

**Comment by Vaelatern** [comment]
Rebase and push again to resolve the conflicts, so this can be considered?

**Comment by Vaelatern** [comment]
@tonkazoid Yes, it would be cleaner to use `:` and do the shell replacement. It would make it obvious where the replacements were happening.

**Comment by ebfe** [comment]
Unfortunately needs another rebase.

**Comment by Vaelatern** [comment]
@ebfe If not for the rebase, would you consider accepting it?

**Comment by tonkazoid** [comment]
Ay, wanted to know this too.
And if so, is `license="mac"` ok?
http://www.monkeysaudio.com/license.html

**Comment by ebfe** [comment]
> @ebfe If not for the rebase, would you consider accepting it?

Sure, why not?

**Comment by Vaelatern** [comment]
I'd say `license="custom"`

**Comment by Vaelatern** [comment]
the correct fix is to rebase on master again.

**Comment by tonkazoid** [comment]
yes, tried to rebase, but it does not add changes to shlibs. idk

**Pull request closed without merging**
