### PR TITLE
New package: scdoc-1.3.3

### PR DESCRIPTION
**Pull request by julio641742**
The package fails to build in arm(*) due to trying to run and generate a manual page with the binary after compilation inside the chroot because the ARCH and BOOSTRAP arch are different

### CODE REVIEW

**Comment by maxice8** [comment]
This allows compilation, it adds scdoc as a hostmakedependency if we are cross-compiling and changes the HOST_SCDOC variable in the Makefile to /usr/bin/scdoc

diff --git a/srcpkgs/scdoc/template b/srcpkgs/scdoc/template
index ac23719e07..c7f4625d85 100644
--- a/srcpkgs/scdoc/template
+++ b/srcpkgs/scdoc/template
@@ -10,7 +10,14 @@ homepage="https://git.sr.ht/~sircmpwn/scdoc"
 distfiles="https://git.sr.ht/~sircmpwn/scdoc/snapshot/scdoc-${version}.tar.xz"
 checksum=05329057b2452036dc22dfa87f0becf94d1a6f821a01d70984621266ecf2aa52
 
+if [ "$CROSS_BUILD" ]; then
+	hostmakedepends+=" scdoc"
+fi
+
 pre_build() {
+	if [ "$CROSS_BUILD" ]; then
+		sed -i 's|^HOST_SCDOC=.*|HOST_SCDOC=/usr/bin/scdoc|g' Makefile
+	fi
 	sed -i "s/\" VERSION \"/ ${version}/g" src/main.c
 }

**Comment by maxice8** [comment]
herp derp, sorry i fucked up things while rewriting this to be nicer.

change `make_build_args+=` to `make_install_args=` , you can't append to empty strings on bash apparently.

**Comment by julio641742** [comment]
Even if I changed the *args* it did nothing to change which binary to call, so I did what you suggested first and it works

**Comment by julio641742** [comment]
anything else i have to change???

**Comment by maxice8** [comment]
On Tue, May 29, 2018 at 05:44:24PM -0700, Julio Galvan wrote:
> anything else i have to change???
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/voidlinux/void-packages/pull/14333#issuecomment-392994222

lgtm, i'd ask nicely on #xbps for a Void Linux member to review and merge.

**Pull request closed without merging**
