### PR TITLE
ladish: fix aarch64

### PR DESCRIPTION
**Pull request by Johnnynator**
depends on #8426

### CODE REVIEW

**Comment by cr6git** [comment]
Failed because [connection timed out](https://travis-ci.org/voidlinux/void-packages/jobs/290855819#L887). 
Use the new repository from [#8426](https://github.com/voidlinux/void-packages/pull/8426).

**Comment by cr6git** [comment]
Failed because [connection timed out](https://travis-ci.org/voidlinux/void-packages/jobs/290855819#L887). 
Try to push again.

**Comment by Gottox** [comment]
no new push needed, I'm restarting the build.

**Comment by Johnnynator** [comment]
The error you get atm with tavis is because a2jmidid and not ladish, it will only work after #8426 is merged because it is a dependency of ladish

**Comment by cr6git** [comment]
`a2jmidid` is ok now.

**Comment by Johnnynator** [comment]
So Travis is happy now

**Comment by cr6git** [comment]
I hope it will be merged soon, in order to build `cadence`.

**Comment by Johnnynator** [comment]
@cr6git this will only fix the shown errors, for cadence to work PyQt4 has to be made cross compilable first.

**Comment by cr6git** [comment]
Me ? I have no idea how to make PyQt4 cross compilable. 😕 
Maybe the maintainer @asergi has an idea ?

**Comment by Johnnynator** [comment]
@cr6git I know that, I just wanted to say that it doesn't make a difference when this PR get merged because cadence will not work yet.

**Comment by cr6git** [comment]
So, for the moment we can't do any more ? 😞

**Comment by cr6git** [comment]
Good! :)

**Pull request merged**
