### PR TITLE
linux4.16: Re-enable kernel modules on Linux 4.16

### PR DESCRIPTION
**Pull request by faulesocke**
This re-enables the rtsx kernel modules that were enabled on previous versions. This is required to use the Realtek SD card readers.

This is a squashed and corrected version of #14217. I've correct commit message wording and revbumped the package.

### CODE REVIEW

**Comment by Johnnynator** [comment]
@faulesocke 
```
scripts/kconfig/conf  --oldconfig Kconfig
*
* Restart config...
*
*
* MMC/SD/SDIO card support
*
MMC/SD/SDIO card support (MMC) [M/n/y/?] m
  MMC block device driver (MMC_BLOCK) [M/n/?] m
    Number of minors per block device (MMC_BLOCK_MINORS) [8] 8
  SDIO UART/GPS class support (SDIO_UART) [M/n/?] m
  MMC host test driver (MMC_TEST) [N/m/?] n
  *
  * MMC/SD/SDIO Host Controller Drivers
  *
  MMC host drivers debugging (MMC_DEBUG) [N/y/?] n
  Secure Digital Host Controller Interface support (MMC_SDHCI) [M/n/?] m
    SDHCI support on PCI bus (MMC_SDHCI_PCI) [M/n/?] m
      Ricoh MMC Controller Disabler (MMC_RICOH_MMC) [Y/n/?] y
    SDHCI support for ACPI enumerated SDHCI controllers (MMC_SDHCI_ACPI) [M/n/?] m
    SDHCI platform and OF driver helper (MMC_SDHCI_PLTFM) [M/n/?] m
  SDHCI support for Fujitsu Semiconductor F_SDH30 (MMC_SDHCI_F_SDH30) [N/m/?] n
  Winbond W83L51xD SD/MMC Card Interface support (MMC_WBSD) [M/n/?] m
  TI Flash Media MMC/SD Interface support (MMC_TIFM_SD) [M/n/?] m
  MMC/SD/SDIO over SPI (MMC_SPI) [M/n/?] m
  ENE CB710 MMC/SD Interface support (MMC_CB710) [M/n/?] m
  VIA SD/MMC Card Reader Driver (MMC_VIA_SDMMC) [M/n/?] m
  VUB300 USB to SDIO/SD/MMC Host Controller support (MMC_VUB300) [M/n/?] m
  USB SD Host Controller (USHC) support (MMC_USHC) [M/n/?] m
  Renesas USDHI6ROL0 SD/SDIO Host Controller support (MMC_USDHI6ROL0) [N/m/?] n
  Realtek PCI-E SD/MMC Card Interface Driver (MMC_REALTEK_PCI) [N/m/?] (NEW) 
```
This doesn't built because it expects `MMC_REALTEK_PCI` to be set.

**Comment by faulesocke** [comment]
I must admit, I haven't tried building it, because Oreo said it worked fine. Added it to my build queue (currently my machine is busy building other packages), will update my PR when I got it working.

**Comment by Johnnynator** [comment]
I only checked the travis output. Also normally you should add `[ci skip]` to the commit message of packages that need more then 45 minutes on Travis to build (e.g. the kernel, Firefox, chromium ...), But it seems this time it wasn't bad not adding it :D.

**Comment by Oreo639** [comment]
I did get some of those, which I just selected as modules, I thought that that was something else (What I mean is that I added commented out text so I could know what the modules I changed were, just in case I forgot for whatever reason, and I thought they had to do with that, I didn't read over them very carefuly).
Anyway checking my current config, they are enabled as modules (the realtek_pci and realtek_usb).

**Comment by faulesocke** [comment]
Okay, this one builds and correctly turns on the SD card slot. Can be merged.

**Comment by faulesocke** [comment]
The build took about 20 GiB for the masterdir, is this normal? (When building arm kernels, they usually take <8GiB so I just symlink them into my /tmp and keep everything in RAM)

**Comment by freshprince** [comment]
seems like these changes have been merged with https://github.com/voidlinux/void-packages/commit/43df6f59ddfa9a7f7f645313e8d65a1b99ad8549

**Pull request closed without merging**
