### PR TITLE
go-ipfs: update to 0.4.11.

### PR DESCRIPTION
**Pull request by CMB**
This does not crossbuild anymore and I can't figure out why.
Looks like it tries to rebuild the go runtime or something on
cross builds.
If someone figures that out before merging, that'd be great.

### CODE REVIEW

**Comment by Vaelatern** [comment]
testing cross build fix now

**Comment by Vaelatern** [comment]
eh, `collect2: fatal error: cannot find 'ld'`
Can you remove nocross so relevant logs are generated?

**Comment by lemmi** [comment]
4.11 introduces plugins. I think we should make the subpackages. Currently there is a **git** and **ethereum** plugin.

**Comment by CMB** [comment]
> Can you remove nocross so relevant logs are generated?

Yes.  Pushed without nocross.

**Comment by CMB** [comment]
Fixed the cross-build issue and pushed.  Builds cleanly on travis for
everything.

**Pull request merged**
