### PR TITLE
New package: python-xlwt-1.1.2

### PR DESCRIPTION
**Pull request by diogoleal**

### CODE REVIEW

**Comment by Vaelatern** [comment]
Is this a dependency for something else?

**Comment by diogoleal** [comment]
Yes, this and python-xlrd are dependencies for rows.
https://github.com/turicas/rows

**Comment by Vaelatern** [comment]
Why not just `pip install`?

**Comment by diogoleal** [comment]
I made all the changes you suggested.

**Comment by diogoleal** [comment]
Is possible, but I don't like to use pip or other package manager the programming language.

**Comment by the-maldridge** [comment]
@diogoleal can you drop the 3.4 from the function call and the link?  We use only the major version number now for that.  Ping me once you've made those changes, this looks pretty much ready to merge.

**Comment by diogoleal** [comment]
@the-maldridge  Is that what you want?

**Comment by the-maldridge** [comment]
@diogoleal not quite.  You need the python3 subpkg, but not the one that explicitly states 3.4 in the version number.  Add back the python3 subpkg and it should be fine, I think what you had was correct.

**Comment by asergi** [comment]
Obsolete. Feel free to resubmit it.

**Pull request closed without merging**
