### PR TITLE
New package: joe-4.0

### PR DESCRIPTION
**Pull request by diogoleal**

### CODE REVIEW

**Comment by pullmoll** [comment]
Change
```
${SOURCEFORGE_SITE}/project/joe-editor/JOE%20sources/${version}/${pkgname}-${version}.tar.gz
```
to
```
${SOURCEFORGE_SITE}/project/joe-editor/JOE%20sources/${pkgname}-${version}/${pkgname}-${version}.tar.gz
```

**Comment by diogoleal** [comment]
variable distfiles fixed!

**Comment by pullmoll** [comment]
:+1:
I'm just not certain if there should be a `conf_files="/etc/joe/joerc …"` added and thus leave the merge to others.

**Comment by diogoleal** [comment]
Added variable $conf_files.

This package conflicts with jupp, how should I proceed ?

**Comment by pullmoll** [comment]
Hmm.. the obvious: you should add `conflicts="jupp>=0"` and ideally create a pr for `jupp` that adds `conflicts="joe>=0"` as well.

**Pull request merged**
