### PR TITLE
firefox-esr: update to 45.1.0

### PR DESCRIPTION
**Pull request by yopito**
runtime is basically fine with x86_64 (glibc) for me. Micmics packaging of Firefox (46): same patches, disabled gstreamer. Main difference with FF46: gtk3 build option is disabled at this point.
Don't know if enabling gkt3 is a good idea or not for FF ESR 45 ?

### CODE REVIEW

**Comment by yopito** [comment]
NB: gtk3 was not used in FF 45 packaging.

**Comment by ebfe** [comment]
gtk3 was also reverted in 46.

**Comment by yopito** [comment]
Indeed, did not checked since 24hours ;). Thanks for the hint.

**Comment by yopito** [comment]
Travis CI fails. lack of memory since no explicit compiler error message ?
For instance, from https://s3.amazonaws.com/archive.travis-ci.org/jobs/126366896/log.txt:
```
rm -f libcommon_audio.a
/builddir/firefox-45.1.0esr/xbps-build/_virtualenv/bin/python /builddir/firefox-45.1.0esr/config/expandlibs_gen.py -o libcommon_audio.a.desc vad_core.o webrtc_vad.o Unified_c_webrtc_common_audio0.o Unified_c_webrtc_common_audio1.o Unified_c_webrtc_common_audio2.o Unified_cpp_webrtc_common_audio0.o Unified_cpp_webrtc_common_audio1.o  
make[3]: Leaving directory '/builddir/firefox-45.1.0esr/xbps-build/media/webrtc/trunk/webrtc/common_audio/common_audio_common_audio'
make[2]: Leaving directory '/builddir/firefox-45.1.0esr/xbps-build'
/builddir/firefox-45.1.0esr/config/recurse.mk:32: recipe for target 'compile' failed
make[1]: *** [compile] Error 2
make[1]: Leaving directory '/builddir/firefox-45.1.0esr/xbps-build'
/builddir/firefox-45.1.0esr/config/rules.mk:547: recipe for target 'default' failed
make: *** [default] Error 2
```

**Comment by ebfe** [comment]
On Thu, Apr 28, 2016 at 06:27:37AM -0700, yopito wrote:
> Travis CI fails. lack of memory since no explicit compiler error message ?
scroll up

```
5465  UnifiedBindings5.o
5466  {standard input}: Assembler messages:
5467  {standard input}:413653: Warning: end of file not at end of a line; newline inserted
5468  {standard input}:413929: Error: unknown pseudo-op: `.cfi_de'
5469  {standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
5470  g++: internal compiler error: Killed (program cc1plus)
5471  0x2ab66fc7478f __libc_start_main
5472          ../csu/libc-start.c:289
5473  Please submit a full bug report,
5474  with preprocessed source if appropriate.
5475  Please include the complete backtrace with any bug report.
5476  See <http://gcc.gnu.org/bugs.html> for instructions.
5477  /builddir/firefox-45.1.0esr/config/rules.mk:956: recipe for target 'UnifiedBindings23.o' failed
5478  make[3]: *** [UnifiedBindings23.o] Error 4
5479  make[3]: *** Waiting for unfinished jobs....
```

**Comment by yopito** [comment]
oops, missed it, thanks for the pointer. I think this is related to Travis CI constrained env: line 5467 makes me think of full FS (no more space). For info, my `masterdir/builddir/` is about 6.8 GB once build of FF ESR was completed.
Already had troubles on Travis while building thunderbird too (log 4+ MB).

**Pull request merged**
