### PR TITLE
sublime-text3: update to 3176

### PR DESCRIPTION
**Pull request by marmeladema**

### CODE REVIEW

**Comment by Dadie** [comment]
Could you update the package to 3176 as it was just released the other day (2018-05-14)?

**Comment by marmeladema** [comment]
@Dadie done

**Comment by Dadie** [comment]
@marmeladema Thank you :)

**Comment by marmeladema** [comment]
@Dadie, do you know who is responsible for accepting this merge request ? Is this "Andrea Brancaleoni <miwaxe@pompel.me>" the maintainer? Should i email him ?

**Comment by Johnnynator** [comment]
No need normally to email him. It will get merged once one of the maintainers has time to review the PR (which not necessarily has to be @thypon ). But currently most of them have their time occupied by other work instead of reviewing PR's which ends in quite long review times until smth gets merged.
Will hopefully get better soon™.

**Comment by marmeladema** [comment]
Thank you very much @thypon  !

**Comment by thypon** [comment]
Since for now the github tasks (issues and prs) are not auto assigned to maintainers it is a good idea to cite me or the involved maintainer.

**Pull request merged**
