### PR TITLE
Bugfix for redis-cli segfaulting on Void Musl x86_64

### PR DESCRIPTION
**Pull request by bitshark**
-Redis-cli binary as-distributed is causing instant-segfault on Void musl x86_64  see #4100

-This commit configures redis to use it's own internal version of jemalloc which is distributed with
the redis source, rather than the system-wide jemalloc.  This solves the segmentation fault bug
on void musl x86_64

Before:
[user@dolphin redis-3.0.7]$ redis-cli
Could not connect to Redis at 127.0.0.1:6379: Connection refused
not connected> quitSegmentation fault

After:
[user@dolphin redis-3.0.7]$ ./src/redis-cli
Could not connect to Redis at 127.0.0.1:6379: Connection refused
not connected> quit

### CODE REVIEW

**Comment by Gottox** [comment]
I'll include this workaround. Nevertheless can you open a seperate issue to fix the real issue?

**Comment by ebfe** [comment]
Not convinced this is a jemalloc problem. Looks more like linenoise is at fault.

**Comment by Gottox** [comment]
This PR breaks cross compiling. Please fix.

**Comment by bitshark** [comment]
I can take a look at the cross compile, but ARM is a bit out of my area of expertise.  If you can offer a suggestion on either (a) how to fix the underling issue causing the segfault (I think it's probably in jemalloc .. what makes you suggest it's linenoise?)  ,  or (b) how I can resolve the build with cross compiling (ie. general tips you could offer), I'd appreciate it, and I'll see what  I can do.  Thanks.

**Comment by xtraeme** [comment]
This PR is unapplicable right now, the issue was fixed.

**Pull request closed without merging**
