### PR TITLE
new package: font-awesome

### PR DESCRIPTION
**Pull request by meowstars**
Install the font font awesome, an iconic font.

Hi,

This is my first package. I got the inspiration from font-sourcecodepro package.
I hope it is good. If not I am ready to change my template to make it perfect :)

Thank you!

### CODE REVIEW

**Comment by steski** [comment]
Looks good. I would use the tags from github for the <code>distfiles</code>. For example:
 
<code>distfiles="https://github.com/FortAwesome/Font-Awesome/archive/v${version}.tar.gz"</code>

 This would remove <code>unzip</code> for <code>hostmakedepends</code> and <code>xbps-src update-check font-fontawesome</code> will be able to find an update.

**Comment by diogoleal** [comment]
I think the package name could be ```font-awesome``` and not ```font-fontawesome```

**Comment by meowstars** [comment]
@diogoleal actually, I think that the name of the font is font awesome that's why I named the package like this.

@steski OK, I will change my source for the github tags :)

**Comment by meowstars** [comment]
I have changed the distfiles source for github tags, as suggested.

**Comment by xtraeme** [comment]
Please rename it to `font-awesome`.

**Pull request merged**
