### PR TITLE
glib: fix on demand init for gquark and gtype

### PR DESCRIPTION
**Pull request by pullmoll**
Besides the quark init on demand, a similar thing is required for `gobject_init()` in `gobject/gtype.c` for the commands like `g-ir-scan` etc. to work right with musl libc.

This fixes NetworkManager `build_option="gir"` for musl libc.

### CODE REVIEW

**Comment by pullmoll** [comment]
A question remaining is if these changes should be scoped by `#if !defined(__GLIBC__)` … `#endif` because for glibc the code works without the overhead of on demand initializations.

**Comment by pullmoll** [comment]
The x86_64 and armv[67]l failures on travis don't happen here. They may be related to `LC_ALL ...` warnings.

**Comment by pullmoll** [comment]
No comment means merge?
This fix is required to fix the `gnome-shell` PIE build, because `gnome-shell` depends on `NetworkManager-1.0.gir`.

**Comment by Vaelatern** [comment]
Nothing glaringly wrong that I could see

**Pull request merged**
