### PR TITLE
sudo: fix flags to enable insults, add license

### PR DESCRIPTION
**Pull request by cr6git**
The flag `-with-all-insults` was obviously not correctly set to enable insults. 
````
  --with-insults          insult the user for entering an incorrect password
  --with-all-insults      include all the sudo insult sets
````

### CODE REVIEW

**Comment by cr6git** [comment]
Travis is complaining about licenses: 
````
srcpkgs/sudo/template:17: license 'BSD', but no use of vlicense
srcpkgs/sudo/template:17: license 'ISC', but no use of vlicense
````

**Comment by Coding-Doctors** [comment]
Have you tested it to need ``--with-insults``? do the insults work without that flag?

**Comment by cr6git** [comment]
Yes. 
Without the flag `--with-insults` during the `do_configure` stage you will see: 
````
checking whether to include insults... no
````

**Comment by Coding-Doctors** [comment]
Thanks for confirming! 👍

**Pull request merged**
