### PR TITLE
New package: schismtracker-20160913

### PR DESCRIPTION
**Pull request by allan**

### CODE REVIEW

**Comment by ebfe** [comment]
cross builds fail with

    configure.ac:63: warning: macro 'AM_PATH_SDL' not found in library
    sh: git: command not found
    sh: git: command not found
    sh: git: command not found
    configure.ac:63: error: possibly undefined macro: AM_PATH_SDL
          If this token and others are legitimate, please use m4_pattern_allow.
          See the Autoconf documentation.

**Comment by pullmoll** [comment]
This perhaps needs SDL-devel in the hostmakedepends as well for autoconf.

**Comment by allan** [comment]
for failing travis builds see #4909

**Comment by ebfe** [comment]
Nope

**Comment by ebfe** [comment]
Thanks @pullmoll  (64374cd30c01e4f6075ae1ebb2b6271018d2cbe9)

**Comment by allan** [comment]
should zap more often...

**Pull request merged**
