### PR TITLE
Use default Monospace font for st.

### PR DESCRIPTION
**Pull request by rogerbraun**
As st configures its font during compile time, running it without the right font can be pretty unusable. If someone wants to run it with a different font they'll have to recompile it anyway.

An example without terminus-font installed:
st_ugly

### CODE REVIEW

**Comment by Duncaen** [comment]
Not sure about this, should we better switch to the default monospace font?

**Comment by rogerbraun** [comment]
@duncaen, which font is that?

**Comment by Duncaen** [comment]
That would be just `Monospace` as an alias to a font, fontconfig chooses.
I have to test if that works.

**Comment by Duncaen** [comment]
In a chroot without DejaVu fonts and Terminus installed i get terminus.
```
[duncan@/home/duncan/repos/github.com/Duncaen/void-packages/masterdir /]$ fc-match Monospace
ter-112n.pcf.gz: "Terminus" "Regular"
```

**Comment by rogerbraun** [comment]
I'll compile it with Monospace and see how it looks.

**Comment by rogerbraun** [comment]
This is how it looks, top is DejaVu as default Monospace font, bottom is Terminus.

st_variants

**Comment by rogerbraun** [comment]
Also, the default font size is really small with 12 pixels... I'd suggest bumping it to 14, but that really is another thing.

**Pull request merged**
