### PR TITLE
ncurses: Generate pkg-config files for devel package

### PR DESCRIPTION
**Pull request by teh-jazzman**

### CODE REVIEW

**Comment by xtraeme** [comment]
What's the reason to close this? seemed ok.

**Comment by teh-jazzman** [comment]
I noticed that the .pc files are only created if pkg-config is installed and the directory /usr/lib/pkgconfig exists. Am I correct in assuming the first is somehow problematic since ncurses is a bootstrap package?

**Comment by teh-jazzman** [comment]
It is building correctly now, but I am not sure if putting pkg-config as a dependency is alright

**Comment by teh-jazzman** [comment]
Dammit, sorry. Apparently I somehow managed to clutter the pull request with old stuff again. I will make a clean one when I know if this is viable.

**Comment by xtraeme** [comment]
Indeed, adding a pkg-config dependency is not a good idea due to base-chroot.

**Comment by teh-jazzman** [comment]
Turns out there is a simple solution. I'll run some tests and then create a new (clean) pull request. Thanks.

**Pull request closed without merging**
