### PR TITLE
gcompat: removed unneeded pre_build function

### PR DESCRIPTION
**Pull request by djames1**
pre_build is no longer needed as they accepted my pull request specifying to use the CC variable rather than hard-coded gcc

### CODE REVIEW

**Comment by Duncaen** [comment]
Its not necessary to increase the revision as it doesn't change the resulting binaries.

**Comment by djames1** [comment]
@Duncaen I have removed the revision bump

**Comment by Vaelatern** [comment]
Did they accept this PR for the version we have, or a newer version?

**Comment by djames1** [comment]
@Vaelatern it is for the version 0.1.0 that we currently have packaged. The pre_build was needed when I originally wrote the template for version 0.0.1.

**Pull request merged**
