### PR TITLE
Run shfmt on all scripts except srcpkgs/

### PR DESCRIPTION
**Pull request by mvdan**
As proposed in https://github.com/voidlinux/void-packages/issues/4746#issuecomment-257049926.

This diff is huge because a lot of files were inconsistently being indented with spaces, so use `git diff -w` for your own sanity. Here: https://clbin.com/e2liY

I added it to the xlint script to avoid introducing new scripts.

Also, since Go isn't available in the image (I assume) this does a download of a binary. Other options could be taken.

CC @ebfe @Vaelatern @dominikh

### CODE REVIEW

**Comment by mvdan** [comment]
Whoops, the travis scripts aren't bash. But most of the files on the repo are. What's the policy here?

**Comment by Vaelatern** [comment]
- Wow that is a lot of changes.
 - From what I saw, they seemed to not change anything at all functionality-wise, but I couldn't be sure (see above)

**Comment by mvdan** [comment]
> Wow that is a lot of changes.

`git diff -w` helps, as well as the fact that srcpkgs is excluded here.

> From what I saw, they seemed to not change anything at all functionality-wise, but I couldn't be sure (see above)

In theory this is just a formatter, so it should not change the program at all. I have a large number of unit tests for all of it and a few other projects are using it, so in practice that should be true too.

> The style seems okay.

To clarify, the style hasn't changed much since the time I opened the issue. Notably, `` `foo` `` is now replaced with `$(foo)`. But otherwise it should be the same.

**Comment by chneukirchen** [comment]
Can you make it indent
```
FOO=BAR \
        foo --bar
```
as-is?

**Comment by chneukirchen** [comment]
There still are spaces around `|` in case, which we don't want.

**Comment by chneukirchen** [comment]
Also I don't think
```
foo \
        || bar
```
is a good idea.

**Comment by mvdan** [comment]
> Can you make it indent
> 
> FOO=BAR \
>         foo --bar
> as-is?

That's a bug, will fix it. Thanks for noticing!

> There still are spaces around `|` in case, which we don't want.

I don't want the tool to have a dozen knobs, so I tried to make the style as consistent as possible. See the discussion in the original issue. Words are always spaced at either side, so I don't see why this one should be an exception.

> Also I don't think
> 
>    foo \
>            || bar
>
> is a good idea.

Also mentioned in the original issue - I'm not too fussed either way, but this form seems to be preferred by some popular styles like Google's. I haven't heard any point against this style other than personal preference, so I haven't changed it.

As before, the less knobs, the better. In any case, I think thinking too much about what style to enforce is bikeshedding - and I've certainly put a lot of thought into it so far :)

**Comment by mvdan** [comment]
@chneukirchen actually, I can't reproduce your first issue:

```
 $ cat f.sh
FOO=BAR \
        foo --bar
 $ shfmt f.sh
FOO=BAR \
        foo --bar
```

**Comment by chneukirchen** [comment]
I don't see anything on wrapping in the Google style guide line, and I think having to add `\` is not intuitive.

**Comment by chneukirchen** [comment]
Ah, what I meant actually happened in `common/build-style/python-module.sh`, and it's

```
env FOO=BAR \
       FOO=BAR \
                foo --bar
```

Guess that's a semantical difference then...

**Comment by mvdan** [comment]
The page isn't rendering for me on chrome, so linking to the source xml directly:

https://github.com/google/styleguide/blob/7ebdcc4f949907b08694dc6010b518bc303bb373/shell.xml#L333

As for:

```
env FOO=BAR \
       FOO=BAR \
                foo --bar
```

The second level of indentation is nonexistent here, so it's on purpose.

**Comment by mvdan** [comment]
I'll be closing this, since there doesn't seem to be enough interest.

**Pull request closed without merging**
