### PR TITLE
uget: downgrade to stable version

### PR DESCRIPTION
**Pull request by cr6git**
2.1.6 is development version, [latest stable](https://sourceforge.net/projects/urlget/files/uget%20%28stable%29/) is 2.0.10

### CODE REVIEW

**Comment by Vaelatern** [comment]
Inadequate `reverts`
Good form, but in a space separated list, need to list all versions to be reverted.

* 99151d45cf uget: update to 2.1.6.
* 1b60e57b16 uget: rebuild for libressl-2.5.3
* 7e2867760d uget: update to 2.1.5.
* d9681d0783 uget: rebuild for libressl-2.4.3
* 6f8f0d6d67 uget: update to 2.1.4.
* 6b95fba6ad uget: update to 2.1.3.
* 9d7c47d940 uget: update to 2.1.2.
* 5b62b54973 uget: new version of libressl
* 7607256e15 uget: update to 2.1.1.
* e6375f0ced uget: update to 2.1.0.

Thank you!

**Comment by cr6git** [comment]
@Vaelatern Done.

**Comment by cr6git** [comment]
Hey what's wrong with Travis ??

**Comment by cr6git** [comment]
are you okay, @Vaelatern ?

**Comment by cr6git** [comment]
12 days and nothing appens... ok I close.

**Pull request closed without merging**
