### PR TITLE
New package: xbmc-adult-1.0.6

### PR DESCRIPTION
**Pull request by beefcurtains**
This is a nice alternative to using Adobe Flash (which RMS doesn't approve) to watch porn. Full-screen, no ads, what's not to like? Enjoy! :point_right::ok_hand:

### CODE REVIEW

**Comment by Gottox** [comment]
I'm not sure, that this should be part of void. Interested users can install this repository in the home directory.

**Comment by dominikh** [comment]
I don't disagree with porn, but I'm not sure we should start packaging arbitrary Kodi repositories.

**Comment by beefcurtains** [comment]
@Gottox: prude

@dominikh  This isn't an arbitrary repository, it's the one and only adult repo

**Comment by dominikh** [comment]
I'll rephrase: I don't think we should package Kodi repositories.

**Comment by Gottox** [comment]
@beefcurtains In some cases yea. ;) But I'm with @dominikh here.

**Comment by xtraeme** [comment]
I agree with @Gottox 

There's no reason to pkg this if the user is able to download it and put it into its home directory.

**Pull request closed without merging**
