### PR TITLE
Texlive2018

### PR DESCRIPTION
**Pull request by Johnnynator**
Updated with support for aarch64 and x86_64-musl.
The texlive installer doesn't detect musl so I add `-force-platform x86_64-linuxmusl` to the `INSTALL`.
Everything else is just copied form the 2017 template.

@chneukirchen

### CODE REVIEW

**Comment by Piraty** [comment]
well done.
looks like texlive finally ships precompiled binaries for musl, [see here](https://www.tug.org/texlive/doc/texlive-en/texlive-en.html#x1-240003.2.1).
Probably worth to mention @svenper

**Comment by Johnnynator** [comment]
> Would it be possible to make the paths relative in the profile or would this fuck up some other things?
I don't that would work properly, but I will take a look.

**Comment by Johnnynator** [comment]
I updated the profile to use relative Path but haven't verified yet if it doesn't break runtime.

**Comment by svenper** [comment]
Nice! `musl` support allows us to stay up do date with binaries more than once a year. Unless we really want dynamically linked binaries...

**Pull request merged**
