### PR TITLE
New package: mate-tweak-18.04.0.

### PR DESCRIPTION
**Pull request by cr6git**
resolves [#9043](https://github.com/voidlinux/void-packages/issues/9043)

### CODE REVIEW

**Comment by maxice8** [comment]
Add `resolves` before the Issue number so when this is merged the Issue will be closed automatically

**Comment by cr6git** [comment]
like that ?

**Comment by maxice8** [comment]
no capital R

**Comment by cr6git** [comment]
ok, I didn't know this function.

**Comment by cr6git** [comment]
Updated to the latest version.

**Pull request closed without merging**
