### PR TITLE
lilypond: fix cross compilation

### PR DESCRIPTION
**Pull request by newbluemoon**
The issue in cross building lilypond is its documentation: it uses help2man to generate the man pages and also creates the texinfo files using the lilypond binary.

My error was that I used the wrong option to disable the documentation which only partially disabled it and so man pages and texinfo files were created. But this failed in a cross build, of course. That’s fixed now. Man pages and texinfo doc are now also contained in the separate lilypond-doc (they were excluded to avoid confilict with the lilypond package). And I cleaned up the template a bit.

Tested the cross build on a Raspberry Pi (armv7l) and everything was fine.

cc @lemmi

### CODE REVIEW

**Comment by lemmi** [comment]
I'm building this locally right now, since travis doesn't like the huge output.

**Comment by newbluemoon** [comment]
Is it ok to use `[skip ci]` for future updates with this package?

**Comment by lemmi** [comment]
Sure, just ping me, so I don't overlook the PR.

**Comment by newbluemoon** [comment]
Ok. Thanks! :)

**Pull request merged**
