### PR TITLE
linux4.16: update to 4.16.12

### PR DESCRIPTION
**Pull request by Oreo639**
Updates the linux kernel to the latest release (4.16.12).
Also adds the rtsx modules from #14249

### CODE REVIEW

**Comment by Oreo639** [comment]
Forgot to enable some the modules for i386. It should be fine now (hopefully).

**Comment by Oreo639** [comment]
Seems fine now.

**Comment by maxice8** [comment]
please add [ci skip] to the pull request or commits to avoid hogging travis.

**Comment by Oreo639** [comment]
Thanks.

**Comment by Oreo639** [comment]
Yep, I'll update the pr as soon as I am available.

**Pull request closed without merging**
