### PR TITLE
New package: crystal-bin-0.24.0

### PR DESCRIPTION
**Pull request by LVMBDV**
This precompiled binary is meant to be used to build Crystal from source (requested #1781) as it requires a binary of itself to compile. The script workaround was needed because the precompiled binary doesn't look for the standard library in the right places.

### CODE REVIEW

**Comment by LVMBDV** [comment]
https://travis-ci.org/voidlinux/void-packages/jobs/313157340
Sorry, missed this one since I was working only on x86_64. I don't think there's a clean solution since files in distfiles are meant to be arch-agnostic source files. Maybe choose only one arch?

**Comment by aeosynth** [comment]
one issue with crystal on void is libressl support: https://github.com/crystal-lang/crystal/issues/4676. not sure if you want to handle that somehow.

**Comment by LVMBDV** [comment]
Yeah, that seems like a problem. Let's hold off until that issue is resolved/closed. I want crystal on void but I don't want it _that_ bad.

**Comment by aeosynth** [comment]
i mean that issue deals with feature detection, which the void package doesn't have to worry about; a few `sed` calls should be enough. but i haven't looked deeply into it.

**Comment by LVMBDV** [comment]
So I looked into it and the solution doesn't seem so complicated after all :)
Since Void Linux supports only  LibreSSL and LibreSSL currently supports only the 1.0.1 API, we could overwrite the checks for the 1.0.2 and 1.1.0 APIs to return false. Or we could add a pkg-config expression that assumes the library is LibreSSL if libssl version is greater than 2.0.0.

I prefer the first change as it would require us to update the `sed` line only if LibreSSL API compatibility changes which doesn't seem to happen very often.

Also, should I add `pkg-config` to `depends` even though it is not listed as [required](https://github.com/crystal-lang/crystal/wiki/All-required-libraries)?

**Comment by Vaelatern** [comment]
+1 for the overwrite checks, maybe write a pkg-config that checks for `libtls` (which is a libressl only library). Don't bother with adding `pkg-config` to depends unless it's really required at runtime.

**Comment by LVMBDV** [comment]
Added a check for `libtls` as @Vaelatern suggested. CI will fail due to xlint misinterpreting backticks in the sed replacement string as "command" backticks.

**Pull request merged**
