### PR TITLE
Fix default umask maddness.

### PR DESCRIPTION
**Pull request by ayghor**
Default umask 022, set by login.defs, which applies to, but not only

 * tty logins
 * `su` sessions
 * `su -l` sessions

issue #2994

### CODE REVIEW

**Comment by xtraeme** [comment]
I don't get what are you solving here. The current behaviour works just fine:

- home dirs are created with 077
- umask is set to 022 for all users
- umask 022 is also set via pam in required modules

The `umask 022` setting in `/etc/profile` can be overrided via your `~/.profile` or similar for your shell.

Can you explain why your changes are required?

**Comment by ayghor** [comment]
1 - usergroups setting
2 - scattered umask all over teh place

**Comment by xtraeme** [comment]
And can you explain why your changes are better than what's there currently? to me this just adds another stupid indirection.

**Comment by ayghor** [comment]
Usergroups:

Users get `umask 002` when their primary group has the same name. This
is useful when you have `setgid` directories.

Consistency:

This way you set 022 in one place, and 077 in another place. Teh current
state is setting 022 for each shell and on /etc/pam.d{su,su-l}.

I have left some comments about what is being done too.

**Comment by ayghor** [comment]
If people must set in `~/.profile`, it is not default and it won't work on non-login shells.

**Comment by ayghor** [comment]
any thoughts on this?

**Comment by ayghor** [comment]
Once more, I updated teh system and got my users umask broken. It should be 002, not 022. This is a bug.

**Comment by xtraeme** [comment]
#3480 is already there.

**Pull request closed without merging**
