### PR TITLE
New package: meson-0.30.0

### PR DESCRIPTION
**Pull request by muddmaker**
See #3846

### CODE REVIEW

**Comment by Vaelatern** [comment]
Please rebase and upsh again to trigger a travis build

**Comment by muddmaker** [comment]
Rebase with what, exactly? My master branch (which I am merging from) is already up to date.

I'm running:
```
$ git rebase master upstream/master
$ git push origin master
```

**Comment by Vaelatern** [comment]
Then change the commit message to include the version `New package: meson-0.30.0` and force push that.

**Comment by Vaelatern** [comment]
Name should almost certainly be `python3.4-meson`.

**Comment by muddmaker** [comment]
But there is no version of meson for any other version of python, and it isn't a library for python. It's an executable that happens to be written in python.

**Comment by Vaelatern** [comment]
It's a python module, it is listed on pypi, but it's possible it shouldn't be listed as a python module.

**Comment by muddmaker** [comment]
I mean, the `scons` package isn't called `python3.4-scons`, yet it is listed in pypi and is even more of a python module than `meson` is, because it works as a library for a build script. `meson` implements its own language for build scripts. Unless you want to call _every_ application written in python `pythonX.Y-app`, that is.

**Comment by xtraeme** [comment]
If the application does not install any python module you can name it just `meson`.

**Pull request merged**
