### PR TITLE
R: add package R-devel (libR.so + includes)

### PR DESCRIPTION
**Pull request by pullmoll**
This will be required for RStudio

### CODE REVIEW

**Comment by pullmoll** [comment]
I wonder if perhaps the includes + lib should be moved to e.g. /usr/include/R and /usr/lib?

**Comment by xtraeme** [comment]
Looks good to me, but please rebase just to be sure.

**Comment by pullmoll** [comment]
travis fails due to xbps-0.45?

**Comment by xtraeme** [comment]
Should be fixed if you rebase again.

**Comment by pullmoll** [comment]
Nope, it isn't.

**Comment by xtraeme** [comment]
Hmm ok

**Comment by xtraeme** [comment]
I think I fixed it here: https://github.com/voidlinux/void-packages/commit/1ffba0ae712332db5cfed319d4d3aef512cbb672

**Comment by beefcurtains** [comment]
Almost...
```
base-chroot-0.64_1.noarch.xbps: [808B 100%] 48MB/s ETA: 00m00s[K
base-chroot-0.64_1.noarch.xbps: 808B [avg rate: 48MB/s][K
base-chroot-0.64_1.noarch.xbps.sig: [512B 100%] 27MB/s ETA: 00m00s[K
base-chroot-0.64_1.noarch.xbps.sig: 512B [avg rate: 27MB/s][K

[*] Verifying package integrity
xbps-triggers-0.96_1: verifying RSA signature...
ERROR: xbps-triggers-0.96_1: the RSA signature is not valid!
[1m[31m=> ERROR: Failed to install bootstrap packages!
```

**Comment by xtraeme** [comment]
Can't do much here, probably that file wasn't downloaded properly.

**Comment by pullmoll** [comment]
I had the same here some hours ago. Removed xbs-triggers* from /var/cache/xbps and repocache (IIRC).

**Comment by pullmoll** [comment]
It looks like https://github.com/voidlinux/void-packages/commit/1ffba0ae712332db5cfed319d4d3aef512cbb672 is causing trouble now:
$ `./xbps-src -m /tmp/musl -N pkg xfce4`
```
=> xfce4-appfinder-4.12.0_1: building (dependency of xfce4) ...
   [host] pkg-config-0.28_4: not found.
   [host] intltool-0.51.0_1: not found.
   [target] garcon-devel-0.4.0_1: not found.
   [target] libxfce4ui-devel-4.12.1_1: not found.
   [runtime] desktop-file-utils>=0: not found.
   [runtime] hicolor-icon-theme>=0: not found.
=> pkg-config-0.28_4: building (dependency of xfce4-appfinder) ...
=> pkg-config-0.28_4: running do-fetch hook: 00-distfiles ...
mkdir: cannot create directory ‘/host/sources’: File exists
=> ERROR: pkg-config-0.28_4: failed to run do-fetch_00-distfiles() at line 37.
```

It looks as if the `-p` isn't passed to mkdir now?

**Comment by pullmoll** [comment]
It looks like something bad is happening with travis downloading xbps packages and signature files. I hope it's not my fault ;-/ I just rebased after https://github.com/voidlinux/void-packages/commit/212c61eff11bd6dc08b6bf8a9485289076441252 to try again.

**Comment by pullmoll** [comment]
Please hold on. The libR.so without version number causes trouble. I'm trying to make it libR.so.3 and convince R itself to link agains that versioned so.

**Comment by pullmoll** [comment]
No need for a R-devel package, since I can't make RStudio build.

**Pull request closed without merging**
