### PR TITLE
python-apsw: update to 3.11.1r1.

### PR DESCRIPTION
**Pull request by bra1nwave**

### CODE REVIEW

**Comment by pullmoll** [comment]
You should not remove `version=` because this is a mandatory variable.

To reflect the `r1` in the version you could perhaps use `version=3.11.1.1` and reformat this `$version` for the wrksrc and distfile like `${version%.*}-r${version##*.}`.

**Comment by pullmoll** [comment]
Oops! Disregard the comment, I overlooked the `version=` line in the diff.

**Comment by bra1nwave** [comment]
No problem. Thanks anyway :)

**Comment by Vaelatern** [comment]
Why a release candidate (if I'm reading the version line correctly)

**Comment by bra1nwave** [comment]
Well, it's not a release candidate. The upstream dev names his releases like this. See: https://github.com/rogerbinns/apsw/releases

**Pull request merged**
