### PR TITLE
Manual.md: add note about supplying licenses

### PR DESCRIPTION
**Pull request by steski**
This just adds a note about supplying licenses with packages. Are there any other licenses I should include?

### CODE REVIEW

**Comment by Gottox** [comment]
So, the License basicly says "If you're a nice guy, add the license?". Damn I hate it, when I feel like I need a lawyer for software development.

**Comment by chneukirchen** [comment]
shall: expressing a strong assertion or intention.

So please do it.

**Comment by steski** [comment]
So this is in reference to #2274 and a couple others alike.

**Comment by dominikh** [comment]
I have a strong feeling that we will need to go over a lot of our packages and update them to include the license files.

**Comment by steski** [comment]
http://dictionary.reference.com/browse/shall
(in laws, directives, etc.) must; is or are obliged to

**Comment by steski** [comment]
Apache-2.0

4. Redistribution. You may reproduce and distribute copies of the Work or Derivative Works thereof in any medium, with or without modifications, and in Source or Object form, provided that You meet the following conditions:

You must give any other recipients of the Work or Derivative Works a copy of this License; and

**Comment by dominikh** [comment]
> a copy of this License

Does "this License" include the copyright notice? Because if not, don't we already fullfil that requirement by having `/usr/share/licenses/Apache-2.0`?

**Comment by steski** [comment]
@dominikh Yeah, I think your right.

**Comment by thypon** [comment]
i think however, to be conservative, that an automatic `xbps-src` pass that vlicense /(LICENSE|COPYING)(\.(md|txt))?/ should solve this problem.

**Pull request merged**
