### PR TITLE
New package: ffmpegthumbnailer-2.0.10

### PR DESCRIPTION
**Pull request by pullmoll**

### CODE REVIEW

**Comment by xtraeme** [comment]
This file is in a wrong path: `
/home/travis/build/voidlinux/void-packages/masterdir/destdir//ffmpegthumbnailer-2.0.10/usr/share/man1/ffmpegthumbnailer.1`

**Comment by xtraeme** [comment]
Please run:

```
$ cat usr/lib/pkgconfig/libffmpegthumbnailer.pc
```

**Comment by pullmoll** [comment]
Hm.. moving usr/man to usr/share/man is not sufficient then. I'll have to patch something...

**Comment by xtraeme** [comment]
I'd like to see the contents of `libffmpegthumbnailer.pc` yet.

**Comment by pullmoll** [comment]
I got you wrong and thought _I_ should have a look:
```
prefix=/usr
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: libffmpegthumbnailer
Description: Generates thumbnails for movie files
Version: 2.0.10
Libs: -L${libdir} -lffmpegthumbnailer
Libs.private: -L -lavcodec -lavutil -lavformat -lswscale /usr/lib64/libjpeg.so /usr/lib64/libpng.so /usr/lib64/libz.so
Cflags: -I${includedir}
```

**Comment by xtraeme** [comment]
As you can see, to link against `libffmpegthumbnailer` some additional libs are required `libavcodec, libjpeg, etc`.... that means that the `-devel` pkg is missing those deps.

This is a general problem for all new packagers that don't pay attention to the required dependencies in development packages.

**Comment by xtraeme** [comment]
Solution to what I said above:

```
foo-devel_package() {
   depends="${makedepends} ${sourcepkg}>=${version}_${revision}"
   ...
}
```

**Comment by pullmoll** [comment]
Ok, I see the problem.. without that you would always have to manually add the (unrecorded) dependencies. I'll add that and rebase

**Comment by xtraeme** [comment]
Exactly.

**Comment by pullmoll** [comment]
Could the build scripts detect this situation and warn, just like in the case of missing common/shlibs entries?

**Comment by pullmoll** [comment]
Hmm.. the libffmpegthumbnailer.pc file doesn't seem to have changed here.

**Comment by xtraeme** [comment]
Dependency names in pkg-config files wouldn't match package names, so that a mapping would still be necessary.

**Comment by pullmoll** [comment]
like here with ffmpeg-devel giving libavcodec, libavutil and libavformat.. I see.

**Pull request merged**
