### PR TITLE
New package: autojump-22.3.4

### LINKED ISSUE #4438: Package request: autojump
I use this program intensively on my arch setup.
It's ``` cd ``` that easily navigate in directories.
https://github.com/wting/autojump

### PR DESCRIPTION
**Pull request by the-maldridge**
Resolves #4438.

This has got a fairly convoluted installer, thus the need for the custom do_install().  As this isn't a python module I don't really see much point in building it against anything but the default system python.

### CODE REVIEW

**Comment by Vaelatern** [comment]
`noarch=yes`

**Comment by Vaelatern** [comment]
An `INSTALL.msg` is probably in order for the installer's notification that:
```
Please manually add the following line(s) to ~/.shrc:
	[[ -s /destdir//autojump-22.3.4/etc/profile.d/autojump.sh ]] && source /destdir//autojump-22.3.4/etc/profile.d/autojump.sh
```

**Comment by Vaelatern** [comment]
Actually, possibly not, with the file it puts in /etc/profile.d

**Comment by Vaelatern** [comment]
Stripping out the `/destdir//autojump-22.3.4` from `${DESTDIR}/etc/profile.d/autojump.sh` might be a good idea.

**Comment by the-maldridge** [comment]
Anything else on this?

**Pull request merged**
