### PR TITLE
gopass: update to 1.6.10.

### PR DESCRIPTION
**Pull request by SevereOverfl0w**
For some reason #10974 was closed by the author, but this seems to work fine
for me.

### CODE REVIEW

**Comment by pullmoll** [comment]
@maxice8 said he left Void and closed his remaining PRs. Now he seems to be back and is filling up our TODO slots :smile:

**Comment by maxice8** [comment]
On Sun, Jan 28, 2018 at 04:18:32AM -0800, Jürgen Buchmüller wrote:
> @maxice8 said he left Void and closed his remaining PRs. Now he seems to be back and is filling up our TODO slots :smile:

Turns out i really didn't like packaging exheres-0 and exlibs and use gerrit for it and packaging for Void looks much better in comparison.

**Comment by pullmoll** [comment]
I hope some of the other maintainers also take up verifying and merging you PRs. *hint.. hint..*
IMO you should be granted commit rights @maxice8 but that's up to @xtraeme .

**Comment by maxice8** [comment]
On Sun, Jan 28, 2018 at 01:43:56PM +0000, Jürgen Buchmüller wrote:
> I hope some of the other maintainers also take up verifying and merging you PRs. *hint.. hint..*
> IMO you should be granted commit rights @maxice8 but that's up to @xtraeme .
> 

Wouldn't make much sense since 99% of what i do is updating stuff other people maintain, i'd have to open a PR eitherway and wait if the maintainer open one of his own or suggest a fix.

**Pull request closed without merging**
