### PR TITLE
New package: sv-netmount

### PR DESCRIPTION
**Pull request by coredumb**
Service to mount/umount network filesystems from fstab

I wasn't sure if there was a default naming for services unrelated to binaries so I used "sv-" as a prefix... Let me know if this should be renamed.

### CODE REVIEW

**Comment by pullmoll** [comment]
You can used "git commit --amend" and "git push -f" for changes on your branch. To squash the currennt changes you can use "git rebase -i HEAD~3" and put an "s" in front of the two Switch license commits :)

**Comment by coredumb** [comment]
Yeah my bad I was lazy and didn't want to commit or stash some changes I'm working on so I couldn't rebase ;)

**Comment by pullmoll** [comment]
It was no demand, just a hint how to get a quicker review + merge in most cases. BTW the commit message should be "New package: sv-netmount-0.1" - see [CONTRIBUTING.md](https://github.com/voidlinux/void-packages/blob/master/CONTRIBUTING.md#committing-your-changes)

**Comment by coredumb** [comment]
Fixed my commits ;)

**Pull request closed without merging**
