### PR TITLE
qutebrowser: update to 1.0.3

### PR DESCRIPTION
**Pull request by NoctuaNivalis**
Something went wrong with the release, hence the strange download URL.

### CODE REVIEW

**Comment by newbluemoon** [comment]
Why not, e.g.,

    version=1.0.3
    revision=1
    _srcrev=1
    ...
    distfiles="https://github.com/The-Compiler/${pkgname}/releases/download/v${version}/${pkgname}-${version}-${_srcrev}.tar.gz"

**Comment by NoctuaNivalis** [comment]
Indeed, why not?

**Comment by cr6git** [comment]
`version2=1.0.3-1`
Why this variable version2 ?

**Comment by NoctuaNivalis** [comment]
Indeed, why?

**Pull request merged**
