### PR TITLE
qemu: disable sdl by default, use gtk instead

### PR DESCRIPTION
**Pull request by Gottox**
This pull request disables sdl support in qemu and replaces it with gtk3.

### CODE REVIEW

**Comment by xtraeme** [comment]
Why?

**Comment by Gottox** [comment]
Primarily because window scaling is broken with sdl{,2} which has become pretty annoying since I started using a 4k.

Secondary because of easier accessibility of common commands in the task bar.

**Comment by Gottox** [comment]
see this for example:
screenshot from 2017-06-07 10-21-12

**Comment by xtraeme** [comment]
Ok, makes sense. Thanks.

**Pull request merged**
