### PR TITLE
libu2f-host: fix udev rules

### PR DESCRIPTION
**Pull request by the-maldridge**
anything less than 777 doesn't seem to work.

### CODE REVIEW

**Comment by ebfe** [comment]
Whatever the problem is, making security related devices world writable doesn't look like the right solution.

**Comment by ebfe** [comment]
The question is why the `TAG+=uaccess` doesn't work. The old version used `GROUP="plugdev", MODE="0660"` https://github.com/Yubico/libu2f-host/blob/master/70-old-u2f.rules.

**Comment by ebfe** [comment]
#4909

**Comment by ebfe** [comment]
Apparently `TAG+=uaccess` is systemd thing.

**Comment by the-maldridge** [comment]
yes, tags are only applied if the system was booted with systemd, otherwise they are silently ignored.  I can revert to the old group, but users seemed more applicable.

**Comment by the-maldridge** [comment]
Anyone else want to weigh in on what the system group should be?  The build passes now that the proot issues have been dealt with.

**Pull request closed without merging**
