### PR TITLE
bash: source system bashrc on login

### PR DESCRIPTION
**Pull request by lemmi**
This adds /etc/profile.d/bash.sh
```
# Bash login shells only run /etc/profile
# Bash non-login shells run only /etc/bash/bashrc
# We want to source /etc/bash/bashrc in any case
```

### CODE REVIEW

**Comment by uggedal** [comment]
-1

**Comment by Duncaen** [comment]
Isn't this what /etc/skel/.bashrc does?

**Comment by uggedal** [comment]
No, login shells don't source `~/.bashrc`

**Comment by lemmi** [comment]
it isn't used and i'm preparing the change to base-files.
the alternative is to remove the systemwide /etc/bash/bashrc sourcing from bash, fix the skels to point to that.
this is close to what gentoo does.

**Comment by Duncaen** [comment]
But ``/etc/skel/.bash_profile`` sources ``~/.bashrc``

**Comment by lemmi** [comment]
exactly, and i'm doing now the same thing system-wide

**Pull request merged**
