### PR TITLE
Build glibc with --enable-obsolete-nsl for the cross-* packages

### PR DESCRIPTION
**Pull request by Hoshpak**
follow-up to #7928 regarding #7846

### CODE REVIEW

**Comment by ebfe** [comment]
@chneukirchen can this be merged as is or does it need some intervention on the builders?

**Comment by ebfe** [comment]
And somewhat unrelated: shouldn't we pull in the glibc patches here too?

**Comment by Gottox** [comment]
@chneukirchen ping

**Comment by chneukirchen** [comment]
Should work, no?

**Comment by Hoshpak** [comment]
Unless there's some dark magic on the builder which requires re-bootstrapping of some kind, it should be fine. Building the packages locally worked fine and the next cross-build just picked up the new revisions and used them for the build.

**Comment by Gottox** [comment]
Please resolve conflicts and get this merged.

**Comment by Hoshpak** [comment]
rebased and resolved the conflicts.

**Pull request merged**
