### PR TITLE
New package: jeti-filemanager-1.1.2

### PR DESCRIPTION
**Pull request by mrshampoo**
ok i hate to do these pull request all the time, wheen i know i bother you. but i want this up!
i am a noob ok. i know i should have just the jeti branch and not closed it. but i just got so tired of seeing all those 30 commits that i didn't know hove exactly thy got there, or how to get rid of them.. at least i am rid of them now, and have removed the wrk.. what ever the line said..

### CODE REVIEW

**Comment by mrshampoo** [comment]
WHOOOOHOOO! :DD

**Comment by mrshampoo** [comment]
it is in right? :D

**Comment by mrshampoo** [comment]
it is in :D :D :D!! thank you pullmoll!! <3

**Comment by logenkain** [comment]
And then I run "jeti" and I get "Segmentation fault"

**Comment by mrshampoo** [comment]
aw now... make an it an issue on the jeti git.. run jeti with -l 4 or 5
# jeti -l 4
and post it in the issue thread ;)

**Comment by mrshampoo** [comment]
the jeti.log file that is ;)

**Comment by mrshampoo** [comment]
@uggedal 
\# jeti -l 1
will show only direct errors in the jeti.log that appers in the current folder if you want to solve it your self ;)

**Comment by mrshampoo** [comment]
would actully love to here of some more bugs, i currently only can think of 2 that i can fix untill next update :)

**Comment by pullmoll** [comment]
Ususally Void packages are for software which at least works to some extent.
A crash at simply running a program is IMO definitely not ready for a release.

I didn't know that or otherwise I wouldn't have merged the pull request.
:sob:

**Comment by mrshampoo** [comment]
oh, im sorry... 
hopefully it isn't something fundamentally wrong. just wrong terminal in jeti.rc or something...
it hasen't crashed on ether linux mint or my void yet simply buy starting it.
but it is a open source projet by a amateur...

**Comment by mrshampoo** [comment]
@uggedal 
https://github.com/mrshampoo/jeti-filemanager/issues
;)

**Comment by mrshampoo** [comment]
aha! hmm i think ifound the issue (i belive i managed reproduced it) jeti cant find the rc at all... i remember i have actually fixed this issue before,  and tested and stuff... it has reapperd fore some unknown reason. 
fix by eather copying jeti.rc to ~/.jeti.rc or run jeti with -c 
\# jeti -c /share/jeti/jeti.rc
i have probably removed some line by mistake when making stuff more slim code

**Comment by mrshampoo** [comment]
i will try to make an update tomorrow ;) to fix this

**Comment by mrshampoo** [comment]
there is now an update waiting, this time test it ;)
https://github.com/voidlinux/void-packages/pull/4042

**Pull request merged**
