### PR TITLE
xbps-src: Implement XBPS_DISTFILES_MIRROR

### LINKED ISSUE #1372: Idea: Implement XBPS_DISTFILES_MIRROR
To reduce download times and impact on many source servers, it would help if a (list of) mirror site(s) for source packages could be provided through etc/conf.

For example for me `http://mirror.netcologne.de/gentoo/distfiles` carries many of the source files required to build packages. Another example may be some source file repository in a local `file:///some/where/distfiles` path or some local network http or ftp server.

The location(s) specified in XBPS_DISTFILES_MIRROR should be queried for a distfile first and the download location specified in the template should be used only as a fallback, if the download itself or the checksum of the downloaded distfile fails.

### PR DESCRIPTION
**Pull request by pullmoll**
Closes #1372
- You may specify one or more alternate download locations for distfiles
- For the file:// scheme to work, manual mount below masterdir/host is required
- Works best with a local network HTTP or FTP server

### CODE REVIEW

**Comment by xtraeme** [comment]
My concern about this patch is this needs manual intervention to make it work in the chroot.

**Comment by xtraeme** [comment]
I could add an option to xbps-uunshare/uchroot to bind mound an additional dir, but first we'd need to have a fixed path in /host.

This could be added for xbps-0.45.

**Comment by pullmoll** [comment]
For the file:// scheme, yes. HTTP and FTP mirrors work fine. Unfortunately I can't bind mount a specified path automagically in xbps-src, because that would need su(do).

**Comment by xtraeme** [comment]
No, you don't need to be root with xbps-uunshare/uchroot.

**Comment by pullmoll** [comment]
Okay, you know better :) An alternate way could be to define XBPS_HOSTDIR to some other local path and under that path mount your distfiles path below e.g. source/distfiles...

**Comment by xtraeme** [comment]
This is a good idea.

**Comment by pullmoll** [comment]
Since you know better, perhaps modify the expert description along those lines?

**Comment by xtraeme** [comment]
I would suggest `/host/sources/mirror` or `/host/sources/distfiles`.

**Comment by xtraeme** [comment]
Sure, will do once the implementation is finished.

**Comment by pullmoll** [comment]
Ah, ok, so you would expect a fixed mountpoint below `/host/sources/somepath` and mount the first (and only) file:// URL's path there?

**Comment by xtraeme** [comment]
@pullmoll are you on IRC? I'd like to talk with you privately.

**Comment by pullmoll** [comment]
Nope, I don't have/use IRC :/

**Comment by xtraeme** [comment]
Please join irc.freenode.net #xbps

**Comment by pullmoll** [comment]
Sorry, I can't now, because I'm away soon. We could discuss by email, if you prefer, or I could try to set up some IRC client next time.

**Comment by xtraeme** [comment]
Ok, no problem. I was going to offer you commit rights to voidlinux.

**Comment by pullmoll** [comment]
No, wait. I'm aboard for just a week or so and wouldn't trust myself enought to commit to void-packages :) I'd rather give me some time until you or others don't have to fix my pull requests anymore.

**Comment by xtraeme** [comment]
Sure, that's ok.

**Comment by xtraeme** [comment]
I've implemented `-b src:dest` in `xbps-uunshare(8)` and `xbps-uchroot(8)` for 0.45.

That means that this issue can be implemented properly once 0.45 is released.

**Comment by pullmoll** [comment]
Great! So one way to go now could be to parse XBPS_DISTFILES_MIRROR for file scheme URLs and

+ create a corresponding path below `masterdir/hostdir/sources/distfiles`
+ bind mount host `/some/path` on `masterdir/hostdir/sources/distfiles/some/path`, probably read only
+ modify `00-distfiles.sh` to prepend not just `/host`, but `/host/sources/distfiles` to the file URLs path.

And when exiting xbps-src, automatically unmount - perhaps also remove mountpoints.

**Comment by pullmoll** [comment]
@xtraeme In 79a361a I tried to add a `setup_distfiles_mirror()` function to create mount points and add corresponding options to `XBPS_CHROOT_CMD_ARGS`. I hope this is (close to) how you meant it should work.

I'm not sure if calling it only when `-z "$IN_CHROOT"` is right, though.

**Comment by xtraeme** [comment]
Now that `xbps-0.45` is out this could be merged, but I'd like to review it a bit more :-)

**Comment by pullmoll** [comment]
It doesn't work as is. I tried again now with xbps-0.45. The problem is in the timing when to bind mount the file:// URLs and exactly where this should happen. I still lack a bit of oversight in the xbps-src and common scripts...

**Pull request closed without merging**
