### PR TITLE
alacritty: update to latest-commit: commit (bot)

### PR DESCRIPTION
**Pull request by Arzte**

### CODE REVIEW

**Comment by Vaelatern** [comment]
Can they please tag versions?

**Comment by mad-s** [comment]
I think the version should be 20180204, as it is not April yet.

**Comment by Coding-Doctors** [comment]
Got the date switched sorry about that, fixed. As far as versions go, from one the maintainers, it'll likely happen once scrollback is implemented. There is a pr open on that repo, but they don't like how some of it is done, and therefore are working on other changes they want to land to make scrollback more performant.

**Comment by Arzte** [comment]
I've updated the template with the current date and commit.

**Comment by Arzte** [comment]
I've updated to the latest commit. Additionally added man pages, bash & zsh completions. (https://github.com/jwilm/alacritty/pull/1133) I'm unsure how long it'll be till this gets merged, but if its going to be a bit longer, it might be worth waiting for [scrollback](https://github.com/jwilm/alacritty/labels/Project%3A%20Scrollback) to land.

**Comment by cr6git** [comment]
[57146b2](https://github.com/voidlinux/void-packages/commit/57146b2a7d3d9ac042de2c16a79cd36af2dc45e1)

**Pull request closed without merging**
