### PR TITLE
redshift: update to 1.9.1 and split GUI

### PR DESCRIPTION
**Pull request by pulux**

### CODE REVIEW

**Comment by Gottox** [comment]
Can you explain why splitting those packages makes sense?

**Comment by pulux** [comment]
so we have a small working app without much deps, and a full featured version with GConf, geoclue, ...
se #1188

**Comment by Gottox** [comment]
I'm not sure about that. @xtraeme mentioned, that it should be split into a -gtk subpackage, this *was* already the case.

Different sets of dependencies are rather done with build_options than through splitting the package.

I don't think this should be merged.

**Comment by xtraeme** [comment]
I don't see any benefit neither :-)

I thought the pkg did not have a -gtk subpackage, but this is not the case.

**Comment by pulux** [comment]
ok

**Pull request closed without merging**
