### PR TITLE
New package: atom-0.186.0

### PR DESCRIPTION
**Pull request by thypon**

### CODE REVIEW

**Comment by bougyman** [comment]
This errors for me when I try to build it.

Here is the fail (at the very end of ./xbps-src pkg atom)
```
=> atom-0.186.0_1: running pre-pkg hook: 05-prepare-32bit ...
=> atom-0.186.0_1: running pre-pkg hook: 06-shlib-provides ...
=> atom-0.186.0_1: running pre-pkg hook: 99-pkglint ...
=> ERROR: atom-0.186.0_1: /bin directory is not allowed, use /usr/bin.
=> ERROR: atom-0.186.0_1: cannot continue with installation!
```
and show-files looks wrong, as well.
./xbps-src show-files atom
```
=> Using `/home/void-packages/hostdir/binpkgs/feature/atom_package' as local repository.
/home/void-packages/masterdir/destdir//atom-0.186.0
/home/void-packages/masterdir/destdir//atom-0.186.0/bin
/home/void-packages/masterdir/destdir//atom-0.186.0/bin/atom
/home/void-packages/masterdir/destdir//atom-0.186.0/bin/apm
/home/void-packages/masterdir/destdir//atom-0.186.0/share
/home/void-packages/masterdir/destdir//atom-0.186.0/share/atom
/home/void-packages/masterdir/destdir//atom-0.186.0/share/atom/LICENSE
/home/void-packages/masterdir/destdir//atom-0.186.0/share/atom/chromedriver
```
...SNIP 14,000 lines...
```
/home/void-packages/masterdir/destdir//atom-0.186.0/share/atom/atom
/home/void-packages/masterdir/destdir//atom-0.186.0/share/atom/libchromiumcontent.so
/home/void-packages/masterdir/destdir//atom-0.186.0/share/atom/libffmpegsumo.so
/home/void-packages/masterdir/destdir//atom-0.186.0/share/atom/libgcrypt.so.11
/home/void-packages/masterdir/destdir//atom-0.186.0/share/atom/libnotify.so.4
/home/void-packages/masterdir/destdir//atom-0.186.0/share/atom/libudev.so.0
/home/void-packages/masterdir/destdir//atom-0.186.0/share/applications
/home/void-packages/masterdir/destdir//atom-0.186.0/share/applications/atom.desktop
/home/void-packages/masterdir/destdir//atom-0.186.0/shlib-requires
/home/void-packages/masterdir/destdir//atom-0.186.0/rdeps
```

Yes that's 14,000 other lines of files that wouldn't fit in this commit. Mostly though I don't think they belong in the root dir of /atom-0.186.0.

**Comment by thypon** [comment]
I think you are using an old non-rebased branch @bougyman

**Comment by thypon** [comment]
@xtraeme https://gist.githubusercontent.com/anonymous/d4a561be2d4b33af232b/raw/stdin .
There is however a problem with .desktop pointing to /destdir instead of /usr/bin

**Comment by bougyman** [comment]
I can't find my previous comment... Install is failing here,

```
bougyman@xena ~/void-packages % ./xbps-src install atom                                                                                                                                                     (git)-[pr/1065] <default> 22:43:14
=> Using `/home/void-packages/hostdir/binpkgs/pr/1065' as local repository.
[*] Updating `http://repo.voidlinux.eu/current/x86_64-repodata' ...
[*] Updating `http://repo.voidlinux.eu/current/nonfree/x86_64-repodata' ...
[*] Updating `http://repo.voidlinux.eu/current/multilib/x86_64-repodata' ...
[*] Updating `http://repo.voidlinux.eu/current/multilib/nonfree/x86_64-repodata' ...
=> Using `/host/binpkgs/pr/1065' as local repository.
=> atom-0.186.0_1: required dependencies:
   [host] git>=0: found git-2.3.1_2 in http://repo.voidlinux.eu/current.
   [host] nodejs>=0.10.0: found nodejs-0.12.0_3 in http://repo.voidlinux.eu/current.
   [host] pkg-config>=0: found pkg-config-0.28_3 in http://repo.voidlinux.eu/current.
   [host] libgnome-keyring-devel>=0: found libgnome-keyring-devel-3.12.0_1 in http://repo.voidlinux.eu/current.
   [target] nodejs>=0.10.0: found nodejs-0.12.0_3 in http://repo.voidlinux.eu/current.
   [target] python<3.0.0: found python-2.7.9_6 in http://repo.voidlinux.eu/current.
   [target] GConf-devel>=0: found GConf-devel-3.2.6_6 in http://repo.voidlinux.eu/current.
   [target] libgnome-keyring-devel>=0: found libgnome-keyring-devel-3.12.0_1 in http://repo.voidlinux.eu/current.
=> atom-0.186.0_1: installing host dependency 'git-2.3.1_2' ...
=> atom-0.186.0_1: installing host dependency 'nodejs-0.12.0_3' ...
=> atom-0.186.0_1: installing host dependency 'pkg-config-0.28_3' ...
=> atom-0.186.0_1: installing host dependency 'libgnome-keyring-devel-3.12.0_1' ...
=> atom-0.186.0_1: running pre-install hook: 00-lib32 ...
=> atom-0.186.0_1: running pre-install hook: 02-script-wrapper ...
=> atom-0.186.0_1: running do_install ...
=> Installing atom in /destdir//atom-0.186.0/usr
Running "install" task
=> ERROR: atom-0.186.0_1: failed to run do_install() at line 26.
```

**Comment by thypon** [comment]
Can't reproduce. It builds without problem on my machine.

**Pull request closed without merging**
