### PR TITLE
New package: fwupd-1.0.4.

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by maxice8** [comment]
Cross-compilation from x86_64 to x86_64-musl is broken with

```
cc -D_FORTIFY_SOURCE=2  -O2 -pipe -mtune=generic -D_GNU_SOURCE  -I/usr/x86_64-linux-musl/usr/include -I/builddir/efivar-0327a3f84412f55761f7eb80606fb3cfa23f4448/src/include/  -specs=/builddir/efivar-0327a3f84412f55761f7eb80606fb3cfa23f4448/gcc.specs  -L.  -Wl,-z,relro -Wl,-z,now -Wl,--as-needed     -L/usr/x86_64-linux-musl/usr/lib -Wl,-z,muldefs        -DEFIVAR_BUILD_ENVIRONMENT -o makeguids makeguids.c guid.c -ldl 
In file included from /usr/x86_64-linux-musl/usr/include/sys/types.h:70:0,
                 from makeguids.c:25:
/usr/x86_64-linux-musl/usr/include/endian.h: In function '__bswap32':
/usr/x86_64-linux-musl/usr/include/endian.h:32:25: error: suggest parentheses around arithmetic in operand of '|' [-Werror=parentheses]
  return __x>>24 | __x>>8&0xff00 | __x<<8&0xff0000 | __x<<24;
                   ~~~~~~^~~~~~~
/usr/x86_64-linux-musl/usr/include/endian.h:32:41: error: suggest parentheses around arithmetic in operand of '|' [-Werror=parentheses]
  return __x>>24 | __x>>8&0xff00 | __x<<8&0xff0000 | __x<<24;
                                   ~~~~~~^~~~~~~~~
/usr/x86_64-linux-musl/usr/include/endian.h: In function '__bswap64':
/usr/x86_64-linux-musl/usr/include/endian.h:37:23: error: suggest parentheses around '+' inside '<<' [-Werror=parentheses]
  return __bswap32(__x)+0ULL<<32 | __bswap32(__x>>32);
         ~~~~~~~~~~~~~~^~~~~
In file included from /builddir/efivar-0327a3f84412f55761f7eb80606fb3cfa23f4448/src/include/efivar/efivar.h:31:0,
                 from makeguids.c:28:
/usr/x86_64-linux-musl/usr/include/byteswap.h: In function '__bswap_32':
/usr/x86_64-linux-musl/usr/include/byteswap.h:14:25: error: suggest parentheses around arithmetic in operand of '|' [-Werror=parentheses]
  return __x>>24 | __x>>8&0xff00 | __x<<8&0xff0000 | __x<<24;
                   ~~~~~~^~~~~~~
/usr/x86_64-linux-musl/usr/include/byteswap.h:14:41: error: suggest parentheses around arithmetic in operand of '|' [-Werror=parentheses]
  return __x>>24 | __x>>8&0xff00 | __x<<8&0xff0000 | __x<<24;
                                   ~~~~~~^~~~~~~~~
/usr/x86_64-linux-musl/usr/include/byteswap.h: In function '__bswap_64':
/usr/x86_64-linux-musl/usr/include/byteswap.h:19:24: error: suggest parentheses around '+' inside '<<' [-Werror=parentheses]
  return __bswap_32(__x)+0ULL<<32 | __bswap_32(__x>>32);
         ~~~~~~~~~~~~~~~^~~~~
cc1: all warnings being treated as errors
In file included from /builddir/efivar-0327a3f84412f55761f7eb80606fb3cfa23f4448/src/include/efivar/efivar.h:23:0,
                 from guid.c:25:
/usr/x86_64-linux-musl/usr/include/endian.h: In function '__bswap32':
/usr/x86_64-linux-musl/usr/include/endian.h:32:25: error: suggest parentheses around arithmetic in operand of '|' [-Werror=parentheses]
  return __x>>24 | __x>>8&0xff00 | __x<<8&0xff0000 | __x<<24;
                   ~~~~~~^~~~~~~
/usr/x86_64-linux-musl/usr/include/endian.h:32:41: error: suggest parentheses around arithmetic in operand of '|' [-Werror=parentheses]
  return __x>>24 | __x>>8&0xff00 | __x<<8&0xff0000 | __x<<24;
                                   ~~~~~~^~~~~~~~~
/usr/x86_64-linux-musl/usr/include/endian.h: In function '__bswap64':
/usr/x86_64-linux-musl/usr/include/endian.h:37:23: error: suggest parentheses around '+' inside '<<' [-Werror=parentheses]
  return __bswap32(__x)+0ULL<<32 | __bswap32(__x>>32);
         ~~~~~~~~~~~~~~^~~~~
In file included from /builddir/efivar-0327a3f84412f55761f7eb80606fb3cfa23f4448/src/include/efivar/efivar.h:31:0,
                 from guid.c:25:
/usr/x86_64-linux-musl/usr/include/byteswap.h: In function '__bswap_32':
/usr/x86_64-linux-musl/usr/include/byteswap.h:14:25: error: suggest parentheses around arithmetic in operand of '|' [-Werror=parentheses]
  return __x>>24 | __x>>8&0xff00 | __x<<8&0xff0000 | __x<<24;
                   ~~~~~~^~~~~~~
/usr/x86_64-linux-musl/usr/include/byteswap.h:14:41: error: suggest parentheses around arithmetic in operand of '|' [-Werror=parentheses]
  return __x>>24 | __x>>8&0xff00 | __x<<8&0xff0000 | __x<<24;
                                   ~~~~~~^~~~~~~~~
/usr/x86_64-linux-musl/usr/include/byteswap.h: In function '__bswap_64':
/usr/x86_64-linux-musl/usr/include/byteswap.h:19:24: error: suggest parentheses around '+' inside '<<' [-Werror=parentheses]
  return __bswap_32(__x)+0ULL<<32 | __bswap_32(__x>>32);
         ~~~~~~~~~~~~~~~^~~~~
cc1: all warnings being treated as errors
```

**Comment by Duncaen** [comment]
Hm why cross compile for the native architecture?
You can bootstrap a musl masterdir on your glibc host.
```
./xbps-src -m masterdir-musl binary-bootstrap x86_64-musl
./xbps-src -m masterdir-musl pkg $foo
```

Including system headers with `-I` isn't a good idea too.

**Comment by maxice8** [comment]
> Hm why cross compile for the native architecture?

i am not

> You can bootstrap a musl masterdir on your glibc host.

i have done that, it works with that but i want to make it work when cross-compiling.

> Including system headers with -I isn't a good idea too.

i have made no changes to the build system.

**Comment by maxice8** [comment]
efivar 34 was properly released, no need for patches anymore, yay

**Pull request closed without merging**
