### PR TITLE
New package: trackma-0.7.4

### PR DESCRIPTION
**Pull request by anjandev**

### CODE REVIEW

**Comment by jnbr** [comment]
there should be `noarch=yes`

**Comment by anjandev** [comment]
@jnbr  done

**Comment by jnbr** [comment]
> @jnbr done

great, but I can not see it in the template. Forgot to add the file before pushing?

**Comment by anjandev** [comment]
@jnbr sorry about that. Just fixed it.

**Comment by anjandev** [comment]
@pullmoll  why was my PR rejected?

**Comment by Johnnynator** [comment]
xD, read the full message. It was included in https://github.com/voidlinux/void-packages/commit/c10578413af80f2492cf8493e8b8d3338318b285 and not rejected

**Comment by anjandev** [comment]
sorry, Im on the web gui and it said closed with unmerged commits

**Comment by pullmoll** [comment]
@anjandev This is how [git-merge-pr](https://github.com/chneukirchen/git-merge-pr) works.
It fetches the PR, then I try to build locally and see if everything is working. When I finally push it to master the original PR will be closed and the commit will marked as your's and me as the committer.

**Comment by anjandev** [comment]
Thank you for teaching me about that. I will definately use that command
for my personal projects. :)

**Pull request closed without merging**
