### PR TITLE
nvidia: add missing symlinks for libnvidia-ptxjitcompiler.so

### PR DESCRIPTION
**Pull request by Hoshpak**
to address #7494

### CODE REVIEW

**Comment by the-maldridge** [comment]
This looks suspiciously like bogus compat symlinks.  Care to expand on why these symlinks should exist?

**Comment by Hoshpak** [comment]
They are needed for certain CUDA applications. The libnvidia-ptxjitcompiler.so symlinks would be set by the nvidia installer if it was run manually, the libnvidia-fatbinaryloader.so would not be set by the installer but are also required according to #7494 .

**Comment by datenwolf** [comment]
It seems like the changes are still not pulled into master. Yesterday I was again running into nonworking CUDA programs on my machine, after a full system update and it was again these symlinkes that were missing.

**Comment by pullmoll** [comment]
nvidia has been updated and it does not contain the creation of symlinks.
@Hoshpak care to update your patch or should I try myself?

**Comment by Hoshpak** [comment]
branch rebased, should be good to go now.

**Pull request closed without merging**
