### PR TITLE
New package: surfraw-2.2.9

### PR DESCRIPTION
**Pull request by evandeaubl**

### CODE REVIEW

**Comment by pullmoll** [comment]
It looks like this package is just (perl) scripts? If this is true, it should be `noarch=yes`.

**Comment by evandeaubl** [comment]
It's pretty much all shell scripts actually, but perl is a dependency because a number of the scripts use it for parsing. I was going to check the manual for a way to specify noarch, and then promptly forgot. :stuck_out_tongue:

**Comment by pullmoll** [comment]
You're quite good at writing templates actually. It looks :ok: to me now.

**Comment by evandeaubl** [comment]
Thanks, appreciate the comment. Compared to writing RPM spec files, xbps templates are heaven. :smiley:

**Pull request merged**
