### PR TITLE
budgie-desktop: update to 10.2.8

### PR DESCRIPTION
**Pull request by mar1n3r0**

### CODE REVIEW

**Comment by Vaelatern** [comment]
This commits should be named as directed by the end of the [Manual (link)](https://github.com/voidlinux/void-packages/blob/master/Manual.md#contributing-via-git).

**Comment by Vaelatern** [comment]
You did not test this locally at all.

**Comment by mar1n3r0** [comment]
Please be more merciful towards newbies. I think those are fixed now, but I still can not properly squash all commits into one. Can you help me achieve that in a neat way ? 
So far I have tried: 

git reset --soft HEAD~3 &&
git commit

This produced even more commits.

And now: 

git rebase -i HEAD~3

Which again caused my local branch the need to be merged with the remote, hence producing again more commits...

**Comment by ebfe** [comment]
There a several ways do it, at least two were given in the comments to your last PR #4875... i don't thinks it's necessary to turn every PR into a tutorial into how to squash commits.

**Comment by mar1n3r0** [comment]
I didn't see any example in my previous PR. Anyways, your comment is not helpful so no need.

**Comment by Gottox** [comment]
```
git pull --all
git reset origin/master
git commit -m "budgie-desktop: update to 10.2.8''
```

**Comment by ebfe** [comment]
You even +1'ed it...

https://github.com/voidlinux/void-packages/pull/4875#issuecomment-252488342
https://github.com/voidlinux/void-packages/pull/4875#issuecomment-252489270

Anyways good luck...

**Comment by mar1n3r0** [comment]
Thanks @Gottox. This had an unpredictable outcome leaving all srcpkgs as modified. Not sure how to proceed with it.

@ebfe None of the suggested solutions worked as you can see in the logs. I +1'ed it because I appreciate any help and suggestions.

**Comment by mar1n3r0** [comment]
Aaand we are finally there bump bump :)

Just FYI the only guide which worked as expected for me was this:

http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request

**Comment by Gottox** [comment]
here we go!

**Pull request merged**
