### PR TITLE
New package: mlocate-0.26.

### PR DESCRIPTION
**Pull request by stpx**

### CODE REVIEW

**Comment by Duncaen** [comment]
adding `#include <paths.h>` to `src/updatedb.c` fixes arm*-musl, i have no idea why x86_64-musl worked.

**Comment by stpx** [comment]
@Duncaen Thanks!

**Comment by xtraeme** [comment]
- The commit message is wrong `coreutils vs findutils`.
- Please use the `g` prefix for `locate`,  `updatedb` and others in findutils.

**Comment by xtraeme** [comment]
:+1:

**Comment by Duncaen** [comment]
I think you breake `/usr/bin/updatedb` in `finutils` if you just rename the files afterwards.
```
: ${frcode:=${LIBEXECDIR}/@frcode@}
: ${bigram:=${LIBEXECDIR}/@bigram@}
: ${code:=${LIBEXECDIR}/@code@}
```

**Comment by stpx** [comment]
```sh
$ xbps-alternatives --set mlocate -g locate
```
Breaks `xlocate`.

cc @chneukirchen

**Comment by chneukirchen** [comment]
xlocate only works with findutils (as by deps), but if the paths change we can fix the script of course.

**Comment by stpx** [comment]
Right... I just wanted to give you a heads up before we merge this.

**Comment by chneukirchen** [comment]
This is missing a config file and a daily cronjob?

**Comment by chneukirchen** [comment]
mlocate should be setgid or something?

**Comment by chneukirchen** [comment]
setgid is not enough here tho?

**Comment by chneukirchen** [comment]
You need a hook to set /usr/bin/mlocate root:mlocate mode 2755

**Comment by dicktyr** [comment]
locate and mlocate each have their own cron.daily script
and `/usr/sbin/run-cron /etc/cron.daily` runs both scripts
instead of only the chosen alternative's script

not really a problem for me but I thought I should mention it

in any case
thank you for the package!

**Pull request merged**
