### PR TITLE
New package: freetds-0.95.19

### PR DESCRIPTION
**Pull request by diogoleal**

### CODE REVIEW

**Comment by pullmoll** [comment]
I see no file `/etc/locales.conf` in the file list. Is it generated at the first run?

**Comment by diogoleal** [comment]
@pullmoll  This file already exists in the tarball.

**Comment by pullmoll** [comment]
Ah, ok, I see it now. It's in the xbps files for musl libc, but no in the ones for glibc.

**Comment by pullmoll** [comment]
Nope, the list of additions to common/shlibs still contains unrelated lines.
Be sure to get it in sync with upstream master, then add your change...

**Comment by pullmoll** [comment]
These are already there in common/shlibs
```
+libcrypto.so.35 libcrypto35-2.2.2_1
+libssl.so.35 libssl35-2.2.2_1
+libtls.so.6 libtls6-2.2.2_1
+libCEGUIBase-0.so.2 cegui-0.8.4_1
+libCEGUIOpenGLRenderer-0.so.2 cegui-0.8.4_1
+libCEGUIOgreRenderer-0.so.2 cegui-0.8.4_1
+libCEGUIIrrlichtRenderer-0.so.2 cegui-0.8.4_1
+libCEGUICommonDialogs-0.so.2 cegui-0.8.4_1
```
and these two are missing according to the build log
=> WARNING: freetds-0.95.19_1: libct.so.4 not found in common/shlibs!
=> WARNING: freetds-0.95.19_1: libsybdb.so.5 not found in common/shlibs!
```

**Comment by pullmoll** [comment]
:+1:

**Comment by diogoleal** [comment]
When changed for  ```vmove /usr/share/${pkgname}/doc ```

``` mv: cannot stat ‘/destdir//freetds-0.95.19//usr/share/freetds-doc/doc’: No such file or directory```
then:
```vmove /usr/share/doc ```

**Pull request closed without merging**
