### PR TITLE
Spotify hotfix 

### PR DESCRIPTION
**Pull request by predme**

### CODE REVIEW

**Comment by Duncaen** [comment]
`version` or `revision` need to be increased or it wouldn't update.

**Comment by predme** [comment]
Went a little fast there, oops! Is there a way to change the commit message after a commit? Not too familiar with git in general.

**Comment by ayghor** [comment]
git commit --amend

**Comment by Duncaen** [comment]
You need to squash your commits too, `git rebase -i HEAD~2` replace `pick` with `fixup` in your seconds commit, then you can use `git commit --amend` to edit the commit message.

And the second change breaks the distfiles urls, you now have two times .96`.

**Comment by ayghor** [comment]
you will need a `git push --force` too

**Comment by predme** [comment]
Would it be okay to close this and re-open it? I did this from the browser and I'm not entirely sure how to fix stuff from here. I just properly set up git locally and modified the template properly etc and am ready to commit.

**Comment by Duncaen** [comment]
I think you can just do `git checkout -b patch-2 && git push -f patch-2` to reuse this pull request.

**Comment by predme** [comment]
There we go! Hopefully it's all correct this time around heh.

**Comment by Duncaen** [comment]
Works, thank you :).

**Comment by ayghor** [comment]
Nice! It was 404ing until this. Patch came just in tiem.

**Pull request merged**
