### PR TITLE
New package: mktorrent-1.0

### PR DESCRIPTION
**Pull request by tonkazoid**

### CODE REVIEW

**Comment by Gottox** [comment]
Looks good :+1:

**Comment by tonkazoid** [comment]
I'm not sure about 'homepage'. Mainsite is http://mktorrent.sourceforge.net/ ... but yes, sourceforge :p 
And i didn't want to mix homepage and distfile

**Comment by beefcurtains** [comment]
Homepage is sf, but it doesn't really matter. You can download the sources on github, so that'll do.

**Comment by beefcurtains** [comment]
Was travis successful? Somehow the results won't show up here. Normally I'd check the list of files in the package for anomalies.

**Comment by Gottox** [comment]
Travis is fine

**Comment by beefcurtains** [comment]
Well then let's roll :)

**Pull request merged**
