### PR TITLE
cava: use bundled iniparser to fix segfault

### PR DESCRIPTION
**Pull request by JayVii**
**Workaround** for #2829 

This pullrequest can be rejected, if someone gets void's [iniparser-package](https://github.com/voidlinux/void-packages/tree/f4fd6b1d9883470e12b314d1de8942a03d3be20e/srcpkgs/iniparser) to work correctly with cava again. 
@pullmoll is the maintainer of that package, so he may have an idea on that.

### CODE REVIEW

**Comment by JayVii** [comment]
Travis failed getting the download-file from github:
```
Certificate verification failed for /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 Extended Validation Server CA
SSL_connect returned 1
https://github.com/karlstav/cava/archive/0.3.5.tar.gz: Operation not permitted

=> ERROR: cava-0.3.5_2: failed to fetch 0.3.5.tar.gz.
```

**Comment by pullmoll** [comment]
We've seen failures with travis-ci and certificate chains in other pull requests already. It is being worked on.

For iniparser I'll check if there are any patches around which could or should be applied. Other than that iniparser is a plain vanilla 4.0 with no frills. And it's just __2__ source files where a bug could hide.

**Comment by pullmoll** [comment]
__OMFG__ - the first function I looked at is like this:
```
/*-------------------------------------------------------------------------*/
/**
  @brief    Copy string in a newly mallocced area
  @param    str  String to copy.
  @return   str  Copied version of the given string allocated with malloc

  Original strdup is not portable, need to implement our own
 */
/*--------------------------------------------------------------------------*/
static char * _strdup(const char *s)
{
    char * copy = (char*) malloc(strlen(s));
    strcpy(copy, s);
    return copy ;
}
```
This is certainly going to write beyond the allocated memory...

If the rest of the code is of the same quality we'd better ditch the iniparser package altogether.

**Comment by pullmoll** [comment]
Please try with iniparser-4.0_3

**Comment by gregf** [comment]
@pullmoll iniparser-4.0_3 fixes the problem I had.

**Comment by JayVii** [comment]
Yes, it fixes the issue. Thank you, @pullmoll :)

**Pull request closed without merging**
