### PR TITLE
[DO NOT MERGE] Gnome 3.26

### PR DESCRIPTION
**Pull request by Gottox**
Tracking PR for merging Gnome 3.26.

## gnome

* [ ] NetworkManager 1.9.2 *unstable version*
* [ ] adwaita-icon-theme 3.25.91 *unstable version*
* [ ] at-spi2-atk 2.26.0
* [ ] at-spi2-core 2.26.0
* [x] atk 2.26.0
* [x] atkmm 2.24.2
* [x] baobab 3.26.0
* [ ] cairomm 1.15.4 *unstable version*
* [x] cantarell-fonts 0.0.25
* [x] caribou 0.4.21
* [x] cheese 3.26.0
* [x] clutter 1.26.2
* [x] clutter-gst 3.0.24
* [x] clutter-gtk 1.8.4
* [x] cogl 1.22.2
* [x] dconf 0.26.0
* [x] eog 3.26.0
* [x] epiphany 3.26.0
* [x] evince 3.26.0
* [ ] evolution-data-server 3.26.0
* [x] file-roller 3.26.0
* [x] folks 0.11.4 *unstable version*
* [x] gcab 0.7 *unstable version*
* [x] gcr 3.20.0
* [x] gdk-pixbuf 2.36.10
* [x] gdm 3.26.0
* [x] gedit 3.22.1
* [x] geocode-glib 3.25.4.1 *unstable version*
* [x] gfbgraph 0.2.3
* [ ] gjs 1.50.0
* [x] glib 2.54.0
* [ ] glib-networking 2.54.0
* [x] glibmm 2.50.1
* [x] gmime 2.6.23
* [ ] gnome-backgrounds 3.25.4 *unstable version*
* [ ] gnome-bluetooth 3.26.0
* [x] gnome-boxes 3.26.0
* [ ] gnome-calculator 3.25.92 *unstable version*
* [ ] gnome-calendar 3.26.0
* [ ] gnome-characters 3.25.92 *unstable version*
* [ ] gnome-clocks 3.26.0
* [ ] gnome-color-manager 3.26.0
* [x] gnome-contacts 3.26
* [x] gnome-control-center 3.26.0
* [x] gnome-desktop 3.26.0
* [x] gnome-disk-utility 3.26.0
* [ ] gnome-documents 3.25.91 *unstable version*
* [ ] gnome-font-viewer 3.25.90 *unstable version*
* [ ] gnome-getting-started-docs 3.26.0
* [x] gnome-initial-setup 3.26.0
* [x] gnome-keyring 3.20.1
* [ ] gnome-logs 3.26.0 *not useful with void*
* [ ] gnome-maps 3.26.0
* [x] gnome-menus 3.13.3 *unstable version*
* [x] gnome-music 3.26.0
* [x] gnome-online-accounts 3.25.92 *unstable version*
* [x] gnome-online-miners 3.26.0
* [x] gnome-photos 3.26.0
* [ ] gnome-screenshot 3.25.0 *unstable version*
* [x] gnome-session 3.26.0
* [x] gnome-settings-daemon 3.26.0
* [x] gnome-shell 3.26.0
* [x] gnome-shell-extensions 3.26.0
* [ ] gnome-software 3.26.0 *not useful with void*
* [ ] gnome-system-monitor 3.26.0
* [x] gnome-terminal 3.26.0
* [x] gnome-themes-standard 3.22.3
* [ ] gnome-todo 3.25.90 *unstable version*
* [x] gnome-user-docs 3.26.0
* [ ] gnome-user-share 3.18.3 *not in void*
* [x] gnome-video-effects 0.4.3
* [ ] gnome-weather 3.26.0
* [x] gobject-introspection 1.54.0
* [ ] gom 0.3.3 *unstable version*
* [ ] graphene 1.6.0 *not in void*
* [ ] grilo 0.3.4
* [x] grilo-plugins 0.3.5 *unstable version*
* [x] gsettings-desktop-schemas 3.24.1
* [x] gsound 1.0.2
* [x] gspell 1.6.0
* [x] gssdp 1.0.2
* [x] gtk+ 3.22.21
* [x] gtk-doc 1.26
* [ ] gtk-vnc 0.7.1 *unstable version*
* [x] gtkmm 3.22.1
* [x] gtksourceview 3.24.4
* [x] gupnp 1.0.2
* [x] gupnp-av 0.12.10
* [x] gupnp-dlna 0.10.5
* [x] gupnp-igd 0.2.4
* [x] gvfs 1.34.0
* [x] json-glib 1.4.2
* [ ] libchamplain 0.12.16
* [x] libcroco 0.6.12
* [ ] libgdata 0.17.9
* [x] libgee 0.20.0
* [ ] libgepub 0.5.2
* [ ] libgnomekbd 3.26.0
* [ ] libgovirt 0.3.4 *unstable version* *not in void*
* [ ] libgrss 0.7.0 *unstable version* *not in void*
* [x] libgsf 1.14.41
* [ ] libgtop 2.38.0
* [ ] libgweather 3.26.0
* [ ] libgxps 0.3.0 *unstable version*
* [ ] libhttpseverywhere 0.4.8 *not in void*
* [x] libmediaart 1.9.4
* [ ] libnotify 0.7.7
* [x] libpeas 1.22.0
* [x] librsvg 2.40.18
* [x] libsecret 0.18.5
* [x] libsigc++ 2.10.0
* [ ] libsoup 2.60.0
* [x] libwnck 3.24.1
* [x] libxml2 2.6.30
* [ ] libxslt 1.1.22
* [x] libzapojit 0.0.3 *unstable version*
* [ ] mm-common 0.9.11
* [x] mousetweaks 3.12.0
* [ ] mutter 3.26.0
* [x] nautilus 3.26.0
* [x] network-manager-applet 1.8.2
* [ ] orca 3.25.4 *unstable version*
* [x] pango 1.40.12
* [x] pangomm 2.40.1
* [ ] phodav 2.2 *not in void*
* [ ] pyatspi 2.26.0
* [ ] pygobject 3.26.0
* [x] rest 0.8.0
* [ ] simple-scan 3.26.0
* [x] sushi 3.24.0
* [ ] totem 3.26.0
* [ ] totem-pl-parser 3.25.90 *unstable version*
* [x] tracker 2.0.0
* [ ] tracker-miners 2.0.0 *not in void*
* [x] vala 0.38.1
* [x] vino 3.22.0
* [x] vte 0.50.0
* [ ] yelp 3.26.0
* [x] yelp-tools 3.18.0
* [x] yelp-xsl 3.20.1
* [x] zenity 3.24.0

## gnome-apps

* [ ] accerciser 3.22.0 *not in void*
* [ ] aisleriot 3.22.3
* [ ] dconf-editor 3.23.4 *unstable version*
* [x] devhelp 3.26.0
* [x] evolution 3.26.0
* [ ] five-or-more 3.26.0
* [ ] four-in-a-row 3.22.2
* [x] ghex 3.18.3
* [x] gitg 3.26.0
* [x] gnome-builder 3.26.0
* [ ] gnome-chess 3.26.0
* [ ] gnome-devel-docs 3.26.0 *not in void*
* [ ] gnome-dictionary 3.26.0
* [ ] gnome-klotski 3.22.2
* [x] gnome-mahjongg 3.22.0
* [ ] gnome-mines 3.26.0
* [ ] gnome-multi-writer 3.26.0 *not in void*
* [x] gnome-nettool 3.8.1
* [x] gnome-nibbles 3.24.0
* [x] gnome-recipes 1.6.2
* [ ] gnome-robots 3.22.2
* [x] gnome-sound-recorder 3.24.0.1
* [ ] gnome-sudoku 3.26.0
* [ ] gnome-taquin 3.22.0 *not in void*
* [x] gnome-tetravex 3.22.0
* [x] gnome-tweak-tool 3.26.0
* [x] hitori 3.22.3
* [x] iagno 3.22.0
* [ ] lightsoff 3.26.0
* [ ] nautilus-sendto 3.8.6
* [x] nemiver 0.9.6 *unstable version*
* [ ] polari 3.26.0
* [x] quadrapassel 3.22.0
* [x] rygel 0.36.0
* [ ] swell-foop 3.26.0
* [x] tali 3.22.0

# missing deps

* [x] libgvc for vala
* [x] mozjs52 for gjs

### CODE REVIEW

**Comment by Gottox** [comment]
I'd like to avoid unstable versions whenever it is possible. So I'm going to update them *only* if otherwise the build fails

**Comment by Gottox** [comment]
@Sir-Boops

**Comment by Sir-Boops** [comment]
https://github.com/voidlinux/void-packages/compare/master...Sir-Boops:gnome-core - Here's my working branch. So far it's all stable versions.

**Comment by Gottox** [comment]
mind if I merge from there?

**Comment by Sir-Boops** [comment]
No i don't mind. But wait until i ping ya so i can test it first.

**Comment by Sir-Boops** [comment]
@Gottox Ok branch works on x86_64 now 👌

**Comment by Gottox** [comment]
Awesome! Currently trying to get mozjs45 to compile on musl.

**Comment by Gottox** [comment]
Building gjs fails with:
```
  CXXLD    gjs-console
Command '[u'/builddir/gjs-1.50.0/tmp-introspectzaFKZO/GjsPrivate-1.0', u'--introspect-dump=/builddir/gjs-1.50.0/tmp-introspectzaFKZO/functions.txt,/builddir/gjs-1.50.0/tmp-introspectzaFKZO/dump.xml']' returned non-zero exit status -11
make[1]: *** [/usr/share/gobject-introspection-1.0/Makefile.introspection:160: GjsPrivate-1.0.gir] Error 1
```

**Comment by Gottox** [comment]
Temporary close the PR to stop filling up travis.

**Pull request closed without merging**
