### PR TITLE
New package: mirage-0.9.5.2-1

### PR DESCRIPTION
**Pull request by sakhmatd**
Adding new package: mirage-0.9.5.2-1

### CODE REVIEW

**Comment by sakhmatd** [comment]
Not sure what to do about aarch64 and armv7hf. I explicitly added python to makedepends, but build job on Travis still claims that python is not found.

**Comment by cr6git** [comment]
Move `python` to the `hostmakedepends` instead!

**Comment by sakhmatd** [comment]
Thanks! That helped, but it looks like the installer only supports x86_64 and i686 anyway?
Unless I am doing something wrong again. Using python-module as a build_style kinda gets me nowhere.

**Comment by cr6git** [comment]
`hostmakedepends="python-devel pygtk-devel"`

No, not the `-devel` packages, only `python` ...

**Comment by sakhmatd** [comment]
Will that make a difference in setup.py detecting arch?

Package manual advices to use `python-devel` in both `hostmakedepends` and `makedepends`, so that's what I did and it does seem to launch `setup.py` now.

I'll try just `python` though. I'm pretty certain `pygtk-devel` is needed to build it too.

**Comment by sakhmatd** [comment]
Using `python2-module` worked out. Thanks for the help!

Apologies for lots of amended commits.

**Comment by Vaelatern** [comment]
That's exactly as it should be!

**Comment by Vaelatern** [comment]
I changed the commit message and merged.

**Pull request merged**
