### PR TITLE
New package: lxd-2.20

### PR DESCRIPTION
**Pull request by iaroki**

### CODE REVIEW

**Comment by Anachron** [comment]
Build will fail on aarch64 as he tested locally, we will have to investigate why.

**Comment by newbluemoon** [comment]
Move acl-devel from `hostmakedepends` to `makedepends`?

**Comment by iaroki** [comment]
Can't understand the difference between `hostmakedepends` and `makedepends`

**Comment by newbluemoon** [comment]
The difference is when cross compiling: `hostmakedepends` contains tools which run on the host that builds the package and `makedepends` contains packages against which is linked (in the targat binary format), in many/most cases the -devel packages.

**Comment by newbluemoon** [comment]
In more detail: You have

```
hostmakedepends="git bzr lxc-devel pkg-config acl-devel"
makedepends="lxc-devel pkg-config acl-devel"
depends="liblxc acl acl-progs rsync squashfs-tools xz"
```

`hostmakedepends` should contain `git`, `bzr`, and `pkg-config` because those packages are only needed to build lxd and run on the host that builds the package. They are in the build host binary format.

`makedepends` should contain `lxc-devel` and `acl-devel` because those packages provide the includes and libraries needed to compile and link lxd. They are in the target binary format.

When creating the final package xbps-src automatically adds the packages that contain the linked against libraries to `depends`, no need to specify them manually. 

Therefore `depends` should only contain packages which are needed at runtime, but cannot be detected when creating the package. Here this would be `acl-progs`, `rsync`, `squashfs-tools`, and `xz` (I didn’t check if they’re essential, just took them as given).

So that as a result you’d have

```
hostmakedepends="git bzr pkg-config"
makedepends="lxc-devel acl-devel"
depends="acl-progs rsync squashfs-tools xz"
```

**Comment by iaroki** [comment]
At the moment to get it working a few steps needed:
* install `lxd` package
* add mappings `echo "root:1000000:65536" | sudo tee -a /etc/subuid /etc/subgid`
* start runit service `ln -s /etc/sv/lxd /var/service`
* run `lxd init` to configure
* add himself to `lxd` group `usermod -aG lxd $USER`

LXD depends on `lxc` package to start containers. And for now to start container with systemd init inside you need `/sys/fs/cgroup/systemd` mounted on the host machine. Here #9811  suggested create and mount manually:

```
mkdir /sys/fs/cgroup/systemd
mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd
```

The problem is this doesn't survive reboot and i don't know how to put all this pieces together.

**Comment by iaroki** [comment]
Added creating and mounting `/sys/fs/cgroup/systemd` to `run` file and mapping/user info to `INSTALL.msg`

**Comment by Anachron** [comment]
Hey, why don't you put the mount command from here
https://github.com/voidlinux/void-packages/pull/9915/commits/8d49edc9507b0272d62786ec5233c1e3d3907175#diff-ef330111a87ff3ce6846733e7fca9657R3
as command on here?
https://github.com/voidlinux/void-packages/pull/9915/commits/8d49edc9507b0272d62786ec5233c1e3d3907175#diff-ef330111a87ff3ce6846733e7fca9657R10

There is no need to do it inside the ifs.

**Comment by iaroki** [comment]
Right, thanks!

**Pull request closed without merging**
