### PR TITLE
lxqt: update to 0.12.0.

### PR DESCRIPTION
**Pull request by maxice8**
- [x] lixqtxdg-3.1.0
- [x] lxqt-build-tools-0.4.0
- [x] liblxqt-0.12.0
- [x] libfm-qt-0.12.0
- [x] libsysstat-0.4.0
- [x] lxqt-l10n-0.12.0
- [x] lxqt-globakeys-0.12.0
- [x] lxqt-qtplugin-0.12.0
- [x] lxqt-runner-0.12.0
- [x] lxqt-panel-0.12.0
- [x] lxqt-sudo-0.12.0
- [x] lxqt-session-0.12.0
- [x] lxqt-about-0.12.0
- [x] lxqt-config-0.12.0
- [x] lxqt-notificationd-0.12.0
- [x] lxqt-powermanagement-0.12.0
- [x] lxqt-policykit-0.12.0
- [x] lxqt-openssh-askpass-0.12.0
- [x] lxqt-admin-0.12.0
- [x] lximage-qt-0.6.0
- [x] obconf-qt-0.12.0
- [x] pavucontrol-qt-0.3.0
- [x] qtermwidget-0.8.0
- [x] qterminal-0.8.0
- [x] compton-conf-0.3.0
- [x] pcmanfm-qt-0.12.0
- [x] lxq-themes-0.12.0
- [x] lxqt-0.12.0

### CODE REVIEW

**Comment by maxice8** [comment]
Anyone interested in tackling the libqtxdg problem [this](https://travis-ci.org/voidlinux/void-packages/jobs/291012506#L2611) is the important bit

**Comment by maxice8** [comment]
Compiled everything successfully on aarch64, found:

**Comment by maxice8** [comment]
found the tail of the problem, some packages have `liblxqt-devel` on `hostmakedepends` and it causes the armv* cross-compilers to try and build for the host arch and strip fails.

Happily we can replace the hostmakedepends with `qt5-tools-devel` and `qt5-devel` and removing `liblxqt-devel` from hostmakedepends seem to make not much difference

**Comment by asergi** [comment]
Please update `compton-conf` here as well.

**Comment by maxice8** [comment]
> Please update compton-conf here as well.

oh my, i knew i was forgetting something, i'll get into it as soon as possible

**Comment by asergi** [comment]
Since b602b212dd6eb32766f5a6638052d01aadad8463, I think is safe to move `lxqt-build-tools` back to `hostmakedepends` again. Could you please test it? Thanks.

**Comment by maxice8** [comment]
Yes it now works ( tested building pcmanfm-qt on armv7hf ), but i don't understand why, it seems like `lxqt-build-tools` is being used as an alias to `qt5-tools-devel` which includes the required file `/usr/lib/cmake/Qt5Help/Qt5HelpConfigExtras.cmake` and `qt5-devel` which includes `/usr/lib/cmake/Qt5Core/Qt5CoreConfigExtras.cmake`

**Comment by asergi** [comment]
The files of the dead `lxqt-common` are now owned by other packages. That means you need to add `replaces="lxqt-common>=0"` to `compton-conf`, `lxqt-globalkeys`, `lxqt-notificationd`, `lxqt-policykit`, `lxqt-session`, `lxqt-themes` and `pcmanfm-qt`.

**Comment by maxice8** [comment]
added `replaces="lxqt-common>=0"`

**Pull request merged**
