### PR TITLE
gcc: add support for SOURCE_DATE_EPOCH environment

### PR DESCRIPTION
**Pull request by pullmoll**
See #3765 and #3774

Discuss before merging - still testing locally.

### CODE REVIEW

**Comment by Gottox** [comment]
:+1:

We need this patch on all the cross compilers too:

* [ ] cross-aarch64-linux-gnu-0.21_2
* [ ] cross-aarch64-linux-musl-0.21_1
* [ ] cross-arm-linux-gnueabi-0.21_3
* [ ] cross-arm-linux-gnueabihf-0.21_3
* [ ] cross-arm-linux-musleabi-0.21_1
* [ ] cross-arm-linux-musleabihf-0.21_1
* [ ] cross-armv7l-linux-gnueabihf-0.21_2
* [ ] cross-armv7l-linux-musleabihf-0.21_1
* [ ] cross-i686-linux-musl-0.21_1
* [ ] cross-i686-pc-linux-gnu-0.21_2
* [ ] cross-mips-linux-musl-0.21_2
* [ ] cross-mipsel-linux-musl-0.21_2
* [ ] cross-mipsel-linux-muslhf-0.21_2
* [ ] cross-x86_64-linux-musl-0.21_1

And for consistence maybe these packages are worth considering too.
* [ ] avr-gcc-4.9.3_1
* [ ] msp430-toolchain-3.05.00.00_1

**Comment by pullmoll** [comment]
To use `_apply_patch()` for `srcpkgs/gcc/patches/libcpp-source_date_epoch.patch` it would have to be `-p1`. Do you think symlinking the patch into `srcpkgs/cross-*/files/<somename>.diff` would be the way to go?

**Comment by pullmoll** [comment]
Please double check the `cross-*` changes:
+ All `_apply_patch()` functions should be the same.
+ There is always a `cd ${wrksrc}/gcc-${_gcc_version}` first
+ The calls to _apply_patch() always have either `-p0` or `-p1` as first parameter

**Comment by pullmoll** [comment]
For `avr-gcc-4.9.3_1` and `msp430-toolchain-3.05.00.00_1` it should suffice to symlink `../../gcc/patches/libcpp-source_date_epoch.patch -> <pkgname>-/patches/`

**Comment by Gottox** [comment]
> For avr-gcc-4.9.3_1 and msp430-toolchain-3.05.00.00_1 it should suffice to symlink ../../gcc/patches/libcpp-source_date_epoch.patch -> <pkgname>/patches/?

Yes. It should also be reasonable to link the same patch to the files directory and apply it manually for the cross-* packages.

@xtraeme what do you think?

**Comment by xtraeme** [comment]
:+1:

**Comment by pullmoll** [comment]
Ok, I think the patch is complete now. I successfully built the checked packages... more to come.

**Comment by pullmoll** [comment]
`./xbps-src pkg avr-gcc` fails with this error:
```
checking for the correct version of gmp.h... yes
checking for the correct version of mpfr.h... yes
checking for the correct version of mpc.h... yes
checking for the correct version of the gmp/mpfr/mpc libraries... no
configure: error: Building GCC requires GMP 4.2+, MPFR 2.4.0+ and MPC 0.8.0+.
Try the --with-gmp, --with-mpfr and/or --with-mpc options to specify
their locations.  Source code for these libraries can be found at
their respective hosting sites as well as at
ftp://gcc.gnu.org/pub/gcc/infrastructure/.  See also
http://gcc.gnu.org/install/prerequisites.html for additional info.  If
you obtained GMP, MPFR and/or MPC from a vendor distribution package,
make sure that you have installed both the libraries and the header
files.  They may be located in separate packages.
=> ERROR: avr-gcc-4.9.3_1: failed to run do_configure() at line 24.
```

Any ideas? Or should I just remove it from the batch for now?

**Comment by chneukirchen** [comment]
Before we push this and the major rebuild starts, I want to propose to also add a patch which reads a specs file from environment.  Then we could enable and disable hardening much easier.

I saw some patch some time ago, but I can't find it right now.

**Comment by chneukirchen** [comment]
Here it is: https://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/sys-devel/gcc/files/gcc-spec-env-r1.patch?view=markup

**Comment by chneukirchen** [comment]
Perhaps we could even implement the fixed time things in terms of this.

**Comment by pullmoll** [comment]
I can integrate that patch.
I don't however get how it could be used to implement the other patch, or did I get you wrong?

**Comment by pullmoll** [comment]
Also I'd need to know how to modify `common/...` to make use of the patch instead of modifying the C{,XX}FLAGS.

**Comment by Gottox** [comment]
Keep in mind, that we potentional break the bootstrap capabilities if we move CFLAFS to that file.

**Comment by pullmoll** [comment]
The `gcc-spec-env-r1.patch` is now in `srcpkgs/gcc/patches` (modified to work with -p0 for gcc), symlinked to the `cross-*/files` directories and applied in the `_gcc_bootstrap()` functions.

**Comment by chneukirchen** [comment]
I would not move general CFLAGS there, just the hardening things.

**Comment by chneukirchen** [comment]
I.e. use it to do PIE by default and the linker flags.

**Comment by pullmoll** [comment]
So who's gonna click the `Merge pull request` button :question:

**Comment by Gottox** [comment]
:fearful:

**Pull request merged**
