### PR TITLE
gimp: update to 2.10.0

### PR DESCRIPTION
**Pull request by kartik-ynwa**
babl: update to 0.1.46
gegl3: update to 0.3.34
New package: gegl4-0.4.0
New package: libmypaint-1.3.0
New package: mypaint-brushes-1.3.0

### CODE REVIEW

**Comment by maxice8** [comment]
make one commit for each  template

**Comment by kartik-ynwa** [comment]
@maxice8 Sure I will cancel this one then.

**Comment by maxice8** [comment]
don't cancel, use git to fix the commits.

**Comment by kartik-ynwa** [comment]
@maxice8 a single PR is fine though?

**Pull request closed without merging**
