### PR TITLE
New package: kdbusaddons-5.26.0

### PR DESCRIPTION
**Pull request by dutsky**

### CODE REVIEW

**Comment by Gottox** [comment]
What packages need this?

**Comment by dutsky** [comment]
kservice, kwrited and polkit-kde-agent

**Comment by Gottox** [comment]
Is there any chance to make crossbuild work before we merge?

**Comment by dutsky** [comment]
I don't know why it's not build in voidlinux. Maybe it's qmake issue #4891

**Comment by pullmoll** [comment]
Qt5 cross compiling is being worked on, but it seems to be difficult to get done.
The culprit is qmake and its (default) settings, which need to be overriden for cross compiling and some of these settings seem to be compile-time only.

Still just let the packages fail to cross build for now, perhaps we manage to solve the issue later on.

**Pull request merged**
