### PR TITLE
nscd: sv service

### PR DESCRIPTION
**Pull request by Gottox**

### CODE REVIEW

**Comment by xtraeme** [comment]
revision must be bumped

**Comment by Gottox** [comment]
fixed.

**Comment by Gottox** [comment]
good to go?

**Comment by Gottox** [comment]
no.

**Comment by xtraeme** [comment]
No what?

**Comment by Gottox** [comment]
Just saw the closing commit. This one had nothing todo with this PR. anyway it was fixed in the commit before.

**Comment by Gottox** [comment]
coffee -.-

**Comment by xtraeme** [comment]
Heh yeah. Because I wanted to make additional changes and close your PR at the same time.

**Pull request closed without merging**
