### PR TITLE
New package: hunspell-da_DK-2.3_1

### PR DESCRIPTION
**Pull request by unixsheikh**

### CODE REVIEW

**Comment by unixsheikh** [comment]
I'm not sure if I have missed anything, but the package builds, installs, and works.

**Comment by the-maldridge** [comment]
Please rebase to a single commit, then ping me for merge.

**Comment by the-maldridge** [comment]
Still not quite to a single commit, what you need to do is use git rebase and squash all the previous commits into the most recent one.

**Comment by unixsheikh** [comment]
6e54626 was rebased, but I could not push before a pull, so a merge was needed. 8fcc66f should be it unless I have messed it up.

**Comment by the-maldridge** [comment]
not quite right, what you should do now is to checkout 6e54626 and reset the branch --hard to that point, then rebase on top of master.  If you are unsure how to do this join #voidlinux on freenode and ask for assistance.

**Comment by unixsheikh** [comment]
I'm going to close this one a make a new pull request as this rebase stuff only provides me with a "noop" option.

**Comment by the-maldridge** [comment]
It was not necessary to close this PR to resolve this issue.

**Comment by unixsheikh** [comment]
Then I need clear instructions on what steps I need to make for this to work. I cannot access IRC right now.

**Comment by unixsheikh** [comment]
Also could we possibly put this in the wiki too?

**Comment by the-maldridge** [comment]
I'm not really interested in copying documentation from git to the wiki nor am I interested in copying it here, you may consult with [The Git Book](https://git-scm.com/book/en/v2) at your leisure.

I suggest you consult section 3.6 for information on rebasing.  You should then select that you wish to 'fixup' all but the last commit on your branch.

**Comment by unixsheikh** [comment]
I already have. I have done rebasing before.

Right now I am stuck with this:

```
$ git rebase -i HEAD~1
Auto-merging srcpkgs/hunspell-da_DK/template
CONFLICT (add/add): Merge conflict in srcpkgs/hunspell-da_DK/template
error: could not apply d6b3e5bd69... New package: hunspell-da_DK-2.3_1

Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".

Could not apply d6b3e5bd69... New package: hunspell-da_DK-2.3_1
```

It's taking too long. Closing up and make a new.

**Comment by Vaelatern** [comment]
It tells you what to do.

**Comment by unixsheikh** [comment]
@Vaelatern, I really hate comments like the one you just made. Of course it tells me what to do! And if I had figured out what to do from the message, I would have done it already. Such comments are not helpful at all.

I eventually resolved the conflict, but then another error prevented me from pushing. I just did a new pull request.

**Comment by Vaelatern** [comment]
The error you found is probably also the most googleable error for git users. And git is not Void tooling, you wouldn't expect help on a void-packages PR with quitting vim either.
As for PRs, you can push a local branch to any remote branch (google how), and PRs just represent branches, and that's how to not lose comment history when you really need to just make a new branch because git is hard.

**Comment by newbluemoon** [comment]
And regarding the error message: it really says all there is to do.

Open `srcpkgs/hunspell-da_DK/template` in your editor. There the conflicting passages are marked. Modify the template to fit your needs. Then run `git add srcpkgs/hunspell-da_DK/template` and then `git rebase --continue`. That’s all. ;)

**Comment by unixsheikh** [comment]
@newbluemoon, I agree 100%, and I thank you for your comment, but last night, all I needed was to get what you did in your last comment, helping instructions. Not because I need the path of least resistance, not because I am lazy, but because at that specific time I had misunderstood the problem, couldn't figure out why Git kept "fighting" back, didn't understand the message (perhaps because I was tired), and just wanted to get the package accepted because I had spent about an hour fighting with Git.

I use Git almost everyday, but are very rusty in rebasing and a lot of the more advanced stuff. I read the whole page on rebasing before posting here, I searched for lots of examples and tried several solutions, and I still didn't get what was going on because Git kept complaining. I didn't even notice the "conflicting" part in the template until after I had closed the issue and made a new PR.

> Open srcpkgs/hunspell-da_DK/template in your editor. There the conflicting passages are marked. Modify the template to fit your needs. Then run git add srcpkgs/hunspell-da_DK/template and then git rebase --continue. 

@Vaelatern , look at the above. This is helping. You're comments, they are not contributing in any way at all.

**Comment by Vaelatern** [comment]
I will leave with: You wouldn't expect help on your text editor from a PR thread.

**Comment by unixsheikh** [comment]
@Vaelatern , seriously?

**Pull request closed without merging**
