### PR TITLE
New package: dolphin-17.04.3

### PR DESCRIPTION
**Pull request by dutsky**

### CODE REVIEW

**Comment by Hoshpak** [comment]
Wouldn't it be better if the current versions had a conflict with the old kde-baseapps package? If both contain e.g. /usr/bin/dolphin, I think they would overwrite each other's files.

**Comment by dutsky** [comment]
Oh, is kde-baseapps contains dolphin?

**Comment by Hoshpak** [comment]
It does, of course it's the KDE 4.x version:

```
# xlocate /usr/bin/dolphin
xlocate: database outdated, please run xlocate -S.
dolphin-emu-5.0_6       /usr/bin/dolphin-emu
dolphin-emu-5.0_6       /usr/bin/dolphin-emu-nogui
kde-baseapps-4.14.3a_1  /usr/bin/dolphin
```

**Comment by dutsky** [comment]
@Hoshpak, conflicts added 🎉

**Pull request merged**
