### PR TITLE
New package: libmemcached

### PR DESCRIPTION
**Pull request by jprjr**
This depends on pull #2372

### CODE REVIEW

**Comment by Gottox** [comment]
pls rebase so we can see what travis thinks of that PR ;)

**Comment by jprjr** [comment]
Done and done!

**Comment by Gottox** [comment]
cross build is broken.

**Comment by jprjr** [comment]
I'm noticing that 'gnu-configure' seems to work correctly for cross-builds over plain 'configure' - just changed to use that, let's see what Travis says.

**Comment by jprjr** [comment]
Looks like cross-build is definitely broken - I also had the wrong license in there (GPL when it should be BSD), plus spaces instead of tabs - fixed all those + rebased.

**Pull request merged**
