### PR TITLE
wget: add upstream fix for background mode logging

### PR DESCRIPTION
**Pull request by auser509**
Add upstream fix for background mode logging (c722973212547aa812cd818279e3fb989fb38dd4).

### CODE REVIEW

**Comment by Vaelatern** [comment]
Why is this not in a release?

**Comment by auser509** [comment]
I am not familiar with the upstream practices of wget in particular, but the fix has been committed for 9 days now, and I would expect a minor release bump from them, as this is a user-facing bug (the logfile is simply empty on release 1.19.4), which simply has not happened yet.

**Comment by Vaelatern** [comment]
Can you link to a git repo with this?

**Comment by auser509** [comment]
http://git.savannah.gnu.org/cgit/wget.git/commit/?id=c722973212547aa812cd818279e3fb989fb38dd4

**Pull request merged**
