### PR TITLE
New package: httrack-3.48.21

### PR DESCRIPTION
**Pull request by mid-kid**
(Forgot the version number in the commit, sorry)

### CODE REVIEW

**Comment by xtraeme** [comment]
Probably a -devel pkg must be created.

**Comment by bougyman** [comment]
Could you rebase this off current master so it can merge cleanly?

**Comment by mid-kid** [comment]
Done.

**Comment by xtraeme** [comment]
Please read the CONTRIBUTING.md file to use our commit style guidelines, aka

`<pkgname>: ...`

**Comment by mid-kid** [comment]
Fixed.

**Pull request closed without merging**
