### PR TITLE
New package: statnot-0.0.4

### PR DESCRIPTION
**Pull request by diogoleal**

### CODE REVIEW

**Comment by xtraeme** [comment]
`noarch=yes`

**Comment by dominikh** [comment]
This package has runtime dependencies. python and xsetroot are the ones I've spotted so far, but please check if it has any other runtime dependencies.

**Comment by diogoleal** [comment]
@dominikh  added ```depends="pygtk python-dbus xsetroot"```

**Comment by dominikh** [comment]
Merged as 1b0ed79fc553b57014aeb77fcb7ef870df69bd23.

**Pull request closed without merging**
