### PR TITLE
mypaint: update to 1.2.0-beta.4

### PR DESCRIPTION
**Pull request by Spencer-H**
The reason for the revision is due to being unable to include the -beta.4 part in the version variable, so I had to trigger an update with the revision.

### CODE REVIEW

**Comment by xtraeme** [comment]
- `revision` must be always set to `1`for new upstream versions
- what's the reason to update it to the beta version?

**Comment by Spencer-H** [comment]
Bug fixes and increased number of translations.

**Comment by Gottox** [comment]
We won't ship unstable releases as long as there's no urgent reason to do so. Imho we should wait for a stable release here.

**Comment by xtraeme** [comment]
What @Gottox said. Just wait until the next stable version is released.

Thanks

**Pull request closed without merging**
