### PR TITLE
Kodi 15.0

### PR DESCRIPTION
**Pull request by Gottox**
readds libcec to kodi on x86; updates kodi-rpi; adds missing dependencies.

ToDo before merge:

* [x] fix crossbuild of the shipped libsquish in kodi{,-rpi}
* [x] testing

Follow up to #2075

### CODE REVIEW

**Comment by Gottox** [comment]
tested on rpi (with cec) and x86.

**Comment by Gottox** [comment]
I experienced a bug with kodi-rpi though: It seems that cec is only working for kodi if cec-client is running in the background. @xtraeme, do you use CEC with your rpi? Could you recheck that?

**Comment by xtraeme** [comment]
Please rebase to avoid the merge commit.

**Comment by Gottox** [comment]
done

**Comment by xtraeme** [comment]
I can't test CEC, ENOHW.

**Comment by beefcurtains** [comment]
(To anyone with cec problems:) New versions, new bugs. If there really is a problem, [ask for help here](http://forum.kodi.tv/forumdisplay.php?fid=33). If problem is specific to the void package, [you know the drill](https://github.com/voidlinux/void-packages/issues).

**Comment by beefcurtains** [comment]
@Gottox I removed ``--enable-libcec``, perhaps it would be good to add that back (after ``--enable-avahi``)

**Comment by xtraeme** [comment]
:+1:

**Comment by Gottox** [comment]
@beefcurtains libcec is enabled on these kodi{,-rpi} builds

**Pull request merged**
