### PR TITLE
python-mechanize: update to 0.3.5

### PR DESCRIPTION
**Pull request by Sir-Boops**
Also updated the destfiles and homepage links

Version 0.3.X has breaking changes over 0.2.X [Changelog](https://github.com/python-mechanize/mechanize/blob/master/ChangeLog#L26)

### CODE REVIEW

**Comment by asergi** [comment]
@the-maldridge @Sir-Boops broken

> * Support HTML 5 (all html is now parsed using html5lib)

**Comment by asergi** [comment]
Also, `calibre` needs to be checked after this.

**Comment by Sir-Boops** [comment]
#6869 fixes the dependency issue as for calibre i tried a few recipes that import mechanize and they seem to work as intended using 0.3.5

**Comment by the-maldridge** [comment]
@asergi good catch.

**Pull request closed without merging**
