### PR TITLE
New package: tinc-pre-1.1pre15

### PR DESCRIPTION
**Pull request by faulesocke**
This is the "prerelease" version.

### CODE REVIEW

**Comment by faulesocke** [comment]
Looks like it does not build with musl. The missing header file (linux/if_tun.h) is from the package kernel-libc-headers. Is there a musl equivalent to this package?

**Comment by faulesocke** [comment]
Okay not sure why it still fails. The file should be there...

**Comment by maxice8** [comment]
Cross-compilation is annoying, try adding kernel-libc-headers to hostmakedepends sometimes the build system only detects if it's installed in the host.

**Comment by Gottox** [comment]
We try to avoid unstable releases whenever possible. Please wait for stable and update tinc.

**Comment by faulesocke** [comment]
It's not an unstable release, it's just not marked as being stable. See the stable release as some LTS thing and the prerelease as the one with the features.

**Comment by Gottox** [comment]
Can you point me to documentation that explains the release behavior?

**Comment by faulesocke** [comment]
I think the release behaviour is probably best explained here:

https://tinc-vpn.org/goals/

So 1.0 is a "stable" release (in the debian way of thinking, i.e. they will mostly fix bugs on this version) where 1.1 is the active branch and 2.0 is the future branch.

**Pull request closed without merging**
