### PR TITLE
busybox: fix `'/dev/nul'*` != `/dev/null` issue.

### PR DESCRIPTION
**Pull request by CasperVector**
cf. http://lists.busybox.net/pipermail/busybox/2018-March/086295.html

### CODE REVIEW

**Comment by Vaelatern** [comment]
How does this fix the problem?

**Comment by Vaelatern** [comment]
And what does `CONFIG_PIE` do?

**Comment by CasperVector** [comment]
Since it seems that PIE is enabled for most packages in void, I adjusted the flag just by the way...
So you think I need to mention this in the commit message? (I would love to...)

**Comment by Vaelatern** [comment]
Does it not otherwise respect our LDFLAGS?

**Comment by CasperVector** [comment]
Just tried: yes, it does.  BTW, did I mention that the `LFLAGS="$LDFLAGS"` part in the old template means that LDFLAGS has always been passed through the environment?

**Comment by Vaelatern** [comment]
it does not mean that.

**Comment by CasperVector** [comment]
Did you realise `LFLAGS` is probably a typo?
```
$ grep -r '\<LFLAGS\>' busybox-1.28.1
$ 
```

**Comment by Vaelatern** [comment]
Ah, did not realize.

**Comment by chneukirchen** [comment]
I partially reverted this in 77d3415 but it still works, and I cannot reproduce the bug outside of xbps-src, no idea what's going one there.

**Comment by CasperVector** [comment]
I can successfully reproduce it outside of xbps-src by:
```
tar xpf busybox-1.28.1.tar.bz2
cd busybox-1.28.1
make defconfig
make prepare
make CFLAGS=-O2
./busybox ash -c "echo '/dev/nul'*"
```

**Comment by chneukirchen** [comment]
I can also reproduce it this way on Arch x86_64 with gcc 7.3 and Debian x86_64 with gcc 6.3.

Ok, I tracked it down: it works with `-funsigned-char`, but just passing CFLAGS= overrides this.

**Comment by CasperVector** [comment]
Nice.  Just [noticed](http://lists.busybox.net/pipermail/busybox/2018-March/086297.html) upstream of this.

**Pull request merged**
