### PR TITLE
icu-58.2, libevent-2.1 revbumps and firefox{,-esr}, thunderbird and chromium update

### PR DESCRIPTION
**Pull request by Duncaen**

### CODE REVIEW

**Comment by Gottox** [comment]
Looks massive but okay to me. When do we schedule the rebuild?

**Comment by Duncaen** [comment]
@Gottox chromium is still segfaulting with musl, trying to fix it at the moment.
For me its ok to do it today/this weekend if i can fix it.

The `icu-58.2` update is necessary for `firefox-52.0` and I added the `libevent-2.1` update to minimize the amount of rebuilds, same for the browser updates.

**Comment by Gottox** [comment]
I'm discard my thunderbird update, can you update the -i18n packages too?

**Comment by Duncaen** [comment]
ah yes, adding them to the branch.

**Comment by Duncaen** [comment]
Chromium works now with musl, thanks to @ebfe for locating the issue and providing a working patch.
@ebfe noted that qt5 on aarch64 should be fixed before the merge, I'm not really sure what the issue is.

**Comment by pullmoll** [comment]
qt5 on aarch64 was solved (builder OOM).

There is an update for libreoffice-5.2.x.y (don't remember the numbers) pending, but this can wait.
libreoffice-5.3.0.3 requires a new version of fbclient (3.x) which has its own issues, read: won't build as is.
As long as the current version builds I'd say: go with it.

**Comment by Gottox** [comment]
Solve the merge conflicts and merge if ready 👍

**Comment by Duncaen** [comment]
Rebased and updated firefox, should I merge #5995 into this PR too?

**Comment by Gottox** [comment]
Seem reasonable to avoid yet another massive rebuild. 👍

**Comment by ebfe** [comment]
@Duncaen qt5 revbump got lost somewhere?

**Comment by Gottox** [comment]
What's the state of this PR?

**Comment by Duncaen** [comment]
Rebased again, maybe someone can merge it if I'm not there and the queue finishes, Thanks 😃.

CC @chneukirchen

**Pull request closed without merging**
