### PR TITLE
borg: adapt to python-msgpack -> msgpack name change.

### PR DESCRIPTION
**Pull request by maxice8**
https://github.com/borgbackup/borg/issues/3515

### CODE REVIEW

**Comment by chneukirchen** [comment]
Did you verify this works?

**Comment by maxice8** [comment]
Yes, it's also one of the fixes mentioned in the link i put there.

**Comment by pullmoll** [comment]
Let's see if this fixes the issue to avoid a revert.

**Comment by chneukirchen** [comment]
```
[*] python3-msgpack-0.5.1_1     Python module for Msgpack serializer (Python3) 
[*] borg-1.1.4_3     Deduplicating backup program with compression and encry...
```

```
% borg                                                                   
Traceback (most recent call last):                                             
  File "/usr/bin/borg", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3147, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3131, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3160, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'msgpack-python>=0.4.6' distribution was not found and is required by borgbackup
```

I don't see how this can work?

**Comment by maxice8** [comment]
On Fri, Jan 12, 2018 at 02:51:12PM +0000, Leаh Neukirchen wrote:
> ```
> [*] python3-msgpack-0.5.1_1     Python module for Msgpack serializer (Python3) 
> [*] borg-1.1.4_3     Deduplicating backup program with compression and encry...
> ```
> 
> ```
> % borg                                                                   
> Traceback (most recent call last):                                             
>   File "/usr/bin/borg", line 6, in <module>
>     from pkg_resources import load_entry_point
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3147, in <module>
>     @_call_aside
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3131, in _call_aside
>     f(*args, **kwargs)
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3160, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in _build_master
>     ws.require(__requires__)
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 984, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 870, in resolve
>     raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'msgpack-python>=0.4.6' distribution was not found and is required by borgbackup
> ```
> 
> I don't see how this can work?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/voidlinux/void-packages/pull/10721#issuecomment-357258025

oops, it's msgpack-python not python-msgpack in the sed.

**Pull request closed without merging**
