### PR TITLE
screenFetch: update to 3.8.0

### PR DESCRIPTION
**Pull request by liwakura**

### CODE REVIEW

**Comment by Vaelatern** [comment]
Considered merging, but that weird patch threw me off.

**Comment by Vaelatern** [comment]
#6397 Where do you guys get these strange patches?

**Comment by liwakura** [comment]
Updating of the patch was only required because it failed to apply completely on 3.8.0, which broke proper distro detection for void.

I also made an [attempt](https://github.com/KittyKatt/screenFetch/pull/489) to merge the patch upstream.

**Comment by Vaelatern** [comment]
Your attempt got merged upstream.

**Pull request merged**
