### PR TITLE
prelink: add config file

### PR DESCRIPTION
**Pull request by Vaelatern**
#4603

### CODE REVIEW

**Comment by Vaelatern** [comment]
How might I get `error.h` on muslc?

**Comment by ebfe** [comment]
> How might I get error.h on muslc?
There are several adhoc replacements in the repo.

**Comment by Vaelatern** [comment]
How might I query with xlocate to find musl packages?

**Comment by Gottox** [comment]
@Vaelatern is this PR ready to merge or do you want to fix musl first?

**Comment by Vaelatern** [comment]
Until I can xlocate for musl platforms, let's merge.

**Pull request merged**
