### PR TITLE
nginx: update to 1.10.1.

### PR DESCRIPTION
**Pull request by Vaelatern**
still not happy on arm.

### CODE REVIEW

**Comment by Gottox** [comment]
#yolo

**Comment by Duncaen** [comment]
In `${FILESDIR}` is a pregenerated header file for `arm*` which has to be synced.
Fixed it in 0bfa499 and 04f7ebe.

**Comment by Vaelatern** [comment]
Where does it get synchronized from?

**Comment by Duncaen** [comment]
`./xbps-src configure nginx` and then `vimdiff srcpkgs/nginx/files/ngx_auto_config.h.armv6l masterdir/builddir/nginx-$version/objs/ngx_auto_config.h`.

**Comment by Gottox** [comment]
cool, can you document this in the template?

**Comment by Vaelatern** [comment]
Just did

**Pull request merged**
