### PR TITLE
Linux: update to 4.1.

### PR DESCRIPTION
**Pull request by beefcurtains**
Because why not?

### CODE REVIEW

**Comment by chneukirchen** [comment]
Because we usually wait for 4.1.1.

**Comment by xtraeme** [comment]
What @chneukirchen said. 4.1 is not yet considered stable.

**Comment by GiedriusS** [comment]
4.1.1 is out. Could you please update the commit? Thanks

**Comment by beefcurtains** [comment]
No need, this is a metapackage.

**Comment by beefcurtains** [comment]
Perhaps we could do non-pae kernel first, and add a friendly message for Xen users that warns them i686 doesn't have Xen guest support anymore. Just in case anyone is running vanilla i686 void kernels on a Xen host. Will have to rebase that pull, np.

**Pull request merged**
