### PR TITLE
New package: netbsd-curses-0.2.1

### PR DESCRIPTION
**Pull request by cr6git**
Somebody talked about it on the forum. Not tested.

### CODE REVIEW

**Comment by Johnnynator** [comment]
@cr6git you probably have to set `HOSTCC=gcc` for cross compilation (either export it in pre_build or try to set it as `make_build_args=`)

**Comment by Duncaen** [comment]
I don't see the point of packaging this as it is, there is no way to possibly install it as it conflicts with `ncurses`.

**Comment by cr6git** [comment]
@Duncaen you're right, I modified the template.
````
provides="ncurses-${version}_${revision}"
replaces="ncurses>=0"
````

**Comment by Johnnynator** [comment]
@cr6git does this actually work as a drop in replacement without the need of recompilation?

**Comment by Duncaen** [comment]
No that doesn't work.

**Comment by Johnnynator** [comment]
Also the `*.so` should not be in the `-devel` subpackage

**Comment by cr6git** [comment]
@Johnnynator I removed `*.so` from `-devel` subpkg.

**Pull request closed without merging**
