### PR TITLE
runit: fix build PIE

### PR DESCRIPTION
**Pull request by thypon**

### CODE REVIEW

**Comment by chneukirchen** [comment]
I'm against dropping `-static`, by default it only applies to runit and runit-init, which have virtually no attack surface.

**Comment by thypon** [comment]
We have to measure the performance impact. By the way there is the static build option that permits to have a full static runit binary. I don't get when a mixed static/dynamic runit is usefull.

**Comment by Gottox** [comment]
[diff ignoring whitespaces](https://github.com/voidlinux/void-packages/pull/2373/files?w=1)

**Comment by thypon** [comment]
@Gottox thank you, i rebased.

**Comment by xtraeme** [comment]
Looks good to me.

Please revbump it.

**Comment by xtraeme** [comment]
I agree with @chneukirchen 

It's good enough as is already, there's no need to chang ethis.

**Pull request closed without merging**
