### PR TITLE
FrankenWM: replace frankenwm-git and unbreak build (#1779)

### PR DESCRIPTION
**Pull request by beefcurtains**
* Upstream packages it as ``FrankenWM``, binary is still ``frankenwm`` (so this should be a drop-in replacement).
* ``pkg-config --cflags`` is never called, cross builds appear to work anyway
* Travis fails because of @Ypnose email addy

### CODE REVIEW

**Comment by Ypnose** [comment]
I know I have to modify the version, because that's ME that requested the tag upstream.   Will merge my own copy this weekend. I prefer using <code>sed</code> instead of an external patch. And my email is fine…

**Comment by xtraeme** [comment]
Assigned to maintainer @Ypnose 

Do not merge this one, @Ypnose will import new pkg.

To respect previous naming behaviour I'd like to see this without caps.

**Comment by thypon** [comment]
meanwhile they released a 1.0.1

**Comment by Ypnose** [comment]
Pushed the fixed version → 6ab5eaf6c1565c

**Comment by beefcurtains** [comment]
Don't bullshit me, I had the thing working just fine. You could've added your changes on top of this. I'll never update one of your packages again, if that's what you want.

**Comment by Ypnose** [comment]
The version I pushed was already done one week ago (for <code>1.0</code>), as I said it in my previous comment. It was much earlier before you decided to update it. And by "fixed", I meant the git transition. I didn't even used your changes.
And if I do not want to take your additions, that's my problem. I owe you nothing…
You seem to be angry, you should calm down.

**Comment by beefcurtains** [comment]
Don't you fucking condescend me, that's unacceptable and I'll have none of it. And you could've left a note in #1779 that you were working on it.

**Comment by Ypnose** [comment]
Ok, stop the diplomacy. Are you fucking dumb? Are you unable to read my comment? What <code>Will merge my own copy this weekend.</code> means to you?
Once again, I do my business, I do not care about what you decide to do. Unacceptable? You started the "streak" why your previous patronizing comment. Seems like I have to excuse me to update my package. Too bad I won't do it. Go cry alone.

**Comment by beefcurtains** [comment]
Now you are *DELIBERATELY* insulting me. That is not becoming of a Void collaborator.
I don't care if you want my changes, but I care how you communicate with others. If insulting people is your method of communicating, you yourself are dumb for even thinking of spouting such nonsense.

**Comment by Ypnose** [comment]
You started to use rude words, I didn't.

**Comment by beefcurtains** [comment]
Well sorry for using "bullshit", but 2 wrongs don't make a right.

**Comment by Ypnose** [comment]
I was a collaborator much before @xtraeme decided to give your write rights here. Didn't have a single problem. I've never had to talk like this to the other commiters, because nobody talked to me like that.

**Comment by beefcurtains** [comment]
None of that is any good reason to insult me.

**Comment by Gottox** [comment]
Both of you guys are whiny bastards. Having those personal arguments on github is embarrassing. If you want to argue about who insulted whom do it somewhere where it's not publicly visible and sent to everyone watching this channel.

**Comment by beefcurtains** [comment]
We were just having a slight disagreement, no big deal. I still :heart: you all!

**Pull request closed without merging**
