### PR TITLE
geeqie: update to 1.3.

### PR DESCRIPTION
**Pull request by lemmi**

### CODE REVIEW

**Comment by lemmi** [comment]
i have no idea why, but when crosscompiling the configure script is generated without the gtk check. thus pkg-config isn't run and the include paths aren't added. suggestions?

**Comment by Vaelatern** [comment]
Possibly `autoreconf -fi`?

**Comment by lemmi** [comment]
sadly, no :\
```
=> geeqie-1.3_1: running pre_configure ...  
aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'  
configure.in:132: warning: AM_NLS is m4_require'd but not m4_defun'd  
/usr/share/aclocal/intltool.m4:27: IT_PROG_INTLTOOL is expanded from...  
configure.in:132: the top level  
configure.in:132: warning: AM_NLS is m4_require'd but not m4_defun'd  
aclocal.m4:675: IT_PROG_INTLTOOL is expanded from...  
configure.in:132: the top level  
configure.in:132: warning: AM_NLS is m4_require'd but not m4_defun'd  
aclocal.m4:675: IT_PROG_INTLTOOL is expanded from...  
configure.in:132: the top level  
configure:7953: error: possibly undefined macro: AM_NLS  
      If this token and others are legitimate, please use m4_pattern_allow.  
      See the Autoconf documentation.  
autoreconf: /usr/bin/autoconf failed with exit status: 1  
=> ERROR: geeqie-1.3_1: failed to run pre_configure() at line 21.  
```

**Comment by xtraeme** [comment]
AM_NLS is due to missing gettext-devel in hostmakedepends.

**Comment by lemmi** [comment]
That gets me as far as running the autogen.sh script. But still missing the gtk check.

**Pull request closed without merging**
