### PR TITLE
qt5: update to 5.10.1

### PR DESCRIPTION
**Pull request by pullmoll**
Build succeeded here for:
- [x] x86_64
- [x] i686
- [x] x86_64-musl
- [x] i686-musl
- [x] aarch64
- [x] aarch64-musl
- [x] armv7l
- [x] armv7l-musl
- [x] armv6l
- [x] armv6l-musl
- [ ] armv5tel qtwebengine fails with `Project ERROR: armv5te architecture is not supported`
- [ ] armv5tel-musl (same)
- [ ] mips-musl
- [ ] mipshf-musl
- [ ] mipsel-musl
- [ ] mipselhf-musl

It seems arm* can be cross compiled from an x86_64 environment with `-no-webengine-v8-snapshot`. Testing this and a bunch of fixes for qtwayland.

[ci skip]

P.S.: For the adventurous *early adopter* there is [a repository to play with](http://repo.voidlinux.de/current/qt5). I tested the x86_64 build with some of my qt5 projects and saw no issues so far.

### CODE REVIEW

**Comment by pullmoll** [comment]
I'll use this comment to tell what the current issue(s) with cross building is or are.
In case you want to help you can pull this PR and try to cross build for e.g. aarch64 first.

- [ ] pre-configure gn bootstrap fails with this error:
```
ERROR Unresolved dependencies.
//content/common:common(//build/toolchain/linux:x64)
  needs //build/linux:fontconfig(//build/toolchain/linux:x64)
```

**Comment by maxice8** [comment]
Seems like qt5 on the new repo has a bad RSA signature

```
$ sudo xbps-install -Suy
[*] Updating `http://repo.voidlinux.de/current/qt5//x86_64-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/x86_64-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/multilib/x86_64-repodata' ...
1 package will be downloaded:

  qt5-5.10.0_1 
2 packages will be updated:

  gopass (1.6.10_1 -> 1.6.10_2) 
  qt5 (5.8.0_10 -> 5.10.0_1) 

Size to download:             7799KB
Size required on disk:        8586KB
Free space on disk:             46GB


[*] Downloading binary packages
qt5-5.10.0_1.x86_64.xbps: [7798KB 0%] 140MB/s ETA: 00m00s
qt5-5.10.0_1.x86_64.xbps: [7798KB 2%] 242KB/s ETA: 00m35s
qt5-5.10.0_1.x86_64.xbps: [7798KB 12%] 541KB/s ETA: 00m14s
qt5-5.10.0_1.x86_64.xbps: [7798KB 22%] 647KB/s ETA: 00m10s
qt5-5.10.0_1.x86_64.xbps: [7798KB 34%] 728KB/s ETA: 00m07s
qt5-5.10.0_1.x86_64.xbps: [7798KB 44%] 733KB/s ETA: 00m06s
qt5-5.10.0_1.x86_64.xbps: [7798KB 54%] 747KB/s ETA: 00m04s
qt5-5.10.0_1.x86_64.xbps: [7798KB 67%] 778KB/s ETA: 00m03s
qt5-5.10.0_1.x86_64.xbps: [7798KB 79%] 801KB/s ETA: 00m02s
qt5-5.10.0_1.x86_64.xbps: [7798KB 92%] 823KB/s ETA: 00m00s
qt5-5.10.0_1.x86_64.xbps: 7798KB [avg rate: 893KB/s]
qt5-5.10.0_1.x86_64.xbps.sig: [512B 100%] 9259KB/s ETA: 00m00s
qt5-5.10.0_1.x86_64.xbps.sig: 512B [avg rate: 9259KB/s]

[*] Verifying package integrity
gopass-1.6.10_2: verifying RSA signature...
qt5-5.10.0_1: verifying RSA signature...
ERROR: qt5-5.10.0_1: the RSA signature is not valid!
ERROR: qt5-5.10.0_1: removed pkg archive and its signature.
```

**Comment by pullmoll** [comment]
Hmm.. there's something wrong with my script to sign the packages it seems.
I'll zap the entire qt5 subdir and rebuild the pkgs to upload them again later or tomorrow.

**Comment by newbluemoon** [comment]
The gn error occurs when it’s trying to rebuild itself with itself. Before building it checks if all dependencies can be resolved. I don’t know where the fontconfig dependency comes from, but I highly doubt that gn needs it for itself.

There is an `-n` option to gn’s `bootstrap.py` which disables a rebuild with itself. I also removed fontconfig from `hostmakedepends` and it’s working. Qt’s configure stage did detect fontconfig. Now it’s building (aarch64 btw.) ... Let’s wait and see what comes up next ;)

So these are the changes I made:
```
--- template.orig
+++ template
@@ -48,8 +48,7 @@
 	# Need some devel packages in the host to build qmake, moc, uic, rcc
 	# wayland-devel contains /usr/bin/wayland-scanner
 	hostmakedepends+=" zlib-devel wayland-devel icu-devel"
-	# More devel packages required to build gn for the hose
-	hostmakedepends+=" fontconfig-devel"
+
 	if [ "$XBPS_MACHINE" = "x86_64" ]; then
 		hostmakedepends+=" gcc-multilib"
 	fi
@@ -217,7 +216,7 @@
 		CC="$CC_host" CXX="$CXX_host" LD="$CXX_host" \
 		CFLAGS="$CFLAGS_host" CXXFLAGS="$CXXFLAGS_host" LDFLAGS="$LDFLAGS_host" \
 		PKGCONFIG=/usr/bin/pkgconfig PKG_CONFIG_PATH="/usr/lib/pkgconfig:/usr/share/pkgconfig" \
-			python2 bootstrap/bootstrap.py --gn-gen-args "${conf}"
+			python2 bootstrap/bootstrap.py -n --gn-gen-args "${conf}"
 		cd ${wrksrc}
 
 		mkdir -p qtwebengine/src/3rdparty/chromium/tools/gn/out/Release
```

**Comment by newbluemoon** [comment]
Patching out the gnu_thin_archive flag in `gcc_toolchain.gni` breaks calling `gcc_ar_wrapper.py` later because `arcommand` doesn’t get set. So I expanded the patch to `gcc_toolchain.gni` and set the corresponding `arcommand` manually (around line 330):

```
sed -i qtwebengine/src/3rdparty/chromium/build/toolchain/gcc_toolchain.gni \
        -e "/defined(toolchain_args.gnu_thin_archive/,+5d" \
        -e "s/\(extra_arflags =\) arcommand/\1 \"rcsD\"/"
```

**Comment by newbluemoon** [comment]
Now it fails with

```
[10304/22014] LINK host/transport_security_state_generator
FAILED: host/transport_security_state_generator 
/usr/bin/python2 "../../3rdparty/chromium/build/toolchain/gcc_link_wrapper.py" --output="host/transport_security_state_generator" -- /usr/bin/g++ -Wl,--fatal-warnings -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -Wl,--no-as-needed -lpthread -Wl,--as-needed -m64 -Wl,-O1 -Wl,--gc-sections -Wl,-rpath-link=host -Wl,--disable-new-dtags -o "host/transport_security_state_generator" -Wl,--start-group @"host/transport_security_state_generator.rsp"  -Wl,--end-group   -ldl -lpthread -lrt -lsmime3 -lnss3 -lnssutil3 -lplds4 -lplc4 -lnspr4 
/usr/bin/ld: cannot find -lsmime3
/usr/bin/ld: cannot find -lnss3
/usr/bin/ld: cannot find -lnssutil3
/usr/bin/ld: cannot find -lplds4
/usr/bin/ld: cannot find -lplc4
/usr/bin/ld: cannot find -lnspr4
collect2: error: ld returned 1 exit status
```

What caught my eye was `/usr/bin/g++`. Turns out webengine is using the host compiler and not the cross setup. But other Qt5 modules which have been built up to now seem to be OK in that respect.

So back to square one, I guess.

**Comment by pullmoll** [comment]
@newbluemoon Thanks for finding this step to a solution. I think then perhaps patching gcc_toolchain.gni can be avoided altogether. I'll be testing this later.

For the repo: I don't know what I'm doing wrong but signing the pkgs does not work for some reason. I get no error signing the `*.xbps` files but still see an error message after downloading them and the `*.sig` from the repo. Perhaps my signing key is corrupted or I'm doing it wrong :P @maxice8 you could perhaps download the `*.x86_64.xbps` files and install from a local directory. In that case signatures are not checked.

**Comment by Johnnynator** [comment]
I just checked your repo and atleast the *-musl signatures do work.

**Comment by pullmoll** [comment]
@Johnnynator I overlooked to also sign the *-repodata files in that subdirectory. Now it works.

**Comment by pullmoll** [comment]
So the next and possibly final thing to do is to find out why qmlcachegen won't link for the target arch.
I tried to add a number of modules to `QT = …` in `srcpkgs/qt5/files/qmlcachegen.pro` to no avail.
Ideas welcome :-)

**Comment by newbluemoon** [comment]
Regarding qmlcachegen I found this bug report: https://bugreports.qt.io/browse/QTBUG-60597
But it says it’s fixed?

**Comment by pullmoll** [comment]
I removed qmlcachegen from the list of files to rebuild and also from the installed packages (when cross compiling).

**Comment by pullmoll** [comment]
Just FYI: I'm trying with a shadow build now which may or may not improve things.

**Comment by pullmoll** [comment]
I'm doing it wrong.. totally wrong.. the cross building I mean.

It actually (no longer) requires so much hackery but just a correctly set up mkspec for the target and a `-hostprefix something` to separate host tools from target tools – it seems.

I got much farther now that I removed the entire `do_install()` section for cross building. I'll clean up the mess and once I can build for aarch64 will update the PR again.

It **had** to be much simpler than we (me) tried to achieve it 8-)

**Comment by pullmoll** [comment]
Wooot! I just now cross built it for [aarch64](http://repo.voidlinux.de/current/qt5).

**Comment by pullmoll** [comment]
So now armv6l failes with invalid assembler code for the architecture.
It's in qtwebengine somewhere and the output is:
```
{standard input}: Assembler messages:
{standard input}:35: Error: selected processor does not support `yield' in ARM mode
```
The patch for qt5-5.8.0 for the YIELD_PROCESSOR macro does not work. It has to be adapted for the update.

**Comment by pullmoll** [comment]
Oh dear! I am having *fun* with `rpi-userland` outdated (5 years old!) versions of KhronosGroup GLES2 headers resulting in conflicts with the definitions and files in qtwayland. This will probably be tough to solve as I would need to patch around the incompatibilities like modified function parameters for e.g.
```
GL_APICALL void GL_APIENTRY glShaderSource (GLuint shader, GLsizei count, const GLchar* const* string, const GLint *length);
```
of `GLES3/gl32.h` in the qt5 tree vs.
```
GL_APICALL void GL_APIENTRY glShaderSource (GLuint shader, GLsizei count, const GLchar** string, const GLint* length);
```
of `/opt/vc/include/GLES2/gl2.h` - and I don't have a clue and nothing but a rpi zero w/o network *lol*

I tried to inject the updated KhronosGroup `GLES2` headers found at https://github.com/KhronosGroup/OpenGL-Registry/tree/master/api into the `rpi-userland` source tree but it of course fails to build then.

I wonder if anyone else already solved this mess?

I think I'll try to disable `qt5-wayland` for `arm*` for now and see how far I can get :-P

**Comment by pullmoll** [comment]
And another hack to get armv6* built. Now our officially supported architectures are covered.
Remaining thing to do is find out why the Designer app and lib are not built when cross compiling.

**Comment by Johnnynator** [comment]
Is it possible that the the lrelease binary is missing? I can only find the symlink (checked on x86_64{,-musl}. On aarch64 is at least `/usr/lib/qt5/bin/lrelease-target`, but the `lrelease-qt5` symlink links also there against the no exisiting lrelease)

```
for i in *x86_64.xbps; do tar tvf $i | grep lrelease ;done
lrwxrwxrwx 0/0               0 2018-02-13 19:54 ./usr/bin/lrelease-qt5 -> ../lib/qt5/bin/lrelease
```
```
for i in *aarch64.xbps; do tar tvf $i | grep lrelease ;done
-rwxr-xr-x 0/0          497544 2018-02-13 19:54 ./usr/lib/qt5/bin/lrelease-target
lrwxrwxrwx 0/0               0 2018-02-13 19:54 ./usr/bin/lrelease-qt5 -> ../lib/qt5/bin/lrelease
```

**Comment by pullmoll** [comment]
Oh, yes, I broke something with moving lrelease, lupdate and lconvert to qt5-host-tools. I have to take a close look at the log to see what goes wrong.

**Comment by pullmoll** [comment]
Ok, aarch64 seems to be fine now. The lconvert, lupdate and lrelease are in qt5-host-tools and the designer and libQt5Designer.so.5.10.1 are in qt5-tools and qt5-tools-devel.
Now building the final 4 important `armv[67]l{,-musl}` and then this is ready to be merged.

**Comment by pullmoll** [comment]
Done.
/me opens a bottle of excellent red wine and waits for one of @voidlinux/pkg-committers to merge.

**Comment by mvf** [comment]
Thank you so much for making this happen, @pullmoll! Among other things, this is a huge quality of life improvement for IME users. [#QTBUG-58362](https://bugreports.qt.io/browse/QTBUG-58362)

**Pull request closed without merging**
