### PR TITLE
p11-kit: update to 0.23.12.

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by pullmoll** [comment]
Did you try if that update works with `gnutls` again, i.e. compatibility to previous versions?
It seems the previous update broke gnults (see #14750).

**Comment by maxice8** [comment]
On Wed, May 30, 2018 at 12:28:32PM -0700, Jürgen Buchmüller wrote:
> Did you try if that update works with `gnutls` again, i.e. compatibility to previous versions?
> It seems the previous update broke gnults (see #14750).
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/voidlinux/void-packages/pull/14798#issuecomment-393287763

yes i built it successfully in x86_64, didn't test on *-musl or aarch64*|armv* .

the change in specific that fixes it comes from https://github.com/p11-glue/p11-kit/pull/160

**Comment by maxice8** [comment]
On Wed, May 30, 2018 at 12:28:32PM -0700, Jürgen Buchmüller wrote:
> Did you try if that update works with `gnutls` again, i.e. compatibility to previous versions?
> It seems the previous update broke gnults (see #14750).
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/voidlinux/void-packages/pull/14798#issuecomment-393287763

regardless i would try build again just to be sure.

**Comment by pullmoll** [comment]
I'm trying with my branch gcc81 and see if that solves the problems.

**Comment by pullmoll** [comment]
Yep, it really solves the issue. Thanks!

**Comment by maxice8** [comment]
On Wed, May 30, 2018 at 07:36:28PM +0000, Jürgen Buchmüller wrote:
> Yep, it really solves the issue. Thanks!
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/voidlinux/void-packages/pull/14798#issuecomment-393290033

<3

**Comment by pullmoll** [comment]
But p11-kit doesn't cross build for `*-musl` .. strange. It cross builds for `*-glibc`, so this has to be some specific check in configure.

**Comment by maxice8** [comment]
On Wed, May 30, 2018 at 07:50:53PM +0000, Jürgen Buchmüller wrote:
> But p11-kit doesn't cross build for `*-musl` .. strange. It cross builds for `*-glibc`, so this has to be some specific check in configure.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/voidlinux/void-packages/pull/14798#issuecomment-393295016

I can take a look later (adding tests to neovim).

**Comment by pullmoll** [comment]
FWIW: [this is the change](https://github.com/p11-glue/p11-kit/commit/71b62aa1cdbdec3724c8e451f621309994dc59a0) which makes cross building `p11-kit` fail for `*-musl`.
In case of glibc the code relies on the `extern int __libc_enable_secure;` and configure does not (need to) run the `issetugid()` brokenness test.

That change should probably check for a configure option to override the test like `--with-issetugid-openbsd={no,yes}`. I dunno how to achieve that by patching `configure.ac`, though.

**Pull request closed without merging**
