### PR TITLE
wpa_gui: rebuild (missing aarch64-musl package)

### PR DESCRIPTION
**Pull request by Piraty**

### CODE REVIEW

**Comment by maxice8** [comment]
While you're at it.

homepage should be https://w1.fi/wpa_supplicant/
use SPDX identifier for the license
and update the maintainer to 'Leah Neukirchen <leah@vuxu.org>'

**Comment by Piraty** [comment]
regarding license, the tarball has `README` (which is used by wpa_supplicant) and `COPYING`, both containing BSD-based texts but different ones.

**Comment by maxice8** [comment]
On Wed, Apr 25, 2018 at 09:39:29PM +0000, Piraty wrote:
> regarding license, the tarball has README (which is used by wpa_supplicant) and
> COPYING, both containing BSD-based texts but different ones.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

use the one from COPYING

**Comment by maxice8** [comment]
please squash them into one commit.

**Comment by Piraty** [comment]
squashed

**Pull request merged**
