### PR TITLE
nano: remove GNU in description

### PR DESCRIPTION
**Pull request by rafeyu**
I remove GNU mark from nano package description.

See: http://git.savannah.gnu.org/cgit/nano.git/commit/?id=3e5fcec76c12b45a5dd12cb731e160c8e8fb1e0c

### CODE REVIEW

**Comment by Gottox** [comment]
please increase revision, thanks.

**Comment by rafeyu** [comment]
I'm sorry. Fixed

**Comment by Vaelatern** [comment]
Can we add the word "text" while we are here? Make it easier to find it when searching.

**Comment by rafeyu** [comment]
@Vaelatern Do you mean "GNU text" or something? I'm sorry, English isn't my native language, so a little bit confuse :(

**Comment by Duncaen** [comment]
I guess `The nano text editor`.

**Pull request merged**
