### PR TITLE
linux4.14: update to 4.14.49.

### PR DESCRIPTION
**Pull request by pbui**

### CODE REVIEW

**Comment by cr6git** [comment]
4.14.38 will be released soon.

**Comment by cr6git** [comment]
@pbui you could change [x86_64-dotconfig](https://github.com/pbui/void-packages/blob/717119f372d569e9007c9b60da4a0c331691d436/srcpkgs/linux4.14/files/x86_64-dotconfig#L7694), [i386-dotconfig](https://github.com/pbui/void-packages/blob/717119f372d569e9007c9b60da4a0c331691d436/srcpkgs/linux4.14/files/i386-dotconfig#L7606), and [armv5tel-dotconfig](https://github.com/pbui/void-packages/blob/717119f372d569e9007c9b60da4a0c331691d436/srcpkgs/linux4.14/files/armv5tel-dotconfig#L5545) according to [#13450](https://github.com/voidlinux/void-packages/issues/13450).

**Comment by pbui** [comment]
@cr6git I've made the changes.

**Comment by cr6git** [comment]
@pbui Time passes, and now we are at 4.14.40.

**Pull request merged**
