### PR TITLE
nodejs: enable cross compilation

### PR DESCRIPTION
**Pull request by cr6git**
Trying to solve [#8951](https://github.com/voidlinux/void-packages/issues/8951). 

I wonder why [#8974](https://github.com/voidlinux/void-packages/pull/8974) failed to build because of this strange error: 
````
Installing xbps...
unxz: (stdin): File format not recognized
tar: This does not look like a tar archive
tar: ./usr/bin/xbps-*: Not found in archive
tar: Exiting with failure status due to previous errors
````

### CODE REVIEW

**Comment by arete** [comment]
Bad SSL certificate?

**Comment by cr6git** [comment]
hmm... what unxz has to do with SSL ?

**Comment by arete** [comment]
https://github.com/voidlinux/void-packages/blob/7920f82ae525517510b46e0de8757cee386126f8/common/travis/prepare.sh#L16

`wget -q -O - http://repo.voidlinux.eu/static/xbps-static-latest.x86_64-musl.tar.xz | \`
this is the failure

**Comment by arete** [comment]
@cr6git  close my pull request  #8974 ?

**Pull request closed without merging**
