### PR TITLE
handle changelog.

### PR DESCRIPTION
**Pull request by maxice8**
based on https://github.com/voidlinux/void-packages/pull/4068 , just added an entry to Manual.md

### CODE REVIEW

**Comment by Vaelatern** [comment]
Please fix commit message

**Comment by maxice8** [comment]
Will do soon, waiting for my big fat burger in a fast door queue

**Comment by maxice8** [comment]
done

**Comment by ebfe** [comment]
Why does the changelog have to be in plain text? That's impractical and a useless restriction.
This change doesn't make sense without xbps 0.52 you need to bump XBPS_VERSION_REQ.

**Comment by Vaelatern** [comment]
What other than plain text would it be?

**Comment by Vaelatern** [comment]
1441834458

**Comment by Duncaen** [comment]
Well its clear that you don't supply a change log link as binary, the plaintext indicates a url should point to a address that has the content type `text/plain`, which is in many cases not possible.

**Pull request closed without merging**
