### PR TITLE
albert: Added qt5-plugin-sqlite as a runtime dependency

### PR DESCRIPTION
**Pull request by jcjordyn130**
This is because everytime I tried to run it I got:
Warning: QSqlDatabase: QSQLITE driver not loaded
Warning: QSqlDatabase: available drivers:
FATAL: Unable to establish a database connection.

### CODE REVIEW

**Comment by Vaelatern** [comment]
Supersedes #5216.

**Comment by asergi** [comment]
Please revbump it.

**Comment by jcjordyn130** [comment]
How can I redownload my copy from my github? every time I try the change is reverted.

**Comment by pullmoll** [comment]
Just commit with --amend and force push:
```shell
# Edit the template and change revision to 2
git add srcpkgs/albert/template
git commit --amend
git push -f
```

**Comment by jcjordyn130** [comment]
@pullmoll I can't edit it, its not there.

**Comment by pullmoll** [comment]
Just not the template, or nothing at all?
If you deleted files in srcpkgs/albert, then `git checkout srcpkgs/albert` should restore them.
If you deleted your repo, just clone again, i.e. `git clone git@github.com/jcjordyn130/void-packages`.

**Comment by pullmoll** [comment]
To simplify this issue, I pushed https://build.voidlinux.eu/changes/33130
You should make yourself comfortable with git and, if you don't know `vi`, set `EDITOR=<your-editor>` in your environment, so git will use your preferred editor instead of `vi`.

**Pull request closed without merging**
