### PR TITLE
linux: update to 4.12.

### PR DESCRIPTION
**Pull request by Gottox**
Updates the default kernel to 4.12.

Before merging check:
* [x] nvidia
* [x] nvidia340
* [x] acpi_call-dkms-1.2.0_2
* [ ] batman-adv-2016.4_1
* [ ] batman-adv14-2013.4.0_8
* [ ] bbswitch-0.8_2
* [x] exfat-dkms-1.2.8_2
* [ ] spl-0.6.5.10_1 See #7158 
* [x] sysdig-0.17.0_1
* [x] tp_smapi-dkms-0.42_2
* [x] virtualbox-ose-dkms-5.1.24_1
* [x] virtualbox-ose-guest-dkms-5.1.24_1
* [x] wireguard-0.0.20170706_1
* [ ] zfs-0.6.5.10_1 See #7158

### CODE REVIEW

**Comment by Sir-Boops** [comment]
Virtualbox-ose and nvidia are working fine

**Comment by cr6git** [comment]
`linux4.12` with `nvidia340` is ok for me.

**Comment by Vaelatern** [comment]
zfs will need a bump to what is currently a `rc` before this is considered safe by upstream. They only support through `-rc3`.

**Comment by chneukirchen** [comment]
wireguard and sysdig are fine.

**Comment by cr6git** [comment]
...but `nvidia304-dkms` build failed ! 
Looking at the Arch package [nvidia-304xx](https://git.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/nvidia-304xx), there's a patch for linux4.12

**Comment by thypon** [comment]
docker lvm backend is broken with 4.12

**Comment by Gottox** [comment]
@thypon Is there a bugreport?

**Comment by thypon** [comment]
@Gottox now there is https://github.com/moby/moby/issues/34283

**Comment by freshprince** [comment]
`tp_smapi-dkms-0.42_2` built fine for 4.12 on x64_64-musl

**Comment by ebfe** [comment]
acpi_call-dkms-1.2.0_2 was already fixed in 783532482d12f08be54dd61a41c4aa73a636e239

**Comment by the-maldridge** [comment]
linux metapackage has pointed at linux4.12 for some time now.

**Pull request closed without merging**
