### PR TITLE
New package: ccl-1.11

### PR DESCRIPTION
**Pull request by lipidity**
The Clozure CL implementation of the Common Lisp programming language

### CODE REVIEW

**Comment by chneukirchen** [comment]
According to the website, the license is Apache-2.0?

If the examples are not too big, you can install them too.

Please use a `case` in line 18/19.

Else :+1:

**Comment by Vaelatern** [comment]
Nopie?

**Comment by chneukirchen** [comment]
Nopie is ok, as CCL is a native compiler that probably doesn't support pie.

**Comment by lipidity** [comment]
Thanks @chneukirchen and @Vaelatern for the feedback on my first submission.

**Pull request merged**
