### PR TITLE
Linphone

### PR DESCRIPTION
**Pull request by Duncaen**
TLS/SSL support depends on polarssl and is missing.
Its is not really tested, but it compiles and runs.

`configure_args="--disable-strict"` in mediastreamer because of ffmpeg deprecation warnings.

### CODE REVIEW

**Comment by xtraeme** [comment]
Looks good at first glance, please rebase.

Thanks :+1:

**Comment by Duncaen** [comment]
Rebased and renamed antlr3 to antlr3-bin or should it be antlr3?

**Comment by dominikh** [comment]
What is the state of this PR?

**Comment by Duncaen** [comment]
@dominikh need to know if I should go for `antlr3-bin` or `antlr3`.

**Comment by Gottox** [comment]
Any news?

**Comment by Vaelatern** [comment]
@Duncaen @Gottox We figured in IRC it should be `antlr3-bin` but @xtraeme didn't weigh in, and nothing was for certain, so it continued to not be merged.

**Comment by Duncaen** [comment]
Ok, I rebase and update some of the packages later and then push it.

**Comment by the-maldridge** [comment]
@Duncaen you win second oldest PR at this time!  still interested in trying to close this PR?

**Pull request closed without merging**
