### PR TITLE
libtorrent: update to 0.13.5

### LINKED ISSUE #1924: RTorrent/libtorrent links are down
https://github.com/rakshasa/rtorrent/issues/295

Maybe we should move to github releases.

### PR DESCRIPTION
**Pull request by pullmoll**
The homepage does not exist anymore, thus migrate to github
Use the github download location and rename file to include pkgname

Partially closes #1924

### CODE REVIEW

**Comment by pullmoll** [comment]
I can't get cross building for arm* working. It always tries to link against `/lib/libstdc++.so` instead of `${XBPS_CROSS_BASE}/lib/libstdc++.so`

Perhaps someone knows how to adapt the patch `srcpkgs/libtorrent/patches/fix-sysroot-handling.patch`?

**Comment by xtraeme** [comment]
This issue should be fixed by forcing a `libtoolize -f` or `autoreconf -fi`.

**Comment by pullmoll** [comment]
`autoreconf -fi` is already there in `pre_configure()` and it runs libtoolize.
Running libtoolize once more with `-f` or `-fi` doesn't change a thing it seems.

**Comment by xtraeme** [comment]
In this case there must be a `-L/usr/lib` somewhere that must be removed.

**Comment by pullmoll** [comment]
Thank you! Several wrong `-L/lib` caused the problem. Replacing them with `-L${XBPS_CROSS_BASE}/lib` solves the issue.

**Pull request merged**
