### PR TITLE
New package: libudev0-shim-1

### PR DESCRIPTION
**Pull request by autrimpo**
A shim package for libudev.so.0 compatibility, required for running Steam with native libraries.

### CODE REVIEW

**Comment by Gottox** [comment]
Is this any useful outside of steam?

**Comment by autrimpo** [comment]
Probably not, even the Arch official package is a dependency of only `steam-native-runtime`. But the package is tiny (less than 3kB when built on my system), builds extremely fast and most probably won't be updated often (if at all), so the maintenance costs are almost zero.

**Comment by Gottox** [comment]
I would prefer to ship with steam directly.

**Comment by autrimpo** [comment]
As in ship the shim in the steam package? Sounds like a good idea.

**Comment by Gottox** [comment]
👍 

Closing

**Pull request closed without merging**
