### PR TITLE
[WIP] Update Cinnamon to 3.6

### PR DESCRIPTION
**Pull request by Johnnynator**
Menu is currently crashing on musl for me so have to check that first #6495

### CODE REVIEW

**Comment by pullmoll** [comment]
Then instead of `mozjs38` probably `mozjs24` can be removed?
It seems `cjs` was the last package referencing it.

**Comment by pullmoll** [comment]
Oops, this merge was by accident. I'll take a look at why menu fails with musl libc.

**Comment by Johnnynator** [comment]
xD, at least 3.6 isn't as buggy on musl as our current 3.2. So the merge only improved the situation.

**Comment by pullmoll** [comment]
Glad to hear that sometimes accidents improve a situation :smile_cat:

**Pull request closed without merging**
