### PR TITLE
New package: tellico

### PR DESCRIPTION
**Pull request by cr6git**
resolves [#8169](https://github.com/voidlinux/void-packages/issues/8169)

### CODE REVIEW

**Comment by cr6git** [comment]
The build failed on `x86_64-musl` **only**, in the same way as [#8287](https://github.com/voidlinux/void-packages/pull/8287).

**Comment by Johnnynator** [comment]
tellico compiles fine for musl if _GNU_SOURCE is set.

```
--- CMakeLists.txt.bak	2017-10-18 17:12:25.378781856 +0200
+++ CMakeLists.txt	2017-10-18 17:12:26.663781772 +0200
@@ -230,6 +230,7 @@
 #    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wnon-virtual-dtor -Wno-long-long -Wextra -fno-check-new -Woverloaded-virtual")
     # remove -Wno-deprecated when porting to KF5 is more advanced
     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wnon-virtual-dtor -Wno-long-long -fno-check-new -Woverloaded-virtual -Wno-deprecated -Wno-deprecated-declarations")
+    add_definitions(-D_GNU_SOURCE)
 endif(CMAKE_COMPILER_IS_GNUCXX)
 
 #add_definitions(${QT_DEFINITIONS}
```

**Comment by cr6git** [comment]
I added your patch for `x86_64-musl`. 
Perfect ! Good job Johnny ! :)

**Comment by Johnnynator** [comment]
@cr6git if a package can't be cross compild because of one dependencie then it is enough that the dependency is marked as nocross. Marking a package as nocross where it is unknow if it cross compiles is a bit missleading.

**Comment by cr6git** [comment]
I understand. I'm not comfortable with that, sorry...

**Pull request closed without merging**
