### PR TITLE
New package: perl-Net-IMAP-Simple-1.2207.

### PR DESCRIPTION
**Pull request by maxice8**
cc @chneukirchen 

#15091

### CODE REVIEW

**Comment by newbluemoon** [comment]
Was just about to open a PR for this, but you were faster. ;)

Just two things: `homepage` shouldn’t point to search.cpan.org anymore, see 014cd960f8173f74984bf5c40d8eaf713adc5add
and perl-Parse-RecDescent depends on perl-Text-Balanced which isn’t in the repo as well, but I have a template ready. If you want to make use of it to save some time here it is:

```
# Template file for 'perl-Text-Balanced'
pkgname=perl-Text-Balanced
version=2.03
revision=1
noarch=yes
wrksrc="${pkgname#perl-}-${version}"
build_style=perl-module
hostmakedepends="perl"
makedepends="perl"
depends="perl"
short_desc="Extract delimited text sequences from strings"
maintainer="newbluemoon <blaumolch@mailbox.org>"
license="Artistic-1.0-Perl, GPL-1.0-or-later"
homepage="https://metacpan.org/release/Text-Balanced"
distfiles="${CPAN_SITE}/Text/Text-Balanced-$version.tar.gz"
checksum=057753f8f0568b53921f66a60a89c30092b73329bcc61a2c43339ab70c9792c8
```

**Comment by maxice8** [comment]
On Tue, Jun 12, 2018 at 01:39:49PM -0700, newbluemoon wrote:
> Was just about to open a PR for this, but you were faster. ;)
> 
> Just two things: `homepage` shouldn’t point to search.cpan.org anymore, see 014cd960f8173f74984bf5c40d8eaf713adc5add
> and perl-Parse-RecDescent depends on perl-Text-Balanced which isn’t in the repo as well, but I have a template ready. If you want to make use of it to save some time here it is:
> 
> ```
> # Template file for 'perl-Text-Balanced'
> pkgname=perl-Text-Balanced
> version=2.03
> revision=1
> noarch=yes
> wrksrc="${pkgname#perl-}-${version}"
> build_style=perl-module
> hostmakedepends="perl"
> makedepends="perl"
> depends="perl"
> short_desc="Extract delimited text sequences from strings"
> maintainer="newbluemoon <blaumolch@mailbox.org>"
> license="Artistic-1.0-Perl, GPL-1.0-or-later"
> homepage="https://metacpan.org/release/Text-Balanced"
> distfiles="${CPAN_SITE}/Text/Text-Balanced-$version.tar.gz"
> checksum=057753f8f0568b53921f66a60a89c30092b73329bcc61a2c43339ab70c9792c8
> ```
> 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/voidlinux/void-packages/pull/15096#issuecomment-396725877

perl text balanced is part of the core perl distribution.

perl-5.26.1_4	/usr/lib/perl5/core_perl/Text/Balanced.pm
perl-5.26.1_4	/usr/share/man/man3/Text::Balanced.3p

i need to modify my 'xnewperl' script to point to cpanmeta or whatever they want us to use now.

**Comment by newbluemoon** [comment]
Ahh, sorry! I should go to bed. I ran `corelist Test::Balanced` instead of `Text::Balanced`!

But anyway, latest version of perl-Net-IMAP-Simple is 1.2212.

**Comment by maxice8** [comment]
> Ahh, sorry! I should go to bed. I ran corelist Test::Balanced instead of Text::Balanced!

sadly it would only find the manapge, the proper module is in ${long_perl_modules_path}/Text/Balanced

**Comment by newbluemoon** [comment]
I’ll keep that in mind, thanks! :)

**Comment by maxice8** [comment]
cpan has a depedency tracker for packages that tell if they are core modules, always good to check (it doesn't list 3-4 levels deep sometimes so better check the dependnecies of each project as root as you add them) 

http://deps.cpantesters.org/?module=Net%3A%3AIMAP%3A%3ASimple;perl=latest

**Pull request merged**
