### PR TITLE
New package: entr-3.2

### PR DESCRIPTION
**Pull request by thypon**

### CODE REVIEW

**Comment by pullmoll** [comment]
Some kind of `compat.h` shielding against `strlcpy()` redifinition?
I looks like configure thinks musl libc doesn't define `strlcpy()`, which it does in `string.h`.

**Comment by thypon** [comment]
I tried patching with the debian patch but other errors comes out. @pullmoll help with musl is welcome.

**Comment by pullmoll** [comment]
Adding these lines to `pre_build()` solves it for me:
```
        case "$XBPS_TARGET_MACHINE" in
                *-musl) # No need for _LINUX_PORT compat.h and strlcpy.c
                        sed -i Makefile -e "s;-D_LINUX_PORT;;"
        esac
```

**Comment by thypon** [comment]
Errors persists with crosscompilation.

**Comment by pullmoll** [comment]
What kind of errors?
Does the executable not behave as expected?

**Comment by thypon** [comment]
forget what i said, seems to work.

**Pull request merged**
