### PR TITLE
SDL2: add -rpath=/opt/vc/lib on rpi archs 

### PR DESCRIPTION
**Pull request by ebfe**
Linking against SDL2 currently fails on armv[67] because ld apparently can't find libbcm-host.so. 

Better solutions?

### CODE REVIEW

**Comment by ebfe** [comment]
cc @voidlinux/pkg-committers

**Comment by pullmoll** [comment]
Oh, I hadn't seen this and patched around for smpeg2, SDL2_image, SDL2_mixer and SDL2_net as well as rocksndiamonds, which failed to cross build for the same reason.

I guess using -rpath here is the correct fix. Then the my patching around can be reverted.

**Comment by Gottox** [comment]
👍

**Comment by ebfe** [comment]
@thypon what are you doing? ;)

**Comment by thypon** [comment]
@ebfe sorry, I was trying the github inline editing. Didn't thought gives these results.

**Pull request merged**
