### PR TITLE
envypn-font: update tarball URL

### PR DESCRIPTION
**Pull request by Ypnose**
Hi,
The upstream URL has changed so it needs to be updated.

### CODE REVIEW

**Comment by Vaelatern** [comment]
Please don't bump revision

**Comment by Vaelatern** [comment]
The package doesn't change or need a rebuild. People installing the software don't care that a statistic like the distfiles url changed. If the homepage changed, that'd be a revbump (anything you can see with `xbps-query -RS $pkg` would need a revbump).

**Comment by Ypnose** [comment]
Indeed. I just forgot the detail. I also wanted to change the homepage but I won't do it.

**Comment by Vaelatern** [comment]
If also updating the homepage, then a revbump is fine.

**Pull request closed without merging**
