### PR TITLE
Add a install message for bluetooth

### PR DESCRIPTION
**Pull request by SirDoctors**
This is so when people install something bluetooth they know why it may not be working.

### CODE REVIEW

**Comment by Duncaen** [comment]
Please remove the boarders, just plain text.
`xbps-install` already adds separators (https://github.com/voidlinux/xbps/blob/1ffac73f540717b201ff180e14f5576e00fcf48d/bin/xbps-install/state_cb.c#L152).

**Comment by TheDoctorsLife** [comment]
ahh I was unaware that was added by xbps. Will fix that.

**Comment by TheDoctorsLife** [comment]
Alright, removed and rebased.

**Comment by TheDoctorsLife** [comment]
Sorry about that, fixed.

**Comment by TheDoctorsLife** [comment]
The travis error is unrelated to my changes.

**Pull request merged**
