### PR TITLE
x265: updated to version 2.6

### PR DESCRIPTION
**Pull request by Thunderbottom**
Updated x265 to 2.6 as per the [latest release](https://bitbucket.org/multicoreware/x265/downloads/) version.

### CODE REVIEW

**Comment by cr6git** [comment]
You did take into account [#9612](https://github.com/voidlinux/void-packages/issues/9612) ?

**Comment by Thunderbottom** [comment]
Oh I didn't see that, I can try although I'm p sure I might fail

**Comment by cr6git** [comment]
Try contacting @hipperson0 to talk about it with him.

**Comment by Thunderbottom** [comment]
Will do

**Comment by ebfe** [comment]
We have 2.7 now

**Pull request closed without merging**
