### PR TITLE
New package: vrms-void-0.1.1

### PR DESCRIPTION
**Pull request by abenson**

### CODE REVIEW

**Comment by Vaelatern** [comment]
Any reason you needed to develop your own, instead of just patches on top of Debian's code?

**Comment by abenson** [comment]
Debian's vrms just seems to check what repo it was installed from or if the name matches a specific package. Mine is checking the project's stated license for GPL-compatibility. 

Mine's also highlighted some issues with template quality regarding the license field, such as misspellings ("Propietary"), incorrect or ambiguous ("opensource" when it should be "MIT"), and even missing license fields.

**Comment by cr6git** [comment]
With all due respect for RMS, I do not feel like this program may be useful in Void linux. 
About the licenses, for example we have `xlint` to test the validity of our templates.

**Comment by abenson** [comment]
> With all due respect for RMS, I do not feel like this program may be useful in Void linux.

That's fair. It was written in response to a request/comment from someone on #voidlinux.  I think my approach might be off, as well: I was looking at what was GPL compatible, and there is a ton of software that isn't GPL compatible (MPL, for example). 

If people don't feel this has much value added, that's fine, I was just offering it up.

>  About the licenses, for example we have xlint to test the validity of our templates.

I don't think that's as relevant as an argument, as `xlint` doesn't check for correctness or accuracy of the reported license, just that the license is reported.

**Comment by cr6git** [comment]
I'm not expert in licenses, maybe you are right. 😉

**Comment by abenson** [comment]
After some thought and discussion, this might not really be something to be included directly in void.

**Pull request closed without merging**
