### PR TITLE
freeorion: fix build number

### LINKED ISSUE #9610: FreeOrion doesn't show build number
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
Void 4.13.15_1 x86_64 GenuineIntel uptodate rrrm
* package:  
  *affected package(s) including the version*
freeorion-0.4.7.1
### Expected behavior
Show build number in bottom right corner.
### Actual behavior
Shows ```[build ???]```
### Steps to reproduce the behavior
Start the program
### Possible solution
After seeing this error in the buildlog:
```
=> freeorion-0.4.7.1_1: skipping check (XBPS_CHECK_PKGS is disabled) ...
=> freeorion-0.4.7.1_1: running pre-install hook: 00-lib32 ...
=> freeorion-0.4.7.1_1: running pre-install hook: 02-script-wrapper ...
=> freeorion-0.4.7.1_1: running do_install ...
[ 16%] Built target GiGi
WARNING: git not installed or not setup correctly
WARNING: Can't determine git commit!
Writing file: util/Version.cpp
Building v0.4.7.1 build ???
[ 16%] Built target freeorionversion
```
I might suspect that git is missing in the (host)makedeps.

### PR DESCRIPTION
**Pull request by codingHahn**
closes #9610 . I implemented @newbluemoon 's fix and now it shows the buildnumber properly.

### CODE REVIEW

**Comment by Gottox** [comment]
Please increase the revision, thanks :)

**Comment by Gottox** [comment]
aaaaand please squash your commits :)

**Comment by codingHahn** [comment]
I tried do that but had to go to school. Will do it this evening
________________________________

**Comment by Vaelatern** [comment]
next time you can squash it yourself :)

**Comment by codingHahn** [comment]
Thank you

**Pull request merged**
