### PR TITLE
gdbm: update to 1.14.1.

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by pullmoll** [comment]
@maxice8 can you please rebase this PR for php, python3 and ruby?

**Comment by maxice8** [comment]
On Sat, Apr 07, 2018 at 08:43:47AM +0000, Jürgen Buchmüller wrote:
> @maxice8 can you please rebase this PR for php, python3 and ruby?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

done

**Comment by pullmoll** [comment]
perl for `x86_64{,-musl}` needs a manual rebuild on the `aarch64{,-musl}` builders. The others should fix themselves once x86_64 `perl-5.26.2_4` is done.

**Comment by maxice8** [comment]
Can't help im on German class

On Apr 7, 2018 11:39, "Jürgen Buchmüller" <notifications@github.com> wrote:

perl for x86_64{,-musl} needs a manual rebuild on the aarch64{,-musl}
builders. The others should fix themselves once x86_64 perl-5.26.2_4 is
done.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/voidlinux/void-packages/pull/12337#issuecomment-379474101>,
or mute the thread

**Comment by pullmoll** [comment]
Hm.. it seems we need a partial bootstrap on the builders because python is now missing.
This is probably (again) due to the builders resetting the environment after every package which then leaves them with a missing update; python in this case.

Someone needs to manually build python at least.

**Pull request closed without merging**
