### PR TITLE
vopt_onoff: rename to vopt_bool.

### PR DESCRIPTION
**Pull request by maxice8**
true or false is more generic and allows us to use -D\<prop>={true|false} on meson build_style as well.

### CODE REVIEW

**Comment by Gottox** [comment]
Naming of the function is wrong then, but I think this could be an okayish tradeoff.

**Comment by maxice8** [comment]
On Thu, May 03, 2018 at 09:13:09AM -0700, Enno Boland wrote:
> Naming of the function is wrong then, but I think this could be an okayish
> tradeoff.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

naming is wrong if you only consider cmake -DPROP=ON|OFF you can also think of it as vopt turn on or turn off a feature.

anyways that doesn't matter much and the change is completely invisible for the user unless there is some crazy cmake invocation that doesn't accept standard boolean names.

**Comment by ebfe** [comment]
Having a build_style specific function named vopt_bool is entirely confusing.

**Comment by Gottox** [comment]
As it is currently unused, we can change that.

How about change to usage to `-D$(vopt_bool XXX)`?

**Comment by Gottox** [comment]
or even `-Doption=$(vopt_bool XXX)`

**Comment by maxice8** [comment]
> -D$(vopt_bool XXX)

i'd take this one
 
`-D$(vopt_bool wayland wayland)` | srcpkgs/enlightenment/template

i'd go as far as change it so if <property> is not given it will use <option>

`-D$(vopt_bool wayland)` == `-D$(vopt_bool wayland wayland)`

**Pull request merged**
