### PR TITLE
New package: gdb-python

### PR DESCRIPTION
**Pull request by pullmoll**
QtCreator does not work with the non-python enabled gdb and depending on an option is not possible.
+ Remove option python from gdb and instead create a distinct package
+ Later make qtcreator depend on the new gdb-python package

### CODE REVIEW

**Comment by xtraeme** [comment]
This is a mess... I'll enable the python option by default then.

**Comment by pullmoll** [comment]
Sorry to be a PITA :(

**Comment by xtraeme** [comment]
No problem :-)

**Comment by pullmoll** [comment]
You said you didn't want what you just did, thus I tried the approach on a different path. Glad you changed your mind ;-)

**Pull request closed without merging**
