### PR TITLE
redis: update to 4.0.7

### PR DESCRIPTION
**Pull request by concatime**

### CODE REVIEW

**Comment by cr6git** [comment]
One commit is enough for that. Why two?

**Comment by concatime** [comment]
In my first commit, I forgot to change the homepage to https. I love details, sorry :)

**Comment by concatime** [comment]
And I have no power to stop a Travis Build.

**Comment by cr6git** [comment]
Just use `git commit --amend`

**Comment by concatime** [comment]
Maybe we should make the build less verbose?
> The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).
The job has been terminated
```
arm-linux-musleabihf-gcc --sysroot=/usr/arm-linux-musleabihf   -g -O2 -pipe -march=armv6 -mfpu=vfp -mfloat-abi=hard -I/usr/arm-linux-musleabihf/usr/include -O2  -g   -O2 -pipe -march=armv6 -mfpu=vfp -mfloat-abi=hard   -I/usr/arm-linux-musleabihf/usr/include -DIN_GCC    -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition  -isystem ./include   -fPIC -fno-inline -g -DIN_LIBGCC2 -fbuilding-libgcc -fno-stack-protector   -fPIC -fno-inline -I. -I. -I../.././gcc -I/builddir/gcc-7.2.0/libgcc -I/builddir/gcc-7.2.0/libgcc/. -I/builddir/gcc-7.2.0/libgcc/../gcc -I/builddir/gcc-7.2.0/libgcc/../include  -DHAVE_CC_TLS  -o _satfractQQTQ_s.o -MT _satfractQQTQ_s.o -MD -MP -MF _satfractQQTQ_s.dep -DSHARED -DL_satfract -DFROM_QQ -DTO_TQ -c /builddir/gcc-7.2.0/libgcc/fixed-bit.c
arm-linux-musleabihf-gcc --sysroot=/usr/arm-linux-musleabihf   -g -O2 -pipe -march=armv6 -mfpu=vfp -mfloat-abi=hard -I/usr/arm-linux-musleabihf/usr/include -O2  -g   -O2 -pipe -march=armv6 -mfpu=vfp -mfloat-abi=hard   -I/usr/arm-linux-musleabihf/usr/include -DIN_GCC    -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition  -isystem ./include   -fPIC -fno-inline -g -DIN_LIBGCC2 -fbuilding-libgcc -fno-stack-protector   -fPIC -fno-inline -I. -I. -I../.././gcc -I/builddir/gcc-7.2.0/libgcc -I/builddir/gcc-7.2.0/libgcc/. -I/builddir/gcc-7.2.0/libgcc/../gcc -I/builddir/gcc-7.2.0/libgcc/../include  -DHAVE_CC_TLS  -o _satfractQQHA_s.o -MT _satfractQQHA_s.o -MD -MP -MF _satfractQQHA_s.dep -DSHARED -DL_satfract -DFROM_QQ -DTO_HA -c /builddir/gcc-7.2.0/libgcc/fixed-bit.c
```
The lines at the end are not exactly the same, so the hypothesis about infinite exceptions is false.

**Pull request closed without merging**
