### PR TITLE
php: update to 7.2.6.

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by Gottox** [comment]
> We can’t connect to the server at www.secure.php.net.

**Comment by Gottox** [comment]
And why change it anyway?

**Comment by Johnnynator** [comment]
@Gottox you need to use https to connect to www.secure.php.net. maxice probably changed the URL so the homepage is using https and not http.

**Comment by Gottox** [comment]
There is no `www.secure.php.net`.

There's `secure.php.net`. But I would prefer `https://php.net` as it works too and is more future proof in case they fix their TLS Setup.

**Comment by Johnnynator** [comment]
Oh yeah my fault. I agree, just `https://php.net` is probably better.

**Comment by maxice8** [comment]
On Mon, May 28, 2018 at 01:31:28AM -0700, John Zimmermann wrote:
> Oh yeah my fault. I agree, just `https://php.net` is probably better.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/voidlinux/void-packages/pull/14732#issuecomment-392458803

fixed

**Pull request closed without merging**
