### PR TITLE
New package: xjadeo

### PR DESCRIPTION
**Pull request by cr6git**

### CODE REVIEW

**Comment by maxice8** [comment]
Musl is stricter with stuff, O_RDNONLY is missing because there isn't an include to fcntl.h

```
--- src/xjadeo/mqueue.c
+++ src/xjadeo/mqueue.c
@@ -23,6 +23,7 @@
 
 #include <sys/types.h>
 #include <sys/stat.h>
+#include <sys/fcntl.h>
 #include <unistd.h>
 #include <stdarg.h>
 ```

Should fix

**Comment by cr6git** [comment]
You are fast! ok I will try your fix...

**Comment by Johnnynator** [comment]
@maxice8 the correct path would be fcntl.h and not sys/fcntl.h.

**Comment by cr6git** [comment]
Oups...

**Pull request closed without merging**
