### PR TITLE
Quotes not needed.

### PR DESCRIPTION
**Pull request by The-Fred**

### CODE REVIEW

**Comment by Vaelatern** [comment]
Eh, but not a bug.

**Comment by Vaelatern** [comment]
You made several mistakes with these contributions.
1) It's not something we care about
2) It isn't substantial in any way
3) None of your commit messages were well enough formed for inclusion.
4) Would have just been a commit to confuse the package history.
5) Again, we just don't care. We don't even mention it in package reviews.

**Comment by The-Fred** [comment]
I think any contribution large or small should be welcomed. Having all existing templates conform may not seem substantial but for someone writing new template(s) it is quite useful. For example if I look at another template I take that as an example for the one I'm writing. Having all templates be as close to some consistency as is possible is good not bad.

**Comment by Duncaen** [comment]
We only apply style fixes if it touches the template for something else, e.g. an update.
The repository is already really large and such changes just add to it, they don't improve anything.
Those quotes are really irrelevant, we had a list way more important fixes in https://github.com/voidlinux/void-packages/issues/2422 but even there we came to the conclusion that its not worth it without real changes.

**Comment by The-Fred** [comment]
@Duncaen this helps to understand Void philosophy.  Good to read that there's flexibility.

**Pull request closed without merging**
