### PR TITLE
Sigrok

### PR DESCRIPTION
**Pull request by lemmi**
http://sigrok.org/wiki/Main_Page

### CODE REVIEW

**Comment by pienjo** [comment]
pulseview and sigrok-cli list a runtime dependency for sigrok-firmware-fx2lafw, but is this really appropriate? This dependency is required for a specific group of logic analyzers, but is not needed for other hardware supported by pulseview (or sigrok-cli)

**Comment by pienjo** [comment]
Libsigrok comes with a useful set of default udev-rules (in contrib/z60_libsigrok.rules), but these don't get installed by default. I would suggest installing this file somewhere along with a gentle reminder.

**Comment by pienjo** [comment]
pulseview comes with a set of icons. For some reason these don't get installed (which makes setting trigger modes rather tricky) Sorry to be a nuisance :/

**Comment by lemmi** [comment]
Hey thanks for looking over that. I'm having another go at the packages this week, once i caught up on some other things.
I know about the udev rules, but we (void) don't use the plugdev group anywhere and I haven't figured out the right approach to that. As for the firmwares: it's not easy enough to mark optional dependencies, which is why I prefer a working environment with a few more packages.

**Pull request merged**
