### PR TITLE
diffutils: bumped revision to force recompile and reinstall.

### PR DESCRIPTION
**Pull request by lonwillett**
@xtraeme 

The version of diffutils for aarch64-musl in the repositories
segfaults for context diffs (-c, -u, and perhaps other things as
well). At least this is what I observed on my machine. But a rebuild
seems to fix the problem, so I haven't investigated further. But it
does seem that the revision should be bumped, to flush the bad version
from the repos and any systems that have it installed.

### CODE REVIEW

**Comment by Vaelatern** [comment]
Does it fix it for cross builds? Really?

**Comment by Vaelatern** [comment]
I don't have aarch64-musl gear yet, so I can't test.

**Comment by lonwillett** [comment]
Oops! I forgot that the build system uses cross-compiling, while I had rebuilt this natively for my testing.

Just rectified this situation, and discovered that this change will *not* fix the issue. The real issue is that cross-compiling generates a bad version for aarch64-musl. So closing the PR, and changing it to an outstanding issue.

**Comment by chneukirchen** [comment]
So is this package now broken or not?

**Comment by chneukirchen** [comment]
Ah yes, #7539. Ok.

**Pull request closed without merging**
