### PR TITLE
gthumb: add INSTALL.msg file

### PR DESCRIPTION
**Pull request by felix**

### CODE REVIEW

**Comment by Vaelatern** [comment]
This should come with a revision bump to `gthumb`.
Why do you not recommend installing `dcraw` as a `gthumb` dependency?

**Comment by felix** [comment]
gthumb does not require dcraw and if the user does not process RAW files then it is an extraneous dependency. I have no idea what Void policy on this is though.

**Comment by felix** [comment]
@Vaelatern do you want it as a required dep?

**Comment by felix** [comment]
@Vaelatern ping

**Comment by ebfe** [comment]
@felix there was still a merge conflict. Rebased locally and applied here e2200c706c91c5ff0db397a21ef52921dc7e8bf5..

**Pull request closed without merging**
