### PR TITLE
New package: hunspell-da_DK-2.3_1

### PR DESCRIPTION
**Pull request by unixsheikh**

### CODE REVIEW

**Comment by cr6git** [comment]
Your template is not properly formatted.
Read [STYLE.md](https://github.com/maxice8/void-packages/blob/0949fe18d00db245b4f5641afbb8d71a53166cfa/STYLE.md) by @maxice8

**Comment by maxice8** [comment]
note: STYLE isn't official (i'm trying to get it to be) and can change at any moment until it becomes official, at that point all revisions will be marked under `REVISIONS`

**Comment by cr6git** [comment]
@maxice8 I know, and I would be happy to see this become official. Your work a good source of inspiration.

**Comment by Gottox** [comment]
Get it in non the less :)

**Comment by unixsheikh** [comment]
This is a copy paste from a template already in Void. Also if this is the case, then there is a LOT of packages with templates that isn't properly formattet.

**Comment by Duncaen** [comment]
@unixsheikh It was merged, I don't see what the problem is.
Can you please tag a release in your repository, the distfile tracks master instead of a tagged release or a specific revision, which is going to break the template at the point you commit something.

**Comment by unixsheikh** [comment]
@Duncaen, thanks! I have just tagged it at version 2.1. Do I need to update the template and make a new PR?

**Comment by Duncaen** [comment]
Yes the distfiles should have `${version}` in the url, but whats the reason that you host this in your git repository instead of using some upstream link?
`hostmakedepends="unzip"` is not necessary.
`license="..."` should be comma separated.

**Comment by unixsheikh** [comment]
I couldn't locate the upstream link for that specific package in any supported format. I looked at some of the other hunspell packages and noticed different sources too.

I haven't had the time to dive into the more complicated setups with xbps-src yet, but I suspect that it's possible to use the upstream main package with all the languages and then build from that.

I also looked at the Debian package which also seems to be put together differently https://packages.debian.org/da/stretch/hunspell-da. So I just decided to volunteer at keeping that package updated on Void.

Regarding the license - should be comma separated, I already had that in, but was told to remove the commas, I cannot remember who said that.

**Pull request closed without merging**
