### PR TITLE
New package: kmymoney-4.8.0

### PR DESCRIPTION
**Pull request by Hoshpak**
This pull request introduces the new package kmymoney requested by me in #4670 . I also added the new package libalkimia which is a necessary dependency for kmymoney and added the libraries provided by both packages to common/shlibs. After testing the build I noticed that the binary packages couldn't be installed because libgwengui-qt4.so.0 couldn't be resolved to package so I moved the entry in common/shlibs to the -qt package the contains the .so file.

### CODE REVIEW

**Comment by Hoshpak** [comment]
pull request updated with a backported patch to fix the previous build failure on i686.

**Comment by pullmoll** [comment]
You could squash the common/shlibs changes into their packages to reduce the number of commits.

**Comment by Hoshpak** [comment]
sure, I just thought that it would be more 	comprehensible if I put them into separate commits. Squashed and pushed.

**Comment by Hoshpak** [comment]
branch rebased on top of current master

**Pull request merged**
