### PR TITLE
New package: urxvtconfig-1.0

### PR DESCRIPTION
**Pull request by cr6git**
I used a custom `do_configure()` because of this problem: 
````
=> urxvtconfig-1.0_1: running do_configure ...
Usage: /usr/lib/qt5/bin/qmake [mode] [options] [files]

=> ERROR: urxvtconfig-1.0_1: failed to run do_configure() at line 17.
````

### CODE REVIEW

**Comment by maxice8** [comment]
can't it be added to configure_args ?

**Comment by cr6git** [comment]
@maxice8 you're right, thanks!! (if you have time, maybe you could look at [#9498](https://github.com/voidlinux/void-packages/pull/9498) too?)

**Comment by newbluemoon** [comment]
`qmake` just didn’t find the .pro file. What also works is to just set

    build_wrksrc="source"

;-)

**Comment by cr6git** [comment]
@newbluemoon yes, I guess this should work too!

**Comment by cr6git** [comment]
That's good! 🎉

**Pull request closed without merging**
