### PR TITLE
New Package: google-chrome-49.0.2623.75

### PR DESCRIPTION
**Pull request by dinoocch**
Package for the Google Chrome web browser.  The templating and install is based extensively on the chrome-pepper-flash package.
This PR continues progress on #3119.

### CODE REVIEW

**Comment by xtraeme** [comment]
I would prefer to set `restricted=yes` and get rid of `INSTALL`.

**Comment by Vaelatern** [comment]
Should we also do that for things like spotify? Having INSTALL and not having `restricted=yes` means people without the whole repository set up on their computer can use it.

**Comment by xtraeme** [comment]
The problem with those packages that use INSTALL scripts is that they are dangerous:

- the file needs to be downloaded, extracted and unpacked into a location
- files need to be removed via REMOVE
- files are not tracked by xbps

With `restricted` those packages will be fully tracked by xbps and will work as expected once built.

**Comment by Vaelatern** [comment]
In which case, how should a user who is not so technically adept get a package like spotify or google chrome? Do we care? Should we have a set of repositories under `current/restricted`, so to get an individual package you need to add that specific repository, but don't need to use the template?

**Comment by the-maldridge** [comment]
Is this PR still alive?

**Comment by Vaelatern** [comment]
@dinoocch has not yet made the changes to remove the `INSTALL` script.

**Comment by Vaelatern** [comment]
In addition, `nopie=yes` must be set.

**Comment by Vaelatern** [comment]
Superseded.

**Pull request closed without merging**
