### PR TITLE
New package: nyx-2.0.4

### PR DESCRIPTION
**Pull request by wpbirney**

### CODE REVIEW

**Comment by cr6git** [comment]
Your template is wrong: 
````
requesting https://files.pythonhosted.org/packages/source/nyx-2.0.4.tar.gz
https://files.pythonhosted.org/packages/source/nyx-2.0.4.tar.gz: Not Found
=> ERROR: nyx-2.0.4_1: failed to fetch nyx-2.0.4.tar.gz.
````

**Comment by newbluemoon** [comment]
The URL in `distfiles` is incomplete. What works is e.g.

    distfiles="$PYPI_SITE/n/${pkgname}/${pkgname}-${version}.tar.gz"

**Comment by wpbirney** [comment]
Fixed the url, odd cause it was working locally for me

**Comment by newbluemoon** [comment]
My guess is you didn’t use `$PYPI_SITE` at first. The sources are cached and unless there’s a version change you wouldn’t notice an error in the URL. Been there ;)

**Pull request closed without merging**
