### PR TITLE
icu: update to 59.1. (soname bump)

### PR DESCRIPTION
**Pull request by ebfe**
nodejs/v8  broken, waiting for a fix

### CODE REVIEW

**Comment by ebfe** [comment]
lots of other packages broken too: http://site.icu-project.org/download/59#TOC-ICU4C-char16_t

**Comment by ebfe** [comment]
Everything seems to build now, had to switch nodejs to use the bundled icu for now (cc @Gottox).

**Comment by Gottox** [comment]
🙄  oh boy. nodejs.

@ebfe can you use a new build_option instead?

**Comment by ebfe** [comment]
If it makes you happy i can add a build_option, but it seems pretty useless to have a build_option you can't enable because the build is broken with it.

**Comment by Gottox** [comment]
@ebfe thanks! :)

**Comment by ebfe** [comment]
@Gottox done

**Comment by ebfe** [comment]
58880f4aa0e4c4f1abe94534d474473dcfbef83f

**Pull request closed without merging**
