### PR TITLE
New package: annie-0.6.4

### PR DESCRIPTION
**Pull request by cr6git**

### CODE REVIEW

**Comment by Vaelatern** [comment]
A go pkg.... noarch?

**Comment by cr6git** [comment]
@Vaelatern well, I was probably misled by the AUR [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=annie)... it's okay, I will change that!

**Comment by cr6git** [comment]
@Vaelatern updated to the latest release.

**Comment by Vaelatern** [comment]
Can you also confirm it actually needs ffmpeg?

**Comment by cr6git** [comment]
https://github.com/iawia002/annie#prerequisites

**Comment by cr6git** [comment]
thanks @Vaelatern

**Pull request merged**
