### PR TITLE
New package: ghostwriter-1.5.0

### PR DESCRIPTION
**Pull request by abenson**

### CODE REVIEW

**Comment by abenson** [comment]
This seems to suffer from the qt5-qmake cross compile problems that other packages have also had.

**Comment by Johnnynator** [comment]
adding the qt5 devel packages also to hostmakepedends for cross compiling normally fixes cross compiling

**Comment by abenson** [comment]
I tried that, but then I started getting other linking issues, specifically with hunspell, and couldn't even build it natively.

**Comment by abenson** [comment]
Okay, I have cross-compiling working now. For some reason Travis is failing before it even gets to build this, any suggestions on that?

**Comment by abenson** [comment]
Ooh, shiny green.

**Pull request merged**
