### PR TITLE
libtool: update to 2.4.6

### PR DESCRIPTION
**Pull request by pullmoll**
I adapted the patches to enable cross compiling to the
new file hierarchy and line numbers:
+ configure and libltdl/configure have just different line numbers
+ libltdl/config/ltmain.m4sh was replaced with build-aux/ltmain.{in,sh}
+ tests/cdemo does no longer exist
+ patched tests/testsuite and tests/sysroot.at instead
+ had to add --force to ./bootstrap

I successfully built for x86_64 and cross built for armv[67]hf e.g.
`alsa-lib` for a test. However, this pr needs to be scrutinized before merge.

+ gmp now needs to run `autoreconf -if` for cross compile case
+ libarchive -"-

I am now running the following tests locally, because travis-ci won't cut it:
- [x] `./xbps-src zap; ./xbps-src binary-bootstrap; ./xbps-src -N pkg base-system`
- [x] `./xbps-src zap -m i686; ./xbps-src -m i686 binary-bootstrap i686; ./xbps-src -m i686 -N pkg base-system`
- [x] `./xbps-src zap; ./xbps-src binary-bootstrap; ./xbps-src -a armv6hf -N pkg base-system`
    Had to restart it once because for unknown reasons in the first pass `ncurses` could not be built (compiler produces no output)?
- [x] `./xbps-src zap; ./xbps-src binary-bootstrap; ./xbps-src -a armv7hf -N pkg base-system`
    Same problem as above in the first stage.
- [x] `./xbps-src zap; ./xbps-src binary-bootstrap; ./xbps-src -N pkg xorg`
- [x] `./xbps-src zap -m i686; ./xbps-src -m i686 binary-bootstrap i686; ./xbps-src -m i686 -N pkg xorg`
- [x] `./xbps-src zap; ./xbps-src binary-bootstrap; ./xbps-src -a armv6hf -N pkg xorg`

    `xorg-fonts`, `xorg-server` and `xorg-apps` built fine. Not all input and video drivers can be cross compiled. Perhaps we could create `xorg-input-drivers-cross` and `xorg-video-drivers-cross` which exclude them and have a `xorg-cross` which builds everything possible to cross compile. The `xf86-video-fbturbo` is arm* only, though it should work with x86 just as xf86-video-fbdev AFAIK.
- [x] `./xbps-src zap; ./xbps-src binary-bootstrap; ./xbps-src -a armv7hf -N pkg xorg`
- [x] `./xbps-src zap -m musl; ./xbps-src -m musl binary-bootstrap x86_64-musl; ./xbps-src -m musl -N pkg base-system`
- [x] `./xbps-src zap -m musl; ./xbps-src -m musl binary-bootstrap x86_64-musl; ./xbps-src -m musl -a armv7hf-musl -N pkg base-system`

### CODE REVIEW

**Comment by pullmoll** [comment]
I broke it between the tests and creating the pr. Investigating.

**Comment by pullmoll** [comment]
I think the failing second build of libtool is because of the missing `./xbps-src clean` between the first (cross) and second (native) builds. Note that the libtool.a which is to be installed in the second build isn't actually compiled, which gives the errors when trying to strip the x86_64 static library which is actually armv[67]l.

**Comment by pullmoll** [comment]
I am now running the following tests locally, because travis-ci won't cut it:
- [ ] `./xbps-src zap; ./xbps-src binary-bootstrap; ./xbps-src -N pkg base-system`
- [ ] `./xbps-src zap -m i686; ./xbps-src -m i686 binary-bootstrap i686; ./xbps-src -m i686 -N pkg base-system`
- [ ] `./xbps-src zap; ./xbps-src binary-bootstrap; ./xbps-src -a armv6hf -N pkg base-system`
- [ ] `./xbps-src zap; ./xbps-src binary-bootstrap; ./xbps-src -a armv7hf -N pkg base-system`
- [ ] `./xbps-src zap; ./xbps-src binary-bootstrap; ./xbps-src -N pkg xorg`
- [ ] `./xbps-src zap -m i686; ./xbps-src -m i686 binary-bootstrap i686; ./xbps-src -m i686 -N pkg xorg`
- [ ] `./xbps-src zap; ./xbps-src binary-bootstrap; ./xbps-src -a armv6hf -N pkg xorg`
- [ ] `./xbps-src zap; ./xbps-src binary-bootstrap; ./xbps-src -a armv7hf -N pkg xorg`

**Comment by pullmoll** [comment]
I'm obviously missing something, because the generated cross (armv[67]l) compilers can't generate code when trying to build the base-system.

I'm not yet sure where to look. Best thing I can think of is verifying again what the patches of 2.4.2_13 did and if I really touched all affected files or their replacements.

**Comment by pullmoll** [comment]
I'm away from my machines now (beer :) and will update the remaining test results later.
I do however think the tests are already sufficient to tell the patch set is working as expected.

We may see some more packages using libtool which now require running `aclocal` or even `autoreconf`, just as it occured for `gmp` and `libarchive`.

**Comment by xtraeme** [comment]
Looks reasonable, and seems to be good enough.

Thanks!

**Pull request merged**
