### PR TITLE
Add python-docopt package

### PR DESCRIPTION
**Pull request by radare**

### CODE REVIEW

**Comment by radare** [comment]
Ready to review + merge. This is needed for the upcoming docker-compose tool.

**Comment by Duncaen** [comment]
You need to add a subpackage for the python3.4 version, see `python-Jinja2` as example.

**Comment by radare** [comment]
Ouch. It bothers me to package python stuff for several reasons, which maybe we can find better solutions than doing it like now we do.

First: packaging packages from other package systems is simply wrong. we will end up repackaging everything or we will miss packages and the user will end up looking at the original repo instead of the distro one. which imho makes sense.

I understand, that having distro packages for those modules makes sense to provide a consistent environment, but we are just dupping the work of all package systems.

xbps should be able to install system-wide node, python, perl, ruby, ... modules without having to type a single line.

All the pkginfo can be extracted from their original pkgmanagers or the website of every project, so all this stuff can be done by a script.

Also, why `python3.4` prefix? what happens with python 3.5 or future 3.6? we will have to rename and re-edit ALL the packages again? imho the only meaningful prefix should be `python3` because its just different from python2.

The same script should be able to detect newer versions of each module and create new packages automatically.

Can I push all those `python3.4-XXX_package()` in a separate commit or do i have to create a new PR with the commit-per-pkg thing again?

**Comment by radare** [comment]
Fixed

**Comment by radare** [comment]
@Duncaen ok to merge now?

**Comment by Duncaen** [comment]
Looks good, can you squash and rebase again, to only have the one `New package: python-docopt-0.6.2` commit?

**Comment by radare** [comment]
done

**Comment by Duncaen** [comment]
@radare `python3.4-docopt` should depend on `python3.4`

**Comment by radare** [comment]
Should be fine now :P

**Comment by radare** [comment]
anyway, any comments on my thoughts about automating this dummy work?

**Comment by xtraeme** [comment]
I agree that duplicating python/perl/XXX packages for xbps is redundant and completely stupid.

**Comment by radare** [comment]
But which is the solution? Add some pip/npm/.. Hooks to automatically register those pkgs into xbps

**Comment by radare** [comment]
soo.. is this going to be merged at anytime?

**Comment by Duncaen** [comment]
Maybe you can copy your input/ideas into another issue and we can try to find a solution there.

**Comment by radare** [comment]
Sure!

**Pull request merged**
