### PR TITLE
chromium: update to 61.0.3163.91.

### PR DESCRIPTION
**Pull request by ebfe**

### CODE REVIEW

**Comment by ebfe** [comment]
musl still wonky, maybe something to do with the stack size estimator code... also something wrong with the shutdown_signal_handler thread on glibc .

**Comment by ebfe** [comment]
> also something wrong with the shutdown_signal_handler thread on glibc .

also happens with google-chrome so i'd assume that one isn't our fault.

**Comment by Duncaen** [comment]
> also happens with google-chrome so i'd assume that one isn't our fault.

Yes this happens for some time already

**Comment by ebfe** [comment]
Updated to chromium 60.0.3112.90, on musl tabs still crash after a while.

**Comment by ebfe** [comment]
glibc build broken by the glibc-2.26 update.

**Comment by chneukirchen** [comment]
Does that help? https://github.com/OSSystems/meta-browser/blob/master/recipes-browser/chromium/files/0002-replace-struct-ucontext-with-ucontext_t.patch

**Comment by ebfe** [comment]
update to 61.0.3163.91, glibc builds no energy left for musl for now.

**Comment by ncopa** [comment]
this is the patch you need for musl: https://github.com/lluixhi/musl-extras/issues/10#issuecomment-328272349

**Comment by ebfe** [comment]
@ncopa thanks. musl builds now too, otherwise untested.

**Comment by ebfe** [comment]
81a77d6f5f7c3256f65fa29e47087fcbf05e5f69

**Pull request closed without merging**
