### PR TITLE
Preparatory work for monodevelop

### PR DESCRIPTION
**Pull request by t0b1nux**
All courtesy for mono update goes to @Hoshpak (cf. https://github.com/voidlinux/void-packages/pull/5070).
This is just a minor update (because #5070 was closed and not merged). Most explanations for the first commit are given at #5070.
All of this is just some prep work to add monodevelop.

### CODE REVIEW

**Comment by t0b1nux** [comment]
After a thought, I checkout and it seems to be not a single program relying on gtk-sharp-2.99 (contained in the package gtk-sharp).
I also added a fsharp recipe. I have some mixed feeling about this one (it need to have internet access during the build to fetch some NuGet packages, so it might breaks without reason) but it is a requirement for monodevelop. I yet have to investigate if it is possible, feasible and interesting to integrate the NuGet packages locally to have a reproducible build proccess.

**Comment by t0b1nux** [comment]
Getting monodevelop to compile on voidlinux is not going to be easy as it requires gnome-sharp, which in turn requires libgnomeui (otherwise it only compile gconf-sharp), which requires itself libbonoboui, etc...
I do not have the time currently to make all theses packages.
So I thinkg upgrading at least mono is still wise, even just from the security point of view. As for gtk-sharp & fsharp, I don't know what would be best.

**Comment by t0b1nux** [comment]
All right, so what I've done so far: update mono (of course), create a new package called gtk-sharp2, add fsharp (needed for monodevelop as stated before) and update gtk-sharp to 3.20.4. I should say that this isn't the version from the mono repository but a fork that is up to date and widely used.

I know the convention used by most gtk packages is : 
- 2.x release: no suffix;
- 3.x release: append a '3' to the package name.
In this case however, gtk-sharp was already C# bindings for gtk3+ (despite being published as 2.99.3 by mono developers). So I tought it was logical to update it to 3.20.4 and create another package called gtk-sharp2 which would contain the release 2.12.42 (that is, the one with gtk+-2.x bindings).

**Comment by t0b1nux** [comment]
All right, so I guess it's time to explain the situation:
to get the current monodevelop version working would require making a gnome-sharp package, which will in turn have other dependencies. Quite frankly, I'm not ready to do this work and further maintain theses required (yet outdated) packages.
However, the development branch of monodevelop has dropped (mono/monodevelop#1661 for reference and the rationale) its requirement for gnome-sharp. As such, I think it's better to wait a bit until the 6.2 branch is out with theses patches.

**Comment by Gottox** [comment]
Sorry for the long delay, void devs were busy moving the server. :D

Okay, let's wait. Does this affect this preparation PR in any way? Can we still merge?

**Comment by t0b1nux** [comment]
No problem for the delay, I do not expect volunteers to be available 24/7, even more if they have way more important things going on.
As for theses packages, they should be fine (except the internet requirement during compilation explained above, I don't know voidlinux policy about it). However, I can not get monodevelop to work until they release 6.2.
This work can be merged if it meet your quality requirements.

**Comment by asergi** [comment]
In the meantime, I already pushed the mono update (https://github.com/voidlinux/void-packages/commit/653309c1880069bf17b8e679c8986112f203bc4c), so that this PR can be merged at a later time.

**Comment by Gottox** [comment]
please resolve the merge conflicts and rebase :D

**Comment by Vtec234** [comment]
Any progress on this? It would be nice to have for Unity3D development.

**Comment by t0b1nux** [comment]
Sorry, I can't handle this for the moment (this week), I'll try to compile and package monodevelop next week when I will have a bit more time.

**Comment by t0b1nux** [comment]
Sorry, but if someone could handle this (@Vtec234 ?), it would be great ! (I tried to compile it but the latest version from git is somewhat incompatible with the Microsoft.Builder package of mono in the distribution). I'm not using monodevelop anymore (I just needed it for a project and we migrated to another language for easier cross-platform simplicity), so this PR is now orphan. Shall I close it ?

**Comment by Vtec234** [comment]
I forked your branch, so you can close this if you want. Hopefully I can get it to work.

**Comment by t0b1nux** [comment]
Ok, thanks and sorry for the disconvenience.

**Pull request closed without merging**
