### PR TITLE
ulatencyd: unbreak + build pie

### PR DESCRIPTION
**Pull request by thypon**

### CODE REVIEW

**Comment by pullmoll** [comment]
It looks like `arm*-musl` misdetects `HAVE_ERROR_H` or similar. There is no `<error.h>` in  `*-musl`, and for `x86_64-musl` detecting it seems to be working, which is odd IMO.

I'm not too good at fixing CMake things, so I can't help too much in this case.

**Comment by thypon** [comment]
Thank you. The only thing that includes it unconditionally is `src/ulatencyd.c`.

Do you know what to include instead?

**Comment by pullmoll** [comment]
I don't think you can include anything, because e.g. `error_at_line(3)` is not available.
It's rather the code using `<error.h>` defined functions has to be disabled.

**Comment by thypon** [comment]
Wasn't error.h related. At least non on ulatencyd.

**Comment by thypon** [comment]
Wasn't error.h related. At least non on ulatencyd.

**Pull request closed without merging**
