### PR TITLE
Gnome 3.18

### PR DESCRIPTION
**Pull request by Gottox**
Some cleanups needs to be done, but anyway it's ready for review.

### CODE REVIEW

**Comment by Gottox** [comment]
I'm using Gnome-3.18 for two days now. Works fine so far.

Also I checked the build for i686, works there too.

**Comment by xtraeme** [comment]
:+1:

**Comment by Gottox** [comment]
I found a minor issue with gnome-shell. Please wait till I sort this out.

**Comment by pullmoll** [comment]
gobject-introspection doesn't build anymore with musl libc.

I checked and also the previous version 1.44.0 won't build anymore, so the origin of the problem is elsewhere. I am clueless where to look, though.

**Pull request merged**
