### PR TITLE
New package: cdetect

### PR DESCRIPTION
**Pull request by cr6git**

### CODE REVIEW

**Comment by Vaelatern** [comment]
please use xbump so the commit message is properly formatted.

**Comment by cr6git** [comment]
Oopss... yes, and you already warned me about that... 
ok, I've learned my lesson! 😉

**Comment by cr6git** [comment]
@Vaelatern look at that: 
````
$ cdetect /usr/bin/leafpad
GCC 4.9.3
````
4.9.3 ? it's really old.

**Comment by cr6git** [comment]
I just recompiled `leafpad` with GCC 7.2.0, but now `cdetect` claims: 
````
$ cdetect /usr/bin/leafpad
GCC 6.3.0
````
How is that possible ??

**Pull request merged**
