### PR TITLE
Add debug-me

### PR DESCRIPTION
**Pull request by SevereOverfl0w**
I likely need feedback on the haskell-stack changes.

### CODE REVIEW

**Comment by SevereOverfl0w** [comment]
Going to push upstream to get a fix for musl. If I added a temporary musl exclusion, would this be added? Or should I wait until upstream has updated & then bump this package?

**Comment by SevereOverfl0w** [comment]
I've used sed to bump the dependency version. This fixes the build for musl.

**Comment by SevereOverfl0w** [comment]
Version bumped, which includes the latest version of posix-pty, fixing the bug with building on musl.

**Comment by ebfe** [comment]
Assigning @chneukirchen for the `haskell-stack` changes

**Comment by chneukirchen** [comment]
I approve the haskell-stack change, but the use of do_fetch is still not acceptable. Please wait for a release, or download a tarball.

**Comment by SevereOverfl0w** [comment]
@chneukirchen Releases are done via git & tags. This is the closest thing to a release process that is available for this project. Unless I've missed the tarball download?

**Comment by SevereOverfl0w** [comment]
@freshprince Documented the stackage changes in Manual.md.

**Comment by SevereOverfl0w** [comment]
@chneukirchen I found the tarball downloads. Updated the build.

**Comment by freshprince** [comment]
Let me help you clean up your pull request.

Right now you have the documentation changes in the same commit that adds the debug-me package.  What you want is to move the documentation to the commit that changes the behaviour of haskell-stack.

First let's take a look:
```
$ git show-branch --sha1-name --topics master adddebugme
! [master] gnome-maps: update to 3.24.3.
 * [adddebugme] New package: debug-me-1.20170509
--
 * [b9941d6909] New package: debug-me-1.20170509
 * [3a0b6b7cae] haskell-stack: Add support for stack.yaml in source
+* [b72d6b7d1e] youtube-dl: update to 2017.05.18.
```

So `b9941d6909` is the commit that adds the package and `3a0b6b7cae` is the commit we want to move the documentation changes into.

What you want to do now is
```
$ git rebase -i master
```
This should open an editor with your two commits and some comments.  What you want to do is to edit the commit `3a0b6b7cae` so change `pick` in that line to `edit`.  Save your changes and close the editor.  Git will tell you that you can now amend the commit you want to edit.

Now you want to get the documentation changes from commit `b9941d6909` into your stage and your working directory.  You can do that with
```
$ git checkout b9941d6909 Manual.md
$ git diff --staged
```
You should now see the changes in `Manual.md`.  Since those changes are already in stage you don't need to do `git add`.

Now we want to amend this change.
```
$ git commit --amend
```
You can leave the commit message as it is.

Now we're done editing that commit and can continue with the rebase
```
$ git rebase --continue
Successfully rebased and updated refs/heads/adddebugme.
```

Now you have the documentation changes in the right commit and you can update this pull request with
```
$ git push -f
```

Let me know if you have any problems or questions.

**Comment by SevereOverfl0w** [comment]
@freshprince Oops, good catch. Thank you for the detailed instructions on fixing it. I've pushed the rewritten history.

**Comment by the-maldridge** [comment]
@ebfe @chneukirchen are you satisfied with this PR?  My only complaint is that this one is nocross, shouldn't that be automagically set because this depends on a package that isn't available on the cross target?

**Comment by SevereOverfl0w** [comment]
I believe I tried removing nocross, and it caused a build failure. I can
double check this evening.

**Comment by the-maldridge** [comment]
You are correct, I had my languages confused for a minute.  `nocross` is appropriate for haskell packages at this time.

**Pull request closed without merging**
