### PR TITLE
New package: rmlint-2.2.0

### PR DESCRIPTION
**Pull request by thypon**
@pullmoll could you help with musl-fts. I cannot get to work.

### CODE REVIEW

**Comment by pullmoll** [comment]
Hmm...
```
case "$XBPS_TARGET_MACHINE" in
	*-musl) makedepends+="musl-fts"
		LIBS="-lfts"
		;;
esac
```
is what I would try. If `LIBS` isn't recognized, perhaps `LDFLAGS="-L${XBPS_CROSS_BASE}/usr/lib -lfts"`

**Comment by thypon** [comment]
I alredy tried LDFLAGS path, unfortunatly, like for ulatencyd i was unable to link against `musl-fts`.

**Comment by thypon** [comment]
I alredy tried LDFLAGS. Too bad i can't get to work musl-fts right now. Maybe i could try with the usual patch in tree.

**Comment by pullmoll** [comment]
See #2421

**Pull request closed without merging**
