### PR TITLE
perf: fix script path

### LINKED ISSUE #5413: perf: unable to run perf script because of wrong path
Steps to reproduce:
```
# perf script rwtop
 Couldn't find script rwtop
[..snip help text..]
```
An [`strace` log](https://gist.github.com/835a0da7b99ba61bd3fdb59f6c6c7f04) shows that `perf` tries to access script directory using wrong path:
```
4878  open("/libexec/perf-core/scripts", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
4878  open("/libexec/perf-core/scripts", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
4878  write(2, " Couldn't find script rwtop\n\n Se"..., 72) = 72
```

### PR DESCRIPTION
**Pull request by ackalker**
This fixes #5413

If the changes are okay after review, I will gladly squash and rebase them to master, remove WIP and bump revision to 5.

### CODE REVIEW

**Comment by ackalker** [comment]
To be clear, `perfexecdir` in `make` command has no effect, because the variable isn't exported to submake. To force change it, I could export `perfexecdir` in the environment, but Void supports `/usr/libexec` directory anyway, so why bother.

**Comment by chneukirchen** [comment]
Was already on it myself, sorry.

**Comment by ackalker** [comment]
@chneukirchen Thanks anyway :-) But shouldn't we disable build on `*-musl` for now (`strerror_r` function signature mismatch, a glibc GNU-ism)?

**Comment by chneukirchen** [comment]
Yeah, this never worked... :>

**Comment by chneukirchen** [comment]
strerror_r is fixed in linux head it seems.

**Comment by chneukirchen** [comment]
Now fixed completely.

**Comment by ackalker** [comment]
Ah, thanks for the info.

**Pull request closed without merging**
