### PR TITLE
Multiple themes added

### PR DESCRIPTION
**Pull request by jambonmcyeah**

### CODE REVIEW

**Comment by jambonmcyeah** [comment]
The build is ok on my machine
The log exceeded the 4MB limit on travis

**Comment by cr6git** [comment]
You should consider @xtraeme comments in [#3809](https://github.com/voidlinux/void-packages/pull/3809#issuecomment-215657874), [#4002](https://github.com/voidlinux/void-packages/pull/4002#issuecomment-208007100) and [#4003](https://github.com/voidlinux/void-packages/pull/4003#issuecomment-208007084).

**Comment by jambonmcyeah** [comment]
Pretty much every linux distro has themes in their repos. Not having themes in the repo just make them a pain to install.

**Comment by cr6git** [comment]
There are many themes I'd like to add myself, but these comments convinced me not to. 
You can still ask the Void devs in IRC, why not ? 😉

**Pull request closed without merging**
