### PR TITLE
New package: wiggle-1.0

### PR DESCRIPTION
**Pull request by okapia**
wiggle is like patch but will apply patches that patch would reject.

### CODE REVIEW

**Comment by chneukirchen** [comment]
Please disable running of the test suite, it will not work for cross-builds. (make_build_args="... wiggle" should do.)

Also the STRIP= is superfluous, we strip ourselves anyway.

**Comment by okapia** [comment]
Thanks. I had wondered what was wrong with the ARM builds.

Assigning something to STRIP is necessary because xbps-src provides STRIP=yes, overriding the value in wiggle's Makefile which was passed on to the install command. "yes" is obviously not a valid option to install. I've changed it from -s to the empty string.

**Comment by chneukirchen** [comment]
Good, please squash this together, then we can merge.

**Comment by okapia** [comment]
Now squashed.

**Pull request merged**
