### PR TITLE
New packages : Fonts released by Swathanthra Malayalam Computing

### PR DESCRIPTION
**Pull request by aashiks**
A set of free and open source fonts released by https://smc.org.in, a developer collective from India

### CODE REVIEW

**Comment by cr6git** [comment]
Hi, you understand the problem here, @aashiks ? 

srcpkgs/font-dyuthi-ttf/template:3: **revision** does not appear immediately after version

pkgname=font-dyuthi-ttf
**revision**=1
version=2.0.0+20161216

srcpkgs/font-karumbi-ttf/template:3: **revision** does not appear immediately after version

pkgname=font-karumbi-ttf
**revision**=1
version=1.0.0+20161217

srcpkgs/font-keraleeyam-ttf/template:3: **revision** does not appear immediately after version

pkgname=font-keraleeyam-ttf
**revision**=1
version=2.0.0+20161217

srcpkgs/font-rachana-ttf/template:3: **revision** does not appear immediately after version

pkgname=font-rachana-ttf
**revision**=1
version=6.1.1

Travis complains because "revision" should appear on the line **below** "version", not above!

**Comment by aashiks** [comment]
Will check and fix this ! Apologies ! Thanks for pointing this out. I think I skipped running the linter.

**Comment by aashiks** [comment]
@cr6git any idea what happens now ? I mean anything more to get the pull requests merged ? I have a couple more packages to go.

**Comment by cr6git** [comment]
@aashiks Me ? How can I say ? Let the devs decide what is most appropriate... :wink:

**Comment by liwakura** [comment]
@aashiks Commit history should be kept clean, could you squash those commits together and do an force push? So it will appear as a single commit.

If you need to update an PR in the future, do an `git commit --amend` to modify your previous commit instead of creating a new one. and then `git push -f` for updating the PR.

**Comment by aashiks** [comment]
Alright. I have no time to go back and squash commits, I will close the request and open another pullrequest, will take care next time.

**Pull request closed without merging**
