### PR TITLE
New package: ternimal

### PR DESCRIPTION
**Pull request by cr6git**

### CODE REVIEW

**Comment by Vaelatern** [comment]
I do not like the `INSTALL.msg`, it takes up a lot of space and seems to duplicate external documentation.

**Comment by cr6git** [comment]
Sorry, I just noticed your message. OK, I will remove this `INSTALL.msg`.

**Comment by Vaelatern** [comment]
For future PRs, can you please use `xbump` to make new commits? It formats commit messages better (in this case, by appending the version).

I don't know how to cross build rust targets. I'm sure somebody knows.

**Comment by cr6git** [comment]
Yeah I should study further the `xtools`.

**Comment by cr6git** [comment]
@Vaelatern To cross build rust targets I guess we need [rustup](https://blog.rust-lang.org/2016/05/13/rustup.html).

**Comment by chneukirchen** [comment]
cross-rust is not supported yet, just mark things nocross=yes for now.

**Comment by chneukirchen** [comment]
Please use `0.0.YYYYMMDD` for untagged versions.

That said, the utility of this package is questionable to me, and it's trivial to build yourself...

**Comment by cr6git** [comment]
I thought it was funny, but if you don't want this package I can drop it. :wink:

**Pull request closed without merging**
