### PR TITLE
icu, libvpx: update. (soname bump)

### PR DESCRIPTION
**Pull request by ebfe**

### CODE REVIEW

**Comment by Vaelatern** [comment]
Is this an example where the staging builds would help prevent breaking the ecosystem, @Gottox?

**Comment by Gottox** [comment]
Yes. I'd like to use this PR for testing staged builds.

**Comment by chneukirchen** [comment]
We could bump libvpx before rebuilding Firefox.

**Comment by ebfe** [comment]
bumped libvpx too, adjusted rebuilds.

**Comment by ebfe** [comment]
Rebased. The libressl bump introduced a few conflicts.

**Comment by ebfe** [comment]
Rebased again. The boost cross build failures seem to be a travis thing and I
can't reproduce them locally. Build tested the following packages on x86_64:
postfix harfbuzz boost xpra znc ffmpeg mpd avidemux qt5 xerces-c toxcore-git
utox dwdiff tracker virtualbox-ose R php firefox openttd mongodb.

@Gottox should I include the webkit2gtk-2.12.0 bump here to save another rebuild?

**Comment by ebfe** [comment]
Rebased, build tested everything except firefox-esr and libreoffice on x86_64.

**Comment by ebfe** [comment]
Rebased. webkit2gtk bumped

**Comment by ebfe** [comment]
Blocking on #4004 for libreoffice rebuild.

**Comment by pullmoll** [comment]
libreoffice -> libetonyek -> liblangtag should be fixed with http://build.voidlinux.eu/changes/24220

**Comment by ebfe** [comment]
> libreoffice -> libetonyek -> liblangtag should be fixed with http://build.voidlinux.eu/changes/24220
Thanks @pullmoll.

**Comment by ebfe** [comment]
Rebased. @xtraeme i think this is good to go.

**Comment by xtraeme** [comment]
@ebfe :+1: 

Thanks! go for it

**Pull request closed without merging**
