### PR TITLE
rakudo-star: updated to 2016.02

### PR DESCRIPTION
**Pull request by xaduha**

### CODE REVIEW

**Comment by chneukirchen** [comment]
Packages with build-style=meta are empty usually, perhaps just drop the build-style for rakudo-star.

Could pandas `--prefix` option help here?

**Comment by xaduha** [comment]
> Could pandas --prefix option help here?

that option is wonky, doesn't work properly.

I'll drop build-style=meta, but other than that it works and I would be glad not to spend any more time on it.

**Comment by chneukirchen** [comment]
After some tweaks, this fails for me with

```
==> Building DBIish
==> Installing DBIish
Failed to copy '/usr/share/perl6/site/.panda-work/1456678380_20/lib/DBDish/Role/Connection.pm6' to '/usr/share/perl6/site/sources/4BB1D5ED9AF9C0A6B34919117A5C823381A9F367': Failed to copy file: no such file or directory
  in any  at /usr/share/perl6/runtime/CORE.setting.moarvm line 1
  in block  at /usr/share/perl6/site/sources/1347B16C1A9219DDFBB4056E85AC710493AEBF8C line 61
  in sub indir at /usr/share/perl6/site/sources/E8FD3F40DA9A18B572C1B94D0BEA6A7B82D20701 line 20
  in method install at /usr/share/perl6/site/sources/1347B16C1A9219DDFBB4056E85AC710493AEBF8C line 42
  in method install at /usr/share/perl6/site/sources/EEEC15709C920EBEABC7BDCBE2C6A72B898D02A9 line 146
  in block  at /usr/share/perl6/site/sources/EEEC15709C920EBEABC7BDCBE2C6A72B898D02A9 line 214
  in method resolve at /usr/share/perl6/site/sources/EEEC15709C920EBEABC7BDCBE2C6A72B898D02A9 line 208
  in sub MAIN at /usr/share/perl6/site/resources/115C3C62D52C2A202169A67CCB7E8D8321201BD0 line 18
  in block <unit> at /usr/share/perl6/site/resources/115C3C62D52C2A202169A67CCB7E8D8321201BD0 line 150

Actually thrown at:
  in any  at gen/moar/m-Metamodel.nqp line 3041
  in block  at /usr/share/perl6/site/sources/1347B16C1A9219DDFBB4056E85AC710493AEBF8C line 61
  in sub indir at /usr/share/perl6/site/sources/E8FD3F40DA9A18B572C1B94D0BEA6A7B82D20701 line 20
  in method install at /usr/share/perl6/site/sources/1347B16C1A9219DDFBB4056E85AC710493AEBF8C line 42
  in method install at /usr/share/perl6/site/sources/EEEC15709C920EBEABC7BDCBE2C6A72B898D02A9 line 146
  in block  at /usr/share/perl6/site/sources/EEEC15709C920EBEABC7BDCBE2C6A72B898D02A9 line 214
  in method resolve at /usr/share/perl6/site/sources/EEEC15709C920EBEABC7BDCBE2C6A72B898D02A9 line 208
  in sub MAIN at /usr/share/perl6/site/resources/115C3C62D52C2A202169A67CCB7E8D8321201BD0 line 18
  in block <unit> at /usr/share/perl6/site/resources/115C3C62D52C2A202169A67CCB7E8D8321201BD0 line 150

```

**Comment by xaduha** [comment]
@chneukirchen what tweaks would that be? I just rebuilt it here without issues. As I said, "prefix" doesn't work properly with panda.

**Comment by chneukirchen** [comment]
I didn't use prefix, I used the commits you had here.

panda lacks depends on git. rakudo-star uses an undefined $f. rakudo needs to depend on libatomic_ops-devel libffi-devel libuv-devel to build.

**Comment by xaduha** [comment]
@chneukirchen I changed some stuff, I don't see any particular issues in the build log https://travis-ci.org/voidlinux/void-packages/jobs/112589697

But if you want to take over I'll be glad to let you be the maintainer.

**Comment by chneukirchen** [comment]
Now I get for a clean build

```
==> Installing Terminal::ANSIColor
Terminal::ANSIColor:ver<*>:auth<>:api<> already installed
...
```

**Comment by chneukirchen** [comment]
Using `panda --force` now, seems to work.

I'm not completely happy with the `rakudo-star` template but I guess it's as good as we can do it right now.

(E.g. reproducible builds or even versioning are not really supported by the ecosystem currently.)

**Pull request closed without merging**
