### PR TITLE
python-Django: update to 1.10

### PR DESCRIPTION
**Pull request by the-maldridge**

### CODE REVIEW

**Comment by the-maldridge** [comment]
Travis fails the build because it spits out too much log data, the build does actually pass.

**Comment by ebfe** [comment]
Why not 1.10?

**Comment by the-maldridge** [comment]
Didn't notice it was out.

**Comment by Duncaen** [comment]
Why do we have this packaged at all?

**Comment by the-maldridge** [comment]
@ebfe updated
@Duncaen its nice to have it packaged so that I'm not juggling a pip package and xbps packages.

**Comment by the-maldridge** [comment]
Once again its worth pointing out that this does actually build successfully, but travis fails the build for excessive log output due to a number of empty directories.

**Pull request closed without merging**
