### PR TITLE
freecad: update to 0.17

### PR DESCRIPTION
**Pull request by Piraty**
- vtk is a mandatory dependency (already merged, see #11993)
 - libmed is a mandatory dependency (supersedes #12572)
 - occt is not mandatory, but recommended by freecad devs (see https://github.com/voidlinux/void-packages/issues/12571#issuecomment-377906827)
 - SMDS patch is not needed anymore
 - freecad's transition to python3 is not complete, maybe in 0.18
 - in order to use qt5, Void needs pyside2 etc. first, which is not officially released yet

I tested this a bit for a few days on a x86_64 glibc system

### CODE REVIEW

**Comment by faulesocke** [comment]
I've looked at it, builds fine. The templates look OK to me, so IMO this can get merged.

When I have time during the weekend, I will look at med again to see whether we can fix compilation with MPI there.

**Comment by yopito** [comment]
Nice work, so huge stuff ... I will give a try ASAP to help. 
* oce: dedicated commit and revbump on oce package in order to "publish" the conflict (with occt).

**Comment by karl-nilsson** [comment]
I successfully built and installed all 3 packages.

One question: why is coin3-doc a build and runtime dependency?

**Comment by Piraty** [comment]
Thanks both of you, I corrected accordingly.

**Comment by yopito** [comment]
about `conflicts`: Uneeded to add it on both sides, only on `occt` is sufficient.

**Pull request closed without merging**
