### PR TITLE
Firefox 60.0

### PR DESCRIPTION
**Pull request by Gottox**
Updates Firefox to the latest release. Build tested on musl, @Duncaen had some issues with sandboxing and sndio while testing.

### CODE REVIEW

**Comment by Gottox** [comment]
nss crossbuild is broken.

**Comment by asergi** [comment]
There is no need to update to nss `3.37`. Firefox 60 requires at least `nss>=3.36.1`. Just update nss to `3.36.1`. Please enforce dependency on `nss>=3.36.1` in firefox template. 

https://github.com/voidlinux/void-packages/blob/master/srcpkgs/firefox/files/mozconfig#L5-L8

You can remove those lines. Upstream dropped the support for building against system cairo: https://bugzilla.mozilla.org/show_bug.cgi?id=1432751.

**Comment by Gottox** [comment]
I experienced similiar issues with 3.36 and 3.36.1

**Comment by Gottox** [comment]
3.36.1 is failing for aarch64 with a similiar error as in 3.37.

armv7 seems to build.

**Comment by Gottox** [comment]
Hmm... I guess something is wrong with `nss/lib/freebl/Makefile` then.

```
495 ifdef USE_64
496     ifdef CC_IS_CLANG
497             HAVE_INT128_SUPPORT = 1
498             DEFINES += -DHAVE_INT128_SUPPORT
499     else ifeq (1,$(CC_IS_GCC))
500         ifneq (,$(filter 4.6 4.7 4.8 4.9,$(word 1,$(GCC_VERSION)).$(word 2,$(GCC_VERSION))))
501             HAVE_INT128_SUPPORT = 1
502             DEFINES += -DHAVE_INT128_SUPPORT
503         endif
504         ifeq (,$(filter 0 1 2 3 4,$(word 1,$(GCC_VERSION))))
505             HAVE_INT128_SUPPORT = 1
506             DEFINES += -DHAVE_INT128_SUPPORT
507         endif
508     endif
509 endif
```
they explicitly disable `HAVE_INT128_SUPPORT` for any gcc > 4.9.x. Is there a reason?

**Comment by newbluemoon** [comment]
Or is it because `$_use64` isn’t used in the template’s cross-build branch?

**Comment by asergi** [comment]
The same goes for `nss<=3.35` on aarch64.
This upstream [commit](https://hg.mozilla.org/projects/nss/rev/1668fafc1db4) exposes the issue to us.

**Comment by asergi** [comment]
@newbluemoon lgtm

**Comment by asergi** [comment]
Fix nss `>=3.36.1` on aarch64: https://gist.github.com/asergi/1048db72e70a4a187bafa17e3e06fde5
Fix nss `3.37` on arm*: https://gist.github.com/asergi/fd42de4a103a638cff5589a2f2c80dd0

**Comment by Gottox** [comment]
Hm. applying the second patch to all platform shouldn't make a difference due to `-Wl,--as-needed`.

**Comment by Gottox** [comment]
@asergi Thanks a lot!

**Comment by Gottox** [comment]
08d5f1fc59f439aab0d2d8a5f46cc69f9f5e1383

**Pull request closed without merging**
