### PR TITLE
libfilezilla: update to 0.10.0.

### PR DESCRIPTION
**Pull request by bra1nwave**

### CODE REVIEW

**Comment by ebfe** [comment]
Breaks filezilla build.

**Comment by cr6git** [comment]
@ebfe `filezilla-3.27.0` has been [released today](https://filezilla-project.org/) and needs `libfilezilla-0.10.0` to build.

**Comment by Gottox** [comment]
put both into the same PR.

**Comment by bra1nwave** [comment]
Done

**Comment by cr6git** [comment]
@bra1nwave `filezilla-3.27.0.1` just came out !

**Pull request closed without merging**
