### PR TITLE
alacritty: bump to 0.1.20180514

### PR DESCRIPTION
**Pull request by kimat**

### CODE REVIEW

**Comment by cr6git** [comment]
[#11390](https://github.com/voidlinux/void-packages/pull/11390) and [#13528](https://github.com/voidlinux/void-packages/pull/13528)

**Comment by cr6git** [comment]
No, no, no, you must have one commit per pull request.

**Comment by kimat** [comment]
ok, can I squash when travis is green or should I do that now ?

**Comment by kimat** [comment]
Failing builds just needs more time to build cf. [this travis run](https://travis-ci.org/kimat/void-packages/jobs/382638592)  with [this edit on .travis.yml](https://github.com/kimat/void-packages/commit/fb38764460a0cb69aae17cf686752d29124fcf32). I doubt we'd want to merge those travis.yml changes though.

Hopefully by next version bump, in 6months ?, compilation goes faster ? Because somehow, this project takes 10 min more to build than [8 months ago](https://travis-ci.org/voidlinux/void-packages/builds/277174411).

**Comment by kimat** [comment]
Seems alacritty is doing LTO now which might also affect the building of dependencies

**Comment by Johnnynator** [comment]
You could have also put that 3 lines into do_build before cargo?

**Comment by kimat** [comment]
@Johnnynator that [works](https://travis-ci.org/kimat/void-packages/builds/382848495)

My other approach to this problem was to have cargo build produce more output so travis wouldn't complain about no seeing any new output since 10min by passing e.g. `-v` or  `-vv` or even `RUST_LOG=trace` but these would either still timeout, either hit travis' limit of 10k lines of output.

**Comment by cr6git** [comment]
[57146b2](https://github.com/voidlinux/void-packages/commit/57146b2a7d3d9ac042de2c16a79cd36af2dc45e1)

**Pull request closed without merging**
