### PR TITLE
elogind: fix musl

### LINKED ISSUE #5887: FYI: working on musl elogind patch
Just to avoid duplicate efforts.

### PR DESCRIPTION
**Pull request by pullmoll**
Compiles but is yet untested.

Closes #5887

### CODE REVIEW

**Comment by Gottox** [comment]
Nice!

**Comment by pullmoll** [comment]
Please take look at if the `secure_getenv()` macro is sane enough or needs more tests.

**Comment by Gottox** [comment]
Fails to start with:
```
[root@void-musl pullmoll-elogind]# /usr/libexec/elogind/elogind.wrapper 
Failed to create root cgroup hierarchy: Invalid argument
Failed to fully start up daemon: Invalid argument
[root@void-musl pullmoll-elogind]# 
```

**Comment by Gottox** [comment]
Personally I used a simple -Dsecure_getenv=getenv macro whenever I thought it was safe enough, but your compatibility macro looks better.

**Comment by pullmoll** [comment]
This is src/login/logind.c:711 function `manager_setup_cgroup()`.
Ah, the fscking `%m` is the culprit. Has to be replaced with `%s` a `strerror_r()` returned string to see what's wrong there.

**Comment by pullmoll** [comment]
For logind.c now musl should print the real error message. There are more source files using "%m".

**Comment by pullmoll** [comment]
Ok, now all `"%m"` are replace with "%s" and a new function `error_str()` defined in `src/shared/log.{c,h}`. That should make all error logging print sane things and work with glibc and musl equally well.

**Comment by Gottox** [comment]
@wingo @Yamakuzure Is there any chance to get musl support for elogind back upstream?

**Comment by Gottox** [comment]
According to the source. musl has support for %m: https://git.musl-libc.org/cgit/musl/tree/src/stdio/vfprintf.c#n615

**Comment by Gottox** [comment]
Okay, I think I got the error tracket down:

The error happens when elogind checks for the existence of a cgroup in ```src/shared/cgroup-util.c:512```, the laccess macro calls ```faccessat(2)``` which return EINVAL. According to the manpage:
```
EINVAL Invalid flag specified in flags.
```

According to the source defined in https://git.musl-libc.org/cgit/musl/tree/src/unistd/faccessat.c#n36, musl does not support ```AT_SYMLINK_NOFOLLOW``` which is used in the laccess macro.

**Comment by Gottox** [comment]
The patch:

cat 009-fix-faccessat-flags.patch 
```diff
--- src/shared/util.h.orig	2017-03-05 17:12:46.654974564 +0100
+++ src/shared/util.h	2017-03-05 17:14:11.998704156 +0100
@@ -1041,7 +1041,11 @@ union inotify_event_buffer {
         uint8_t raw[INOTIFY_EVENT_MAX];
 };
 
+#ifdef __GLIBC__
 #define laccess(path, mode) faccessat(AT_FDCWD, (path), (mode), AT_SYMLINK_NOFOLLOW)
+#else
+#define laccess(path, mode) faccessat(AT_FDCWD, (path), (mode), 0)
+#endif
 
 int ptsname_malloc(int fd, char **ret);
```

With this patch applied eloginctl seems to work fine.

**Comment by Gottox** [comment]
The daemon runs, but loginctl does not show sessions. Anyway, with this patch applied it is good enough to merge.

**Comment by pullmoll** [comment]
Ok, the 009-fix-faccessat-flags.patch is there now.

**Comment by pullmoll** [comment]
> According to the source. musl has support for %m: https://git.musl-libc.org/cgit/musl/tree/src/stdio/vfprintf.c#n615

I wonder why the errors your reported were all just `Invalid argument` then.
While working on the patches, I also read one of those flamewar like threads regarding logind where someone told that the use of "%m" was causing problems for other libcs (possibly *BSD).

If the patch really isn't required, just drop it.

**Comment by Gottox** [comment]
Imho it isn't required.

**Comment by Gottox** [comment]
Okay, session tracking seems to work. The error was caused by a missconfigured pam on my end.

**Comment by pullmoll** [comment]
Perhaps we can keep the patch in srcpkgs/elogind/files for the case that anyone with a libc who does definitely not support "%m" want to use it.

**Comment by Gottox** [comment]
or just keep it in the git-history.

**Comment by pullmoll** [comment]
Please merge. The musl builders have some things in the queue already :)

**Comment by Gottox** [comment]
here we go :D

**Pull request merged**
