### PR TITLE
ffmpeg: update to 3.1.3.

### PR DESCRIPTION
**Pull request by Vaelatern**
Still needs any revdeps added. What's the command to find reverse dependencies that need rebuilding after a shlib bump?

2.8-3.0 is a relatively simple changelog for ffmpeg, from a packaging perspective.

### CODE REVIEW

**Comment by xtraeme** [comment]
xbps-src will tell you which pkgs need to be revbumped if the soname is not available in `common/shlibs` (comment out them and then try a temporary build with `./xbps-src -t install ffmpeg`).

Use `xrevbump` from xtools to revbump the reverse dependencies.

**Comment by Vaelatern** [comment]
Build in that case ends with:
```
   SONAME: libswresample.so.2 <-> UNKNOWN PKG PLEASE FIX!
   SONAME: libavutil.so.55 <-> UNKNOWN PKG PLEASE FIX!
   SONAME: libva.so.1 <-> libva>=1.0.14_1
   SONAME: libpthread.so.0 <-> glibc>=2.8_1
   SONAME: libxvidcore.so.4 <-> xvidcore>=1.2.2_1
   SONAME: libx265.so.79 <-> x265>=1.9_1
   SONAME: libx264.so.142 <-> x264>=20140928.2245_1
   SONAME: libvpx.so.2 <-> libvpx>=1.4.0_1
   SONAME: libm.so.6 <-> glibc>=2.8_1
   SONAME: libvorbisenc.so.2 <-> libvorbis>=1.2.1rc1_1
   SONAME: libvorbis.so.0 <-> libvorbis>=1.2.1rc1_1
   SONAME: libtheoraenc.so.1 <-> libtheora>=1.0_1
   SONAME: libtheoradec.so.1 <-> libtheora>=1.0_1
   SONAME: libspeex.so.1 <-> libspeex>=1.1_1
   SONAME: libz.so.1 <-> zlib>=1.2.3_1
   SONAME: libmp3lame.so.0 <-> lame>=3.98.2_1
   SONAME: libcelt0.so.2 <-> celt>=0.11.1_1
   SONAME: libc.so.6 <-> glibc>=2.8_1
=> ERROR: libavcodec-3.0_1: cannot guess required shlibs, aborting!
```

**Comment by Vaelatern** [comment]
I feel some of these revbumps are not necessary.

All the travis builds fail on `opencl` at present.

**Comment by Vaelatern** [comment]
Now gets as far as `xine` before breaking.

**Comment by Vaelatern** [comment]
Is there anything that can be done for xine? They have not seen commits since 2014, and are not compatible with the ABI changes in ffmpeg-devel>=3.0

**Comment by Vaelatern** [comment]
Failing on openimageio, which needs to be bumped anyway.

**Comment by Vaelatern** [comment]
Even the latest openimageio, 15 days old at time of writing, can't use ffmpeg3.0. Patches of the kind applied to `xine-lib` incoming.

**Comment by Vaelatern** [comment]
vlc is also blocking this.

**Comment by pullmoll** [comment]
You opened up Pandora's box it seems. LMK if I can help with (even more) problems.

**Comment by ebfe** [comment]
Since this is bumping opencv to 3.1 (also a soname bump), i think this is missing revbumps for actiona, gmic, nomacs, nomacs-qt5 (maybe incomplete)?

Also theres an openimageio update and a rebuild later. Probably ony need the update.

**Comment by Vaelatern** [comment]
@ebfe I put the revbump in to make it clear what is happening. I do the same on `opencv` but github doesn't seem to be aware of that.

**Comment by Vaelatern** [comment]
@ebfe Can you confirm that list of additional revbumps so far is correct?

**Comment by Vaelatern** [comment]
Now with the revbumps for `opencv`.

**Comment by Vaelatern** [comment]
Currently blocking on linking errors in openimageio and vlc patches for ffmpeg3.0

```
Linking CXX executable idiff
../libOpenImageIO/libOpenImageIO.so.1.6.11: undefined reference to `cvCreateCameraCapture'
../libOpenImageIO/libOpenImageIO.so.1.6.11: undefined reference to `cvReleaseCapture'
../libOpenImageIO/libOpenImageIO.so.1.6.11: undefined reference to `cvQueryFrame'
collect2: error: ld returned 1 exit status
```
https://s3.amazonaws.com/archive.travis-ci.org/jobs/117768222/log.txt

**Comment by ebfe** [comment]
ffmpeg 3.0.1 available

**Comment by Vaelatern** [comment]
Still waiting on vlc upstream to not refuse ffmpeg >= 3.0

**Comment by Vaelatern** [comment]
Added a patch mentioned in #4755 to vlc. Ready for review and possibly merge.

**Comment by Vaelatern** [comment]
I consider this ready to merge. Dunno if anything else here is actually broken.

**Comment by pullmoll** [comment]
If really anything is broken, people will certainly report it. IMO just update mgba and merge.

**Comment by asergi** [comment]
Done.

**Pull request closed without merging**
