### PR TITLE
New package: Abricotine

### PR DESCRIPTION
**Pull request by praticamentetilde**
[Here](http://abricotine.brrd.fr) the website. I just made the template, not the application itself.

### CODE REVIEW

**Comment by Anachron** [comment]
It's electron based so very unlikely to get merged.

**Comment by praticamentetilde** [comment]
Atom is based on electron, and it's in the official repository. Do you mean that the package should depend on an `electron` package?

**Comment by the-maldridge** [comment]
@praticamentetilde we're actively trying to get rid of the electron based apps since they aren't designed for packaging.  Atom comes from a time where we thought the quality of electron derived codebases would improve with time, this assertion turned out to be very much false.

**Comment by praticamentetilde** [comment]
In this case, I guess I should close this.

**Comment by the-maldridge** [comment]
feel free to leave it for review, another maintainer may be willing to merge it.

**Comment by the-maldridge** [comment]
Other maintainers have had plenty of time to claim this PR, seems that (as expected) no one wants to shoulder another electron app.

**Pull request closed without merging**
