### PR TITLE
Xfce4-whiskermenu-plugin: update to 2.0.3

### PR DESCRIPTION
**Pull request by Piraty**
This seems to be mostly a gtk3 update, as 2.x is maintained along 1.6.x
exo needed an update too.

### CODE REVIEW

**Comment by Duncaen** [comment]
By just updating `exo` you break all other packages that depend on it.

```
$ xbps-quert -RX exo
thunar-volman-0.8.1_2
xfburn-0.5.4_2
xfce4-4.12.0_5
xfce4-mailwatch-plugin-1.2.0_1
xfce4-panel-4.12.1_1
xfce4-places-plugin-1.7.0_1
xfce4-screenshooter-1.8.2_3
xfce4-settings-4.12.1_1
xfce4-whiskermenu-plugin-1.6.2_1
xfdesktop-4.12.3_2
```

You would have to revbump all to rebuild them, if they already work with the updated exo and gtk3.
Maybe its better if you copy the template to `exo-gtk3`.

**Comment by Piraty** [comment]
Well, then I'll do some testing with all of them, most of them are installed on my machine anyway.
Should [WIP] or sth. be added to the title for the time i test this?
Or do you prefer to have a seperate package (like `exo-0.11` or like your `exo-gtk3` or whatever)?

**Comment by asergi** [comment]
`xfce4-whiskermenu-plugin` hasn't been updated to version 2.0 on purpose because of what @Duncaen already said. Also, `exo-0.11.x` are development releases.

**Comment by cr6git** [comment]
To update `xfce4-whiskermenu-plugin` to the latest release 2.1.5, it is necessary to update `exo` to 0.12.0.

@asergi are `exo-0.12.x` development releases?

**Pull request closed without merging**
