### PR TITLE
New package: dotgit-1.2.0

### PR DESCRIPTION
**Pull request by oliver-cfc**

### CODE REVIEW

**Comment by Vaelatern** [comment]
The software has no problem with just being installed in a bin folder by a user. No compilation necessary. Not sure we want this included.

**Comment by oliver-cfc** [comment]
Fair enough.  I thought it might be nice to get some automated updates.

**Comment by Vaelatern** [comment]
Someone still has to package those updates.

**Comment by oliver-cfc** [comment]
I meant updates to the script (and bash-completion if there are ever new features)... Wouldn't the buildbot take care of everything once the version number was bumped?

**Comment by Vaelatern** [comment]
No, that is not automatic, since changes can happen between version numbers that require modifying the template significantly.

**Pull request closed without merging**
