### PR TITLE
New package: bfs

### PR DESCRIPTION
**Pull request by cr6git**

### CODE REVIEW

**Comment by cr6git** [comment]
Have you noticed ? 
The [author](https://github.com/tavianator) is working for Microsoft. 
This is intolerable.

**Comment by chneukirchen** [comment]
Quick, delete the Linux kernel.

The license is fine, I see no reason we can't have this package.

**Comment by cr6git** [comment]
Why delete the Linux kernel ? 
AFAIK Linus Torvalds is not working for Microsoft... 

You can copy this template to make the pull request yourself, no problem! ;)

**Comment by chneukirchen** [comment]
But Microsoft is a Top 5 contributor to Linux. ;)

**Comment by cr6git** [comment]
Microsoft should take care of its own garbage kernel.

**Pull request closed without merging**
