### PR TITLE
New package: spotify-0.9_1

### PR DESCRIPTION
**Pull request by teh-jazzman**
Version numbers vary significantly between 32 and 64 bit. 0.9 is the smallest common denominator.
xlint claims allow_unknown_shlibs is a custom variable...

### CODE REVIEW

**Comment by silvernode** [comment]
I've been waiting for this, thanks

**Comment by xtraeme** [comment]
I'm not sure about legal terms with that one... are we allowed to pkg and distribute this, even in a non-free repository?

**Comment by teh-jazzman** [comment]
Hmm, you're right. I thought it was at least in the official Debian/Ubuntu repos, but they are providing their own repo. How about I change the package to only contain the libgcrypt library and do the rest at installation-time via the INSTALL and REMOVE files?

**Comment by Gottox** [comment]
@teh-jazzman that's a solution. We already do that with [chromium-pepper-flash](https://github.com/voidlinux/void-packages/tree/master/srcpkgs/chromium-pepper-flash) and [oracle-jdk](https://github.com/voidlinux/void-packages/tree/master/srcpkgs/oracle-jdk)

**Comment by Gottox** [comment]
Great!

The only remaining issue is that the launcher icons aren't correctly installed. Will merge after the fix.

**Comment by teh-jazzman** [comment]
I changed the icon names to fit the entry in the spotify.desktop file. I hope that fixes the problem. I currently don't run a DE, so I don't know if it is working or not. If not I'll build me a test environment later today.

**Comment by Gottox** [comment]
Works for enlightenment :+1:

**Pull request merged**
