### PR TITLE
new package: osbuddy

### PR DESCRIPTION
**Pull request by ibrokemypie**

### CODE REVIEW

**Comment by Duncaen** [comment]
I don't see that this would be merged, the license is questionable, we don't know if it grants the rights to redistribute.

**Comment by Vaelatern** [comment]
And this PR adds a lot of artifacts to the repo that surely can be downloaded from elsewhere.

**Comment by ibrokemypie** [comment]
Its all from the package over at the AUR, which has had no licensing problems and has now become endorsed by the project on their home page.
The artifacts could be taken from the aur if that is better?

**Comment by Duncaen** [comment]
The AUR does not host any third-party files, its just a build script.
If we merge this package, we would redistribute their binaries on our repository server and mirrors.
We can't do this if the license does not allow it explicitly.

**Comment by Vaelatern** [comment]
The license still makes me nervous, and is unclear.

**Comment by Jazqa** [comment]
ibrokemypie, take a look at HikariKnight's Runescape client for Unix. It's GNU licensed and supports both, Runescape 3 and Old School Runescape.

**Comment by Vaelatern** [comment]
@ibrokemypie so where does the AUR license these other files for redistribution?

**Comment by Jazqa** [comment]
@Vaelatern AUR lists the license as "custom" and downloads the .jar directly from OSBuddy's website. OSBuddy is not open source software and they offer a premium model that has a monthly cost. It's an unofficial, third party client for the game. However, most players prefer OSBuddy as it offers multiple features the official client does not have. 

I've used the client I linked but I'm not very familiar with the technical side. It's made by a Runescape moderator and is completely open-source and somehow adjusts the official Runescape client to work on Linux.

Again, I'm not completely sure how Runescape or the clients work on a technical level but I guess they act like a browser, connecting to the Runescape server, downloading necessary files and running the game.

**Comment by ibrokemypie** [comment]
I still think having OSBuddy packaged would be a good thing, the more the merrier, so I will contact them and ask permission to redistribute in binary form through XBPS

**Comment by Jazqa** [comment]
@ibrokemypie, I don't know but it's packaged for other distributions. It seems to be the most ["official"](https://support.runescape.com/hc/en-gb/articles/206659489-Linux-Native-Clients) Linux client for Runescape.

If OSBuddy is to be packaged, remember to mark it for the non-free repository as it's closed source software.

**Comment by ibrokemypie** [comment]
@all going to just leave this until developers get back and update when/if they do. In the mean time, going to do rsu-client since we need a bit of runescape in whatever wrapping :)

**Comment by the-maldridge** [comment]
@ibrokemypie At this time, the official stance is that the license is iffy at best.  If no other maintainer has comments on this in the next 2 days, I'd suggest closing this PR given that we really aren't comfortable merging this at this time.

**Comment by Vaelatern** [comment]
License is iffy, there are too many random artifacts, and it's nonfree anyway.

**Comment by Soundtoxin** [comment]
I understand why this was not merged, but can we see a package made for the client mentioned by @Jazqa? It looks like it should be fine. I just found this thread while searching how I can play OSRS on Void.

**Comment by ibrokemypie** [comment]
@Soundtoxin just need to clean this one up
https://github.com/voidlinux/void-packages/pull/6725

**Pull request closed without merging**
