### PR TITLE
khelpcenter: update to 17.12.0.

### PR DESCRIPTION
**Pull request by Chocimier**

### CODE REVIEW

**Comment by Chocimier** [comment]
Any hints how to make libxapian.so visible during cross build?

**Comment by jambonmcyeah** [comment]
Add libxapian-devel to makedepends

**Comment by newbluemoon** [comment]
CMake’s script to find xapian is unaware of `$XBPS_CROSS_BASE`. By adding the variables the script sets explicitly to `configure_args` it works. :)

And maybe it’s also a good idea to put the additions to `hostmakedepends` inside the ‘cross branch’, too.

```
if [ -n "$CROSS_BUILD" ]; then
        hostmakedepends+=" qt5-qmake qt5-host-tools python kdoctools kconfig"
        configure_args+=" -DXAPIAN_LIBRARIES=${XBPS_CROSS_BASE}/usr/lib/libxapian.so
         -DXAPIAN_INCLUDE_DIR=${XBPS_CROSS_BASE}/usr/include -DXAPIAN_FOUND=TRUE"
fi
```

**Comment by Chocimier** [comment]
Thanks, @newbluemoon

**Pull request closed without merging**
