### PR TITLE
RFC: base-files: add vkpurge.8

### PR DESCRIPTION
**Pull request by Vaelatern**
#4058

### CODE REVIEW

**Comment by xtraeme** [comment]
Did you run this with `mandoc -Wall` by chance? please do so and fix the warnings (if applicable).

**Comment by Vaelatern** [comment]
Runs without errors.

**Comment by xtraeme** [comment]
Perfect, thanks :+1:

**Comment by chneukirchen** [comment]
Please let `-man` die, I'll rewrite it in `-mandoc`. Thanks for the content!

**Comment by chneukirchen** [comment]
Slightly tweaked: http://sprunge.us/cCbU

**Comment by Vaelatern** [comment]
Done, @chneukirchen

**Pull request merged**
