### PR TITLE
New package: gimp2.9-2.9.2_1

### PR DESCRIPTION
**Pull request by antonio-malcolm**
This is the new 2.9.x Gimp, with improved bit depth and other features.

### CODE REVIEW

**Comment by ebfe** [comment]
Why a new package rather than updating the existing one?

**Comment by Gottox** [comment]
keep in mind that 2.9.x is the development branch of gimp 2.10.

**Comment by antonio-malcolm** [comment]
We can certainly do that, but while 2.9.x is reportedly stable (used in production by a few), it is still a developer's release (as it will be, until 2.10.x or 3.x), and I thought it would be good to give folks the choice of using this new version, or staying with 2.8.x.

If folks would rather have this as an update, I can move the code over.

**Comment by antonio-malcolm** [comment]
(BTW, this is for i686 and x86_64 only, so it won't pass the ARM tests.)

**Comment by Gottox** [comment]
I'd like to wait untill gimp releases a stable version.

**Comment by antonio-malcolm** [comment]
Good luck. That will be a long-time coming, knowing the Gimp team (esp. if they decide to skip 2.10, for a 3.x release). There's a lot of capability in 2.9, which you won't get with 2.8. I'll keep my branch up,and keep it updated, with the template, for anyone who wants it.

**Pull request closed without merging**
