### PR TITLE
Adapta: update to 3.22.2.22.

### PR DESCRIPTION
**Pull request by demiaster**

### CODE REVIEW

**Comment by chneukirchen** [comment]
Is it really necessary to update this package every single day?

**Comment by demiaster** [comment]
I could update only when the minor c (a.b.c.d) releases comes out, if you think it is better. Anyway, since it is the first time for me maintaining a package, may I ask why is not ok to update so frequently?

**Comment by pullmoll** [comment]
And I thought `lollypop` was the most frequently updated package. :lollipop: 

In theory it's ok to update every time, but then there may be changes which are not **that** important, i.e. not that kind of important as in *live saving important*.

For lollypop I always wait until after the weekend, which usually allows me to skips 3-4 builds. :smile:

**Comment by demiaster** [comment]
@pullmoll thank you for the clarification, I will follow your advice :smile:

**Pull request merged**
