### PR TITLE
google-chrome updated to 51.0.2704.106

### PR DESCRIPTION
**Pull request by logenkain**
Chrome failed to download for me so I updated it.

### CODE REVIEW

**Comment by logenkain** [comment]
So... I suppose this can be closed now? Looks like the maintainer got a merge in. I'll be honest, too tired/lazy to confirm at this point.

**Comment by logenkain** [comment]
Okay, I had to check...
So, I made this commit 2 days or so ago, any reason why mine was ignored and the maintainer's was merged within the hour?

**Comment by Vaelatern** [comment]
@logenkain Sorry, I saw the maintainer's commit shortly after, so could review to make sure it was the most recent version. I had not seen this commit then.

Your PR was correct.

**Comment by logenkain** [comment]
@Vaelatern No problem, I was just curious. Thanks!

**Pull request closed without merging**
