### PR TITLE
ldb: update to 1.1.27

### PR DESCRIPTION
**Pull request by the-maldridge**
Currently broken on musl, I'm considering removing this simply because SSSD is such a pain to maintain and use, and its the only thing that depends on this that I know of.

### CODE REVIEW

**Comment by Vaelatern** [comment]
How do `rep_stroll` and `stroll` compare? musl has `stroll`

**Comment by Duncaen** [comment]
It uses `stroll` by default but it looks like the tests in `ldb-1.1.27/lib/replace/wscript` are wrong or musls `strtoll` behaves like the bsd variant.

**Comment by Vaelatern** [comment]
I'd believe it behaves like the BSD `stroll` and friends.

**Comment by Duncaen** [comment]
The it should use the internal `rep_strtoll` function from `/ldb-1.1.27/lib/replace/replace.c`.

**Comment by Vaelatern** [comment]
Yet it can't find it.

**Comment by the-maldridge** [comment]
Its worth pointing out that the only consumer of this is sssd and that has insanely tight coupling to glibc.

**Pull request closed without merging**
