### PR TITLE
openbabel: update to 2.4.1 / unbreak arm* and aarch64*

### PR DESCRIPTION
**Pull request by newbluemoon**
The patch is taken from upstream where I reported the [issue](https://github.com/openbabel/openbabel/issues/1689).

### CODE REVIEW

**Comment by newbluemoon** [comment]
This is strange: locally avogadro is built without any problem, I even zapped the masterdir and all is OK.

**Comment by cr6git** [comment]
Travis complains about `eigen2`
````
/usr/include/eigen3/Eigen/Core:321:2: error: #error Eigen2-support is only available up to version 3.2.
````

The AUR [package](https://aur.archlinux.org/packages/avogadro) is using a patch related to eigen2 something... Perhaps this is the solution?

**Comment by ebfe** [comment]
We have eigen2 and eigen3.2 for this.

**Comment by ebfe** [comment]
The reason it works sometimes is that avogadro depends on eigen2 and openbabel on eigen... which should conflict but doesn't. So which version you get depends on package install order...

**Comment by newbluemoon** [comment]
So maybe I should do a separate PR for avogadro then?

**Comment by ebfe** [comment]
Hmm, the problem is not the conflicts. It's that avogadro prefers eigen 3.x if available (which is pulled in by openbabel). Since it relies on the 2.x compatibility, the only solution i see is to make them both to depend on eigen3.2. No need for a new PR.

**Comment by newbluemoon** [comment]
Ok, made both use eigen3.2. Let’s wait and see... ;)

**Comment by newbluemoon** [comment]
That did it. Thank you!

**Pull request closed without merging**
