### PR TITLE
New package: Kvantum-0.10.5

### PR DESCRIPTION
**Pull request by gspe**

### CODE REVIEW

**Comment by newbluemoon** [comment]
You need to add `qt5-host-tools` to `hostmakedepends` when cross-compiling.

**Comment by newbluemoon** [comment]
There is a space missing:

    hostmakedepends+=" qt5-host-tools qt5-devel"

**Comment by gspe** [comment]
Thank for you suggestion and time.
Now should build correctly

**Comment by pullmoll** [comment]
Do you really want the uppercase first letter? Other distributions seem to use `kvantum` and users generally complain about Uppercase or even CamelCase package names :)

**Comment by gspe** [comment]
Not really, I've just followed the indication in the manual

> For those packages the upstream packages name should be used. Remember that in contrast to many other distributions, void doesn't lowercase package names. As a rule of thumb, if the tar.gz of a package contains uppercase letter, then the package name should contain them too; if it doesn't, the package name is lowercase.

but I agree that Lowercase is just nice, so I'm going to rename it Lowercase

**Comment by pullmoll** [comment]
It's a matter of taste actually and Void does not enforce one or the other AFAIR. In fact there are quite well known packages with camel case like `ModemManager` or `NetworkManager`, first character uppercase like `Thunar`, or some packages with an all-uppercase name like `SDL`.

KDE5 packages seem to prefer all lowercase...

**Pull request closed without merging**
