### PR TITLE
opencv: enable opencl/openmp

### PR DESCRIPTION
**Pull request by thypon**

### CODE REVIEW

**Comment by beefcurtains** [comment]
Have you tried compiling it on musl? Maybe you can figure out the recursive mutex initializer :star:

**Comment by thypon** [comment]
Nope, we should upgrade to 3.0 instead, maybe it solves musl bugs upstream.

**Comment by beefcurtains** [comment]
[It doesn't](https://github.com/voidlinux/void-packages/pull/1816).

**Comment by thypon** [comment]
Could i merge this one?

**Comment by beefcurtains** [comment]
I'd rather update first, either or both might be default now.

**Comment by thypon** [comment]
We have to revbump also all the dependencies i think.

This update should only improve performance.

**Comment by thypon** [comment]
opencl is default but it needs the headers/devel files to be installed.

**Comment by beefcurtains** [comment]
We'd have to revbump again after updating to 3.0.0, but I don't see any revdeps.
Let's see if adding ``opencl2-headers opencl-headers libgomp-devel`` on 3.0 adds more shlibs.

**Comment by thypon** [comment]
I think we could close this one continuing with opencv 3.0

**Pull request closed without merging**
