### PR TITLE
gpgme: change to gnupg2

### PR DESCRIPTION
**Pull request by Vaelatern**
Closes #3567 and removes extra variable.

### CODE REVIEW

**Comment by xtraeme** [comment]
The same question I did in #3567 remains.

**Comment by Vaelatern** [comment]
No, it is not necessary at build at all. That is why I remove it here.
So far I have determined either of `gnupg` or `gnupg2` satisfies basic runtime depends.

**Comment by ebfe** [comment]
gpgme prefers gpg2 and checks at runtime which binaries are available. So the `depends=` change should be fine.

**Comment by xtraeme** [comment]
Took a look at the source code (src/posix-util.c):

```
/* Return the full file name of the GPG binary.  This function is used
   if gpgconf was not found and thus it can be assumed that gpg2 is
   not installed.  This function is only called by get_gpgconf_item
   and may not be called concurrently.  */
```

So that even if it depends on gpg2, it will use gpg it gpgconf is in PATH.

**Comment by ebfe** [comment]
On Tue, Mar 29, 2016 at 06:30:06AM -0700, Juan RP wrote:
> So that even if it depends on gpg2, it will use gpg it gpgconf is in PATH.

I think you read that wrong. gpgconf is only in gpg2.

**Comment by xtraeme** [comment]
Hmm you are right. In this case it will prefer gpg2.

Thanks for the clarification.

This PR can be merged :+1:

**Pull request merged**
