### PR TITLE
New package: linux_logo-5.11

### PR DESCRIPTION
**Pull request by cr6git**

### CODE REVIEW

**Comment by wpbirney** [comment]
this brings back memories! 

although it says my system ram is 128TB LOL

**Comment by cr6git** [comment]
A closer look at the build:
````
=> linux_logo-5.11_1: running do_configure ...
/usr/bin/xgettext
/usr/bin/gcc

CONFIGURING LINUX_LOGO
  Detected Architecture:     i686
  Detected Operating System: Linux
  Install prefix:  /usr
  Install program: /builddir/.xbps-linux_logo/wrappers/install
  xgettext:   xgettext
  libsysinfo: libsysinfo-0.2.2
  C Compiler : gcc
  CFLAGS     : -Wall -O2

/usr/bin/gcc
/usr/bin/ar

CONFIGURING LIBSYSINFO
  Detected Architecture:     i686
  Detected Operating System: Linux
  C Compiler : gcc
  AR         : ar
  CFLAGS     : -Wall -O2
````
I don't think these CFLAGS are correct, however.
No idea how to fix that.

**Comment by wpbirney** [comment]
libsysinfo-0.2.2 was written for kernel 2.4* I'm sure some stuff has changed since then

everything appears accurate except the cpu freq shows current freq not max, and memory is showing 128TB on a 32GB ram system...

Ill look into the memory side, that should be a simple patch

**Comment by wpbirney** [comment]
oh im slow today,
it works just fine running as root, the memory is read from /proc/iomem which isn't accessible by non root

**Comment by Vaelatern** [comment]
It's not respecting any of our variables
https://travis-ci.org/voidlinux/void-packages/jobs/338731857#L940

**Comment by Vaelatern** [comment]
Probably `configure` build style.

**Comment by cr6git** [comment]
Thank you both. I don't have time today to work on this.

**Comment by wpbirney** [comment]
it appears that the configure script is not an an autoconf configure script

From the top of configure
`#  This is not a real autoconf configure script.`

this would be why it is ignoring our variables

**Comment by Vaelatern** [comment]
@cr6git no rush. We are asynchronous here. PRs stay open until no progress for more than a month

**Comment by newbluemoon** [comment]
The first `sed` modifies the configure script to use Void’s flags. The second `sed` is because the binary `parse_logos` is executed. It’s just used for building purposes so I think it’s safe to modify the `Makefile` to compile it with the host compiler.

```
if [ -n "$CROSS_BUILD" ]; then
	pre_configure() {
		# make use of Void’s flags
		sed -i -e "s|echo \"CC=\$CC\"|echo \"CC=$CC\"|" \
		 -e "s|echo \"ARCH=\$ARCH\"|echo \"ARCH=$XBPS_TARGET_MACHINE\"|" \
		 -e "s|echo \"CFLAGS=\$CFLAGS\"|echo \"CFLAGS=$CFLAGS\"|" \
		 -e "s|echo \"LDFLAGS=\$LDFLAGS\"|echo \"LDFLAGS=$LDFLAGS\"|" \
		 configure libsysinfo-0.2.2/configure

		# compile 'parse_logos' with host compiler
		sed -i -e "s|^\(\s\+\)\$(CC)\s\+\$(CFLAGS)|\1gcc -O2 -pipe|" \
		 -e "s|^\(\s\+\)\$(CC)\s\+\$(LDFLAGS)|\1gcc|" \
		 Makefile
	}
fi
```

I admit this doesn’t look very nice. Perhaps someone has a better idea?

**Comment by cr6git** [comment]
@newbluemoon it doesn't work.
````
+ Added logo ./logos/distributions/sourcemage-banner.logo... done.
make[3]: Entering directory '/builddir/linux_logo-5.11/libsysinfo-0.2.2/Linux'
make[3]: *** No rule to make target 'aarch64-musl', needed by 'cpuinfo.o'.  Stop.
make[3]: Leaving directory '/builddir/linux_logo-5.11/libsysinfo-0.2.2/Linux'
make[2]: *** [Makefile:40: libsysinfo.a] Error 2
make[2]: Leaving directory '/builddir/linux_logo-5.11/libsysinfo-0.2.2'
make[1]: *** [Makefile:67: libsysinfo-0.2.2/libsysinfo.a] Error 2
make[1]: *** Waiting for unfinished jobs....
 containing "Source Mage GNU/Linux banner"
+ Added logo ./logos/distributions/ubuntu.logo containing "Ubuntu Logo"
+ Added logo ./logos/distributions/pld.logo containing "PLD Linux banner"
+ Added logo ./logos/distributions/slackware.logo containing "Slackware Logo"
+ Added logo ./logos/distributions/debian-old.logo containing "Debian Old Penguin Logos "
+ Added logo ./logos/distributions/sourcemage.logo containing "Source Mage GNU/Linux large"
+ Added logo ./logos/distributions/mandriva-banner.logo containing "Mandriva(TM) Linux Banner"
+ Added logo ./logos/distributions/gnu-linux.logo containing "Classic GNU/Linux"
+ Added logo ./logos/distributions/suse.logo containing "SUSE Logo"
+ Added logo ./logos/distributions/redhat-banner.logo containing "RedHat Banner (white) "
+ Added logo ./logos/distributions/mandrakelinux-banner.logo containing "Mandrakelinux(TM) Banner"
+ Added logo ./logos/distributions/debian.logo containing "Debian Swirl Logos"
+ Added logo ./logos/distributions/sme.logo containing "SME Server Banner Logo..."
+ Added logo ./logos/distributions/core.logo containing "Core Linux Logo"

 done.
... done.
... done.
... done.
... done.
... done.
... done.
make[2]: Leaving directory '/builddir/linux_logo-5.11/po'
make[1]: Leaving directory '/builddir/linux_logo-5.11'
make: *** [Makefile:42: logos-all] Error 2
=> ERROR: linux_logo-5.11_1: failed to run do_build() at line 13.
````
:confused:

**Comment by newbluemoon** [comment]
Hm... I didn’t test it on all platforms, but it’s working for me on armv7l. I’ll try to find out what’s wrong. :)

**Comment by newbluemoon** [comment]
There seems to be a problem only with aarch64, the other targets work for me. But I just found out that `disable_parallel_build=yes` has to be set.

**Comment by newbluemoon** [comment]
It doesn’t know aarch64. With

```
case "$XBPS_TARGET_MACHINE" in
	aarch64*) make_build_args+=" ARCH=arm"
esac
```

the package is built.

Debian uses this patch (which is basically the same):

```
Description: Add minimal support for arm64 aka aarch64
Author: Axel Beckert <abe@debian.org>
Forwarded: https://github.com/deater/linux_logo/pull/6
Bug-Debian: https://bugs.debian.org/791929

Index: linuxlogo/libsysinfo-0.2.2/Linux/Makefile
===================================================================
--- linuxlogo.orig/libsysinfo-0.2.2/Linux/Makefile      2016-04-26 00:17:47.419671863 +0200
+++ linuxlogo/libsysinfo-0.2.2/Linux/Makefile   2016-04-26 00:19:17.179550584 +0200
@@ -6,6 +6,9 @@
 ifneq (,$(findstring arm,$(ARCH)))
    ARCH := arm
 endif
+ifneq (,$(findstring aarch64,$(ARCH)))
+   ARCH := arm
+endif
 ifneq (,$(findstring sh,$(ARCH)))
    ARCH := sh
 endif
```

**Comment by newbluemoon** [comment]
The first `sed` command should also have the line
`-e "s|echo \"AR=\$AR\"|echo \"AR=$AR\"|"`
to use the cross ar. Missed that previously, sorry.

Perhaps changing `CFLAGS` and `LDFLAGS` should always be happening because Void’s flags aren’t respected in any case. Here’s a remodeled `pre_configure()`. Because the libsysinfo subdirectory is versioned I added a way to determine it and not have to keep track of it.

```
pre_configure() {
	_libsysinfo_dir=$(sed -n "s/^LIBSYSINFO=//p" configure)

	# make use of Void’s flags
	sed -i -e "s|echo \"CC=\$CC\"|echo \"CC=$CC\"|" \
	 -e "s|echo \"AR=\$AR\"|echo \"AR=$AR\"|" \
	 -e "s|echo \"ARCH=\$ARCH\"|echo \"ARCH=$XBPS_TARGET_MACHINE\"|" \
	 -e "s|echo \"CFLAGS=\$CFLAGS\"|echo \"CFLAGS=$CFLAGS\"|" \
	 -e "s|echo \"LDFLAGS=\$LDFLAGS\"|echo \"LDFLAGS=$LDFLAGS\"|" \
	 configure ${_libsysinfo_dir}/configure

	if [ -n "$CROSS_BUILD" ]; then
		# compile 'parse_logos' with host compiler
		sed -i -e "s|^\(\s\+\)\$(CC)\s\+\$(CFLAGS)|\1gcc -O2 -pipe|" \
		 -e "s|^\(\s\+\)\$(CC)\s\+\$(LDFLAGS)|\1gcc|" \
		 Makefile
	fi
}
```

**Comment by cr6git** [comment]
@newbluemoon it doesn’t look very nice but that works. :smiley: well done! thank you.

**Comment by newbluemoon** [comment]
> it doesn’t look very nice

Indeed ;)

Alternatively one could edit the generated `Makefile.defaults` in a `post_configure()` stage, but that wouldn’t be much different. I also tried to just remove the flags set in `configure` so that the environtment variables set by xbps-src were used, but that brought up new errors.

**Comment by silvernode** [comment]
Even on Ubuntu it says I have 128TB of RAM when I only have 8GB. I guess not even Debian bothers to fix it.

**Comment by newbluemoon** [comment]
@silvernode But it has been reported upstream: https://github.com/deater/linux_logo/issues/14

**Comment by wpbirney** [comment]
I know it is not ideal but in its current state it shows the proper ram amount when ran by root

Looking over the source for linux_logo it would be trivial to patch it to fallback to /proc/meminfo instead of /proc/iomem, there is already a function to fetch it from meminfo... although there is a comment in the code saying that meminfo is normally 1MB-20MB off

**Comment by cr6git** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=839594

**Comment by cr6git** [comment]
@wpbirney do you think you can fix that? if not, I will close.

**Comment by wpbirney** [comment]
@cr6git i can create a patch to use meminfo instead... ill post it here tonight

**Comment by wpbirney** [comment]
I made a simple patch to use the meminfo function instead and it works but displays as mandrake linux instead now. Not sure why, but will have to look into it more

**Pull request closed without merging**
