### PR TITLE
fcitx: revert using libexecinfo

### PR DESCRIPTION
**Pull request by newbluemoon**
The change to use libexecinfo in favor of patching it out seems to cause a segmentation fault, see #12585. This reverts it to use the patch again.

### CODE REVIEW

**Comment by pullmoll** [comment]
FWIW There are warnings when compiling libexecinfo for e.g. armv7l-musl:
```
stacktraverse.c:11:20: warning: unsupported argument to '__builtin_return_address'
     case 0: return __builtin_return_address(1);
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```
There are no such warnings for x86_64-musl, i686-musl or aarch64-musl, but perhaps these warnings indicate something is wrong with how libexecinfo tries to traverse the stack.

**Comment by newbluemoon** [comment]
Would you suggest to better not use libexecinfo then?

**Comment by pullmoll** [comment]
I'm not sure, but we should keep an eye on packages using libexecinfo and bug reports for *-musl.
I don't feel like trying to debug what actually was causing the segfault in fcitx.
Perhaps one of the other packages using libexecinfo is easier to test?
Currently we use it in `julia`, `telegram-desktop`, `ddcutil`, `remmina` and `varnish`, none of which I know about or use :P

**Comment by newbluemoon** [comment]
Ok, thanks. I’ll keep that in mind. :)
Trying to track this down I don’t think I can be of much help. ;)

**Pull request closed without merging**
