### PR TITLE
gnome-builder: update to 3.26.3.

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by pullmoll** [comment]
`flatpak-builder` is broken for musl. This needs to be fixed or marked as `broken=<logfile>`

**Comment by maxice8** [comment]
On Wed, Feb 07, 2018 at 09:21:56AM -0800, Jürgen Buchmüller wrote:
> `flatpak-builder` is broken for musl. This needs to be fixed or marked as `broken=<logfile>`
>

Noted, the failure is the same that flatpak has, i will just rebase the patch.

**Comment by maxice8** [comment]
also noted lots of makedepends should be in hostmakedepends.

**Comment by maxice8** [comment]
ok i updated, let's wait travis.

**Pull request closed without merging**
