### PR TITLE
Docker compose and deps

### PR DESCRIPTION
**Pull request by radare**
Cleanup commits from https://github.com/voidlinux/void-packages/pull/3258

### CODE REVIEW

**Comment by asergi** [comment]
@radare
```diff
diff --git a/srcpkgs/docker-compose/template b/srcpkgs/docker-compose/template
index f8bd9aa..5a2088a 100644
--- a/srcpkgs/docker-compose/template
+++ b/srcpkgs/docker-compose/template
@@ -1,24 +1,22 @@
 # Template file for 'docker-compose'
 pkgname=docker-compose
 version=1.5.2
-revision=4
+revision=1
 noarch=yes
 wrksrc=compose-${version}
 build_style=python-module
 hostmakedepends="python-setuptools"
-depends="python python-jsonschema python-docker-py python-dockerpty python-websocket-client python-requests python-docopt"
+depends="python-setuptools python-jsonschema python-docker-py python-dockerpty
+ python-websocket-client python-requests python-docopt python-yaml python-six
+ python-enum34 python-texttable"
 pycompile_module="compose"
 short_desc="Tool to define and run multi-container Docker applications"
 maintainer="pancake <pancake@nopcode.org>"
 homepage="https://docs.docker.com/compose/"
-license="MIT"
+license="Apache-2.0"
 distfiles="https://github.com/docker/compose/archive/${version}.tar.gz"
 checksum=8f0851b417d89bc5023e72918233449a0fa72d9952ac66494c1b37434516583d
 
 pre_build() {
        sed -i '/requests/s|, < 2.8||' setup.py
 }
-
-post_install() {
-       vlicense LICENSE
-}
```

**Comment by radare** [comment]
push -f with squashed last 3 commits

**Comment by radare** [comment]
Rebased to get python-docopt from master

**Comment by radare** [comment]
How can i rerun travis after a push -f

**Comment by Duncaen** [comment]
Should do it automatically, if the commits changed.
Try `git commit --amend` to refresh the last commit and then force push.

**Comment by asergi** [comment]
@radare https://gist.github.com/asergi/cc30dc33880a1510c8ad

**Comment by radare** [comment]
-six?

**Comment by radare** [comment]
Anyway.. i have pushed your patch (@asergi). Is there anything else to get this merged into master?

**Comment by Duncaen** [comment]
Squashing into one commit per template.

**Comment by radare** [comment]
Where's the script you use to do this boring task? Because i have already done this 3 times and its not exactly a pleasant feeling knowing that every single change i do i have to reconstruct the last 6 commits and force push

**Comment by asergi** [comment]
Merged manually.

**Comment by radare** [comment]
Thanks! But i would like to know if there are those instructions, or scripts to help packaging stuff somewhere.

**Pull request closed without merging**
