### PR TITLE
libgnomekbd: add build option 'gir'

### PR DESCRIPTION
**Pull request by pullmoll**
Also fix cross building by setting LDFLAGS to the appropriate
${XBPS_CROSS_BASE}/usr/lib

### CODE REVIEW

**Comment by beefcurtains** [comment]
I think this can be done unconditionally: ``LDFLAGS="-L${XBPS_CROSS_BASE}/usr/lib"`` and there's no ``vopt_enable`` or ``vopt_if`` in ``configure_args`` or ``hostmakedepends``. Why is that?

**Comment by pullmoll** [comment]
True, the LDFLAGS can be set unconditionally, since XBPS_CROSS_BASE is empty or undefined for non cross. I simply forgot the vopt_if.

**Comment by beefcurtains** [comment]
Sorry, didn't mean to be rude! :heart: :heart: It looks ok now.

**Comment by pullmoll** [comment]
You weren't rude but right. Thanks for auditing this change :)

**Pull request merged**
