### PR TITLE
qtox: update to 1.12.0

### PR DESCRIPTION
**Pull request by Piraty**
i patched upstream's `-Werror`, because all builds failed https://travis-ci.org/Piraty/void-packages/builds/283382488
In the patchfile I linked two issues in upstream's github, they were not ready for that yet...

### CODE REVIEW

**Comment by Piraty** [comment]
hm still unbuildable for armv7

**Comment by ebfe** [comment]
#7915

**Comment by ebfe** [comment]
please rebase

**Comment by Piraty** [comment]
done @ebfe

**Pull request merged**
