### PR TITLE
albert: update to 0.14.14.

### PR DESCRIPTION
**Pull request by cr6git**
resolves [#8598](https://github.com/voidlinux/void-packages/issues/8598). 
I know at least one person who will complain about `do_fetch()` but this is the recommended solution (see [comment-339348380](https://github.com/albertlauncher/albert/issues/555#issuecomment-339348380)).

### CODE REVIEW

**Comment by Johnnynator** [comment]
And you know the recommended way by void is smth like this :p
```
_plugins_rev="a5ee438af138d6e069384edc749d097bb0038c56"
_pybind_version=2.2.1
distfiles="${homepage}/archive/v${version}.tar.gz
 https://github.com/albertlauncher/plugins/archive/${_plugins_hash}.tar.gz
 https://github.com/pybind/pybind11/archive/v${_pybind_version}.tar.gz"
checksum="8abfa38f306e26d2419549a15fffc8d8b5b466c2e189f566c7b9e8f1e1491bdf
 f5a893f3a2c85e466dbc6ec981819f679279dba9bc2cfab7d9301f88ade6d2c6
 f8bd1509578b2a1e7407d52e6ee8afe64268909a1bbda620ca407318598927e7"

pre_configure() {
	cp -rup ${wrksrc}/../plugins-*/* ${wrksrc}/plugins
	cp -rup ${wrksrc}/../pybind11-*/* ${wrksrc}/plugins/python/pybind11
}
```

**Comment by cr6git** [comment]
> the recommended way by void

Where is it documented? Some examples?

**Comment by Johnnynator** [comment]
> Where is it documented? Some examples?

There is no documentation but tar balls have a couple of advantages, e.g. you have to fetch them only once and you can easily verify if anything has changed. Also literally everyone here will agree that tarballs should be used if possible and not git. 
Also there are only 27 packages that define their own do_fetch.

**Comment by cr6git** [comment]
ok @Johnnynator I will study the question!

**Comment by pullmoll** [comment]
Indeed @Johnnynator , common sense will tell you that when e.g. updating a pkg to a newer version one doesn't want to wait for every trial and error build to first spend minutes on git pulling the same files again and again :)

**Comment by cr6git** [comment]
@Johnnynator you made a mistake here: 
````
_plugins_rev="a5ee438af138d6e069384edc749d097bb0038c56"
${_plugins_hash}.tar.gz
````
Hence the error: 
````
https://github.com/albertlauncher/plugins/archive/.tar.gz: Not Found
=> ERROR: albert-0.14.14_1: failed to fetch .tar.gz.
````

**Comment by cr6git** [comment]
Now the second patch doesn't work: 
````
=> albert-0.14.14_1: patching: 0002_FindPythonLibsNew.cmake.patch.
The text leading up to this was:
--------------------------
|--- plugins/python/pybind11/tools/FindPythonLibsNew.cmake
|+++ plugins/python/pybind11/tools/FindPythonLibsNew.cmake
--------------------------
File to patch: 
Skip this patch? [y] 
1 out of 1 hunk ignored
=> ERROR: albert-0.14.14_1: failed to run post-extract_00-patches() at line 34.
````

If I remove this patch I can build the package for `x86_64-musl`, but it fails when cross compiling: 
````
-- Detecting CXX compile features - done
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindPythonInterp.cmake:152 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  plugins/python/pybind11/tools/FindPythonLibsNew.cmake:60 (find_package)
  plugins/python/pybind11/tools/pybind11Tools.cmake:16 (find_package)
  plugins/python/pybind11/CMakeLists.txt:33 (include)

-- Configuring incomplete, errors occurred!
See also "/builddir/albert-0.14.14/build/CMakeFiles/CMakeOutput.log".
=> ERROR: albert-0.14.14_1: failed to run do_configure() at line 36.
````
😕

**Comment by Johnnynator** [comment]
@cr6git sorry, pre_configure has to be post_extract.

**Comment by cr6git** [comment]
It's good now, thank you @Johnnynator !

**Pull request closed without merging**
