### PR TITLE
New package: gscope (GTK2)

### PR DESCRIPTION
**Pull request by cr6git**

### CODE REVIEW

**Comment by cr6git** [comment]
Failed **only** on x86_64-musl, because of an [obscure error](https://travis-ci.org/voidlinux/void-packages/jobs/266355269#L865)...

**Comment by Johnnynator** [comment]
I wouldn't call it obscure since it is actually fairly simple: The glibc has this line `sys/stat.h:# define ACCESSPERMS (S_IRWXU|S_IRWXG|S_IRWXO) /* 0777 */` and musl doesn't.

Adding a patch which defines it also in MUSL is fairly simple:

```
#ifndef ACCESSPERMS
#define ACCESSPERMS (S_IRWXU|S_IRWXG|S_IRWXO) 
#endif
```

**Comment by cr6git** [comment]
maybe "obscure" for me, but you are far more skilled than me!! 
thank you for the help @Johnnynator

**Comment by Gottox** [comment]
Hmm... Is there a reason why we need the gtk2 version of this software if we can provide gtk3?

**Comment by cr6git** [comment]
@Gottox No particular reason. I can close this one if you prefer.

**Pull request closed without merging**
