### PR TITLE
spotify: update to 1.0.31

### PR DESCRIPTION
**Pull request by teh-jazzman**

### CODE REVIEW

**Comment by ebfe** [comment]
This release randomly segfaults for me.

**Comment by teh-jazzman** [comment]
Does ist work for you at all? Do you hear sound?
I can reproduce segfaults when using alsa for sound output. There seems to be something wrong with their alsa driver. It's running stable on pulseaudio for me so far though.

Since this is closed source there is not much I can do about it. Maybe we should skip this version and hope for a fix in the next one?

**Comment by ebfe** [comment]
I don't run pulseaudio. The furthest I got was pressing the play button...

I think we should skip this release. The problem is the 0.29 .deb is
no longer available, which means currently installing spotify fails. We might want to
actually downgrade to 0.28 since the .deb for that is still available...

**Comment by teh-jazzman** [comment]
Agreed. I'll see how the next version performs, it should be around in 1-2 weeks.

**Pull request closed without merging**
