### PR TITLE
suricata: update to 4.0.0

### PR DESCRIPTION
**Pull request by Sir-Boops**

### CODE REVIEW

**Comment by Sir-Boops** [comment]
Not sure why the builder is half failing as I've built this locally on "broken" platforms and it builds fine

**Comment by ebfe** [comment]
```
=> suricata-4.0.0_1: verifying checksum for distfile 'emerging.rules.tar.gz'... 
=> ERROR: SHA256 mismatch for 'emerging.rules.tar.gz:'
```

**Comment by Sir-Boops** [comment]
Fixed

**Comment by ebfe** [comment]
3654da8f7419d60daac6543bd90ed4911648d434

**Pull request closed without merging**
