### PR TITLE
libmilter/opendkim: enable ipv6

### PR DESCRIPTION
**Pull request by jprjr**

### CODE REVIEW

**Comment by cr6void** [comment]
Hi @jprjr !

I am looking at your build of opendkim on Travis CI ...

The [first job](https://travis-ci.org/voidlinux/void-packages/jobs/214641396) failed because of:

`srcpkgs/opendkim/template:22: short_desc should not start with whitespace`

Why ??
The template seems to be correct: `short_desc="DKIM library"`

And the [second job](https://travis-ci.org/voidlinux/void-packages/jobs/214641397) failed because of:

`ftp://ftp.sendmail.org/pub/sendmail/sendmail.8.15.2.tar.gz: Connection timed out`
`=> ERROR: libmilter-1.0.2_3: failed to fetch sendmail.8.15.2.tar.gz.`

However I can download this tarball manually.
This is weird... :(

**Comment by mvf** [comment]
> The first job failed because of:
srcpkgs/opendkim/template:22: short_desc should not start with whitespace
Why ??

I guess because line 22 sets `short_desc` for `opendkim-devel` like this:
`short_desc=" - development files"`
Should be:
`short_desc+=" - development files"`

**Comment by cr6void** [comment]
@mvf True! Sorry, yesterday I hadn't noticed `short_desc=" - development files"` in the template...

**Comment by jprjr** [comment]
Sorry about that! Fixed + rebased + pushed

**Comment by cr6void** [comment]
I can download `sendmail.8.15.2.tar.gz` manually on the [ftp stite](ftp://ftp.sendmail.org/pub/sendmail/) with **firefox**.

On the contrary, when I try to download the tarball manually with **wget** I get this **error**:

`$ wget ftp://ftp.sendmail.org/pub/sendmail/sendmail.8.15.2.tar.gz
--2017-03-26 12:35:12--  ftp://ftp.sendmail.org/pub/sendmail/sendmail.8.15.2.tar.gz
           => « sendmail.8.15.2.tar.gz.1 »
Résolution de ftp.sendmail.org… 50.19.116.123, 2600:1f18:677f:2e00::112
Connexion à ftp.sendmail.org|50.19.116.123|:21… connecté.
Ouverture de session en tant que anonymous… Session établie.
==> SYST ... terminé.    ==> PWD ... terminé.
==> TYPE I ... terminé.  ==> CWD (1) /pub/sendmail ... terminé.
==> SIZE sendmail.8.15.2.tar.gz ... 2207417
==> PASV ... impossible d'établir la connexion à 10.95.0.112 sur le port 61067 : Aucun chemin d'accès pour atteindre l'hôte cible`

**Comment by cr6void** [comment]
@jprjr Today I made a test and it worked very well with this mirror:

`ftp://ftp.mirrorservice.org/sites/ftp.sendmail.org/pub/sendmail/sendmail.8.15.2.tar.gz`

**Comment by jprjr** [comment]
@cr6void nice!! Just pushed up an update that uses ftp.mirrorservice.org

**Pull request merged**
