### PR TITLE
New package: sc3-plugins-3.8.0

### PR DESCRIPTION
**Pull request by jarbowski**
Extension plugins for the SuperCollider3 audio synthesis server.

Sorry for the double pr

### CODE REVIEW

**Comment by Vaelatern** [comment]
Stop closing PRs without need.
There was no need.

**Comment by jarbowski** [comment]
I don't see anything obvious, would it be enough to add x86_64-musl=broken?

**Comment by jarbowski** [comment]
@Vaelatern 
since supercollider didn't build neither on musl, what do you recommend?

**Comment by jarbowski** [comment]
@thypon 
since supercollider didn't build neither on musl, what do you recommend?

**Comment by thypon** [comment]
`only_for_archs` should be enough

**Comment by jarbowski** [comment]
@thypon 
ok, thank you

**Comment by the-maldridge** [comment]
@Vaelatern @thypon Are you satisfied with this package?

**Comment by thypon** [comment]
Not until it contains an update file. The custom `do_fetch` breaks the `update-check`.

I already started a review.

**Comment by jarbowski** [comment]
@thypon 
searching a solution to make an update file, I found that the libpurple-telegram package which is similar to this one, doesn't contain any update file.
so, is it necessary and how can I resolve this?

**Comment by thypon** [comment]
https://github.com/voidlinux/void-packages/blob/master/srcpkgs/urbanterror/update something like this should work.

**Comment by jarbowski** [comment]
@thypon 
Is it okay now, can I rebase and propose it?

**Comment by thypon** [comment]
It is ok for me.

**Comment by thypon** [comment]
rebase and I merge

**Pull request closed without merging**
