### PR TITLE
New package: unison-2.48.3

### PR DESCRIPTION
**Pull request by allan**

### CODE REVIEW

**Comment by xtraeme** [comment]
- Please use the common style for templates
- If it's a binary generated by ocaml it should not be stripped (nostrip=yes)

**Comment by allan** [comment]
* The packaging guidelines of our favorite distribution `Fedora` say that OCaml binaries should be striped.
 * What is not common in this template, is it `CFLAGS= make...`?

**Comment by xtraeme** [comment]
- I don't remember exactly but I think ocaml binaries did not work if they were stripped, that info could be outdated. If you've verified it behaves correctly I'll trust you.
- What I mean is `func() { ... }` rather than:

```
do_build() {
 ...
}
```

**Comment by xtraeme** [comment]
no manual page?

**Comment by allan** [comment]
here you go.  There has been some issues in the past where compiled with `ocaml -custom` which could not be stripped.
No man page.  The doc is built into the binary. Something like `unison -doc tutorial` and stuff.

**Comment by xtraeme** [comment]
Perfect, thanks.

**Pull request merged**
