### PR TITLE
New package: fortune-mod-void-001

### PR DESCRIPTION
**Pull request by tonkazoid**

### CODE REVIEW

**Comment by chneukirchen** [comment]
Looks ok, but better use YYYYMMDD as version number.

**Comment by chneukirchen** [comment]
Applied.

**Comment by tonkazoid** [comment]
i dont' know where it got wrong, but `hostmakedepends` should be `makedepends`, no?

https://github.com/voidlinux/void-packages/blob/d9cc272634fcb9c3dcca5f9357c1e9a0b82a5dbe/srcpkgs/fortune-mod-void/template
https://github.com/voidlinux/void-packages/blob/master/srcpkgs/fortune-mod-void/template

**Comment by chneukirchen** [comment]
No. I fixed that when applying.

**Comment by tonkazoid** [comment]
And xtraeme fixed 'depends' :P. I still mix up makedepends with
hostmakedepends sometimes.

**Pull request closed without merging**
