### PR TITLE
octoxbps: don't use --force

### PR DESCRIPTION
**Pull request by Piraty**
As it has already been discussed a few times, this is a dangerous flag to have in a package managing too, especially if user's may not be aware of it.
Whover wants to --force on his xbps-system, should do that on the terminal.

### CODE REVIEW

**Comment by Duncaen** [comment]
What about fixing it upstream?

**Comment by Piraty** [comment]
I have a PR with the same patch, until that makes it into the project eventually, void could use this patch.

**Comment by Vaelatern** [comment]
Link the patch file to the upstream pull request (as in, link to the PR for upstream) and I think this is mergable.

**Comment by Piraty** [comment]
done

**Comment by the-maldridge** [comment]
@Vaelatern is this merge-able even with the broken cross issues?

**Comment by Vaelatern** [comment]
Yes. It never cross built.

**Comment by ebfe** [comment]
just ftr: ujpstream disagrees with this patch.

**Pull request merged**
