### PR TITLE
New package: subtle-contrib-125

### PR DESCRIPTION
**Pull request by thypon**

### CODE REVIEW

**Comment by thypon** [comment]
Broken :-(

**Comment by pullmoll** [comment]
You need to either disable -Werror or change the `#include <sys/poll.h>` to `#include <poll.h>`. The latter can be unconditionally, i.e. works with glibc as well.

**Comment by thypon** [comment]
It's subtle and not subtle-contrib that fails. Testing subtle-contrib i found some bug in the scripts from `subtle-contrib`.

**Comment by pullmoll** [comment]
Ah, ok, got you wrong then.. sorry :)

**Pull request closed without merging**
