### PR TITLE
New package: discord-canary-0.0.31

### PR DESCRIPTION
**Pull request by gingyr**

### CODE REVIEW

**Comment by Vaelatern** [comment]
How is this diferent from `discord`?

**Comment by gingyr** [comment]
Discord Canary is Discord's alpha testing program that receives updates before PTB, which receives updates before Stable.

**Comment by Vaelatern** [comment]
We do not generally merge alpha quality software.

**Comment by Coding-Doctors** [comment]
Discord prefers that regular users don't use canary as it is prone to breakages. If any "testing version" of Discord would be considered, ptb would be it. This is best left as discord prefers, where users who are intrested go out and grab it themselfs, rather than being overly public about it. 
**Canary isn't intended as a general consumer program.**

**Comment by gingyr** [comment]
Understandable. I will close this PR.

**Pull request closed without merging**
