### PR TITLE
build-style/cmake.sh: fix default do_check

### PR DESCRIPTION
**Pull request by Chocimier**

### CODE REVIEW

**Comment by Vaelatern** [comment]
example of it being broken?

**Comment by Chocimier** [comment]
evolution, any kde package

**Comment by maxice8** [comment]
are packages that have working tests (like cmake itself) keep working ?

**Comment by Chocimier** [comment]
Tests for cmake still run. Are there other packages that should be tested for regression?

**Comment by ebfe** [comment]
Looks right to me

**Pull request merged**
