### PR TITLE
qtikz: change qt version to qt5

### PR DESCRIPTION
**Pull request by Johnnynator**
@Piraty #12152

### CODE REVIEW

**Comment by Piraty** [comment]
looks good, except broken theming...

**Comment by Piraty** [comment]
you could bump to 0.12 while at it

**Comment by ebfe** [comment]
@Piraty good to merge?

**Comment by Piraty** [comment]
@ebfe sure.
Theming was my own issue only (need to use `QT_STYLE_OVERRIDE=gtk2` or sth similar for correct theming to apply)

**Pull request merged**
