### PR TITLE
Update yarn{,-bin} to 1.1.0

### PR DESCRIPTION
**Pull request by the-eater**

### CODE REVIEW

**Comment by Vaelatern** [comment]
Is there a reason we keep the `-bin` package around?

**Comment by the-eater** [comment]
@Vaelatern https://github.com/voidlinux/void-packages/pull/6949#issue-240273378

I vote for keeping it in tho, otherwise it would break building the repo from scratch

**Comment by Vaelatern** [comment]
Then perhaps we should have a bootstrap build option that defaults to off, which makes us want `yarn-bin` instead of `yarn`.

**Comment by the-eater** [comment]
We may be able to use that also for `go` I imagine?

**Comment by the-maldridge** [comment]
@Vaelatern bootstrap should be simple, I'm fine with having both normal and bin, and there are cases where it may be preferable to use -bin.

**Pull request merged**
