### PR TITLE
bitlbee: add libpurple

### PR DESCRIPTION
**Pull request by the-eater**
This will add libpurple support and also fix the building of bitlbee with openssl

### CODE REVIEW

**Comment by thypon** [comment]
Maybe a disabled option is better in this case.

**Comment by the-eater** [comment]
for what?

**Comment by thypon** [comment]
`libpurple` was disabled on purpose by `bitlbee` developers. 

This is what they say about the `libpurple` support the developers and one of the reason it is disabled by default.

> The downside is it adds a lot of dependencies (on most Debian systems it means installing around 100MBytes of extra packages), and it makes the program more resource-hungry at runtime. Also, its huge codebase may have more stability/scalability issues when running on large installations.

**Comment by the-maldridge** [comment]
nomerge until a default-off build option is in place.

libpurple's questionable support for protocols is infamous.

**Comment by jcjordyn130** [comment]
Would a subpackage be any better?

**Comment by Gottox** [comment]
Not possible with bitlbee. I'm in favor of adding it as build option with default off.

**Pull request closed without merging**
