### PR TITLE
Desystemd

### PR DESCRIPTION
**Pull request by Gottox**
Please recheck my commits, I did them half asleep :sleeping:

### CODE REVIEW

**Comment by pullmoll** [comment]
I think in some packages there are systemd service files left in `${FILESDIR}` which could be removed.

**Comment by Gottox** [comment]
Should be fixed now.

**Comment by pullmoll** [comment]
Looks :ok: for me.

**Comment by xtraeme** [comment]
`rm -rf systemd` has been 100% completed, thanks.

**Pull request closed without merging**
