### PR TITLE
opencv: update to 3.3.0

### PR DESCRIPTION
**Pull request by juliendehos**
- update to opencv-3.3.0 (https://github.com/opencv/opencv/releases/tag/3.3.0)
- add python3 support
- enable cross build (without python support, because of numpy)

### CODE REVIEW

**Comment by Gottox** [comment]
The dependants of opencv need to be bumped if the soname changes.

**Comment by juliendehos** [comment]
Ok. Fixed.

**Comment by Duncaen** [comment]
Please make a separate commit for each bumped template.

**Comment by juliendehos** [comment]
Done

**Comment by Duncaen** [comment]
Please use the commit message scheme described in [CONTRIBUTING.md](https://github.com/voidlinux/void-packages/blob/master/CONTRIBUTING.md#committing-your-changes).
`$pkgname: bump for opencv-3.3.0`.

**Comment by juliendehos** [comment]
Fixed.

**Pull request closed without merging**
