### PR TITLE
geis: fix cross compilation

### PR DESCRIPTION
**Pull request by cr6git**
To help [#10614](https://github.com/voidlinux/void-packages/pull/10614).

### CODE REVIEW

**Comment by cr6git** [comment]
Travis is doing weird things. 😕

**Comment by newbluemoon** [comment]
I’m not sure if it’s a good idea to set `CFLAGS="-Wno-error"`. There is a debian [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=853415) which addresses the issue which I think you’re trying to work around. ;) And they have a patch:

```
From: Khem Raj <raj.khem@gmail.com>
Date: Mon, 24 Apr 2017 12:34:55 -0700
X-Dgit-Generated: 2.2.17-1.2 32cf7d865222f63ba5da5f79d340acf895ff9379
Subject: libgeis: Compare the first character of string to null

gcc7 wants to be specific when it comes to comparing characters
and strings

fixes

| ../../../../../../../workspace/sources/geis/libgeis/geis_v1.c: In function '_v1_subscribe_device':
| ../../../../../../../workspace/sources/geis/libgeis/geis_v1.c:613:20: error: comparison between pointer and zero character constant [-Werror=pointer-compare]

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Bug-Debian: https://bugs.debian.org/853415

---

--- libgeis/geis_v1.c
+++ libgeis/geis_v1.c
@@ -610,7 +610,7 @@ _v1_subscribe_device(GeisInstance instan
                      const char **gesture_list)
 {
   GeisStatus result = GEIS_UNKNOWN_ERROR;
-  if (gesture_list == GEIS_ALL_GESTURES)
+  if (gesture_list[0][0] == GEIS_ALL_GESTURES)
   {
     geis_debug("subscribing device %d for all gestures", device_id);
   }
@@ -757,7 +757,7 @@ geis_unsubscribe(GeisInstance     instan
                  GeisGestureType *gesture_list)
 {
   GeisStatus status = GEIS_STATUS_NOT_SUPPORTED;
-  if (gesture_list == GEIS_ALL_GESTURES)
+  if (gesture_list[0] == GEIS_ALL_GESTURES)
   {
     status = geis_subscription_deactivate(instance->subscription);
   }
```

**Comment by cr6git** [comment]
> I’m not sure if it’s a good idea to set CFLAGS="-Wno-error".

This is not ideal, I understand.
For information, I found this trick [here](https://aur.archlinux.org/cgit/aur.git/commit/?h=geis&id=5af50821af0d1c36e10b71b629e88ccb39dc99f4)...

I will try your solution instead! 😉

**Comment by cr6git** [comment]
Hurray! 😃

**Pull request closed without merging**
