### PR TITLE
kdeconnect: update to 1.3.

### PR DESCRIPTION
**Pull request by Johnnynator**

### CODE REVIEW

**Comment by maxice8** [comment]
Seems like travis crapped out

**Comment by Johnnynator** [comment]
Looks more like it was some problems with the mirror.

**Comment by maxice8** [comment]
On Thu, May 24, 2018 at 03:08:50AM -0700, John Zimmermann wrote:
> Looks more like it was some problems with the mirror.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/voidlinux/void-packages/pull/14672#issuecomment-391661427

either way let's see if it works out now.

**Comment by Johnnynator** [comment]
Nope still fails to fetch the deps.

**Pull request merged**
