### PR TITLE
nfs-utils: patch to add missing include of stdint.h

### PR DESCRIPTION
**Pull request by lonwillett**
@xtraeme 

Trivial fix, but needed to build.

### CODE REVIEW

**Comment by Vaelatern** [comment]
needs revbump at least.

**Comment by Vaelatern** [comment]
and please use the real commit msgs.

**Comment by lonwillett** [comment]
@Vaelatern 

Do you really want a revision bump? In theory, this change shouldn't result in an observably different package than one that compiled with headers that pulled in the missing include behind the scenes.

In actuality, I think there have been changes in the system environment that do result in a different package, or there have been changes to the package that should have had a revision bump but didn't. At any rate, that is a different issue than the one addressed here. I'll defer to your opinion, and add the bump, but let me know if you change your mind and want it retracted, or done as a separate commit.

**Comment by Vaelatern** [comment]
hm, where is it needed to build? It built for the x86_64-glibc repo at least...

**Comment by lonwillett** [comment]
It's missing for aarch64-musl, which I was just trying out. Of course, its nice to be able to rebuild packages anyway.

**Comment by the-maldridge** [comment]
@lonwillett merged as written but please try to get this upstreamed.

**Pull request closed without merging**
