### PR TITLE
arduino: update to 1.8.3

### PR DESCRIPTION
**Pull request by liwakura**

### CODE REVIEW

**Comment by liwakura** [comment]
When running the IDE, sketches cant be compiled.

```
Arduino: 1.8.3 (Linux), Board: "Arduino Nano, ATmega328"

/usr/lib/arduino/arduino-builder -dump-prefs -logger=machine -hardware /usr/lib/arduino/hardware -tools /usr/lib/arduino/tools-builder -built-in-libraries /usr/lib/arduino/libraries -libraries /home/nero/Arduino/libraries -fqbn=arduino:avr:nano:cpu=atmega328 -ide-version=10803 -build-path /tmp/arduino_build_797217 -warnings=none -build-cache /tmp/arduino_cache_362518 -prefs=build.warn_data_percentage=75 -verbose /usr/lib/arduino/examples/01.Basics/Blink/Blink.ino
/usr/lib/arduino/arduino-builder -compile -logger=machine -hardware /usr/lib/arduino/hardware -tools /usr/lib/arduino/tools-builder -built-in-libraries /usr/lib/arduino/libraries -libraries /home/nero/Arduino/libraries -fqbn=arduino:avr:nano:cpu=atmega328 -ide-version=10803 -build-path /tmp/arduino_build_797217 -warnings=none -build-cache /tmp/arduino_cache_362518 -prefs=build.warn_data_percentage=75 -verbose /usr/lib/arduino/examples/01.Basics/Blink/Blink.ino
Using board 'nano' from platform in folder: /usr/lib/arduino/hardware/arduino/avr
Using core 'arduino' from platform in folder: /usr/lib/arduino/hardware/arduino/avr
Detecting libraries used...
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10803 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR   "-I/usr/lib/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/lib/arduino/hardware/arduino/avr/variants/eightanaloginputs" "/tmp/arduino_build_797217/sketch/Blink.ino.cpp" -o "/dev/null"
Generating function prototypes...
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10803 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR   "-I/usr/lib/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/lib/arduino/hardware/arduino/avr/variants/eightanaloginputs" "/tmp/arduino_build_797217/sketch/Blink.ino.cpp" -o "/tmp/arduino_build_797217/preproc/ctags_target_for_gcc_minus_e.cpp"
"/usr/lib/arduino/tools-builder/ctags/5.8-arduino11/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "/tmp/arduino_build_797217/preproc/ctags_target_for_gcc_minus_e.cpp"
Compiling sketch...
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10803 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR   "-I/usr/lib/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/lib/arduino/hardware/arduino/avr/variants/eightanaloginputs" "/tmp/arduino_build_797217/sketch/Blink.ino.cpp" -o "/tmp/arduino_build_797217/sketch/Blink.ino.cpp.o"
Compiling libraries...
Compiling core...
Using previously compiled file: /tmp/arduino_build_797217/core/wiring_pulse.S.o
Using previously compiled file: /tmp/arduino_build_797217/core/WInterrupts.c.o
Using previously compiled file: /tmp/arduino_build_797217/core/hooks.c.o
Using previously compiled file: /tmp/arduino_build_797217/core/wiring.c.o
Using previously compiled file: /tmp/arduino_build_797217/core/wiring_analog.c.o
Using previously compiled file: /tmp/arduino_build_797217/core/wiring_digital.c.o
Using previously compiled file: /tmp/arduino_build_797217/core/wiring_pulse.c.o
Using previously compiled file: /tmp/arduino_build_797217/core/wiring_shift.c.o
Using previously compiled file: /tmp/arduino_build_797217/core/CDC.cpp.o
Using previously compiled file: /tmp/arduino_build_797217/core/HardwareSerial.cpp.o
Using previously compiled file: /tmp/arduino_build_797217/core/HardwareSerial0.cpp.o
Using previously compiled file: /tmp/arduino_build_797217/core/HardwareSerial1.cpp.o
Using previously compiled file: /tmp/arduino_build_797217/core/HardwareSerial2.cpp.o
Using previously compiled file: /tmp/arduino_build_797217/core/HardwareSerial3.cpp.o
Using previously compiled file: /tmp/arduino_build_797217/core/IPAddress.cpp.o
Using previously compiled file: /tmp/arduino_build_797217/core/PluggableUSB.cpp.o
Using previously compiled file: /tmp/arduino_build_797217/core/Print.cpp.o
Using previously compiled file: /tmp/arduino_build_797217/core/Stream.cpp.o
Using previously compiled file: /tmp/arduino_build_797217/core/Tone.cpp.o
Using previously compiled file: /tmp/arduino_build_797217/core/USBCore.cpp.o
Using previously compiled file: /tmp/arduino_build_797217/core/WMath.cpp.o
Using previously compiled file: /tmp/arduino_build_797217/core/WString.cpp.o
Using previously compiled file: /tmp/arduino_build_797217/core/abi.cpp.o
Using previously compiled file: /tmp/arduino_build_797217/core/main.cpp.o
Using previously compiled file: /tmp/arduino_build_797217/core/new.cpp.o
"/usr/bin/avr-gcc-ar" rcs  "/tmp/arduino_build_797217/core/core.a" "/tmp/arduino_build_797217/core/wiring_pulse.S.o"
signal: segmentation fault
Error compiling for board Arduino Nano.
```

avr-gcc-ar segfaults after #6849

**Comment by the-maldridge** [comment]
I'm a fan of dropping the arduino package.  In the 3 years I've been using Void it has worked once that I've tried it.  The Arduino foundation has a very serviceable webapp to compile and for serious developers, the avr-gcc toolchain works reliably with makefiles.

**Comment by liwakura** [comment]
The problem was caused by `avr-gcc` after the 7.1.0 update. Arduino itself works fine the the  6.3.0_1 version.

**Comment by the-maldridge** [comment]
I guess I'm just struggling to see the relevance of a very buggy local IDE.  What value does the environment provide if it can't actually compile the programs you write in it?

**Comment by liwakura** [comment]
@the-maldridge you can compile it, just not with the avr-gcc 7.1.0. The brokenness is not specific to arduino and caused by gcc itself. Without updating avr-gcc, arduino works fine

**Pull request closed without merging**
