### PR TITLE
New package: kitty-0.7.1

### PR DESCRIPTION
**Pull request by tim241**

### CODE REVIEW

**Comment by tim241** [comment]
It builds on my own pc, but whenever I try it here, Travis CI fails with
```
Linking kitty/glfw-wayland ...
Traceback (most recent call last):
  File "setup.py", line 673, in <module>
    main()
  File "setup.py", line 657, in main
    package(args)
  File "setup.py", line 501, in package
    compileall.compile_dir(ddir, quiet=1, workers=4)
  File "/usr/lib/python3.6/compileall.py", line 79, in compile_dir
    with ProcessPoolExecutor(max_workers=workers) as executor:
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 402, in __init__
    EXTRA_QUEUED_CALLS)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 102, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/usr/lib/python3.6/multiprocessing/context.py", line 67, in Lock
    return Lock(ctx=self.get_context())
  File "/usr/lib/python3.6/multiprocessing/synchronize.py", line 163, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/usr/lib/python3.6/multiprocessing/synchronize.py", line 60, in __init__
    unlink_now)
PermissionError: [Errno 13] Permission denied
=> ERROR: kitty-0.7.1_1: failed to run do_install() at line 17.
```

**Comment by Vaelatern** [comment]
#6585 - Is this at all related?

**Comment by tim241** [comment]
@Vaelatern it is, sorry!

**Comment by Vaelatern** [comment]
By all means adopt that work... that PR seems abandoned.

**Pull request closed without merging**
