### PR TITLE
gcc: update to gcc-6.2.1

### PR DESCRIPTION
**Pull request by pullmoll**
Review is required.

Meanwhile testing the (new) bootstrap.

### CODE REVIEW

**Comment by Gottox** [comment]
Is the list of failing packages in https://github.com/voidlinux/void-packages/issues/4825 up to date?

**Comment by pullmoll** [comment]
Yep,  the list was created with the 2nd update I tried.

**Comment by pullmoll** [comment]
Oops: The patches for gcc6 fail here with the latest.

**Comment by pullmoll** [comment]
It looks as if this patch is already included in macro.c, so we just can remove the patch.

**Comment by pullmoll** [comment]
More failures when bootstrapping this one. There's a problem with `libatomic` now.
Investigating.

**Comment by Gottox** [comment]
This is todays snapshot release.

**Comment by pullmoll** [comment]
Obviously upstream is adding fixes and changes, so we need to cope with it. Most or all of them will be in the official release anyway. You or anyone else could test the bootstrap with this one as well and see what needs to be fixed.

**Comment by pullmoll** [comment]
Reverting to an earlier snapshpt? Hm, I'd rather move on forward to the release version.
I don't expect complicated fixes to be required now, but just minor things.

The libatomic failure may be just a missing configure option.

**Comment by pullmoll** [comment]
Here's the current problem with libatomic:
http://misc.voidlinux.de/gcc-6.2.1-build.txt

**Comment by pullmoll** [comment]
Haha.. now I got it. You checked out the latest gcc-7.0.0 branch, not gcc6!

**Comment by Gottox** [comment]
argh! let me fix.

**Comment by pullmoll** [comment]
Darn. Then I need to restore all the `libcpp-source_date_epoch.patch` stuff, but of course I force pushed the changes :(

**Comment by pullmoll** [comment]
Let's drop this one and try again later.

**Pull request closed without merging**
