### PR TITLE
alarm-clock: update to 1.4.9

### PR DESCRIPTION
**Pull request by cr6git**
Added `depends="dbus"` , because of this error: 
````
$ alarm-clock

** (alarm-clock:8912): WARNING **: Unable to open a connection to the session bus: Erreur lors de la génération de la ligne de commande « dbus-launch --autolaunch=1d55b7ac8795bb3bbdafc2fd59ce60d5 --binary-syntax --close-stderr » : Le processus fils s’est terminé avec le code 1

(alarm-clock:8912): GLib-GIO-CRITICAL **: g_dbus_connection_call_sync_internal: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
Erreur de segmentation
````

### CODE REVIEW

**Comment by liwakura** [comment]
It still throws `(alarm-clock:3827): GLib-CRITICAL **: g_file_set_contents: assertion 'contents != NULL || length == 0' failed` for me, but builds and runs fine otherwise.

**Comment by cr6git** [comment]
Nevertheless, the dbus dependency is a little annoying... 😕

**Comment by xtraeme** [comment]
Did you try with `depends="dbus-libs"` instead?

**Comment by cr6git** [comment]
Yes, but `depends="dbus-libs"` is not enough.

**Comment by cr6git** [comment]
No merge? I close.

**Pull request closed without merging**
