### PR TITLE
openimageio: update to 1.6.13.

### PR DESCRIPTION
**Pull request by lemmi**

### CODE REVIEW

**Comment by Vaelatern** [comment]
Chances are really good (have not built to test) that `openimageio-1.6.13` will need to revbump the dependencies on the current SONAME, `libOpenImageIO.so.1.6.12` and `libOpenImageIO_Util.so.1.6.12` and change the `common/shlibs` line.

**Comment by Vaelatern** [comment]
https://gist.github.com/f7a47fe0584305659e752f5583f86029 are the packages that depend on one of those sonames

**Comment by Vaelatern** [comment]
No, no revbumps necessary.

**Comment by lemmi** [comment]
Yeah, this is only a patch-level update. But to confirm it, blender still runs with the updates version.

**Pull request merged**
