### PR TITLE
New package: seafile-client-qt

### PR DESCRIPTION
**Pull request by yopito**
https://www.seafile.com/ is an "Open Source Cloud Storage for your teams and organizations", including the ability to create your own private storage.

include packaging for libsearpc, ccnet, seafile-libclient.

### CODE REVIEW

**Comment by yopito** [comment]
Hello,

Travis CI fails with this pull request, but this is related to a particular case, not from my packaging.
And my private cross-compiling is fine with ARCH=armv7hf and BOOSTRAP=x86_64.

The particular case is this pull request introduces several packages in the same commit, they are dependencies between these packages (both at target and host level) , and one of them is "noarch".

Here some logs to illustrate: Excerpt of Job #3396.4 : ARCH=armv6hf BOOTSTRAP=x86_64
(https://travis-ci.org/voidlinux/void-packages/jobs/82787419)

```
493 => Installing armv6hf cross pkg: cross-vpkg-dummy ...
494 => libsearpc-1.2.2.20140814_1: removing autodeps, please wait...
495 => libsearpc-1.2.2.20140814_1: removing autocrossdeps, please wait...
496 => libsearpc-1.2.2.20140814_1: building ...

808 => Registering libsearpc-devel-codegen-1.2.2.20140814_1.noarch.xbps into /host/binpkgs ...
814 => Registering libsearpc-devel-1.2.2.20140814_1.armv6l.xbps into /host/binpkgs ...
820 => Registering libsearpc-1.2.2.20140814_1.armv6l.xbps into /host/binpkgs ...

839 => ccnet-4.4.0_1: building ...
840   [host] automake-1.15_4: found (http://repo.voidlinux.eu/current)
841   [host] libtool-2.4.2_13: found (http://repo.voidlinux.eu/current)
842   [host] pkg-config-0.29_1: found (http://repo.voidlinux.eu/current)
843   [host] python-2.7.10_7: found (http://repo.voidlinux.eu/current)
844   [host] vala-0.30.0_1: found (http://repo.voidlinux.eu/current)
845   [host] libsearpc-devel-codegen-1.2.2.20140814_1: not found.
846   [target] glib-devel-2.46.0_1: found (http://repo.voidlinux.eu/current)
847   [target] sqlite-devel-3.8.11.1_3: found (http://repo.voidlinux.eu/current)
848   [target] libressl-devel-2.2.3_1: found (http://repo.voidlinux.eu/current)
849   [target] libevent-devel-2.0.22_5: found (http://repo.voidlinux.eu/current)
850   [target] libuuid-devel-2.27_1: found (http://repo.voidlinux.eu/current)
851   [target] libsearpc-devel-1.2.2.20140814_1: found (/host/binpkgs)
852 => libsearpc-1.2.2.20140814_1: building (dependency of ccnet) ...
```

So: rebuilding a 2nd time libsearpc (line 852) for ARCH=x86_64 because package `libsearpc-devel-codegen` (noarch) has not been found for the bootstrap host (x86_64), even if already built and present in `/host/binpkgs/` (line 808).

It just a little waste of resources, but the most important is that now `libsearpc` has to be rebuild on native architecture (x86_64) since `libsearpc-devel-codegen` is missing.

And for some reason, building `libsearpc` natively fails because GLIB has not been found .. I suspect that the travis CI env a little bit constrained, and has been designed for cross-compiling only, not native build ?

Please also notice that the Travis CI native building on x86_64 of `libsearpc*` packages is fine.

What do you think about it ?

**Comment by pullmoll** [comment]
Perhaps try to add `glib-devel` to the `hostmakedepends` in libsearpc to fix cross builds? There  may checks for the `/usr/bin/glib-*` binaries in the configure script. I haven't looked into it, but we have had such cases where `glib-devel` was required for the host, too.

**Comment by yopito** [comment]
Hello,
Thanks for the hints.
I've tried several attempts with `glib-devel` and `libglib-devel` in `(host)makedepends`, but none of them is working fine for cross-building with Travis-CI ...
To summarize:
* all packages (including `libsearpc*` ones) built fine for x86_64 and i686 without cross-build (not arm*), both with glibc and musl as libc
* on cross-build (like for target `armv7hf`):
  * `libsearpc*.armv7hf` packages built nicely,
  * `ccnet*.armv7hf` fails to build because it requires `libsearpc*.x86_64` packages (in `hostmakedepends`): the cross-build had to rebuild packages `libsearpc*.x86_64` (yes x86_64). It tries to but fails, contrary to native building ?!

Of course, I can't reproduce its behaviour on my personal systems: cross-build for armv7hf from scratch is fine.

Travis-CI in this particular context is driving me nuts ... 
Would you please consider to merge this pull request anyway ?
I afraid I won't be able to fix Travis CI for them. For me, this problem is specific to Travis-CI,I can't try to figure out what's happening and possibly fix it without shell acces in one of its build system.

Thanks - Pierre

**Comment by yopito** [comment]
possible workaround : one PR for `libsearpc`, wait for inclusion (and binary packages availability), then 2nd PR for the other packages ?

**Pull request closed without merging**
