### PR TITLE
wvstreams: add musl support

### PR DESCRIPTION
**Pull request by uriah0**
I'm pretty sure that some of these patches are inadequate, but it builds, so I'd like to know how I can make them better please. Thanks.

### CODE REVIEW

**Comment by pullmoll** [comment]
I think `xplc/modulemgr.cc` should unconditionally `#include <limits.h>` which defines `PATH_MAX`. This should work with glibc also.

The execinfo.h / backtrace() patches look ok to me, especially since they rely on `HAVE_EXECINFO_H`.

Not sure about the getcontext(3) and setcontext(3) hackery, which seems to disable everything context related. There is an include file `/usr/include/ucontext.h` in musl libc. Did you try to explicitly include it in `utils/wvtask.cc`? As long as the internals of `struct __ucontext` are not touched - which is always a bad idea and doesn't seem to be the case - including ucontext.h might be sufficient.

**Comment by uriah0** [comment]
Thanks, I'll try #include <limits.h> for PATH_MAX.

As for ucontext.h, I did try to include it, to no avail. I still got the same errors about getcontext/setcontext being undefined. I read somewhere (probably here: https://github.com/9fans/plan9port/issues/36 ) that those functions aren't actually implemented, which is why I did what I did. Any thoughts?

**Comment by pullmoll** [comment]
I didn't know the function declarations are not implemented anywhere. The discussion you linked to talks about implementing the functions should be easy, so perhaps we can conceive a `musl-context` package, like I did in similar cases `musl-fts` and `musl-obstack`.

For now I think disabling the context stuff should be ok. I of course have no idea on the impact of this on the application itself.

**Comment by uriah0** [comment]
pullmoll, made the suggested change to xplc/modulemgr.cc, it succeeds on all tests.

**Comment by pullmoll** [comment]
:+1:

**Pull request merged**
