### PR TITLE
New package: minetest-game-0.4.16

### PR DESCRIPTION
**Pull request by jcjordyn130**

### CODE REVIEW

**Comment by Vaelatern** [comment]
Please look before you package. That said, your template should have looked more like the pre-existing template.

**Comment by Vaelatern** [comment]
I should read more carefully. But is there any reason for this to be a package?

**Comment by jcjordyn130** [comment]
@Vaelatern The only thing included with minetest by default is the minimum development test, and iirc minetest only reads games from it's prefix.

**Comment by Vaelatern** [comment]
Then this PR should actually be a minetest package that also downloads minetest_game in the distfiles, and installs minetest_game in a `post_install`

**Comment by jcjordyn130** [comment]
Oh yeah, I thought about that.

**Comment by jcjordyn130** [comment]
Closing issue as this commit should be in minetest and not a new package.

**Pull request closed without merging**
