### PR TITLE
openssh: enable kerberos5 support

### PR DESCRIPTION
**Pull request by the-maldridge**

### CODE REVIEW

**Comment by Gottox** [comment]
Do we want kerberos in base? cc @voidlinux/pkg-committers

**Comment by the-maldridge** [comment]
From conversations with @bougyman there is desire to manage the servers a bit better than "here are some servers".  Adding kerberos into ssh is one of the technologies that would make that substantially easier, though I suppose we could do a custom build with a vopt for void infrastructure if it is deemed too heavy for base.

Seems kind of silly though that void infrastructure wouldn't be using mainline void packages though.

**Comment by Vaelatern** [comment]
It's about 10 megabtytes for mit-krb5 + dependencies, so it's not oppressive. It would not be useful to a live CD, but it would be nice to have it present in a package for a developer who wants to change login methods.

I support it so long as it's a build option.

**Comment by Gottox** [comment]
We could switch from openssh to dropbear in base.

**Comment by chneukirchen** [comment]
Please keep openssh in base.

These issues are mainly build issues, not that base-system is too big.

**Comment by Vaelatern** [comment]
Against dropbear in base.

**Comment by the-maldridge** [comment]
I also am weary of anything that isn't openssh.  The others just don't feel "battle tested" enough.

**Pull request closed without merging**
