### PR TITLE
font-symbola: set nonfree

### PR DESCRIPTION
**Pull request by Johnnynator**
the new License does not allow redistribution.

If anyone finds the old version with also a License then we could downgrade but the official site only hosts the newest version.

### CODE REVIEW

**Comment by Johnnynator** [comment]
#13731 see comments there

**Comment by Chocimier** [comment]
What about turning to nonfree instead?

**Comment by Johnnynator** [comment]
@Chocimier you mean `restricted=yes` ? Because `nonfree` is for packages that are nonfree but still allow redistribution. That should also work, but would probably require that someone removes the package manually from the binary repo (?). (idk how the cleaning script works).

**Comment by Gottox** [comment]
moving packages between repositories is basicly the same problem as deleting it from the repository completely. So restricted is fine with me too.

**Comment by Johnnynator** [comment]
The PR sets font-symbola to restricted now.
If for any reason the nonfree method with INSTALL and REMOVE is preferred, it still is in my repo https://github.com/Johnnynator/void-packages/tree/font-symbola-nonfree

**Pull request closed without merging**
