### PR TITLE
busybox: Added poweroff/halt/reboot/init to be compiled

### PR DESCRIPTION
**Pull request by jcjordyn130**

### CODE REVIEW

**Comment by chneukirchen** [comment]
What is this good for? (I guess `halt -f` can make sense, but the one in runit-void isn't exactly large).

Also, why all the other changes?

NACK for now.

**Comment by jcjordyn130** [comment]
I don't know where the other changes came from, I only enabled init/poweroff/reboot/halt in menuconfig.

**Comment by Vaelatern** [comment]
Why do you want busybox's version of init? Would that play well at all with anything else?

**Comment by jcjordyn130** [comment]
I tested it on a fresh install of void with xfce in a vm and on my personal void system, and it didn't conflict with anything as it doesn't override init/poweroff/reboot/halt from runit

**Comment by pullmoll** [comment]
There can't be a conflict because nothing is installed. Take a look at https://travis-ci.org/voidlinux/void-packages/jobs/170271420#L563 and expand the line.

**Comment by Vaelatern** [comment]
So the advantage is...?

**Comment by jcjordyn130** [comment]
None really, its just for people who want to use busybox init. I do get your point though

**Pull request closed without merging**
