### PR TITLE
kernel-libc-headers: musl libc support for compat with linux/*.h

### PR DESCRIPTION
**Pull request by yopito**
following issue #5786 
still WIP, but NetworkManager 1.0.2 builds (native muslc)

### CODE REVIEW

**Comment by pullmoll** [comment]
Thanks! The patch, once working, needs to be symlinked in all `cross-*musl*` packages to `<pkgname>/files/<patchname>` as well, and it needs to be applied there with
```
    _apply_patch -p0 ${FILESDIR}/<patchname>
```
after or around `_apply_patch -p1 ${FILESDIR}/gcc-6.3.0-musl.diff`.

**Comment by yopito** [comment]
thanks for your help, I was not aware about the `cross-*musl*` packages.

I've just bump their revision since they apply all patches from `kernel-libc-headers` in their `_linux_headers()` routines (no need to link these files).

Let's see if Travis CI can deal with it.

**Comment by pullmoll** [comment]
Ouch! I see the cross*musl* packages are still using musl 1.1.15. We should update that at the same time.

**Comment by yopito** [comment]
dedicated commit ? seperate PR ?

**Comment by yopito** [comment]
git rewrites: separated commits for `kernel-libc-headers` and `cross*musl`.
reworked `blueman` patches to take advantage of my `kernel-libc-headers` (build fine on native musl libc)

**Comment by pullmoll** [comment]
I think the two `cross*musl*` commits should be squashed into one.
IMO grouping the update of 6 or 7 packages with the same change into one commit is ok, while there is usually the rule to have one package per commit. What do the other contributors think?

I also have a libreoffice pending here, which currently fails to build for musl libc, so merging this patch rather sooner than later would be good :)

**Comment by yopito** [comment]
Hello, I've squashed my commits, added 2 forgotten `cross*musl` packages and review my comments within the patch of `linux/libc-compat.h`.
Ready to be merged or respond to reviewers ;)

**Comment by pullmoll** [comment]
Merged. I'm building from scratch locally again to see if/what packages would still fail for *-musl.
Thank you for the patches.

**Pull request merged**
