### PR TITLE
Manual: build option commands were incomplete

### PR DESCRIPTION
**Pull request by Piraty**

### CODE REVIEW

**Comment by Vaelatern** [comment]
But it also works for other commands.

**Comment by Piraty** [comment]
so maybe add sth. like: (pkg|extract|...) ?
If you don't agree, please close it.

**Comment by ebfe** [comment]
Maybe ```$ ./xbps-src -o option,option1 <cmd>``` avoids the confusion

**Comment by Piraty** [comment]
in fact, i call `./xbps-src <cmd> <some more flags> -o  <pkgname>`.
but in general i agree.

**Comment by Vaelatern** [comment]
@Piraty Until recently, your syntax would not have worked.
I'm happy with this PR as `<cmd>` instead of `pkg`

**Comment by Piraty** [comment]
Well, it's been corrected.

**Comment by asergi** [comment]
Please squash your commits together next time.

**Pull request merged**
