### PR TITLE
New package: tarsnap-1.0.35

### PR DESCRIPTION
**Pull request by gour**
New package with 'proprietary' license and 'restricted' for distribution, but ready for local builds.

Sincerely,
Gour

### CODE REVIEW

**Comment by thypon** [comment]
Shouldn't be in the nonfree repository?

**Comment by beefcurtains** [comment]
Tarsnap doesn't ship the files used to create the ``configure`` script (usually ``configure.ac``). Either you have to carefully audit all that junk, or ask the author to start shipping the files used to build that script. Personally, I consider the script effectively a binary and am therefore unable to fully reproduce tarsnap from the given source code.

So that is in addition to the problem of not being able to distribute binaries. :-1: from me.

**Comment by gour** [comment]
No problem. xtraeme added 
```
XBPS_ALLOW_RESTRICTED=yes
```

option today and told me to submit it with

```
license=proprietary
```

for building it locally.

Since I have need for it, local build is enough for me. ;)

**Comment by beefcurtains** [comment]
I don't like that feature if that means opening the floodgates to stuff we previously would've rejected. Sure, this package is just an oddball and building it locally is a useful workaround. But this shouldn't become an excuse to merge in shit programs. Call me a pessimist, but there was nothing stopping you from building it locally before (either wholly outside of xbps-src, or in a local branch). Also it could lead to support questions of the "can't install package x" variety.

By all means, go for it. But in my book this is declared a misfeature.

**Comment by gour** [comment]
Fair-enough. ;)

**Comment by xtraeme** [comment]
I added `restricted=yes` and `XBPS_ALLOW_RESTRICTED` specifically for cases like this one.

You will be able to build the binary packages if `XBPS_ALLOW_RESTRICTED` is defined in `etc/conf`, but the official build servers will never build a binary package, because redistribution of sources and binaries is restricted.

This is how FreeBSD/ports and pkgsrc works, you do have the build definitions to build and pkg it locally.

**Pull request merged**
