### PR TITLE
new package: qutebrowser-git

### PR DESCRIPTION
**Pull request by mattiasgiese**

### CODE REVIEW

**Comment by pullmoll** [comment]
Install xtools and run `xlint srcpkgs/qutebrowser-git/template` to see a list of things to fix

**Comment by mattiasgiese** [comment]
Thanks for the hint :-)

**Comment by GiedriusS** [comment]
I'm pretty sure that -git packages are not allowed.

**Comment by Gottox** [comment]
What's the reason to use -git over a release?

**Comment by mattiasgiese** [comment]
I have seen some -git packages in the repository so i thought it might be okay.

**Comment by mattiasgiese** [comment]
Well, The-Compiler does not release as often and the current git master has some interesting features like speed enhancements and history lookup.

**Comment by Gottox** [comment]
It's a small world. I talked to @the-compiler about Void on 31c3. I think he'll releases a new version if you ask him kindly.

We deprecated the usage of -git packages some months ago. Therefore if it's not definitely needed we won't accept any non-release packages.

**Comment by The-Compiler** [comment]
But then I'll have to adjust all my issue milestones! :wink:

No, you guys are right, it's probably time for a v0.3 earlier than I wanted.

**Comment by xtraeme** [comment]
`-git` pkgs won't be accepted unless there's a good reason, use the released version.

**Comment by The-Compiler** [comment]
I just released qutebrowser v0.3.0 - so probably you'll get it very soon when @uggedal or someone else had time to update the package :smile:

Sorry it took me another four weeks!

**Comment by uggedal** [comment]
0.3.0 pushed.

**Comment by The-Compiler** [comment]
That was quick - thank you! :+1:

**Pull request closed without merging**
