### PR TITLE
Clang next

### PR DESCRIPTION
**Pull request by thypon**
This adds the lld cross architecture linker to llvm.

### CODE REVIEW

**Comment by chneukirchen** [comment]
But 3.6.2 release can't link ELF yet, as this has landed only two weeks ago, no?

**Comment by thypon** [comment]
@chneukirchen I included also mclinker to overcome the lld shortcomings.

**Comment by thypon** [comment]
Right now i can't crosscompile cleanly, i think some CFLAGS/LDFLAGS are the problem.

I think this could be merged until 8641474. Then i have to continue experimenting.

**Comment by thypon** [comment]
Merged (partially) manually.

**Pull request closed without merging**
