### PR TITLE
mono: update to 5.4.1.7

### PR DESCRIPTION
**Pull request by Hoshpak**

### CODE REVIEW

**Comment by pullmoll** [comment]
Unfortunately it fails to build locally for x86_64.
```
CSC     [build-linux] cil-stringreplacer.exe
Stacktrace:
…
<a long crash dump>
```

Were you able to build it?

**Comment by Hoshpak** [comment]
Yes, but that was before the gcc-7.3 update. I will try again and update the PR if necessary.

**Comment by Hoshpak** [comment]
Zapped and re-bootstraped my masterdirs, built fine on my computer for x86_64 and x86_64-musl. I rebased on top of current master to give travis another run.

**Comment by pullmoll** [comment]
Then perhaps it's my build environment which caused this fault.
I'll merge it and push and we will see what the builders tell us :)

**Pull request closed without merging**
