### PR TITLE
Llvm 3.7.0

### PR DESCRIPTION
**Pull request by thypon**
I'll rebase in a single commit.

Btw lld seems not to be compilable anymore in tree. I have to test if can be compiled outside without problems.

### CODE REVIEW

**Comment by thypon** [comment]
Broken on musl and armv7hf

**Comment by xtraeme** [comment]
Not enough to merge, an update must build in the same architectures than the previous pkg was built for.

**Comment by thypon** [comment]
Working on it. Unneeded since mesa-11.0.

**Comment by thypon** [comment]
x86_64-musl bug was trivial. i686 and armv7 seems subtle.

- i686 can't find libcompiler-rt.a
- armv7 loops forever when it tries to compile the Verifier

**Comment by thypon** [comment]
Ready for merge. Armv7hf fails on travis-ci but succeeds on a real buildserver (the problem is in an interactive timeout with travis-ci).

**Comment by xtraeme** [comment]
Great! well done :+1: 

Thanks

**Pull request merged**
