### PR TITLE
New package: goxel

### PR DESCRIPTION
**Pull request by cr6git**
It's [Goxel](https://guillaumechereau.github.io/goxel/). 
I can compile and run the program on x86_64, see [screenshot](https://prnt.sc/g8yo70). 
For now, I am forced to put `nocross=yes` and `nopie=yes` because I think FLAGS are not correctly set in the source file `SConstruct`. 
Correct me if I am wrong.

### CODE REVIEW

**Comment by cr6git** [comment]
musl does not agree.

**Comment by cr6git** [comment]
Failed, x86_64-musl does not agree.

**Comment by Johnnynator** [comment]
You can try adding
```
case "$XBPS_TARGET_MACHINE" in
	*-musl) makedepends+=" argp-standalone";;
esac
```
so argp gets installed for musl (glibc has it already integrated)

**Comment by Johnnynator** [comment]
A patch which creates imgui.ini in ~/.config/goxel instead in the current work folder would probably nice

**Comment by cr6git** [comment]
Nice work @Johnnynator !

**Pull request closed without merging**
