### PR TITLE
new package: unoconv

### PR DESCRIPTION
**Pull request by antonio-malcolm**

### CODE REVIEW

**Comment by xtraeme** [comment]
`GPL` licenses do not need to be installed.

**Comment by antonio-malcolm** [comment]
vlicense removed.

**Comment by xtraeme** [comment]
- This is a python script and there's no dependency for it.
- This just contains a python script, hence this needs `noarch=yes`.

**Comment by antonio-malcolm** [comment]
Ok, added the noarch flag and python-devel, to ensure it has libpython v2.7

**Comment by xtraeme** [comment]
Your latest `makedepends` change is wrong... change this to `depends="python"`.

**Comment by antonio-malcolm** [comment]
AH, you're right. Changed it to depends="python". That said, don't we need the development package for shared libs?

**Comment by xtraeme** [comment]
Yes, but this pkg only provides a script and won't be linked to any shared library.

python is only required at runtime.

**Comment by antonio-malcolm** [comment]
Ok, because looking at how it's packaged with other distros points to it 
needing the sahred lib. That said, it's working with libreoffice and 
gloobus-preview without issue.

On 12/23/2015 01:02 AM, Juan RP wrote:
>
> Yes, but this pkg only provides a script and won't be linked to any 
> shared library.
>
> python is only required at runtime.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/voidlinux/void-packages/pull/3211#issuecomment-166837956>.
>

-- 
/"Creative ability is best displayed with the most basic tools"/

**Pull request merged**
