### PR TITLE
i2pd: update to 2.15.0

### PR DESCRIPTION
**Pull request by Sir-Boops**

### CODE REVIEW

**Comment by Sir-Boops** [comment]
Not sure why the builder is half failing as I've built this locally on "broken" platforms and it builds fine

**Comment by Gottox** [comment]
#yolo ;)

**Comment by Gottox** [comment]
please resolve the conflicts and ping me afterwards.

**Comment by Sir-Boops** [comment]
@Gottox Fixed

**Comment by Gottox** [comment]
builds locally. #yolomerge

**Pull request merged**
