### PR TITLE
mupdf: generate shared libraries

### PR DESCRIPTION
**Pull request by svenper**
The bulk of the binary sizes are font data that can be in a shared library instead.

### CODE REVIEW

**Comment by chneukirchen** [comment]
These .so will need sonames.

**Comment by chneukirchen** [comment]
And we need to fix the packages depending on mupdf I guess.

**Comment by svenper** [comment]
Since the shared library is unofficial, what would be a suitable version? 0? 0.0.0? Both?

**Comment by chneukirchen** [comment]
Why not `1.11`? We use this information to track rebuilds.

**Comment by svenper** [comment]
I amended the pull request [like this gist](https://gist.github.com/svenper/6c543ac99195799c1c1dd92b8e396824).

Now for the depending packages. I assume the only ones are `fbpdf` and `zathura-pdf-mupdf` as their makedepends are the only ones that contain mupdf-devel. What kind of changes are needed besides making sure the makefiles know what to look for?

**Comment by chneukirchen** [comment]
You need to check they still build (use proper -lmupdf), and then increase the revision to trigger a rebuild.

**Comment by chneukirchen** [comment]
Also please pass the version via a variable into the Makefile, so we don't need to adjust the patch on every release.

**Comment by svenper** [comment]
`fbpdf` and `zathura-pdf-mupdf` build without issues with no changes.

**Comment by Gottox** [comment]
@chneukirchen ok to merge?

**Pull request merged**
