### PR TITLE
Newsbeuter: fix STFL error on musl

### PR DESCRIPTION
**Pull request by E100Beta**
fixes https://github.com/voidlinux/void-packages/issues/6206

Also `xlint` complained about not using package's license.
Is there a better way to conditionally patch the package than what I came up with?

### CODE REVIEW

**Comment by Duncaen** [comment]
Don't patch conditionally.

**Comment by E100Beta** [comment]
@Duncaen I know it's bad, just didn't want to rob `glibc` users of functionality... Well, okay, transliteration isn't that critical of a function. I reworked the commit.

**Comment by E100Beta** [comment]
Okay, I got around git's segfaults and **now** it's reworked.

**Comment by E100Beta** [comment]
Er... Now there're two commits. Okay, this is getting ridiculous...
*After some git tutorials*
Okay, it should be 100% fine.
I am REALLY sorry for all this. (BTW git crashes were my fault too, I was experimenting with localization on musl and it seems git didn't like it)

**Comment by neton-bricio** [comment]
@E100Beta Thanks for this.

**Pull request merged**
