### PR TITLE
openvpn: update to 2.3.10.

### PR DESCRIPTION
**Pull request by ebfe**
Patch taken from upsteam git master for libressl compat.

### CODE REVIEW

**Comment by TheDoctorsLife** [comment]
The short description is to long should be less than 72 characters.

**Comment by ebfe** [comment]
> The short description is to long should be less than 72 characters.

Yes, i know the xlint fails, but the `short_desc` is like that since Feb
2013, so I guess that is on purpose?

**Comment by TheDoctorsLife** [comment]
Maybe, shorting it should help kick Travis to redo the build, (since one of them timed out). Plus, fixing errors is a nice thing to do, even if it was left.

**Comment by ebfe** [comment]
Updated.

**Comment by TheDoctorsLife** [comment]
Cool, now Travis is happy

**Pull request merged**
