### PR TITLE
New package: syncplay-1.4.0

### PR DESCRIPTION
**Pull request by KeepBotting**
http://syncplay.pl/
https://github.com/Syncplay/syncplay

Free software that synchronises media players so that faraway friends can watch videos together.

Edit: New to Void packaging, can anyone educate me on how to interpret Travis CI? I'm not sure why aarch64 and ARM builds are failing.

### CODE REVIEW

**Comment by Johnnynator** [comment]
It seems like Shiboken a dependency of python-pyside can't be cross compiled for these Systems. So it is not you fault that the builds fail.

**Comment by KeepBotting** [comment]
Thanks for the info! I've updated the template to only build for the architechtures that pass the check.

**Comment by Johnnynator** [comment]
The one that just be marked as broken is Shiboken and not your package, since you package may or may not built correctly if all the dependecies would be there.

**Comment by KeepBotting** [comment]
@Johnnynator thanks again. I've pushed another commit, everything should match up now.

**Comment by Johnnynator** [comment]
You have always to expect that someone makes a typo and no one notices it 😄 , there is a H missing in MAC_H_INE.

**Comment by KeepBotting** [comment]
@Johnnynator Right. Completely my fault, I copied what you posted without checking :P fixed.

**Comment by Vaelatern** [comment]
Love it. I'm reviewing and intend to merge.

**Comment by Vaelatern** [comment]
4742526fe86bf0a13f098d48e1568326e4bce1f7

**Comment by Vaelatern** [comment]
My changes are as follows: only one commit per template, I removed the custom broken to indicate what the problem actually was (a mere packaging error, really, that will be fixed at some point). I also removed the bashism of `${pkgname^}` since that doesn't work in basically any other shell (even zsh) and github is not case sensitive.

**Pull request closed without merging**
