### PR TITLE
Add SELinux and AppArmor in kernel but keep them disabled by default

### PR DESCRIPTION
**Pull request by olivier-mauras**
See https://github.com/voidlinux/void-packages/issues/6879 for details

### CODE REVIEW

**Comment by chneukirchen** [comment]
FWIW, Debian seems to compile in both by default, Arch has AppArmor.

**Comment by olivier-mauras** [comment]
Having them enabled without any userland installed is pointless.
It makes more sense to enable them explicitely from the command line when userland is installed.

**Comment by M3rsy** [comment]
How can enable apparmor and Selinux thanks

**Comment by olivier-mauras** [comment]
Right now only AppArmor has working userlands, SELinux is still WIP.

For AppArmor then, update your kernel latest version, install apparmor package. 
Install message will tell you what to do, this should be straightforward.

**Pull request merged**
