### PR TITLE
[WIP] Gnome 3.20

### PR DESCRIPTION
**Pull request by Gottox**
TODO:
- [x] Wait till all packages released stable versions
- [ ] Switch all Gnome packages to use elogind instead of ConsoleKit
- [ ] Test
  - [ ] x86_64 on my productive systems for a few days
  - [ ] i686 on the secondary notebook
  - [ ] x86_64-musl on the secondary notebook (maybe)

### CODE REVIEW

**Comment by Gottox** [comment]
#3873 gucharmap update.

**Comment by Gottox** [comment]
Strange stuff on libgee:
```
$ xbps-query -Rf libgee                                                            
/usr/lib/girepository-1.0/Gee-1.0.typelib
/usr/lib/libgee.so.2.0.0
/usr/lib/libgee.so -> /usr/lib/libgee.so.2.0.0
/usr/lib/libgee.so.2 -> /usr/lib/libgee.so.2.0.0
```
```
/usr/lib/libgee-0.8.so.2.5.1
/usr/lib/girepository-1.0/Gee-0.8.typelib
/usr/lib/libgee-0.8.so -> /usr/lib/libgee-0.8.so.2.5.1
/usr/lib/libgee-0.8.so.2 -> /usr/lib/libgee-0.8.so.2.5.1
```

**Comment by ebfe** [comment]
There is libgee (pinned to 0.11.4) that provides libgee.so and is only still used by birdie. And libgee08, that provides libgee-0.8.so, is updated and used by everything else.

**Comment by eye-sigil** [comment]
Hey, is this still going or does someone else need to take over?

**Comment by Gottox** [comment]
Hey, I'm currently involved in my daytime job. Feel free to finish the Update :)

If you need any help, don't hasitate to ask.

**Pull request closed without merging**
