### PR TITLE
yakuake: update to 3.0.4

### PR DESCRIPTION
**Pull request by djames1**

### CODE REVIEW

**Comment by Chocimier** [comment]
Do you plan to add also other kde5 apps to repo?

**Comment by djames1** [comment]
@Chocimier yakuake is the only KDE program that I use, but I do have more applications I plan to add to repo such as SeaMonkey and Remmina

**Comment by phikal** [comment]
Will/can SeaMonkey be added? Or is there any progress on that?

**Comment by djames1** [comment]
@phikal I tried to package seamonkey, but ran across various issues. I will try again at some point. Until then, if you are using x86 or x86_64 GLIBC builds, there are prebuilt binaries available on the official SeaMonkey home page.

**Pull request closed without merging**
