### PR TITLE
Glibc-2.25_1 revert

### PR DESCRIPTION
**Pull request by Gottox**
There are repeatedly coming up issues with glibc-2.25 both breaking systems and services.

This PR addresses this issue by reverting this release and going back to 2.24 which runs fine.

### CODE REVIEW

**Comment by chneukirchen** [comment]
Reverting possibly breaks even more since there are binaries now that link against 2.25 features.

x86_64 works fine for me, the problems seem to appear on 32-bit platforms. I guess we need better bug reports to fix them...

**Comment by chneukirchen** [comment]
Hm, only ruby references 2.25 symbols here on my system.

**Comment by Gottox** [comment]
oh boy. 🙄

**Comment by xtraeme** [comment]
IMHO reverting is simply useless. Let's find and fix the real issues instead.

**Comment by chneukirchen** [comment]
I have a i686 machine image now, and just updated without issues. Please tell me what's broken. :)

**Comment by Gottox** [comment]
IRC-Logs:
```
bind still won't run since glibc update without logging being set to stderr with -g
```

**Comment by arete** [comment]
With last update bind work fine,is only an mistach of log permission #5708

Il 17 feb 2017 16:36, "Enno Boland" <notifications@github.com> ha scritto:

**Comment by chneukirchen** [comment]
One i686 that sproadically appears (only on real HW so far) seems to result from https://github.com/bminor/glibc/commit/23d27709a423aec32821e9a5198a10267107bae2

**Comment by chneukirchen** [comment]
We could try reverting that one, after all, it wasn't noticed before...

**Comment by Hoshpak** [comment]
As I mentioned on IRC, reverting that commit solved the issue for me. Since it was possible to collect at least some information on the issue (thanks @chneukirchen for your help with that) and I am able to reproduce it reliably with grep, I decided to create an upstream bug report: https://sourceware.org/bugzilla/show_bug.cgi?id=21182 .

**Comment by chneukirchen** [comment]
I have access to a Atom N270 now, and couldn't reproduce this yet.

I think `-dbg` packages on i686 are broken because they use `/usr/lib/debug/usr/lib` and not `lib32`...

**Comment by Gottox** [comment]
superseeded by #5840

**Pull request closed without merging**
