### PR TITLE
flatpak: update to 0.11.1

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by maxice8** [comment]
xdg-desktop-portal needs to be updated in lockstep according to upstream, also new xdg-desktop-portal needs libpipewire, please see #11123

**Comment by maxice8** [comment]
do not merge until commit with pipewire update to 0.1.8 (required by xdg-desktop-portal) is added.

**Comment by Vaelatern** [comment]
odd, it seems to build.

**Comment by maxice8** [comment]
it has --disable-pipewire, if pipewire is enabled then it isn't enough because pipewire 0.1.8 is required

**Comment by maxice8** [comment]
i'm currently working on bumping pipewire to 0.1.8 but it is a glibc fest of `error.h` and `error()`

**Comment by maxice8** [comment]
There we go, the patches to fix musl compat amount to `269` lines.

**Pull request closed without merging**
