### PR TITLE
New package: mmv-1.01b

### PR DESCRIPTION
**Pull request by pullmoll**

### CODE REVIEW

**Comment by chneukirchen** [comment]
Looks good, do you want to add the symlinks for mcp, mad, mln too?

**Comment by pullmoll** [comment]
Okay, will add them.

**Comment by pullmoll** [comment]
Aw, its usr/share/man/man1 ... wait

**Comment by pullmoll** [comment]
IMHO mmv should be even in base-system :)

**Comment by chneukirchen** [comment]
Not before ed is. ;)

**Pull request merged**
