### PR TITLE
atom: update to 1.23.2

### PR DESCRIPTION
**Pull request by wpbirney**

### CODE REVIEW

**Comment by wpbirney** [comment]
odd, x86_64 builds fine locally for me

**Comment by jarbowski** [comment]
Hi,
It seems that the script builds a wrong /usr/share/applications/atom.desktop
I just installed it and the executable and icon are in a wrong path (buiddir)

**Comment by wpbirney** [comment]
@jarbowski 
thanks for the update i must have overlooked that... (I don't personally use .desktop icons), ill add the patch back for the .desktop

**Comment by jarbowski** [comment]
@wpbirney 
%F was good but %U would work too
thank you, anyway

**Pull request closed without merging**
