### PR TITLE
ardour: update to 5.8

### PR DESCRIPTION
**Pull request by cr6-git**

### CODE REVIEW

**Comment by cr6-git** [comment]
aarch64 & armv7 are problematic, as usual... 

I'm currently using Ardour 5.8 on my Void i686 because I need a recent version. 

Regards.

**Comment by ebfe** [comment]
#6074

**Comment by juliendehos** [comment]
so do I
#6074

**Comment by cr6-git** [comment]
Thanks, but **why** the build failed on aarch64 & armv7 ?? 
I don't see any useful information in the Travis log... 
What can I do to help ? 

Regards.

**Comment by ebfe** [comment]
Build it on your own machine and look at:
```
(complete log in /builddir/ardour-5.8/build/config.log)
```

**Comment by cr6-git** [comment]
I tried to build for armv7hf, see the first [first log](https://pastebin.com/W7qS7sE2), but I don't know what's wrong in [config.log](https://pastebin.com/yLABsQNW).

**Comment by ebfe** [comment]
Tries to execute cross compiled binaries during configure. the boost version check can be disabled with
```
--- wscript.orig        2017-05-05 17:52:26.000000000 +0000
+++ wscript     2017-05-05 17:56:36.820706988 +0000
@@ -982,7 +982,7 @@
             else:
                 conf.check_cc(function_name='dlopen', header_name='dlfcn.h', lib='dl', uselib_store='DL')
         conf.check_cxx(fragment = "#include <boost/version.hpp>\nint main(void) { return (BOOST_VERSION >= 103900 ? 0 : 1); }\n",
-                  execute = "1",
+                  execute = False,
                   mandatory = True,
                   msg = 'Checking for boost library >= 1.39',
                   okmsg = 'ok',

```

but there are more issues along the road. Marking nocross is probably ok here.

**Comment by cr6-git** [comment]
ok I give up.

**Comment by juliendehos** [comment]
> Marking nocross is probably ok here.

+1

**Pull request closed without merging**
