### PR TITLE
xbps-src: new vopt_onoff helper

### PR DESCRIPTION
**Pull request by jaagr**
CMake helper function used to set bool argument value for cache entries.

Usage example:

    configure_args+=" $(vopt_onoff logging WITH_LOGGING)"

    configure_args+=" -DWITH_LOGGING=OFF"

### CODE REVIEW

**Comment by Anachron** [comment]
I like it, can we search and replace pkgs automatically so that they use this?

**Comment by jaagr** [comment]
We can at least replace the ones that are using the same format: `-D<prop>:BOOL={ON,OFF}`

**Comment by xtraeme** [comment]
You can skip completely the ":TYPE" part... simply "-DPROP=VALUE".

2016-11-19 14:59 GMT+01:00 Michael Carlberg <notifications@github.com>:

**Comment by Vaelatern** [comment]
@xtraeme this looks good to merge?

**Comment by maxice8** [comment]
@Vaelatern i don't think you're getting an answer

ping

**Comment by Vaelatern** [comment]
lol

**Pull request merged**
