### PR TITLE
st: split terminfo files in subpkg

### PR DESCRIPTION
**Pull request by xYuusha**

### CODE REVIEW

**Comment by Vaelatern** [comment]
Why?

**Comment by xYuusha** [comment]
To be able to only install the terminfo in a headless machine.
rxvt-unicode is doing the same.

**Comment by wpbirney** [comment]
It's definitely great for headless machines

**Comment by xtraeme** [comment]
revision must be increased

**Comment by xYuusha** [comment]
I always forget to increment the revision. Done now.

**Pull request merged**
