### PR TITLE
New package: ocaml-findlib

### PR DESCRIPTION
**Pull request by jprjr**

### CODE REVIEW

**Comment by pullmoll** [comment]
Instead of 
`install -m755 src/findlib/ocamlfind_opt $DESTDIR/usr/bin/`
you can use
`vbin src/findlib/ocamlfind_opt`.

**Comment by jprjr** [comment]
Done and done!

**Comment by pullmoll** [comment]
You really should run `xlint` from the `xtools` package on your templates :smile_cat:
There's trailing whitespace on line 20 of the template. It's just cosmetics, I know, but then...
```
xlint srcpkgs/ocaml-findlib/template
```
Also there's a `vlicense ...` missing for the MIT license

**Comment by jprjr** [comment]
I was wondering where that is! I didn't see a mention of it in Manual.md, had no idea what package to look for, I'll start running it on my end now :-D

**Comment by jprjr** [comment]
Rebased + pushed

**Comment by pullmoll** [comment]
Hmm.. the i686 failing may be due to 32/64 bit word size issues. I don't know ocaml to tell if or how to fix it. Any takers?

**Comment by pullmoll** [comment]
It doesn't look like anyone knows how to fix i686 thus you may want to add `only_for_archs="x86_64 x86_64-musl"` for now.

**Comment by steski** [comment]
Try adding <code>disable_parallel_build=yes</code>.

**Comment by jprjr** [comment]
Fixed/rebased/pushed

**Comment by steski** [comment]
@jprjr You can remove <code>only_for_archs="..."</code>. I think <code>disable_parallel_build=yes</code> will fix <code>i686</code>

**Comment by jprjr** [comment]
@steski done and done!

**Comment by steski** [comment]
Just add <code>vlicense LICENSE</code> to your <code>do_install</code>, becuase it's <code>MIT</code>, and you should be good.

**Comment by jprjr** [comment]
Added

**Pull request merged**
