### PR TITLE
manual: descriptions for -data and -doc pkgs

### PR DESCRIPTION
**Pull request by pullmoll**

### CODE REVIEW

**Comment by xtraeme** [comment]
Looks good, thanks.

My only concer is the confusion with `-doc` and `-docs`. I believe that we should just choose one and fix the existing ones.

I vote for `-doc`.

**Comment by pullmoll** [comment]
I agree. Should I go ahead and change *-docs to *-doc in the voidlinux/void-packages repo?

**Comment by xtraeme** [comment]
Go ahead :+1:

**Comment by pullmoll** [comment]
What about `gnome-gettings-started-docs` and `gnome-user-docs`? They are standalone packages, not subpackages.

**Comment by xtraeme** [comment]
Those pkgs are fine as is.

**Comment by xtraeme** [comment]
:+1:

**Pull request merged**
