### PR TITLE
vim: update to 8.0.0946

### PR DESCRIPTION
**Pull request by cr6git**

### CODE REVIEW

**Comment by Vaelatern** [comment]
You do know that vim pushes a new release every commit, yes?

What's gained by this version that it's worth bumping?

**Comment by cr6git** [comment]
Good question, but I'm not smart enough to give you the answer. 🃏

**Comment by chneukirchen** [comment]
I guess a bump every 100 or 200 patches is enough. (Esp. in times of heavy development as currently.)

**Comment by cr6git** [comment]
@Vaelatern & @chneukirchen No problem, I will slow down the pace! 
I tend simply to follow the AUR updates, even if it's not really necessary... 
I am at your service. :)

**Comment by Gottox** [comment]
Merging this one nontheless, thanks mate!

**Pull request merged**
