### PR TITLE
lvm2: update to 2.02.164.

### PR DESCRIPTION
**Pull request by subsonik**

### CODE REVIEW

**Comment by chneukirchen** [comment]
Have you verified this works on musl?

**Comment by chneukirchen** [comment]
```
commands/toolcontext.c: In function 'create_toolcontext':
commands/toolcontext.c:1859:32: warning: passing argument 1 of 'reopen_standard_stream' discards 'const' qualifier from pointer target type
    if (!reopen_standard_stream(&stdin, "r"))
                                ^
In file included from ../include/lib.h:89:0,
                 from commands/toolcontext.c:16:
../include/lvm-logging.h:41:5: note: expected 'struct FILE **' but argument is of type 'struct FILE * const*'
 int reopen_standard_stream(FILE **stream, const char *mode);
```

I'm fairly sure these are serious fails on musl.

**Comment by subsonik** [comment]
After testing on musl, it does indeed seem to fail with:

`File descriptor 3 (socket:[189647]) leaked on lvchange invocation. Parent PID 10405: /bin/bash
Segmentation fault`

I guess I should close this PR and leave it to someone more knowledgable?

**Comment by Vaelatern** [comment]
Leave it up. Someone more knowledgeable will probably submit a patch for you to add.

**Comment by chneukirchen** [comment]
Obsoleted by 2.02.166.

**Pull request closed without merging**
