### PR TITLE
kdenlive: update to 17.12.2. [ci skip]

### PR DESCRIPTION
**Pull request by jnbr**
Travis CI is skipped as usual for kdenlive. Large amount of compiler warnings would exceed maximum for Travis log file.

### CODE REVIEW

**Comment by jnbr** [comment]
broken after qt update

**Comment by jnbr** [comment]
I removed `qt5-webkit-devel` from `hostmakedepends` to unbreak build.

It is not really important: `-- Qt5 WebKitWidgets not found. You cannot use your Freesound.org credentials, only preview files can be downloaded from the Online Resources Widget`

**Comment by pullmoll** [comment]
qt5-webkit needs a revbump after #11719 is solved.

**Comment by jnbr** [comment]
with the revbump of qt5-webkit, all builds are working again (tested on local machine)

**Comment by jnbr** [comment]
missed, the output of the i686 build. It is currently failing in the configure step:
```
=> kdenlive-17.12.2_1: running do_configure ...
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /builddir/.xbps-kdenlive/wrappers/i686-pc-linux-gnu-gcc
-- Check for working C compiler: /builddir/.xbps-kdenlive/wrappers/i686-pc-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /builddir/.xbps-kdenlive/wrappers/i686-pc-linux-gnu-c++
-- Check for working CXX compiler: /builddir/.xbps-kdenlive/wrappers/i686-pc-linux-gnu-c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Failed
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
CMake Warning at /usr/share/ECM/modules/ECMQueryQmake.cmake:43 (message):
  Failed call: /usr/i686-pc-linux-gnu/usr/lib/qt5/bin/qmake -query
  "QT_INSTALL_PREFIX"
Call Stack (most recent call first):
  /usr/share/ECM/kde-modules/KDEInstallDirs.cmake:463 (query_qmake)
  CMakeLists.txt:33 (include)


CMake Error at /usr/share/ECM/modules/ECMQueryQmake.cmake:44 (message):
  QMake call failed: No such file or directory
Call Stack (most recent call first):
  /usr/share/ECM/kde-modules/KDEInstallDirs.cmake:463 (query_qmake)
  CMakeLists.txt:33 (include)


-- Configuring incomplete, errors occurred!
```

**Pull request closed without merging**
