### PR TITLE
vlc: do not install precompiled lua scripts when cross compiling

### PR DESCRIPTION
**Pull request by newbluemoon**
Lua scripts precompiled with a 64 bit host luac won’t run on a 32 bit target (same with respect to endianess). So just install the uncompiled source .lua files.
Tested on a Raspberry Pi and everything seems fine.

### CODE REVIEW

**Comment by Vaelatern** [comment]
I don't think we crossbuild i686, but this would break there too, yes?

**Comment by newbluemoon** [comment]
I think so. The issue was brought up in this [forum thread](https://forum.voidlinux.eu/t/vlc-on-armv7l/4678) when running vlc on a Raspberry Pi.

I don’t know if there are other packages that precompile lua scripts. When researching I found some comments that suggested that a 64 bit luac could be patched to produce 32 bit output. I don’t know if it would make sense to create a luac package just for this purpose?

**Comment by newbluemoon** [comment]
Of course, this solution isn’t optimal, just a workaround. Perhaps a better way would be to byte-compile the lua scripts when installing the package, similar to python packages? Either in a custom `INSTALL` script or (preferably) via an xbps-trigger hook?

**Comment by newbluemoon** [comment]
It seems only vlc is affected:

```
$ xlocate .luac$
bash-completion-2.7_2	/usr/share/bash-completion/completions/luac
vlc-2.2.8_6	/usr/lib/vlc/lua/extensions/VLSub.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/intf/cli.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/intf/dummy.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/intf/dumpmeta.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/intf/http.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/intf/luac.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/intf/modules/host.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/intf/modules/httprequests.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/intf/telnet.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/meta/art/00_musicbrainz.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/meta/art/01_googleimage.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/meta/art/02_frenchtv.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/meta/art/03_lastfm.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/meta/fetcher/tvrage.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/meta/reader/filename.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/modules/common.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/modules/dkjson.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/modules/sandbox.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/modules/simplexml.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/playlist/anevia_streams.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/playlist/anevia_xml.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/playlist/appletrailers.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/playlist/bbc_co_uk.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/playlist/break.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/playlist/canalplus.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/playlist/cue.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/playlist/dailymotion.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/playlist/extreme.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/playlist/france2.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/playlist/googlevideo.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/playlist/jamendo.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/playlist/joox.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/playlist/katsomo.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/playlist/koreus.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/playlist/lelombrik.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/playlist/liveleak.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/playlist/metacafe.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/playlist/metachannels.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/playlist/mpora.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/playlist/pinkbike.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/playlist/pluzz.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/playlist/rockbox_fm_presets.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/playlist/soundcloud.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/playlist/vimeo.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/playlist/youtube.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/playlist/youtube_homepage.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/playlist/zapiks.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/sd/fmc.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/sd/icast.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/sd/icecast.luac
vlc-2.2.8_6	/usr/lib/vlc/lua/sd/jamendo.luac
```

So perhaps the best solution is to just use the .lua files; anyhow, the lua interface in the current state of the package isn’t usable.

**Pull request closed without merging**
