### PR TITLE
tint2: update to 0.12.2

### PR DESCRIPTION
**Pull request by Spencer-H**
update the tint2 package to 0.12.2

Switch to tint2 on gitlabs - Google Code shut down.
Remove patch, didn't compile with it.

### CODE REVIEW

**Comment by dominikh** [comment]
Is the patch not needed anymore, or did you simply remove it so you wouldn't have to port it to the new version?

**Comment by Spencer-H** [comment]
I could attempt to port the patch, but I am not familiar with what it was fixing. And looking at the tint2 code, the battery seems to have been almost completely rewritten. If I knew what this was fixing (and if it was still an issue0, I would try to port it.

I will add that the battery monitor works perfectly fine on my computer, but I as I don't know what this was fixing I don't even know if it would apply to me.

**Comment by dominikh** [comment]
Looking at the code, the patch shouldn't be required anymore. At one point in time, it was part of upstream. Some time after that, they restructured the code entirely.

**Comment by dominikh** [comment]
Can't build reliably because gitlab isn't generating the archive in time. Apparently they're over capacity, and the archive generation ends in a redirect loop. Will merge the PR once gitlab is more stable.

**Comment by dominikh** [comment]
Merged as 1fb3dda.

**Pull request closed without merging**
