### PR TITLE
vte: add patch for fixing scroll region glitches

### LINKED ISSUE #2068: vte: add patch to fix upstream bugs #542087 and #686097 (change scroll region)
[This patch](https://bug542087.bugzilla-attachments.gnome.org/attachment.cgi?id=176035) fixes a problem with VTE-based terminal, when "change scroll region" operation is used, resulting in many text glitches. It's strongly noticeable when using software heavily dependant on this feature, like `mosh` or complex `ncurses` apps.

Related GNOME Bugzilla entries: [#542087](https://bugzilla.gnome.org/show_bug.cgi?id=542087) [#686097](https://bugzilla.gnome.org/show_bug.cgi?id=686097)

### PR DESCRIPTION
**Pull request by skrzyp**
Closes #2068

### CODE REVIEW

**Comment by xtraeme** [comment]
revision must be bumped.

**Comment by skrzyp** [comment]
Done.

**Comment by skrzyp** [comment]
Woah… that was weird. I'm sure it should be fixed now.

**Comment by beefcurtains** [comment]
Looks fine by me :+1:

**Pull request merged**
