### PR TITLE
nvidia-stable: updated to 352.79

### PR DESCRIPTION
**Pull request by Vaelatern**
#3495

### CODE REVIEW

**Comment by Vaelatern** [comment]
xlint fails because vman doesn't understand .gz files can be man pages but xlint expects it to.

**Comment by chneukirchen** [comment]
Void does not use compressed manpages, they should be unpacked first.

**Comment by Vaelatern** [comment]
They were not uncompressed in the package before. I shall add decompression.

**Comment by Vaelatern** [comment]
Decompression added, all checks passing.

**Pull request merged**
