### PR TITLE
New package: perl-Net-IMAP-Client-0.9505.

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by maxice8** [comment]
On Sun, Feb 04, 2018 at 11:46:14PM -0800, joseapascual wrote:
> Hi, what's the status of this package? 
> It wasn't merged and It is now closed. Any reason? Can I help?
> Thanks.

I packaged and made a PR to merge it but it was before i went to Exherbo and closed all my PRs, this can be revived if there is any interest

**Comment by joseapascual** [comment]
Hi, 
thanks for answering. I'm planning to add a new package and this is the only missing dependency. If you don't mind to revive it that would be great. If you can't (or don't have time) I'll try to do it myself. In any case, thanks.

**Comment by maxice8** [comment]
Done #11477

**Comment by joseapascual** [comment]
Sorry, I missed this. Thanks.

**Pull request closed without merging**
