### PR TITLE
Build gtk2 and gtk3 versions of webkitgtk

### PR DESCRIPTION
**Pull request by uggedal**
Builds locally under x86_64. i686 and armv7hf builds currently running locally.

### CODE REVIEW

**Comment by xtraeme** [comment]
Looks good to me, thanks :+1:

**Comment by uggedal** [comment]
Does not cross build :/ Will look into it in the morning.

**Comment by uggedal** [comment]
I was mistaken, it does cross compile. All dependants which did cross build before does so now. Will merge this tonight.

**Comment by xtraeme** [comment]
Great :+1:

**Pull request merged**
