### PR TITLE
oce: update to 0.18.2.

### PR DESCRIPTION
**Pull request by yopito**

### CODE REVIEW

**Comment by karl-nilsson** [comment]
I successfully built the oce update on x86_64 glibc today, tested FreeCAD, and everything worked fine. Please merge.

**Comment by yopito** [comment]
Thanks for your time on runtime tests. Did you also test FreeCAD update (PR #7239) ?

**Comment by karl-nilsson** [comment]
Yes.

**Comment by yopito** [comment]
Just rebased freeCAD to be mergeable (PR #7239).  
FYI, no ABI changes from this oce update, so oce and FreeCAD updates are not related from a packaging perspective.

**Pull request merged**
