### PR TITLE
New package: sonic-visualiser-3.0.3

### PR DESCRIPTION
**Pull request by newbluemoon**
This addresses issue #6771.

There are two files piper.capnp.c++ and piper.capnp.h which are precompiled with capnproto 0.6.0. This leads to a version mismatch error with void’s newer version of capnproto. The source file piper.capnp is not included in the source tarball. I see two possibilities:
a) Download the file piper.capnp from upstream after source archive extraction and run capnproto on the host system.
b) Put precompiled files (those are text files, btw.) into $FILESDIR and copy them to the corresponding location.
For now I chose a).

While cross-compiling for arm (I tested armv7l-musl) works, a native build (on a Raspberry Pi 3) fails with

    configure: creating ./config.status
    config.status: creating config.pri
    Could not find qmake configuration file devices/void-armv7l-linux-musleabihf-g++.
    Error processing project file: sonic-visualiser.pro
    configure: error: qmake failed: Command was "/bin/qmake-qt5 -r"
    => ERROR: sonic-visualiser-3.0.3_1: failed to run do_configure() at line 7.

Running the same command from inside xbps-src’s chroot with explicitly using the `-spec` option yields

    # /bin/qmake-qt5 -spec /usr/lib/qt5/mkspecs/devices/void-armv7l-linux-musleabihf-g++ -r sonic-visualiser.pro
    Project ERROR: CROSS_COMPILE needs to be set via -device-option CROSS_COMPILE=<path>
    Could not read qmake configuration file /usr/lib/qt5/mkspecs/devices/void-armv7l-linux-musleabihf- g++/qmake.conf.
    Error processing project file: sonic-visualiser.pro

I wonder if this is possibly a bug or am I missing something?

### CODE REVIEW

**Comment by newbluemoon** [comment]
Travis complains

    /usr/armv7l-linux-musleabihf/usr/include/lrdf.h:8:20: fatal error: raptor.h: No such file or directory
    #include <raptor.h>

I had that very same error, too, but then it was suddenly gone. Just compiled it on my system again for armv7l-musl with

    ./xbps-src -m masterdir-x86_64-musl -a armv7l-musl -j9 pkg sonic-visualiser

with no error. Hmm...

**Comment by cr6git** [comment]
````
/usr/include/lrdf.h
#include <raptor.h>

$ xbps-query -f raptor-devel
/usr/lib/pkgconfig/raptor2.pc
/usr/include/raptor2/raptor.h
/usr/include/raptor2/raptor2.h
````

Possible confusion between raptor1 / raptor2 ? 
See [this](https://github.com/hydrogen-music/hydrogen/issues/521), and [this](https://github.com/hydrogen-music/hydrogen/issues/342) which seems related.

**Comment by newbluemoon** [comment]
Thank you @cr6git, but `raptor.h` just contains the line

    #include <raptor2.h>

so I think this problem can be ruled out.

The [build log](https://travis-ci.org/voidlinux/void-packages/jobs/264770316) (e.g. for armv7hf-musl) shows

    -I/usr/armv7l-linux-musleabihf/usr/armv7l-linux-musleabihf/usr/include/raptor2

is included. So I don’t know why the error occurs. But as stated above I had this error locally, too, but I don’t remember doing anything about it, it just vanished. Might have been a simple `xbps-src clean`?

**Comment by newbluemoon** [comment]
Disabled the test-suite on i686, too. One out of 35 tests fails. Should build now on native i686 (it did so locally).

**Comment by newbluemoon** [comment]
Added the location of `raptor.h` explicitly to `configure_args` and now it’s found. :)

**Comment by cr6git** [comment]
@newbluemoon That's very interesting. I am currently trying to create a [new template](https://bpaste.net/show/3b9ed778669a) for the package [guitarix2](https://www.archlinux.org/packages/community/x86_64/guitarix2/), but I suffer from the same [kind of error](https://bpaste.net/show/799266ee6496) as you with raptor... 
I have no idea how to solve the problem, however.

**Comment by newbluemoon** [comment]
@cr6git Sorry, I know almost nothing about the waf building system. Had a look at it, but couldn’t find out what’s wrong. Maybe you should open a thread on the forum for discussion?

**Comment by lemmi** [comment]
I'm going to test this the next couple of days. If you have anything added, please rebase and push again.

**Comment by newbluemoon** [comment]
No, I haven’t added/changed anything.

**Pull request closed without merging**
