### PR TITLE
wireguard: add missing depends on openresolv

### LINKED ISSUE #14517: Missing dependency openresolv for wireguard
### System

* xuname:  
  Void 4.16.7_1 x86_64 GenuineIntel uptodate rrrrmmnFF
* package:  
  wireguard-0.0.20180514_1

### Expected behavior
Bring up a wireguard interface with `wg-quick mullvad-se1`.
### Actual behavior
Command fails with:
```bash
[#] ip link add mullvad-se1 type wireguard
[#] wg setconf mullvad-se1 /dev/fd/63
[#] ip address add 10.99.16.239/32 dev mullvad-se1
[#] ip address add fc00:bbbb:bbbb:bb01::10ef/128 dev mullvad-se1
[#] ip link set mtu 1420 dev mullvad-se1
[#] ip link set mullvad-se1 up
[#] resolvconf -a mullvad-se1 -m 0 -x
/usr/bin/wg-quick: line 73: resolvconf: command not found
[#] ip link delete dev mullvad-se1
```
### Steps to reproduce the behavior
- openresolv not installed
- try to bring up a wireguard interface with `wg-quick up <config>`

### PR DESCRIPTION
**Pull request by TehDaniel37**
resolves #14517

### CODE REVIEW

**Comment by maxice8** [comment]
please add resolve #14518  or closes #14518  so that the github issue will be automatically closed when the commit is merged.

**Comment by TehDaniel37** [comment]
Oh, I didn't know that. Is it sufficient to edit the pull request like I did or do I need to amend the commit?

**Comment by TehDaniel37** [comment]
`wg-quick` is still part of the wireguard package though. But I see your point. If it was possible to declare optional dependencies this would be a good candidate imo.

**Comment by maxice8** [comment]
> Oh, I didn't know that. Is it sufficient to edit the pull request like I did or do I need to amend the commit?

editing the pull request is not sufficient, some Void Linux org members (the people that merge your Pull requests) do so in different ways and i some ways github ignores `resolves` and `closes` statements when inside the PR, so putting in the commit is to guarantee it will.

**Comment by TehDaniel37** [comment]
I have amended the commit now and added `resolves #14517` to the commit message.

**Pull request closed without merging**
