### PR TITLE
Fix gnuradio

### PR DESCRIPTION
**Pull request by abenson**
ARM support seems to be lacking.

### CODE REVIEW

**Comment by pullmoll** [comment]
Hmm.. commented out only_for_archs= in volk and only_for_archs= in gnuradio.
Can we definitely say it won't build for anything besides i686 and x86_64, i.e. not the *-musl variants?

**Comment by abenson** [comment]
The comment was wrong. I haven't seen it fail on musl, it's just ARM. Let
me fix the comment.

--
AndrewB
Knowing is Half the Battle.

On Sat, Feb 17, 2018 at 1:36 AM, Jürgen Buchmüller <notifications@github.com

**Comment by pullmoll** [comment]
Of course. I just asked because it's an obviously nothing-changing change in volk.

**Comment by abenson** [comment]
It's alright. Just getting really frustrated with this one.

--
AndrewB
Knowing is Half the Battle.

On Sat, Feb 17, 2018 at 1:39 AM, Jürgen Buchmüller <notifications@github.com

**Comment by pullmoll** [comment]
Or is it more that cross compiling fails? In that case `nocross=yes` would be advised.
What the heck, I'm going to try locally to see what makes sense.

**Comment by abenson** [comment]
Cross compiling is fine, I'm cross-compiling for musl/i686 and it works.
It's just ARM, in my experience.

--
AndrewB
Knowing is Half the Battle.

On Sat, Feb 17, 2018 at 1:41 AM, Jürgen Buchmüller <notifications@github.com

**Comment by abenson** [comment]
I didn't bump revision, I need to do that, right?

--
AndrewB
Knowing is Half the Battle.

**Comment by pullmoll** [comment]
FWIW just built fine for x86_64-musl and i686-musl, both as native builds.
That means `nocross=yes` instead of `only_for_arch="…"` is advised, as usual.

**Comment by abenson** [comment]
Okay. I'll adjust.

--
AndrewB
Knowing is Half the Battle.

On Sat, Feb 17, 2018 at 2:09 AM, Jürgen Buchmüller <notifications@github.com

**Pull request closed without merging**
