### PR TITLE
base-files: Use IPv6 privacy extensions by default

### PR DESCRIPTION
**Pull request by Duncaen**

### CODE REVIEW

**Comment by ebfe** [comment]
Can we put these things in a `conf_file`? #6840 etc.

**Comment by the-maldridge** [comment]
This will break my network.  I would like to see the sysctl loading issue fixed before this is merged so it is possible to override back to what I had before.

**Comment by cr6git** [comment]
This is not already set by dhcpcd ? 

```
# /etc/dhcpcd.conf
# Generate Stable Private IPv6 Addresses instead of hardware based ones
slaac private
```

**Comment by cr6git** [comment]
In fact [RFC4941](https://tools.ietf.org/html/rfc4941) and [RFC7217](https://tools.ietf.org/html/rfc7217) are directly related.

**Comment by lemmi** [comment]
I'm just going to mention that I had a lot of trouble using privacy extensions on networks with changing prefixes (as it is common for Germany).
Essentially what happens:
- On a prefix change, new temporary addresses will be generated for an interface. These are the newest addresses, so they will be used.
- Old addresses are kept for a while for open connections.
- After an address runs out of its lifetime, a new address is generated. 
- If that happens to be an address of the old prefix, this one will be the default address and now.
- bam

**Comment by lemmi** [comment]
@voidlinux/pkg-committers can we close this?

**Comment by the-maldridge** [comment]
Working as intended.

**Pull request closed without merging**
