### PR TITLE
cgmanager: add man pages for native builds

### PR DESCRIPTION
**Pull request by Duncaen**
Maybe the test scripts can be removed from the package too?
```
/usr/share/cgmanager/tests/test02.sh
/usr/share/cgmanager/tests/test06.sh
/usr/share/cgmanager/tests/test23.sh
/usr/share/cgmanager/tests/test18.sh
/usr/share/cgmanager/tests/test09.sh
/usr/share/cgmanager/tests/test12.sh
/usr/share/cgmanager/tests/test27.sh
/usr/share/cgmanager/tests/test17.sh
/usr/share/cgmanager/tests/test19.sh
/usr/share/cgmanager/tests/test22.sh
/usr/share/cgmanager/tests/test24.sh
/usr/share/cgmanager/tests/test11.sh
/usr/share/cgmanager/tests/runtests.sh
/usr/share/cgmanager/tests/test26.sh
/usr/share/cgmanager/tests/test05.sh
/usr/share/cgmanager/tests/test25.sh
/usr/share/cgmanager/tests/test01.sh
/usr/share/cgmanager/tests/test13.sh
/usr/share/cgmanager/tests/test07.sh
/usr/share/cgmanager/tests/test14.sh
/usr/share/cgmanager/tests/test20.sh
/usr/share/cgmanager/tests/test08.sh
/usr/share/cgmanager/tests/test03.sh
/usr/share/cgmanager/tests/test15.sh
/usr/share/cgmanager/tests/test21.sh
/usr/share/cgmanager/tests/test10.sh
/usr/share/cgmanager/tests/test16.sh
/usr/share/cgmanager/tests/test04.sh
```

### CODE REVIEW

**Comment by Vaelatern** [comment]
My only comment is that manpages may also be generated for cross builds by doing builds on the master, as suggested in [#4029](https://github.com/voidlinux/void-packages/pull/4029#discussion_r59832354)

**Comment by xtraeme** [comment]
I would prefer to have consistent pkgs: have the same contents building natively or cross compiled.

**Comment by Vaelatern** [comment]
How much of the build must be completed for help2man to do its job?

**Comment by ebfe** [comment]
> How much of the build must be completed for help2man to do its job?

Everything. It runs "$bin --help"  for each binary.

**Comment by Duncaen** [comment]
I close this as I don't see any additional value by having man pages generated by help2man and its really not worth building it two times while cross compiling.

**Pull request closed without merging**
