### PR TITLE
New package: xf86-video-mga-1.6.4

### PR DESCRIPTION
**Pull request by pullmoll**
Yes, I really have a box with a Matrox PCI card here and VESA just doesn't cut it.

### CODE REVIEW

**Comment by thypon** [comment]
:+1:

**Comment by pullmoll** [comment]
It works, but the [Xorg.0.log](http://sprunge.us/aKeB) suggests some things are missing or not working right.
```
[    17.707] (EE) MGA(0): [drm] Failed to initialize DMA! (-2)
```
This leads to DRI2 not working - but then I don't know if it is supposed to work with this driver.
Perhaps some of you can make sense from the Xorg.0.log output.

**Comment by xtraeme** [comment]
error -2 is ENOENT, that means the `mga` drm kernel module wasn't loaded/found.

**Comment by pullmoll** [comment]
In `dmesg` I saw the mga module wants to load a `matrox/g400_warp.fw` firmware. I found it somewhere on the net; it loads and still leaves me with an error `AGP not found: -19`.
I don't know if this is due to my motherboard not setting up the PCI memory or something else.

I think however that adding
```
vmove usr/lib/firmware/matrox
```
to `srcpkgs/linux-firmware/template` would be good if this package is merged.

**Comment by pullmoll** [comment]
We could merge this pr, but I'll definitely go and buy some cheapo ATI graphics card to replace this old Matrox.

The driver doesn't work (fully) with my hardware. Here's an excerpt from the output of dmesg:
```
[   15.529126] [drm] Initialized drm 1.1.0 20060810
[   15.531312] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[   15.531315] [drm] No driver support for vblank timestamp query.
[   15.531317] [drm] Initialized mga 3.2.1 20051102 for 0000:02:00.0 on minor 0
[   15.532154] [drm:mga_do_agp_dma_bootstrap [mga]] *ERROR* Unable to acquire AGP: -19
```

X11 video (XV) doesn't work at all. Also no 2D acceleration as it seems. Window moving and resizing is very slow. This is despite the Xorg.0.log telling DRM is ok now:
```
[    15.287] (II) MGA(0): [drm] bpp: 32 depth: 24
[    15.288] (II) MGA(0): [drm] Sarea 2200+664: 2864
[    15.288] drmOpenDevice: node name is /dev/dri/card0
[    15.292] drmOpenDevice: node name is /dev/dri/card0
[    15.320] drmOpenByBusid: Searching for BusID pci:0000:02:00.0
[    15.320] drmOpenDevice: node name is /dev/dri/card0
[    15.320] drmOpenDevice: open result is 11, (OK)
[    15.320] drmOpenByBusid: drmOpenMinor returns 11
[    15.320] drmOpenByBusid: drmGetBusid reports pci:0000:02:00.0
[    15.320] (II) [drm] loaded kernel module for "mga" driver.
[    15.320] (II) [drm] DRM interface version 1.4
[    15.320] (II) [drm] DRM open master succeeded.
```
I'll see if I can find any hints on the `Unable to acquire AGP: -19` error...

**Pull request merged**
