### PR TITLE
util-linux: update to 2.31.

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by chneukirchen** [comment]
needs provides= and replaces=.

**Comment by maxice8** [comment]
Done, please check, first time doing it.

**Comment by chneukirchen** [comment]
LGTM.

**Comment by cr6git** [comment]
I'm glad to see `rfkill` included in `util-linux`.

**Comment by maxice8** [comment]
Reading the [lwn article](https://lwn.net/Articles/736909/) on it (great read), they now use `runstatedir` instead of `localstatedir`, i have updated the commit accordingly.

**Comment by cr6git** [comment]
@maxice8 Looks like this update broke `uuidd`.

**Comment by cr6git** [comment]
Solved by [commit](https://github.com/voidlinux/void-packages/commit/71815ec6f9a312f56899f9dd0f63abc98d590bf2). 😄

**Comment by cr6git** [comment]
The `rfkill` package has not been removed ? [#9652](https://github.com/voidlinux/void-packages/issues/9652).

**Pull request merged**
