### PR TITLE
acme-client: update to 0.1.16

### PR DESCRIPTION
**Pull request by freshprince**
ATTENTION: acme-client changed default directories from "letsencrypt" to "acme" so this might break running setups.

Should I add a `install.msg` with a note?

### CODE REVIEW

**Comment by Vaelatern** [comment]
Huh, will check what upstream expected as a migration mechanism

**Comment by Vaelatern** [comment]
Yes please, a 1-line `INSTALL.msg`, max 80 characters.

**Comment by freshprince** [comment]
I hope the wording is alright.

**Comment by freshprince** [comment]
Crossbuilds are now fixed too.

**Pull request closed without merging**
