### PR TITLE
new package: cura

### PR DESCRIPTION
**Pull request by equalsraf**
Packaged cura and dependencies.

ref  #4138, #3586

ping @karl-nilsson in case you are still looking into this.

### CODE REVIEW

**Comment by karl-nilsson** [comment]
You beat me to it!
2 minor things in the libArcus template:

- you may want to disable building examples by default -DBUILD_EXAMPLES=OFF
- you may want to use ${version} for the distfiles link

other than that, LGTM

**Comment by equalsraf** [comment]
Added you changes. xlint complains on cmake_args for some reason

```
libArcus/template:6: custom variables should use _ prefix: cmake_args="-DBUILD_EXAMPLES=OFF"
```

**Comment by the-maldridge** [comment]
@equalsraf can you rebase this to run a new travis build?  Also file a bug against xtools if you are seeing linter errors that shouldn't be there.

**Comment by ebfe** [comment]
s/cmake_args/configure_args/

**Comment by equalsraf** [comment]
🤦‍♂️ yeah that fixes it.

**Comment by karl-nilsson** [comment]
@equalsraf cura, cura-engine, and Uranium just released v2.7.0

ping @lyzech

**Comment by karl-nilsson** [comment]
@equalsraf Uranium has a hard dependency on python-scipy. Also, cura throws out a bunch of errors if python-zeroconf isn't installed. Finally, python-numpy-stl enables 20x better performance for importing STLs, so I'm going to include that as well.

Expect a new PR tonight.

**Comment by equalsraf** [comment]
Thanks, closing this for https://github.com/voidlinux/void-packages/pull/7645

**Pull request closed without merging**
