### PR TITLE
New package: chkrootkit

### PR DESCRIPTION
**Pull request by cr6git**
[#6460](https://github.com/voidlinux/void-packages/issues/6460).

### CODE REVIEW

**Comment by cr6git** [comment]
musl cannot bear it.

**Comment by maxice8** [comment]
Another case of lack of `fcntl.h` and now PATH_MAX which is from `limits.h`

First patch, fixes missing fcntl.h

```
--- chklastlog.c
+++ chklastlog.c
@@ -41,6 +41,7 @@ int main () { return 0; }
 #include <stdlib.h>
 #endif
 #include <sys/stat.h>
+#include <fcntl.h>
 #include <unistd.h>
 #include <string.h>
 #include <signal.h>
--- chkproc.c
+++ chkproc.c
@@ -62,6 +62,7 @@ int main (){ return 0; }
 #include <string.h>
 #include <errno.h>
 #include <sys/types.h>
+#include <fcntl.h>
 #include <dirent.h>
 #include <ctype.h>
 #include <stdlib.h>
--- chkwtmp.c
+++ chkwtmp.c
@@ -25,6 +25,7 @@ int main () { return 0; }
 #include <stdio.h>
 #include <stdlib.h>
 #include <unistd.h>
+#include <fcntl.h>
 #include <string.h>
 #include <utmp.h>
 #include <time.h>
```

second patch, fixes PATH_MAX

```
--- chkdirs.c
+++ chkdirs.c
@@ -33,6 +33,7 @@
 #include <sys/syslimits.h>
 #endif
 
+#include <limits.h>
 #include <stdio.h>
 #include <stdlib.h>
 #include <sys/types.h>
```

Tried compiling with `-m ~/src/masterdir-musl` and it worked

**Comment by maxice8** [comment]
Also needs `binutils` on `depends` otherwise it will error out with

```
chkrootkit: can't find 'strings'.
```

**Comment by cr6git** [comment]
Thank you @maxice8 , I will try right now.

**Pull request merged**
