### PR TITLE
poppler: update to 0.59.0. (soname bump)

### PR DESCRIPTION
**Pull request by ebfe**
broken: pdf2htmlEX

### CODE REVIEW

**Comment by ebfe** [comment]
> pdf2htmlEX is no longer under active development. New maintainers are wanted.

**Comment by chneukirchen** [comment]
Missing zathura-pdf-poppler?

**Comment by ebfe** [comment]
> Missing zathura-pdf-poppler?

No, that depends on poppler-glib.so which wasn't bumped.

**Comment by Gottox** [comment]
Will wait with #7713 till this is merged.

**Comment by ebfe** [comment]
Don't hold your breath, fixing pdf2htmlEX is not on my shortlist.

**Comment by Gottox** [comment]
wilco

**Comment by ebfe** [comment]
Marking pdf2htmlEx as broken. Seems unlikely that a proper fix will show up anytime soon.

**Comment by ebfe** [comment]
a5e8b89fbb4a4dd1a790442a8a599adc383134e8

**Pull request closed without merging**
