### PR TITLE
New package: suricata-3.0

### PR DESCRIPTION
**Pull request by thypon**
Link to #2797

### CODE REVIEW

**Comment by Vaelatern** [comment]
Musl build fails but the afflicted file `util-affinity.h` needs to `#include <sched.h>` to get `cpu_set_t`.

**Comment by inliniac** [comment]
This will be fixed in Suricata 3.0.1. This is the fix: https://github.com/inliniac/suricata/commit/e91b9bf22b5768f4919bde1606fdc93ab75951fd

**Comment by Vaelatern** [comment]
Rebase and push to re-test?

**Comment by Vaelatern** [comment]
Version is currently `3.1.1`, recommend update of template to fix build and make mergable.

**Pull request closed without merging**
