### PR TITLE
New package: simulavr-1.1start (closes #14010)

### LINKED ISSUE #14010: Package request: simulavr
Simulator for the Atmel AVR family of microcontrollers

I tried to compile `simulavr-1.0.0.tar.gz` from http://download.savannah.nongnu.org/releases/simulavr/ . The problem is that it requires libiberty, which we don't seem to have.

They also say (http://savannah.nongnu.org/forum/forum.php?forum_id=8454):
>Please use the latest git master. The version from the download area is outdated and contains many many known bugs. So please use latest content from git master!

So I tried to compile http://git.savannah.nongnu.org/cgit/simulavr.git/snapshot/simulavr-rel-1.1-start.tar.gz which succeeded (doesn't seem to require libiberty), the executable binary is created and seems to work, but the make fails because of some gtest error:
```
Making all in gtest
make[2]: Entering directory '/tmp/simulavr/simulavr-rel-1.1-start/regress/gtest'
depbase=`echo session_001/unittest001.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I../../src    -Dprivate=public -Dprotected=public  -Igtest-1.6.0/include/gtest -Igtest-1.6.0/include -Igtest-1.6.0 -I../../src -g -g -O2 -MT session_001/unittest001.o -MD -MP -MF $depbase.Tpo -c -o session_001/unittest001.o session_001/unittest001.cpp &&\
mv -f $depbase.Tpo $depbase.Po
In file included from gtest-1.6.0/include/gtest/internal/gtest-port.h:197:0,
                 from gtest-1.6.0/include/gtest/internal/gtest-internal.h:40,
                 from gtest-1.6.0/include/gtest/gtest.h:57,
                 from session_001/unittest001.cpp:4:
/usr/include/c++/7.3/sstream:348:7: error: 'struct std::basic_stringbuf<_CharT, _Traits, _Alloc>::__xfer_bufptrs' redeclared with different access
       struct __xfer_bufptrs
       ^~~~~~
make[2]: *** [Makefile:580: session_001/unittest001.o] Error 1
make[2]: Leaving directory '/tmp/simulavr/simulavr-rel-1.1-start/regress/gtest'
make[1]: *** [Makefile:429: all-recursive] Error 1
make[1]: Leaving directory '/tmp/simulavr/simulavr-rel-1.1-start/regress'
make: *** [Makefile:506: all-recursive] Error 1
```

What do?

### PR DESCRIPTION
**Pull request by cr6git**

### CODE REVIEW

**Comment by cr6git** [comment]
````
srcpkgs/simulavr/template:12: use $NONGNU_SITE
````
No idea how to fix this?

**Comment by abenson** [comment]
From the commit description for that, it doesn't sound like that's an actual release.

> Release branch for 1.1 is starting here from master branch.

 1.0.0 is still the latest on the project page.

**Comment by cr6git** [comment]
@abenson you probably didn't read @avoidr 's comment in [#14010](https://github.com/voidlinux/void-packages/issues/14010) ?

**Comment by abenson** [comment]
I just mean, packaging that as 1.1 is going to be weird when they release 1.1.

**Comment by newbluemoon** [comment]
Regarding the version: The [description](http://git.savannah.nongnu.org/cgit/simulavr.git/tag/?h=rel-1.1-start) of the snapshot says

> Release branch for 1.1 is starting here from master branch.

So maybe use the tag date as well, i.e. version `1.1.20160220` or `1.1.0.20160220`?

The build errors, I believe, are due to parallelism: tested locally and in a first run it errored, in a second one everything was ok. The problem seems to be generating `simulavr.info`. So to not have to disable the parallel build for the whole package one could “make” the info file in a seperate step:

```
pre_build() {
        make -j1 info
}
```

**Comment by cr6git** [comment]
Thanks!
Would you agree with `version=1.1start` ?

**Comment by cr6git** [comment]
````
$ common/travis/xlint.sh
srcpkgs/simulavr/template:12: use $NONGNU_SITE
````
:confused: ?
I still don't know how to fix this...

**Comment by Johnnynator** [comment]
You an't. Just ignore that error. It is nor really a issue.

**Comment by abenson** [comment]
Check Manual.md, you can replace most of the URL with $NONGNU_SITE to save
redundancy in templates.

**Comment by cr6git** [comment]
As I'm not an expert of this sort of things, what do you think about @pienjo 's PR?

https://github.com/void-linux/void-packages/pull/260

They both look similar...

**Comment by pienjo** [comment]
They're similar, in that both packages serve the same purpose, but not the same. They both have their pro and cons - the fact that there's no stable working release of SimulAVR being a massive con ;)

**Comment by avoidr** [comment]
simavr looks fine, too, but I have never used it, so can't definitely tell.

**Pull request closed without merging**
