### PR TITLE
jo: update to 0.7

### PR DESCRIPTION
**Pull request by jpmens**
jo: update to 0.7

### CODE REVIEW

**Comment by dominikh** [comment]
Wrong commit message.

**Comment by jpmens** [comment]
I was trying to be helpful.
It would help if you'd explain what's wrong about the commit message (other than that it's empty)

**Comment by dominikh** [comment]
The commit message (which includes the "subject") for package updates should be of the form "<package>: update to <version>", so in this case "jo: update to 0.7" instead of "bump to v0.7".

Sorry if I came across as rude.

**Comment by dominikh** [comment]
I've rewritten the commit message to fit. You only updated the PR subject, not the actual git commit; but there's no point in extra roundtrips for a trivial commit. Thanks for the update.

**Pull request closed without merging**
