### PR TITLE
qtcreator: update to 4.4.1.

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by pullmoll** [comment]
I'd like to wait until qt5-5.9.2 is merged because qtcreator-full will then get some more packages added.

**Comment by maxice8** [comment]
Alright, i'll close this and rework on qt-creator once Qt5-5.9.x is merged

**Comment by pullmoll** [comment]
You don't have to work on it :)
I'm regularly checking my pending updates and usually update whenever it seems to fit.

**Comment by maxice8** [comment]
Alright, i'll find other stuff to update/fix/add missing license . :)

**Pull request closed without merging**
