### PR TITLE
ngspice: add shared library

### PR DESCRIPTION
**Pull request by faulesocke**
This is useful for building various other software and the upcoming kicad will also require it.

### CODE REVIEW

**Comment by faulesocke** [comment]
Don't know, why building fails on this single architecture and works on all the others...

**Comment by newbluemoon** [comment]
I think it’s a musl problem. The other musl architectures are cross-compiled, but that’s not possible:

`ERROR: ngspice-27_2: cannot be cross compiled, exiting...`

**Comment by cr6git** [comment]
Oddly enough, on the Arch [PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/ngspice) the `./configure` step is executed in two passes.

**Comment by newbluemoon** [comment]
Configure option `--with-ngshared` conflicts with `--with-x`, see `INSTALL` file:

```
1.4.2 Options Specific to Enable Ngspice as a shared library

 --with-ngshared
        This option let you compile ngspice as a shared
        library or dll, allowing an application controlling
        ngspice. This option excludes using --with-x or
        --with-wingui. Useful additional options are
        --enable-xspice --enable-cider --enable-openmp.
        No graphics inetrface is provided, this has to be
        handled by the controlling application.
```

I think this is why Arch uses a two-step build.

**Comment by faulesocke** [comment]
Okay, I've modified the template once more, now it does a two-step-like build.

**Comment by Vaelatern** [comment]
The `--with-x` never worked quite right. Rather than complicating the template, I'd like to see as follows: shared library, perhaps `--enable-xspice`, and a new template for a new Xorg controller for ngspice.

**Comment by newbluemoon** [comment]
I think I found a way to fix cross compilation. Maybe you can make use of it. It’s based on the template before your two-step modification.

The target built binary `ngmakeidx` is run to create an index file. This just compiles it with the host compiler under a different name (I chose `makeidx`), because the real `ngmakeidx` is part of the package.

```
if [ -n "$CROSS_BUILD" ]; then
	pre_build () {
		cd src
		gcc -Iinclude -I${XBPS_CROSS_BASE}/include -o makeidx makeidx.c
		sed -i -e 's|\./ngmakeidx$(EXEEXT)|\./makeidx|' Makefile
	}
fi
```

Just to be sure I compared the generated file with a native build and they’re identical.

**Comment by Vaelatern** [comment]
I'd be happy to see `--with-x` removed.

**Comment by Vaelatern** [comment]
I'm handling this

**Pull request closed without merging**
