### PR TITLE
restic: update to 0.8.3.

### PR DESCRIPTION
**Pull request by eichf**

### CODE REVIEW

**Comment by Vaelatern** [comment]
#11846 please don't close and re-open PRs.

**Comment by eichf** [comment]
didn't close and reopen, this is a new version of the package (old was 0.8.2)

**Comment by maxice8** [comment]
Just amend commit and change title of the PR

**Comment by eichf** [comment]
okay, will do in the future. i just thought this was cleaner since it makes PRs which become deprecated before they're merged trackable.

**Comment by maxice8** [comment]
On Tue, Feb 27, 2018 at 07:08:48PM +0000, Florian Eich wrote:
> i just thought this was cleaner since it makes PRs
> which become deprecated before they're merged trackable.
> 

This doesn't make any sense to me.

**Comment by eichf** [comment]
having a lot of packages which get updated again before the previous update's PR is merged might be an interesting metric. by amending the commit and renaming the PR, you're discarding that information.

as i said, i'll just amend and rename in the future, i just thought it would be cleaner to preserve PRs even if they don't get merged.

**Pull request merged**
