### PR TITLE
DO NOT MERGE New package: git-imerge-0.7.0 

### PR DESCRIPTION
**Pull request by thypon**

### CODE REVIEW

**Comment by dominikh** [comment]
Maybe install the bash completion as well?

**Comment by thypon** [comment]
It's not in the 0.7.0, i could install the latest since there is no update in an year.

PS: ops i changed your commend instead of creating a new one :-)

**Comment by dominikh** [comment]
Maybe convince the maintainer to make a new release. Unless there's no useful/important changes (other than bash completion), then just package 0.7.0 and be happy :-)

P.S. addressing your P.S.S.: You're a collaborator, you can edit issues and comments. Apparently that includes those of other collaborators. Why? Because GitHub.

**Comment by thypon** [comment]
The stable version isn't working as expected, closing for now.

**Pull request closed without merging**
