### PR TITLE
Libressl-2.4.2

### PR DESCRIPTION
**Pull request by Vaelatern**
Waiting on xbps-0.52 for consistent repositories.

### CODE REVIEW

**Comment by Vaelatern** [comment]
Current build issues:
When running `./xbps-src pkg $pkg`, the following values of `$pkg` caused a non-zero return code.

[ ] android-tools 
[ ] argyllcms 
[ ] balsa 
[ ] boinc 
[ ] burp2-server 
[ ] collectd 
[ ] gkrellm 
[ ] gnome-shell 
[ ] inadyn 
[ ] kicad 
[ ] libesmtp 
[ ] libreoffice 
[ ] libwebsockets 
[ ] mosquitto 
[ ] mumble 
[ ] ngircd 
[ ] rdis-git 
[ ] seafile-client-qt 
[ ] seafile-libclient 
[ ] serf 
[ ] stunnel 
[ ] tcpflow 
[ ] transmission 
[ ] virtualbox-ose 
[ ] xar 
[ ] zathura-pdf-mupdf 

All patches will be copied in the comments here to make sure they get in.

**Comment by stpx** [comment]
@Vaelatern the kicad issues were fixed in the last update.

**Comment by Vaelatern** [comment]
```
--- a/srcpkgs/kicad/template
+++ b/srcpkgs/kicad/template
@@ -1,12 +1,12 @@
 # Template file for 'kicad'
 pkgname=kicad
 version=4.0.3
-revision=1
+revision=2
 build_style=cmake
 configure_args="-DKICAD_BUILD_VERSION=$version -DKICAD_SKIP_BOOST=ON
  -DKICAD_SCRIPTING=ON -DKICAD_SCRIPTING_MODULES=ON -DKICAD_SCRIPTING_WXPYTHON=ON
  -DwxWidgets_CONFIG_EXECUTABLE=/usr/bin/wx-config-3.0"
-hostmakedepends="cmake pkg-config swig"
+hostmakedepends="pkg-config swig"
 makedepends="wxWidgets-devel wxPython-devel python-devel glew-devel cairo-devel
  libressl-devel boost-devel"
 depends="wxPython"
```

**Comment by Vaelatern** [comment]
```
--- a/srcpkgs/seafile-client-qt/template
+++ b/srcpkgs/seafile-client-qt/template
@@ -9,7 +9,7 @@ configure_args="-DUSE_QT5=ON"
 
 # nocross since qt unavailable for arm* architecture
 nocross=yes
-hostmakedepends="pkg-config cmake"
+hostmakedepends="pkg-config"
 makedepends="sqlite-devel jansson-devel ccnet-devel libsearpc-devel
        libressl-devel seafile-libclient-devel libevent-devel libuuid-devel
        qt5-devel qt5-tools-devel desktop-file-utils"
```

**Comment by Vaelatern** [comment]
Updated all revbumps by removing them all. A few packages link against libressl that were not in the and it was easier to redo the revbumps and reapply patches.

**Comment by Vaelatern** [comment]
The list of things that either need fixing or to be marked broken before this is merged:

[ ] - `argyllcms`
[ ] - `boinc`
[ ] - `gnome-shell`
[ ] - `libreoffice`
[ ] - `rdis-git`
[ ] - `mumble`
[ ] - `stunnel`
[ ] - `tcpflow`
[ ] - `transmission`
[ ] - `virtualbox-ose`
[ ] - `xar`
[ ] - `zathura-pdf-mupdf`

This is not that many items.

**Comment by Gottox** [comment]
@Vaelatern can you rebase the commits? - I'd like to reactivate this PR :)

**Comment by chneukirchen** [comment]
xar build is fixed.

for tcpflow, I'd recommend to use tarballs from github.

**Comment by chneukirchen** [comment]
zathura-pdf-mupdf i could not reproduce.

**Comment by Gottox** [comment]
https://github.com/voidlinux/void-packages/pull/4841 - fixes tcpflow

**Comment by Vaelatern** [comment]
Rebasing and making right now.

**Comment by Vaelatern** [comment]
@Gottox @chneukirchen 
` + b0cd8ad...ff9c70f libressl2.4.2 -> libressl2.4.2 (forced update)`

**Comment by Vaelatern** [comment]
My list of libressl bumps changed thus:
```
@@ -1,4 +1,5 @@
 Ice
+acme-client
 aircrack-ng
 alpine
 android-tools
@@ -24,9 +25,7 @@
 ccnet
 ceph
 cgit
-cinnamon-settings-daemon
 clamav
-clementine
 collectd
 cryptsetup
 curl
@@ -40,12 +39,9 @@
 encfs
 erlang
 ettercap
-evolution-data-server
 facter
 fdm
 fetchmail
-firefox
-firefox-esr
 fossil
 freerdp
 freshplayerplugin
@@ -54,7 +50,6 @@
 git-series
 gkrellm
 glusterfs
-gnome-shell
 gsoap
 gst-plugins-bad
 gst-plugins-bad1
@@ -67,7 +62,6 @@
 httperf
 httrack
 icecast
-icecat
 icinga2
 imapfilter
 inadyn
@@ -89,12 +83,10 @@
 libetpan
 libevent
 libfetch
-libfprint
 libgda
 libgit2
 libimobiledevice
 libmowgli
-libpurple-steam
 libqtelegram-ae
 libreoffice
 libssh
@@ -157,7 +149,6 @@
 openvpn
 openvswitch
 opusfile
-outils
 owncloudclient
 pam_ssh
 pen
@@ -170,7 +161,6 @@
 pgadmin3
 phantomjs
 php
-pidgin
 pidgin-sipe
 pjproject
 podofo
@@ -219,7 +209,6 @@
 tcpdump
 tcpflow
 telepathy-salut
-thunderbird
 tinc
 tlsdate
 tnftp
```

**Comment by Vaelatern** [comment]
Updated for libressl 2.4.3.

**Comment by Vaelatern** [comment]
Current build issues:

- [ ] aircrack-ng

**Comment by Vaelatern** [comment]
Current list of packages that fail to build on my machine when building all of the above packages with the latest libressl. @chneukirchen @Gottox 

- [] ceph
- [] kicad
- [] mosquitto
- [] stunnel
- [] virtualbox-ose

Build still in progress. I'll post the errors for the above when I get a chance.

**Comment by chneukirchen** [comment]
Mosquitto patch is at https://github.com/eclipse/mosquitto/pull/281/commits/9f74e09373f3be7b77f510ef8b0ae2c887f7b325

**Comment by Vaelatern** [comment]
Build completed. Applying the following patch to mosquitto and rebuilding just the problem packages.

```
From 9f74e09373f3be7b77f510ef8b0ae2c887f7b325 Mon Sep 17 00:00:00 2001
From: Natanael Copa <ncopa@alpinelinux.org>
Date: Tue, 4 Oct 2016 14:35:33 +0200
Subject: [PATCH] [280] Fix build with libressl

Fix building with libressl which broke in commit fff741613 (Support for
openssl 1.1.0).

Signed-off-by: Natanael Copa <ncopa@alpinelinux.org>
---
 lib/mosquitto_internal.h | 3 +++
 src/mosquitto_passwd.c   | 4 ++--
 src/security_default.c   | 2 +-
 3 files changed, 6 insertions(+), 3 deletions(-)

diff --git a/lib/mosquitto_internal.h b/lib/mosquitto_internal.h
index 4b4cf85..700bbb0 100644
--- lib/mosquitto_internal.h
+++ lib/mosquitto_internal.h
@@ -25,6 +25,9 @@ and the Eclipse Distribution License is available at
 
 #ifdef WITH_TLS
 #  include <openssl/ssl.h>
+#  if OPENSSL_VERSION_NUMBER >= 0x10100000L && !defined(LIBRESSL_VERSION_NUMBER)
+#    define HAVE_OPENSSL_OPAQUE_STRUCTS
+#  endif
 #else
 #  include <time.h>
 #endif
diff --git a/src/mosquitto_passwd.c b/src/mosquitto_passwd.c
index de9a719..5b854d9 100644
--- a/src/mosquitto_passwd.c
+++ b/src/mosquitto_passwd.c
@@ -90,7 +90,7 @@ int output_new_password(FILE *fptr, const char *username, const char *password)
 	unsigned char hash[EVP_MAX_MD_SIZE];
 	unsigned int hash_len;
 	const EVP_MD *digest;
-#if OPENSSL_VERSION_NUMBER < 0x10100000L
+#ifndef HAVE_OPENSSL_OPAQUE_STRUCTS
 	EVP_MD_CTX context;
 #else
 	EVP_MD_CTX *context;
@@ -117,7 +117,7 @@ int output_new_password(FILE *fptr, const char *username, const char *password)
 		return 1;
 	}
 
-#if OPENSSL_VERSION_NUMBER < 0x10100000L
+#ifndef HAVE_OPENSSL_OPAQUE_STRUCTS
 	EVP_MD_CTX_init(&context);
 	EVP_DigestInit_ex(&context, digest, NULL);
 	EVP_DigestUpdate(&context, password, strlen(password));
diff --git a/src/security_default.c b/src/security_default.c
index 64ca846..9ad8708 100644
--- src/security_default.c
+++ src/security_default.c
@@ -770,7 +770,7 @@ int mosquitto_psk_key_get_default(struct mosquitto_db *db, const char *hint, con
 int _pw_digest(const char *password, const unsigned char *salt, unsigned int salt_len, unsigned char *hash, unsigned int *hash_len)
 {
 	const EVP_MD *digest;
-#if OPENSSL_VERSION_NUMBER < 0x10100000L
+#ifndef HAVE_OPENSSL_OPAQUE_STRUCTS
 	EVP_MD_CTX context;
 
 	digest = EVP_get_digestbyname("sha512");
```

**Comment by Vaelatern** [comment]
Ceph won't build - it's marked broken with no explanation

Mosquitto patch does not apply. The conditionals don't appear to be in the code at all.

Stunnel is stunnel. Switching to a distfile archive fixes the build on libressl2.4.3

```
index 6de3a13..7541946 100644
--- a/srcpkgs/stunnel/template
+++ b/srcpkgs/stunnel/template
@@ -10,7 +10,9 @@ short_desc="SSL encryption wrapper"
 maintainer="Christian Neukirchen <chneukirchen@gmail.com>"
 license="GPL-2"
 homepage="https://www.stunnel.org/"
-distfiles="https://www.stunnel.org/downloads/${pkgname}-${version}.tar.gz"
+distfiles="https://www.stunnel.org/downloads/archive/5.x/stunnel-5.31.tar.gz"
+# Commented out until stunnel gets bumped.
+#distfiles="https://www.stunnel.org/downloads/${pkgname}-${version}.tar.gz"
 checksum=a746b71ab3dc6c23eacb0daf7342467870e43ac933430905eb1b1d050bbae0b7
 
 post_install() {
```

kicad doesn't build due to distfile downloading, and then the wrksrc is set wrong. After that, the build is fixed.

```
--- a/srcpkgs/kicad/template
+++ b/srcpkgs/kicad/template
@@ -2,7 +2,7 @@
 pkgname=kicad
 version=4.0.4
 revision=2
-wrksrc=${pkgname}-${version%.*}
+#wrksrc=${pkgname}-${version%.*}
 build_style=cmake
 configure_args="-DKICAD_BUILD_VERSION=$version -DKICAD_SKIP_BOOST=ON
  -DKICAD_SCRIPTING=ON -DKICAD_SCRIPTING_MODULES=ON -DKICAD_SCRIPTING_WXPYTHON=ON
@@ -16,4 +16,4 @@ maintainer="Steve Prybylski <sa.prybylx@gmail.com>"
 license="GPL-2"
 homepage="http://kicad-pcb.org"
 distfiles="https://launchpad.net/${pkgname}/${version%.*}/${version}/+download/${pkgname}-${version}.tar.xz"
-checksum=3c16d38ed0779f560fd8e913150277c803ba4f270c9a8f1ea687b5878bf5c5b6
+checksum=6da5d3f7bc63a9c5b4d0f5e4b954411b45d712168596b5af02957343c87eda00
```

virtualbox-ose fails on a build system error,
`libgcc-4.9.3_4 (update) breaks installed pkg `libgcc-devel-4.9.4_1'`
and `=> ERROR: virtualbox-ose-5.1.6_3: failed to install 'gcc-c++-multilib-4.9.4_2' dependency! (error 19)`


warzone2100 builds now. Not sure why it failed earlier.

I'm happy to push this soon.

**Comment by Vaelatern** [comment]
On my box with no packages on the above list already built it took 2:17:13 to `./xbps-src pkg virtualbox-ose`

mosquitto doesn't need the patch, it's the older version. But importantly it can't find `libwebsockets.so.8.1` despite it being available.
`   SONAME: libwebsockets.so.8.1 <-> UNKNOWN PKG PLEASE FIX!`

**Comment by pullmoll** [comment]
The libwebsockets update to 2.0.3 (or earlier?) missed to add a line 
```
libwebsockets.so.8.1 libwebsockets-2.0.3_1
```
or similar to `common/shlibs`.

**Comment by Vaelatern** [comment]
```
--- a/common/shlibs
+++ b/common/shlibs
@@ -2039,7 +2039,7 @@ libcvm-v1client.so.1 cvm-0.97_1
 libcvm-v2client.so.1 cvm-0.97_1
 libudns.so.0 udns-0.4_1
 libcriu.so.1 criu-1.5.1_2
-libwebsockets.so.8 libwebsockets-2.0.0_1
+libwebsockets.so.8.1 libwebsockets-2.0.3_2
 libbitcoinconsensus.so.0 litecoin-0.10.1.2_1
 libnfc.so.0 libnfc-1.7.1_1
 libfuzzy.so.2 libfuzzy-2.12_1
```

**Comment by Vaelatern** [comment]
Caught two packages for arm and not x86_64. Ready to merge.

**Comment by Gottox** [comment]
One conflict caused by todays s-nail update and we're ready to go :balloon:

**Pull request merged**
