### PR TITLE
New package: cadence-0.8.1.20170707

### PR DESCRIPTION
**Pull request by cr6git**
resolves [#7572](https://github.com/voidlinux/void-packages/issues/7572)

### CODE REVIEW

**Comment by cr6git** [comment]
It sounds like this package cannot be cross compiled.

**Comment by cr6git** [comment]
The build failed on `x86_64-musl` **only**, I don't know why...

**Comment by Johnnynator** [comment]
The probem is that the sys/prctl.h header in glibc just inlcudes the linux/prctl.h header while on musl sys/prctl.h redefines everything. Therefore the linux/prctl.h doesn't have to be included manually (at least I think so).

```
--- c++/jackbridge/CarlaUtils.hpp	2013-07-16 06:36:57.000000000 +0200
+++ c++/jackbridge/CarlaUtils.hpp	2017-10-18 15:56:12.684964988 +0200
@@ -36,7 +36,6 @@
 # include <kernel/OS.h>
 #elif defined(CARLA_OS_LINUX)
 # include <sys/prctl.h>
-# include <linux/prctl.h>
 #endif
```

**Comment by cr6git** [comment]
Thank you @Johnnynator 
I added your patch for `x86_64-musl`.

**Comment by Johnnynator** [comment]
#8305 ladish cross compilation is fixed in this PR, but then you run into the problem that python-gobject can't be cross compiled. (And you don't have to flag cadence as nocross because you don't know if it cross compiles or not)

**Comment by cr6git** [comment]
ok I will change my template.

**Comment by cr6git** [comment]
The build is ok now! 😃

**Comment by cr6git** [comment]
Changed the source to github.

**Comment by jarbowski** [comment]
@cr6git 

thank you very much but I think it's missing python dbus to be functional:

Traceback (most recent call last):
  File "/usr/share/cadence/src/cadence_session_start.py", line 5, in <module>
    import dbus, sys
ModuleNotFoundError: No module named 'dbus'


jackdbus doesn't launch

**Comment by cr6git** [comment]
@jarbowski I probably mixed up `python-dbus` (already pulled by `jack`) with `python3-dbus` ? 

@pullmoll fixed the issue!

**Pull request closed without merging**
