### PR TITLE
Cinnamon 3.4

### PR DESCRIPTION
**Pull request by Gottox**
With this update the following has changed:

* switched from upower0 to upower
* switched from ConsoleKit2 to elogind

### CODE REVIEW

**Comment by Gottox** [comment]
Update breaks musl. I'm investigating.

**Comment by Gottox** [comment]
a click on the menu icon results in this stacktrace: 
```
Thread 22 "pool" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 2174]
0x00007fffedfd8a07 in af_glyph_hints_init (memory=0x5555568b56a0, hints=0x7fffd81d3da0) at /builddir/freetype-2.8/src/autofit/afhints.c:653
653     /builddir/freetype-2.8/src/autofit/afhints.c: No such file or directory.
(gdb) bt
#0  0x00007fffedfd8a07 in af_glyph_hints_init (memory=0x5555568b56a0, hints=0x7fffd81d3da0) at /builddir/freetype-2.8/src/autofit/afhints.c:653
#1  af_autofitter_load_glyph (module=0x5555568b9c20, slot=0x555557be05a0, size=<optimized out>, glyph_index=36, load_flags=66048)
    at /builddir/freetype-2.8/src/autofit/afmodule.c:558
#2  0x00007fffedf896b5 in FT_Load_Glyph (face=face@entry=0x555557b45d40, glyph_index=36, load_flags=load_flags@entry=66048) at /builddir/freetype-2.8/src/base/ftobjs.c:749
#3  0x00007fffefc0e3dc in _cairo_ft_scaled_glyph_init (abstract_font=0x555557c3e380, scaled_glyph=0x555557b51428, info=CAIRO_SCALED_GLYPH_INFO_METRICS) at cairo-ft-font.c:2264
#4  0x00007fffefbac887 in _cairo_scaled_glyph_lookup (scaled_font=scaled_font@entry=0x555557c3e380, index=<optimized out>, info=info@entry=CAIRO_SCALED_GLYPH_INFO_METRICS, 
    scaled_glyph_ret=scaled_glyph_ret@entry=0x7fffd81d7370) at cairo-scaled-font.c:2993
#5  0x00007fffefbacaba in INT_cairo_scaled_font_glyph_extents (scaled_font=0x555557c3e380, glyphs=glyphs@entry=0x7fffd81d73d0, num_glyphs=num_glyphs@entry=1, 
    extents=extents@entry=0x7fffd81d73f0) at cairo-scaled-font.c:1614
#6  0x00007ffff04effb2 in compute_glyph_extents (entry=0x555557b36980, glyph=36, cf_priv=0x555555961718) at pangocairo-font.c:775
#7  _pango_cairo_font_private_get_glyph_extents_cache_entry (glyph=36, cf_priv=0x555555961718) at pangocairo-font.c:798
#8  _pango_cairo_font_private_get_glyph_extents (cf_priv=0x555555961718, glyph=36, ink_rect=0x0, logical_rect=0x7fffd81d7460) at pangocairo-font.c:835
#9  0x00007fffee488654 in pango_fc_hb_font_get_glyph_advance (font=<optimized out>, font_data=<optimized out>, glyph=<optimized out>, user_data=<optimized out>)
    at pangofc-shape.c:139
#10 0x00007fffe8e1afd2 in ?? () from /lib/libharfbuzz.so.0
#11 0x00007fffe8ded142 in hb_shape_plan_execute () from /lib/libharfbuzz.so.0
#12 0x00007fffe8dec7b2 in hb_shape_full () from /lib/libharfbuzz.so.0
#13 0x00007fffee488b32 in _pango_fc_shape (font=0x5555559616a0, item_text=<optimized out>, item_length=<optimized out>, analysis=0x555557c67310, glyphs=0x555555d06020, 
    paragraph_text=<optimized out>, paragraph_length=1) at pangofc-shape.c:408
#14 0x00007ffff02c8bd8 in pango_shape_full (item_text=0x555556f64600 "A", item_length=1, paragraph_text=<optimized out>, paragraph_length=1, 
    analysis=analysis@entry=0x555557c67310, glyphs=glyphs@entry=0x555555d06020) at shape.c:116
#15 0x00007ffff02bab07 in shape_run (line=line@entry=0x5555575c7770, state=state@entry=0x7fffd81d7bb0, item=item@entry=0x555557c67300) at pango-layout.c:3300
#16 0x00007ffff02bc302 in process_item (layout=layout@entry=0x555556f5aa20, line=line@entry=0x5555575c7770, state=state@entry=0x7fffd81d7bb0, force_fit=force_fit@entry=1, 
    no_break_at_end=no_break_at_end@entry=0) at pango-layout.c:3413
#17 0x00007ffff02be7a8 in process_line (state=0x7fffd81d7bb0, layout=0x555556f5aa20) at pango-layout.c:3712
#18 pango_layout_check_lines (layout=<optimized out>) at pango-layout.c:4040
#19 0x00007ffff02c0498 in pango_layout_get_extents_internal (layout=0x555556f5aa20, ink_rect=0x0, logical_rect=0x7fffd81d7d10, line_extents=0x0) at pango-layout.c:2594
#20 0x00007ffff02c0a36 in pango_layout_get_size (layout=layout@entry=0x555556f5aa20, width=width@entry=0x7fffd81d7d9c, height=height@entry=0x7fffd81d7da0)
    at pango-layout.c:2837
#21 0x00007fffd83d6c57 in rsvg_text_render_text (y=0x7fffd81d7e18, x=0x7fffd81d7e10, text=<optimized out>, ctx=0x555557b9eb80) at rsvg-text.c:613
#22 _rsvg_node_text_type_children (ctx=ctx@entry=0x555557b9eb80, x=x@entry=0x7fffd81d7e10, y=y@entry=0x7fffd81d7e18, lastwasspace=lastwasspace@entry=0x7fffd81d7e0c, 
    usetextonly=usetextonly@entry=0, self=<optimized out>) at rsvg-text.c:182
#23 0x00007fffd83d6f80 in _rsvg_node_text_draw (self=<optimized out>, ctx=0x555557b9eb80, dominate=<optimized out>) at rsvg-text.c:298
#24 0x00007fffd83d1502 in rsvg_node_draw (dominate=0, ctx=0x555557b9eb80, self=<optimized out>) at rsvg-structure.c:54
#25 rsvg_node_svg_draw (self=0x555557bb5300, ctx=0x555557b9eb80, dominate=<optimized out>) at rsvg-structure.c:309
#26 0x00007fffd83d1e18 in rsvg_node_draw (self=<optimized out>, ctx=ctx@entry=0x555557b9eb80, dominate=dominate@entry=0) at rsvg-structure.c:54
#27 0x00007fffd83de513 in rsvg_handle_render_cairo_sub (handle=handle@entry=0x555557ab0c50, cr=cr@entry=0x5555573405a0, id=id@entry=0x0) at rsvg-cairo-render.c:224
#28 0x00007fffd83dea0f in rsvg_handle_get_pixbuf_sub (handle=0x555557ab0c50, id=id@entry=0x0) at rsvg.c:90
#29 0x00007fffd83dea97 in rsvg_handle_get_pixbuf (handle=<optimized out>) at rsvg.c:119
#30 0x00007fffd85ebe36 in gdk_pixbuf__svg_image_stop_load (data=0x555556127a80, error=0x7fffd81d8040) at io-svg.c:158
#31 0x00007fffef92c2d3 in gdk_pixbuf_loader_close () from /lib/libgdk_pixbuf-2.0.so.0
#32 0x00007fffef927beb in ?? () from /lib/libgdk_pixbuf-2.0.so.0
#33 0x00007fffef929bad in gdk_pixbuf_new_from_stream_at_scale () from /lib/libgdk_pixbuf-2.0.so.0
#34 0x00007ffff0bddc3a in icon_info_ensure_scale_and_pixbuf (icon_info=0x555557b9d630) at gtkicontheme.c:3940
#35 0x00007ffff0bdde6c in load_icon_thread (task=0x555557af9e00, source_object=<optimized out>, task_data=<optimized out>, cancellable=<optimized out>) at gtkicontheme.c:4161
#36 0x00007ffff6a1473d in g_task_thread_pool_thread (thread_data=0x555557af9e00, pool_data=<optimized out>) at gtask.c:1328
#37 0x00007ffff649883e in g_thread_pool_thread_proxy (data=<optimized out>) at gthreadpool.c:307
---Type <return> to continue, or q <return> to quit---
#38 0x00007ffff6497e45 in g_thread_proxy (data=0x555557770680) at gthread.c:784
#39 0x00007ffff7dc0e4b in start () from /lib/ld-musl-x86_64.so.1
#40 0x0000000000000000 in ?? ()

```

**Comment by asergi** [comment]
Superseded by #10178?

**Comment by Johnnynator** [comment]
Can be closed since cinnamon is updated.

**Pull request closed without merging**
