### PR TITLE
afl: fix default helper path

### PR DESCRIPTION
**Pull request by ebfe**

### CODE REVIEW

**Comment by Vaelatern** [comment]
Irrelevant. The build-style provides that already.

**Comment by ebfe** [comment]
> Irrelevant. The build-style provides that already.
No, it doesn't.

**Comment by Vaelatern** [comment]
Ah. Probably an oversight.
https://github.com/voidlinux/void-packages/blob/master/common/build-style/gnu-makefile.sh#L7-L18 Should probably be modified with this patch to put things in `/usr`

**Comment by chneukirchen** [comment]
The build-styles generally don't pass this in `do_build`... if we change it, we need to do it everywhere.

**Comment by ebfe** [comment]
Rebased. If #3582 gets merged this can be changed to a simple revbump.

**Pull request merged**
