### PR TITLE
New package: fping-3.10

### PR DESCRIPTION
**Pull request by nmeum**
See: http://fping.org/.

### CODE REVIEW

**Comment by nmeum** [comment]
Turns out: This is not under BSD. It looked BSDish, but it is licensed under a custom license. Since that means that it isn't free as in freedom because that license isn't approved by the OSI or by the FSF. I don't know how to handle this,, any hints?

**Comment by bougyman** [comment]
non-free seems good.

**Comment by nmeum** [comment]
Done. I wasn't sure what to call the license so I just decided to call it 'fping'. Should I install that license using `vlicense`?

**Comment by xtraeme** [comment]
The license used in fping is a MIT-alike one, so that it's completely free.

**Pull request closed without merging**
