### PR TITLE
New package: bombsquad

### PR DESCRIPTION
**Pull request by cr6git**
Explosive game [BombSquad](http://www.froemling.net/apps/bombsquad). 
I took the license [here](http://www.froemling.net/apps/bombsquad/terms-of-use).

### CODE REVIEW

**Comment by pullmoll** [comment]
This one probably needs `repository="nonfree"` because the license is.

**Comment by Vaelatern** [comment]
License and desktop file should be downloaded by some means which do not mean including them in the repo.

**Comment by cr6git** [comment]
desktop file may be downloaded from [AUR](https://aur.archlinux.org/cgit/aur.git/tree/bombsquad.desktop?h=bombsquad) ... however, I can't figure out a way to download the license [bombsquad/terms-of-use](http://www.froemling.net/apps/bombsquad/terms-of-use), it's HTML and illegible text.

**Comment by Vaelatern** [comment]
So download as `LICENSE.html`?

**Comment by Vaelatern** [comment]
I'd rather a `.desktop` source other than the AUR. Where did the AUR get it from? Why isn't it contributed upstream?

**Comment by cr6git** [comment]
Ah yes! it reminded me of the `gendesk` utility: [github.com/xyproto/gendesk](https://github.com/xyproto/gendesk)

**Comment by cr6git** [comment]
I updated the template, but the build does not start... :confused:

**Comment by Vaelatern** [comment]
I agree.

**Comment by cr6git** [comment]
was sent to prison, with `madbomber`.

**Comment by Vaelatern** [comment]
Prison?

**Comment by cr6git** [comment]
it was a joke 😉

**Pull request closed without merging**
