### PR TITLE
timestamp-macros: fix creation and add cleanup

### PR DESCRIPTION
**Pull request by pullmoll**
As described in #3765

Afterwards the package `perl` must be rebuilt to clean the leaked flags.
There may be more packages which were built since the timestamp-macros were introduced.

### CODE REVIEW

**Comment by Gottox** [comment]
It's an ugly hack, but I think it's reasonable enough till the real issue is found.

**Comment by ebfe** [comment]
Can we have a flag to disable the timestamps machinery from the template ('nofixedtimestamps=yes')? This likely also affects other packages where this workaround doesn't work.

**Comment by Gottox** [comment]
This is a bug in xbps-src, not in the packages. There's no reason to disable it for specific packages.

**Comment by ebfe** [comment]
> This is a bug in xbps-src, not in the packages. There's no reason to disable it for specific packages.
Same could be said for most of the nocross=yes instances...

**Comment by pullmoll** [comment]
@Gottox I disagree. There is no bug in xbps-src. If you add something to the CFLAGS or CXXFLAGS, like the timestamps stuff does, any development package can assume the flags are valid for building other packages depending on them.

A possible solution might be to modify the CFLAGS and CXXFLAGS only after the package to be built was configured. That could perhaps happen in a pre-build hook. In case the package creates shell scripts, configuration files, package config files or similar which in the configure stage, there's a good chance the timestamps additions won't leak.

FWIW I now built about 800 packages without trouble with this workaround.

**Comment by pullmoll** [comment]
As I saw just now in the package `ImageMagic` the timestamp macros flags leak into an XML file:
```
=> WARNING: Can't clean /usr/lib/ImageMagick-6.9.3/config-Q16/configure.xml (mime-type: application/xml) ...
```
So the `07-cleanup-timestamp-macros.sh` should include `"application/xml"` as well.

**Comment by Gottox** [comment]
Adding a flag to disable reproducible builds is not an option in any way.

But we need a fix for that. I'm more and more considering the compiler patches instead of the CFLAGS.

**Comment by pullmoll** [comment]
Seriously, switching to a gcc (cpp) patch is the only way to prevent demolishing a lot of packages!

It should be considered and implemented rather soon, because every updated package may now pick up the leaked, wrong C{,XX}FLAGS and later on cause trouble for everyone.

**Pull request merged**
