### PR TITLE
papirus-icon-theme: update to 20180501.

### PR DESCRIPTION
**Pull request by cr6git**
For a package (typically an icon-theme) containing millions of files, it's faster to extract the tarball directly to `${DESTDIR}`. This is why I modified the `do_install()` stage.

Correct me if I am wrong, of course.
ping @gspe

### CODE REVIEW

**Comment by cr6git** [comment]
`The log length has exceeded the limit of 4 MB`

**Comment by gspe** [comment]
Hi,
for sure you are more expert and have more experience  that me,I still have a lot of thing to learn so I agree with you.

**Comment by cr6git** [comment]
I may have experience, but I am certainly not an expert. :laughing:

**Comment by cr6git** [comment]
I just updated to 20180501.

**Comment by cr6git** [comment]
@gspe I have the impression that my pull request got lost in the long list of PRs. :unamused: 

I close.

**Pull request closed without merging**
