### PR TITLE
New package: perl-Math-Prime-Util-0.65

### PR DESCRIPTION
**Pull request by newbluemoon**
Package request #7531.

### CODE REVIEW

**Comment by chneukirchen** [comment]
So quick, thanks!

**Comment by newbluemoon** [comment]
Just wasn’t busy atm ;-)

**Comment by newbluemoon** [comment]
Cross compilation of perl-Math-Prime-Util-GMP fails and perl-Math-Prime-Util doesn’t detect gmp because `Makefile.PL` uses the Devel::CheckLib module which compiles some code and then tries to execute it.

So I disabled the tests by adding to the perl-Math-Prime-Util-GMP template:
<pre>
if [ -n "$CROSS_BUILD" ]; then
	pre_configure() {
		sed -i -e "s/^check_lib_or_exit(lib => 'gmp', header => 'gmp.h');//" Makefile.PL
	}
fi
</pre>

and to the perl-Math-Prime-Util template:
<pre>
if [ -n "$CROSS_BUILD" ]; then
	pre_configure() {
		sed -i -e "s/^\(my \$have_gmp =\).*/\1 1;/" Makefile.PL
	}
fi
</pre>

From my point of view this should be OK, because gmp-devel is specified in `makedepends` and is there anyway. Should I open a new PR to add these changes?

**Comment by chneukirchen** [comment]
Yes, this fix is fine. Please make a PR.

**Pull request merged**
