### PR TITLE
khal: update to 0.9.9.

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by asergi** [comment]
Broken: https://github.com/pimutils/khal/commit/0fea680afa1cb0e13220f98948dbfe95ad22876c

**Comment by Gottox** [comment]
Thanks, feel free to mention me in such cases.

**Comment by Gottox** [comment]
I'm going to be more careful with python merges now :)

**Comment by asergi** [comment]
Fixed in https://github.com/void-linux/void-packages/commit/b20b5f8f586196587e5f52ceb167cc48f8f0e5aa.

**Pull request closed without merging**
