### PR TITLE
New package: go-md2man-1.0.6

### PR DESCRIPTION
**Pull request by ackalker**

### CODE REVIEW

**Comment by ackalker** [comment]
This can be used as build dependency for `docker` package to build man pages.

**Comment by ebfe** [comment]
You can depend on the host version of the package. See gnubg or postfix for example.

**Comment by ackalker** [comment]
Depending on host package doesn't seem to work, at least not for Travis-CI. How to fix?

**Comment by ebfe** [comment]
Try executing the correct binary ;) (/destdir/aarch64-linux-gnu/go-md2man-1.0.6/usr/bin/go-md2man is the wrong one).

Either way not sure if this works on travis.

**Comment by ebfe** [comment]
```
       if [ "$CROSS_BUILD" ]; then
               /usr/bin/go-md2man -in=go-md2man.1.md -out=go-md2man.1
       else
               ${DESTDIR}/usr/bin/go-md2man -in=go-md2man.1.md -out=go-md2man.1        
       fi
```

**Comment by ebfe** [comment]
Or just drop the manpage and `vdoc` the markdown instead, it doesn't seem very useful anyways.

**Comment by maxice8** [comment]
already in repos

@ebfe please close

**Pull request closed without merging**
