### PR TITLE
New package: openbazaar-1.0.6

### PR DESCRIPTION
**Pull request by ananteris**

### CODE REVIEW

**Comment by Vaelatern** [comment]
Travis fails in xlint. https://travis-ci.org/voidlinux/void-packages/jobs/114355543

**Comment by ananteris** [comment]
What's the significance of failing xlint?

**Comment by ananteris** [comment]
commit ammended.

**Comment by Vaelatern** [comment]
`repository="nonfree"`

**Comment by Vaelatern** [comment]
Are there no runtime dependencies?

**Comment by Vaelatern** [comment]
933e668

**Pull request closed without merging**
