### PR TITLE
alsa-firmware: prevent conflict with linux-firmware

### PR DESCRIPTION
**Pull request by cr6git**
To help [#8113](https://github.com/voidlinux/void-packages/issues/8113)

### CODE REVIEW

**Comment by cr6git** [comment]
Error, again. 
````
[*] Downloading binary packages

ERROR: [trans] failed to download `xbps-triggers-0.102_3' package from `http://198.204.250.219/current': Operation timed out

=> ERROR: Failed to install bootstrap packages!
````

**Comment by jcjordyn130** [comment]
Try another mirror.

**Comment by cr6git** [comment]
it's okay now ! 😃

**Comment by jcjordyn130** [comment]
Nice

**Comment by Duncaen** [comment]
I think the files should be removed from `alsa-firmware` instead.
`alsa-firmware` is newer and users that use on of those firmwares only have `linux-firmware` installed and would need to switch to `alsa-firmware`.

**Comment by cr6git** [comment]
@Duncaen ok I modified `alsa-firmware` instead.

**Comment by cr6git** [comment]
Remove the unneeded files during `post_install()` , do you agree @Duncaen ?

**Pull request merged**
