### PR TITLE
New package: plank-0.9.1

### PR DESCRIPTION
**Pull request by steski**

### CODE REVIEW

**Comment by pullmoll** [comment]
Probably needs `hostmakedepends="... gdk-pixbuf ..."` or `gdk-pixbuf-devel` to cross compile?

**Comment by xtraeme** [comment]
Please add `gdk-pixbuf-devel` to `hostmakedepends` to the `plank` template, this should fix cross compilation.

Looks good otherwise, thanks :+1:

**Comment by xtraeme** [comment]
Please rebase to avoid the merge commit.

**Comment by steski** [comment]
Sorry bout that... <code>gdk-pixbuf-devel</code> had to be added to <code>libwnck</code> to fix cross-compilation.

**Pull request merged**
