### PR TITLE
New package: cbatticon-gtk2

### PR DESCRIPTION
**Pull request by cr6git**
Package Request [#7281](https://github.com/voidlinux/void-packages/issues/7281), based on the AUR [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=cbatticon-gtk2).

### CODE REVIEW

**Comment by Johnnynator** [comment]
You could use the gnu-makefile build style instead of none.

**Comment by cr6git** [comment]
@Johnnynator I know there is a Makefile, but if I use `build_style=gnu-makefile` in this template it generates an error with `glib.h` , see [paste](https://bpaste.net/show/2b0278ced85d) ...

**Comment by Johnnynator** [comment]
have you tried setting make_use_env ?

**Comment by cr6git** [comment]
Hurray!! Yes it was that, you are good ;)

**Pull request closed without merging**
