### PR TITLE
usbmuxd: move to usr/bin.

### PR DESCRIPTION
**Pull request by thypon**

### CODE REVIEW

**Comment by kylesusername** [comment]
why exactly are you moving all of these to /usr/bin?

**Comment by thypon** [comment]
because /usr/sbin would became a symlink to /usr/bin shortly.

**Comment by kylesusername** [comment]
But if these commands are meant to be run as root, then /usr/sbin is their standardized home.

**Comment by beefcurtains** [comment]
@kylesusername sbin has been deprecated in void for some time, the templates just hadn't been updated to reflect that until recently. xtraeme is through 75% of his list now.

**Comment by thypon** [comment]
Nowadays this division is more or less ridiculous. The capability system is in place synce years and unless you want a single prefixed directory for every single capability (like rbin for NET_RAW capability for example) it's here only to complicate things.

**Comment by kylesusername** [comment]
@beefcurtains Ah, okay. Good to know. 
@thypon Pardon me for not knowing about this deprecation.

**Comment by dominikh** [comment]
Can't we/you update all these packages in a single PR (one commit per changed package)? That'd avoid a lot of work, and merge commits.

**Comment by thypon** [comment]
Yep, we could. But i like to do this thing gradually and with some peer review. On archlinux this change broke the distro badly for some day (imho because was too repentine).

**Pull request merged**
