### PR TITLE
gnome-online-accounts: update to 3.22.4

### PR DESCRIPTION
**Pull request by Sir-Boops**
also removed some unneeded flags.

### CODE REVIEW

**Comment by SirDoctors** [comment]
Just being curious, but how were those flags unneeded?

**Comment by Sir-Boops** [comment]
Those options are enabled by default so no need for a ++

**Comment by SirDoctors** [comment]
Alright, that was what I assumed.

**Comment by Sir-Boops** [comment]
Updated in 468648c9751d04c19343338af8207528bf72dc16

**Pull request closed without merging**
