### PR TITLE
New package: z80ex-1.1.21

### PR DESCRIPTION
**Pull request by diogoleal**

### CODE REVIEW

**Comment by pullmoll** [comment]
This one should have a devel subpackage, or every package linkit against the shared libs `libz80ex.so.1` or `libz80ex_dasm.so.1` would install the static libs for no reason.

```
z80ex-devel_package() {
        short_desc+=" - development files"
        depends="${sourcepkg}>=${version}_${revision}"
        pkg_install() {
                vmove usr/include
                vmove usr/lib/*.a
                vmove usr/lib/*.so
        }
}
```

**Comment by diogoleal** [comment]
Sorry for my mistake.

**Comment by pullmoll** [comment]
You forgot to add the symlink `z80ex-devel` (after doing `ln -s z80ex srcpkgs/z80ex-devel`) to this PR.

**Comment by diogoleal** [comment]
ops. I forgot this link, sorry again.

**Pull request merged**
