### PR TITLE
elogind: cleanup after doing tests.

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by Gottox** [comment]
Is there a way to adjust the tests so that they don't access the files?

**Comment by maxice8** [comment]
On Tue, Jan 16, 2018 at 04:26:26AM -0800, Enno Boland wrote:
> Is there a way to adjust the tests so that they don't access the files?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/voidlinux/void-packages/pull/10879#issuecomment-357944709

problably but i won't mess up with C source code.

**Comment by Gottox** [comment]
os-release can easily be overwritten, machine-id is harder to change.

**Comment by maxice8** [comment]
sorry but i don't understand what's the big wop.

**Comment by Gottox** [comment]
Let's get this merged, and do the rest later 👍

**Pull request merged**
