### PR TITLE
lxqt-build-tools: update to 0.4.0

### PR DESCRIPTION
**Pull request by cr6git**
This update is needed, in order to build `compton-conf` [version 0.3.0](https://github.com/lxde/compton-conf/releases).

### CODE REVIEW

**Comment by maxice8** [comment]
https://github.com/voidlinux/void-packages/pull/8441

**Comment by cr6git** [comment]
Fine, I'll do that then.

**Comment by maxice8** [comment]
There is no need since lxqt-builds-tools and obconf-qt are already being updated together with the rest of the lxqt suite on #8441 , just some cross-compilation issues need to be ironed out

**Comment by cr6git** [comment]
Ah yes, exactly!

**Pull request closed without merging**
