### PR TITLE
mergerfs: update to 2.23.1.

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by cr6git** [comment]
`maintainer="xinterer <xinterer@users.noreply.github.com>"`

maintainer needs a valid address for sending mail

**Comment by maxice8** [comment]
Sadly can't help with that, that's the person's only know email adress

**Comment by cr6git** [comment]
It looks like the original maintainer @xinterer is no longer active [on github](https://github.com/xinterer).

**Comment by Gottox** [comment]
change to `maintainer="Orphaned <orphan@voidlinux.eu>"`

**Pull request merged**
