### PR TITLE
Opencv

### PR DESCRIPTION
**Pull request by Vaelatern**

### CODE REVIEW

**Comment by Vaelatern** [comment]
nomacs and -qt5 should be bumped. Will take care if it later if nobody else does it today.

**Comment by Vaelatern** [comment]
Man that's complicated,

**Comment by Vaelatern** [comment]
With the `nomacs` version bump, we'd need to lose `nomacs` and replace it with the `nomacs-qt5` variant, since upstream doesn't support `libopencv-3.1` and `qt4` at the same time.

**Comment by asergi** [comment]
`nomacs` bumped. All issues should be solved now.

**Comment by asergi** [comment]
Apply the following patch to `opencv`: https://patch-diff.githubusercontent.com/raw/Itseez/opencv/pull/5861.patch. That should fix your issue with `gmic`.

**Comment by asergi** [comment]
`gmic` package fixed.

**Comment by Vaelatern** [comment]
Now `nomacs`, `gmic`, both build fine. It's now `actiona` that's at fault. I'll have a poke later.

**Comment by Vaelatern** [comment]
There are no patches in the actiona tree to fix this

**Pull request merged**
