### PR TITLE
faad2: try to fix crash in icecat/firefox

### PR DESCRIPTION
**Pull request by pullmoll**
Try to fix issue #2461

### CODE REVIEW

**Comment by thypon** [comment]
wow fixes the bugs.

**Comment by pullmoll** [comment]
Fine! So my guess was right.

**Comment by thypon** [comment]
i actually don't get why this bug presents only on musl.

**Comment by pullmoll** [comment]
Perhaps the code is actually buggy and writes beyond the margins of the array? On the stack this easily causes faults, in static memory it may write in other others which goes unnoticed.

I'd try to run firefox under valgrind with the debug binaries to see if it reports anything in libfaad2.

**Pull request merged**
