### PR TITLE
New package: pithos-1.3.1

### PR DESCRIPTION
**Pull request by OSN64**

### CODE REVIEW

**Comment by Vaelatern** [comment]
First review:
Template doesn't look awful, commit message is totally wrong (but depending on your comfort with git this may just be something I should fix myself) and your INSTALL.msg is at least wrong, but probably should be removed.
Pending actual review later.

**Comment by OSN64** [comment]
Ah, ill fix the commit message, missed it in the CONTRIBUTING.md. How should i specify optional dependencies?

**Comment by Vaelatern** [comment]
It's in Manual.md
Currently we don't specify optional deps, but how optional are they?

**Comment by OSN64** [comment]
They enable these plugins. So they are not needed to run the application.
Mpris: Allows player control via dbus. - python3-dbus 
Lastfm: Scrobble tracks listened to on Last.fm - python-pylast

**Comment by the-maldridge** [comment]
merged with minor changes

**Pull request closed without merging**
