### PR TITLE
New package: octoxbps-0.1.0

### PR DESCRIPTION
**Pull request by beefcurtains**
Qt frontend for xbps

### CODE REVIEW

**Comment by pullmoll** [comment]
The result is rather empty, or is it?
The musl build log tells there's a function without return value.

**Comment by beefcurtains** [comment]
It's like Qt went insane overnight. Can't get qtpass and quimup to install, either.

Tried to build locally, but I ran out of device space.

**Comment by pullmoll** [comment]
I think you just need to
```
do_install() {
        make INSTALL_ROOT="${DESTDIR}" install
}
```

**Comment by beefcurtains** [comment]
No amount of extra variables will make it do something. The problem may be in the ``.pro`` file, but I already tried things from other projects and it didn't work right. The error here goes like ``Nothing to do for target ''install''``.

**Comment by pullmoll** [comment]
You can do this in `do_configure()`
```
        sed -i ${pkgname}.pro -e "/DESTDIR += /s;bin;${DESTDIR}/usr/bin;"
```
or alternatively
```
do_install() {
        vbin bin/${pkgname}
}
```

Adding some `octoxbps.desktop` file to `/usr/share/applications` and also adding some icon to `/usr/share/pixmaps` would be helpful for the average GUI user :)
And the package should depend on either `gksu` or `kdesu` as mentioned in the `README`

**Comment by beefcurtains** [comment]
It has occurred to me to just ``vbin`` the binary, but that doesn't cover anything that should go into /usr/share, like icons.

**Comment by pullmoll** [comment]
Icons are compiled in as a resource through the generated `qrc_resources.cpp`.
I tested the app and it seems to work so far. I didn't test it with kdesu or gksu, though.

**Comment by beefcurtains** [comment]
I'm waiting for Qt to compile locally, then I'll build the package myself and test it more thoroughly.

**Pull request merged**
