### PR TITLE
gnome-online-accounts: update to 3.18.1

### PR DESCRIPTION
**Pull request by pullmoll**

### CODE REVIEW

**Comment by Gottox** [comment]
Can you explain what this change is actually fixing?

**Comment by pullmoll** [comment]
It makes gnome-online-accounts compile.
Without the autoreconf I get this error:
```
=> gnome-online-accounts-3.18.0_2: running pre-build hook: 02-script-wrapper ...
=> gnome-online-accounts-3.18.0_2: running do_build ...
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /builddir/gnome-online-accounts-3.18.0/missing aclocal-1.14 -I m4 
/builddir/gnome-online-accounts-3.18.0/missing: line 81: aclocal-1.14: command not found
WARNING: 'aclocal-1.14' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
Makefile:460: recipe for target 'aclocal.m4' failed
make: *** [aclocal.m4] Error 127
=> ERROR: gnome-online-accounts-3.18.0_2: failed to run do_build() at line 13.
```

**Comment by pullmoll** [comment]
Perhaps we could avoid autoreconf, if we kept an automake1.14 package?

**Comment by Gottox** [comment]
Try adding `gettext-devel` to hostmakedepends.

**Comment by pullmoll** [comment]
Updating to 3.18.1 solves all issues.

**Pull request merged**
