### PR TITLE
abcm2ps: update to 8.11.2.

### PR DESCRIPTION
**Pull request by Vaelatern**
@lemmi, your sign-off on this would be appreciated.

### CODE REVIEW

**Comment by Vaelatern** [comment]
Relevant Travis build: https://travis-ci.org/Vaelatern/void-packages/builds/118839668

**Comment by Vaelatern** [comment]
Relevant travis build (as well as ours): https://travis-ci.org/Vaelatern/void-packages/builds/118839668

**Comment by lemmi** [comment]
@Vaelatern, I just finished testing my tunes on x64 without errors.

**Comment by Vaelatern** [comment]
fcc5a73

**Pull request closed without merging**
