### PR TITLE
gnumeric: updated to 1.12.22

### PR DESCRIPTION
**Pull request by hanspolo**

### CODE REVIEW

**Comment by xtraeme** [comment]
Please add `gdk-pixbuf-devel` to `hostmakedepends` to fix cross compilation.

**Comment by hanspolo** [comment]
I updated it.

**Comment by xtraeme** [comment]
Thanks :+1:

**Comment by xtraeme** [comment]
Looks like gdx-pixbuf-devel wasn't enough, but it's ok for now.

**Pull request merged**
