### PR TITLE
New package: riot-desktop-0.13.5

### PR DESCRIPTION
**Pull request by zethra**
I've seen from reading the issues that ya'll are not the most fond of electron apllications (and rightfully so).  But I hope ya'll will accept this one.  Matrix is a great messaging protocol and Riot is the best full-featured desktop client for it.  I'm new to void so if ya'll find any issues with my package I'll try to fix them.

### CODE REVIEW

**Comment by zethra** [comment]
Will do.

**Comment by zethra** [comment]
I realized there is an issue. Don't merge yet please.

**Comment by Vaelatern** [comment]
change the title back when you are ready for merge.

**Comment by zethra** [comment]
@Vaelatern It's ready to be merged now.

**Pull request closed without merging**
