### PR TITLE
New package: jeti-filemanager-1.1.1

### PR DESCRIPTION
**Pull request by mrshampoo**
this will not work. i have already done this probably twice

### CODE REVIEW

**Comment by pullmoll** [comment]
I suggest you
+ 1. reset your fork of void-packages to master
+ 2. create or copy the `srcpkgs/jeti-filemanager/template` again
+ 3. add, commit and comment with `New package: jeti-filemanager-1.1.1`
+ 4.  in the future only use `git commit --amend` after adding changes
+ 5. If you need to merge from `voidlinux/void-packages` master, always use `git pull --rebase`
+ 6. stop closing and creating new pull requests because it annoys everyone

**Comment by mrshampoo** [comment]
oh sorry i dint know. i just wanted the dam thing to work.

**Comment by pullmoll** [comment]
No problem, we all once began to annoy everyone until we learned how to do it right :)
FWIW If you want to add more packages, create a separate branch for each package in your fork of void-packages, or github will start to mix changes to your master into unrelated pull requests.

**Comment by pullmoll** [comment]
Here's a suggestion for a cleaned up Makefile which works with xbps-src without any extra changes required in the template.
It changes the meaning of `DESTDIR` and adds `PREFIX` such that:
+ `DESTDIR` is the install root directory (default: `/`)
+ `PREFIX` is the base path inside `$(DESTDIR)` where to install (default: `/usr`)

Further changes:
+ The variables which may need to be overriden by a build system are default initialized with `?=`
+ Instead of `mkdir(1)` and `cp(1)` it uses `install(1)` to install files
+ It adds a target `all:` which depends on `$(OBJDIR)` to only once create the obj path.
+ The target `install:` depends on `all` so you can just call `make install` in one go.

```
TARGET = jeti

DESTDIR ?= /
PREFIX ?= /usr

CONFIG = jeti.rc
CONFDIR = share/jeti
OBJDIR = obj
INCDIR = include
BINDIR = bin

INCLUDES = $(addprefix $(INCDIR)/,autocomplete.h command-window.h directorys.h environment.h handleflags.h navigation.h projecttypes.h soundeffects.h systemlog.h window.h)
OBJECTS := $(addprefix $(OBJDIR)/,main.o handleflags.o systemlog.o soundeffects.o navigation.o environment.o autocomplete.o window.o command-window.o directorys.o)

CC ?= gcc
CFLAGS ?= -g -Wall
LIBS ?= -lncurses

all:	$(OBJDIR) $(BINDIR)/$(TARGET)

$(OBJDIR):
	mkdir -p $(OBJDIR)

$(OBJDIR)/%.o: %.c $(INCLUDES)
	$(CC) $(CFLAGS) $(LIBS) -c $< -I$(INCDIR) -o $@

$(BINDIR)/$(TARGET): $(OBJECTS)
	mkdir -p $(BINDIR)
	$(CC) $(CFLAGS) $(LIBS) $^ -o $@

install: all $(CONFDIR)/$(CONFIG)
	install -D $(BINDIR)/$(TARGET) -t $(DESTDIR)$(PREFIX)/bin/
	install -D $(CONFDIR)/* -t $(DESTDIR)$(PREFIX)/$(CONFDIR)/

uninstall: $(DESTDIR)/bin/$(TARGET) $(DESTDIR)/$(CONFDIR)
	rm -f $(DESTDIR)$(PREFIX)/bin/$(TARGET)
	rm -rf $(DESTDIR)$(PREFIX)/$(CONFDIR)

.PHONY : clean
clean:
	rm -f $(BINDIR)/$(TARGET) $(OBJECTS)
	rm -r $(BINDIR) $(OBJDIR)
```

**Comment by mrshampoo** [comment]
thank you so mush! :D
this is exactly what i need. just thank you, thank you, thank you!

**Comment by mrshampoo** [comment]
now what? :)

**Comment by Vaelatern** [comment]
Now, if you would, please try to make all 13 of these commits into just 1 commit. You do this by git rebasing. You don't need to close or reopen the PR, just force push to your master branch (in this case since the PR is from your master).

**Comment by mrshampoo** [comment]
# git rebase -i adadf65
"pick adadf65
s b2e9eaf
s 5cbb464
s ddd0e9e
s 7dc97c5
s 4ba4ff9
s 0bcfcf9
s 7cff2c0
s 6adae9a
s d25afb6
s eede11a
s 44e2603
s 1f96b8e"
# git commit --allow-empty
this doesn't seem to have made the trick :( 
it was almost easier to program jeti itself then to get it uploaded

**Comment by pullmoll** [comment]
I don't know what `git commit --allow-empty` would be good for here.
After squashing all your commits into one just do `git push -f`.

**Comment by mrshampoo** [comment]
"The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty"

**Comment by pullmoll** [comment]
Well, this is because you rebased on the wrong `<id>`. Look at `git log` and find the first `<id>` *before* you started adding and committing for jeti-filemanager.

**Comment by mrshampoo** [comment]
git log
fatal: bad default revision 'HEAD'
i have absolutely no ide any longer of what i am doing...
i will quit for to day and drive home to my parents house and celebrate easter instead.

**Comment by Gottox** [comment]
please reopen this issue once you've cleaned up ;)

**Pull request closed without merging**
