### PR TITLE
font-awesome: update to 5.0.13.

### PR DESCRIPTION
**Pull request by DirectorX**

### CODE REVIEW

**Comment by cr6git** [comment]
it closes [#14057](https://github.com/voidlinux/void-packages/pull/14057)...

**Comment by cr6git** [comment]
@DirectorX see [#14361](https://github.com/voidlinux/void-packages/issues/14361)...

**Comment by lemmi** [comment]
Closing #14361

**Comment by cr6git** [comment]
[#14375](https://github.com/voidlinux/void-packages/pull/14375)

**Pull request closed without merging**
