### PR TITLE
ifupdown: update to 0.8.28.

### PR DESCRIPTION
**Pull request by maxice8**
wasn't thoroughly tested.

### CODE REVIEW

**Comment by the-maldridge** [comment]
Try to pay more attention when updating.  This version is explicitly marked as not released by upstream.

**Comment by maxice8** [comment]
Where ? checking their git they [sent](https://anonscm.debian.org/git/collab-maint/ifupdown.git/commit/?id=33ca99198e6e177d5963f80d1ea7a669df0867a2) to debian unstable 8 hours ago

**Comment by the-maldridge** [comment]
Hmm, you are correct.  I will discuss this on IRC and see if we are willing to accept this in as a stable package.

**Comment by maxice8** [comment]
0.8.25 was updated without hiccups even being marked as [unstable](http://metadata.ftp-master.debian.org/changelogs/main/i/ifupdown/unstable_changelog)

**Comment by the-maldridge** [comment]
Have you checked to see if this version works with musl again?

**Comment by maxice8** [comment]
On Wed, Oct 25, 2017 at 08:43:12PM -0700, Michael Aldridge wrote:
> Have you checked to see if this version works with musl again?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/voidlinux/void-packages/pull/8563#issuecomment-339542457

No i do not test musl binaries only x86_64 binaries, libs and noarch python modules, perl modules.

If you want i can spin a lxc void-musl container to run it

**Comment by maxice8** [comment]
Worked on a void-musl container built with xbps-src and separated with `Containers` package

**Pull request closed without merging**
