### PR TITLE
libressl: update to 2.5.5.

### PR DESCRIPTION
**Pull request by Gottox**

### CODE REVIEW

**Comment by ebfe** [comment]
Anything including `openssl/x509v3.h` and is using `EXFLAG_SI`/`EXFLAG_SS` might need a rebuild/patch.

**Comment by Gottox** [comment]
https://gist.github.com/288f0298b3955be36e95c5435b237648

Afaik those are only formatting changes. ABI should be stable. Nevertheless, odd to change this in a micro release.

**Comment by ebfe** [comment]
No

```diff
-#define EXFLAG_SI              0x20
-#define EXFLAG_SS              0x20
...
+#define EXFLAG_SI              0x0020  /* Self issued. */
...
+#define EXFLAG_SS               0x2000 /* Self signed. */
```

**Comment by Gottox** [comment]
Ah, now I get what you're saying.

This won't change the current behavior though. Nevertheless, lets dig through the sources...

**Comment by ebfe** [comment]
> This won't change the current behavior though.

Ah, right. Seems `EXFLAGS_SS` is never set alone, only in addition to `EXFLAGS_SI`.

**Comment by Gottox** [comment]
```
chromium-58.0.3029.110/chromium-58.0.3029.110.tar.xz Binary file (standard input) matches
libressl-2.5.4/libressl-2.5.4.tar.gz     if (x->ex_flags & EXFLAG_SS)
libressl-2.5.4/libressl-2.5.4.tar.gz     if (x->ex_flags & EXFLAG_SS)
libressl-2.5.4/libressl-2.5.4.tar.gz #define V1_ROOT (EXFLAG_V1|EXFLAG_SS)
libressl-2.5.4/libressl-2.5.4.tar.gz #define EXFLAG_SS           0x20
mono-5.0.1.1/mono-5.0.1.1.tar.bz2 Binary file (standard input) matches
musescore-2.1.0/v2.1.0.tar.gz Binary file (standard input) matches
nodejs-8.1.4/node-v8.1.4.tar.gz Binary file (standard input) matches
qt5-5.8.0/qt-everywhere-opensource-src-5.8.0.tar.xz Binary file (standard input) matches
qt5-doc-5.8.0/qt-everywhere-opensource-src-5.8.0.tar.xz Binary file (standard input) matches
synergy-1.8.8/v1.8.8-stable.tar.gz Binary file (standard input) matches
```

**Comment by ebfe** [comment]
1128366eb3e3652897121a284f98a1caba6ed4b1

**Pull request closed without merging**
