### PR TITLE
New package: scala-2.11.8 and sbt-0.13.12

### PR DESCRIPTION
**Pull request by crater2150**
Using the binary distribution, because building scala from source requires scala and sbt (which in turn requires scala and sbt for building).

Also added sbt, requested in #1177

### CODE REVIEW

**Comment by Vaelatern** [comment]
A "bootstrap" flag which gets the binaries, but you can turn off to build off of itself, would be good.

**Comment by crater2150** [comment]
I'm not sure I understand how this works. As far as I can tell, the bootstrap flag causes the package to be installed from the host repository with `./xbps binary-bootstrap`, but how is that initial package in the repository built? For example the template for make does not contain anything about how to build it whithout make.

**Comment by xtraeme** [comment]
Bootstrap pkgs expect software available in the host system. See the
xbps-src script forma details.

**Comment by Vaelatern** [comment]
I was referring to a `build_option` for bootstrap, much like we have for OpenJDK.

**Pull request closed without merging**
