### PR TITLE
glib: downgrade to 2.52.1

### PR DESCRIPTION
**Pull request by E100Beta**
Fixes https://github.com/voidlinux/void-packages/issues/6375

### CODE REVIEW

**Comment by ebfe** [comment]
https://github.com/GNOME/glib/commits/glib-2-52. There are very few commits between 2.52.1 and 2.52.2. Only https://github.com/GNOME/glib/commit/2b47c8360c70a8455d61fa4bb94ec57b93bf228e looks like it cause this. Care to try with this patch reverted?

**Comment by ebfe** [comment]
https://github.com/GNOME/glib/commit/5d74233476d61771b4d67d50bec5420f551ef922 might be the fix.

**Comment by E100Beta** [comment]
@ebfe Huge thanks! Tested `glib-2.52.2_2` just now, Libreoffice works fine!

**Comment by ebfe** [comment]
Thanks for identifying the source :)

**Comment by xtraeme** [comment]
Michael you are the MAN

**Pull request closed without merging**
