### PR TITLE
WIP: New Package: Linphone an ever annoing to built sip client

### PR DESCRIPTION
**Pull request by Johnnynator**
~~I will check later if it is possible to let antlr3 generate the needed c code for belle-sip on another system and then use it on all the other systems where we don't have Java.~~

Cross compiling results in unusable devel packages for use when compiling natively (and vice versa)

The PR is based on #5354

### CODE REVIEW

**Comment by Johnnynator** [comment]
Why is Travis never working as expected, both failing builds just compile fine on my system...

**Comment by wagnerflo** [comment]
Are you planning to work on this again? I'd be a user/tester of your package...

**Comment by Johnnynator** [comment]
I will try to fix some new bugs (doesn't compile anymore) tomorrow and the ask someone to finally review it (so it doesn't rot another 4 month here)

**Comment by wagnerflo** [comment]
Thank you!

**Comment by Johnnynator** [comment]
@wagnerflo If you want you can compile the linphone package yourself and test it.
The qt gui (linphoneqt package) does built but will not run before qt5.9 is merged into void.

**Comment by Johnnynator** [comment]
Damm, it seems linke I broke it somewhere so it will take more time. It compiles fine but anything related to network doesn't work at all (which is everything useful)

**Comment by Johnnynator** [comment]
Everything should be fine now, my problem was a problem in the new qt gui.
I will add the Qt gui in a later PR since we need qt>5.9 for that.

**Comment by Vaelatern** [comment]
Oh, please do open this on the new fork

**Comment by Johnnynator** [comment]
I will once I got everything in a more usable manner (aka working cross builds)

**Pull request closed without merging**
