### PR TITLE
New package: iridium-58.0

### PR DESCRIPTION
**Pull request by faulesocke**
Iridium is a modified version of chromium intended to enhance user privacy. The template is basically a copy of the chromium template with minor fixes to it.

### CODE REVIEW

**Comment by ebfe** [comment]
The general consensus seems to be to not add any more browsers to repo for now.

**Comment by faulesocke** [comment]
Okay, I accept that but would like to note, that Iridium is easy to maintain since it's *really* similar to chromium. And @Gottox tried to include it back in 2016 but it failed for some reason.

**Comment by faulesocke** [comment]
Is there still interest in this? Otherwise I'll close the PR.

**Comment by travankor** [comment]
@faulesocke Upstream is no longer in sync with chromium's release schedule. Maybe you can help package [this](https://github.com/Eloston/ungoogled-chromium/issues/375) instead?

**Comment by avoidr** [comment]
I would have liked Iridium in the repos, as it's the only google-free Chromium-based browser. But since you reenable everything that is non-free, what is the point?

@faulesocke, does the template work?

**Comment by faulesocke** [comment]
@avoidr it worked back when I created it. Not sure about any options I choose there. I don't use this browser anymore since Firefox 57 came out.

**Pull request closed without merging**
