### PR TITLE
New package: btsync-2.0.105

### PR DESCRIPTION
**Pull request by JuhaniImberg**

### CODE REVIEW

**Comment by chneukirchen** [comment]
I think we are not allowed to redistribute this.

**Comment by tonkazoid** [comment]
alternative?
https://github.com/voidlinux/void-packages/tree/master/srcpkgs/syncthing

"Syncthing replaces proprietary sync and cloud services with something open, trustworthy and decentralized."

**Comment by JuhaniImberg** [comment]
So I changed the package to work like `chromium-pepper-flash`, it downloads and installs the program only as an post-install hook so you would be redistributing just an installation script.

@tonkazoid I would use that but I need support for Windows Phone, otherwise it looks way better.

**Comment by Gottox** [comment]
INSTALL and REMOVE are missing newline at the end, otherwise looks reasonable too me.

**Pull request merged**
