### PR TITLE
New package: partclone-utils

### PR DESCRIPTION
**Pull request by cr6git**

### CODE REVIEW

**Comment by cr6git** [comment]
Does not build on musl.

**Comment by Vaelatern** [comment]
If I had twenty minutes for this, I'd look at the file `sysdep_posix.c:82:1: error: conflicting types for 'posix_close'` and see if there is a `#ifdef` that guards this functionality.

**Comment by Vaelatern** [comment]
+1 @cr6git for letting it stay not building on musl. makes next steps easier to see.

**Comment by cr6git** [comment]
I no longer have time to work on this, sorry. 
I must take care of my real life.

**Pull request closed without merging**
