### PR TITLE
New package: dot-xsession-0.1-1.

### PR DESCRIPTION
**Pull request by wagnerflo**
As discussed with @the-maldridge in #6785 this packages adds a .desktop-file in `/usr/share/xsessions` as well as a shell-script in `/usr/libexec` to make it possible to start the session provided in a user's `~/.xsession`.

### CODE REVIEW

**Comment by wagnerflo** [comment]
Package name is up for discussion. I couldn't come up with anything better at the moment...

**Comment by the-maldridge** [comment]
This looks okay, can you fix the xlint errors and push again?

**Comment by wagnerflo** [comment]
Here you go! I should probably get my emacs to switch to tab-indentation for template-files automatically... :)

**Comment by the-maldridge** [comment]
This should be `noarch=yes` since its just shell scripts.  I'm satisfied with it but I'd like a second opinion from @Vaelatern @Duncaen @ebfe or @chneukirchen before I merge this.

**Comment by wagnerflo** [comment]
Oh right! Here you go...

**Comment by wagnerflo** [comment]
Thanks!

**Pull request closed without merging**
