### PR TITLE
New package: ulatencyd

### PR DESCRIPTION
**Pull request by thypon**

### CODE REVIEW

**Comment by thypon** [comment]
@xtraeme i don't understand why this can be built without problem on i686, x86_64 and x86_64-musl on my machine but not on buildbot.

I have problem with luaposix on other archs.

**Comment by xtraeme** [comment]
Looks ok

**Comment by xtraeme** [comment]
Please fix the build issue before merging.

**Comment by thypon** [comment]
I can't reproduce the bug in the buildbots. As i said it builds w/o errors on i686, x86_64 and x86_64-musl.

**Pull request merged**
