### PR TITLE
alsa-tools: add missing dependency of hwmixvolume

### PR DESCRIPTION
**Pull request by Chocimier**

### CODE REVIEW

**Comment by Vaelatern** [comment]
This is misleading naming, no provided evidence that this is necessary.

**Comment by Vaelatern** [comment]
This is misleading naming, no provided evidence that this is necessary.

**Comment by Chocimier** [comment]
How is it misleading?

 From hwmixvolume/README:
This tool requires Python, pygtk, and alsa-pyton 1.0.22 or later.

also:
% grep import /usr/bin/hwmixvolume
import gobject, gtk
from pyalsa import alsacard, alsahcontrol

**Comment by Vaelatern** [comment]
Merged. The phrasing of the commit message made it sound like I'd see a patch depending on `hwmixvolume`

**Pull request closed without merging**
