### PR TITLE
lemonbar: add xft and xft_monitor build options

### PR DESCRIPTION
**Pull request by jaagr**

### CODE REVIEW

**Comment by Vaelatern** [comment]
Only one commit is necessary.

**Comment by chneukirchen** [comment]
and please write an informative subject like "lemonbar: add xft and xft_monitor build options".

**Comment by chneukirchen** [comment]
also, is xtraeme ok with you adopting the package?

**Comment by jaagr** [comment]
@chneukirchen I never asked him, but I reverted the maintainer change

**Pull request closed without merging**
