### PR TITLE
cmst: update to 2017.03.18

### PR DESCRIPTION
**Pull request by cr6void**

### CODE REVIEW

**Comment by cr6void** [comment]
Oops... I don't know why the build failed only with aarch64-musl ?

**Comment by cr6void** [comment]
Could it be related to this kind of problem: [#5762](https://github.com/voidlinux/void-packages/pull/5762) ? 

Regards.

**Comment by cr6void** [comment]
Look at [this error](https://travis-ci.org/voidlinux/void-packages/jobs/205580486#L697) from the **connman** build by @ackalker , 

Now look at [the error](https://travis-ci.org/voidlinux/void-packages/jobs/219975872#L733) from the **cmst** build by me... 

The two errors look similar, or I am wrong ? 

Regards.

**Comment by Gottox** [comment]
Classical musl vs glibc error.

musl uses its own defines for kernel structs whereas glibc uses kernel-headers directly. This error can occur when an header from kernel-headers is included in userspace software. We had this issue with NetworkManager too. If you like you can fix it, but this PR is ready to merge nontheless.

**Comment by cr6void** [comment]
No, I don't know how to fix it. 
There is nothing more I can do here, sorry. 

Thank you.

**Comment by Gottox** [comment]
We may (or may not) fix that upstream. 😅

**Pull request merged**
