### PR TITLE
numix-themes: build it instead of getting it pre-built.

### PR DESCRIPTION
**Pull request by jcjordyn130**
Upstream doesn't provide pre-built tarballs anymore it seems.

### CODE REVIEW

**Comment by Vaelatern** [comment]
revbump

**Comment by Vaelatern** [comment]
remove fetch build style and the tar/cd commands.
do_install should just be 2 lines.

**Comment by liwakura** [comment]
@jcjordyn130 are you still on this?

**Comment by jcjordyn130** [comment]
@liwakura yes.

**Comment by jcjordyn130** [comment]
Hopefully this is correct this time.

**Comment by the-maldridge** [comment]
@jcjordyn130 This looks good to merge but your patch no longer applies.  Please rebase your changes onto master and mention me when you have done so.

**Comment by jcjordyn130** [comment]
oops, I think I rebased way too many commits.

**Comment by jcjordyn130** [comment]
@the-maldridge ping pong, the patch applies now

**Comment by the-maldridge** [comment]
Uhh, this doesn't build.  Care to try again?

**Comment by jcjordyn130** [comment]
oops I forgot do_install(), it should be building now.

**Pull request closed without merging**
