### PR TITLE
boost: update to 1.62.0. (soname bump)

### PR DESCRIPTION
**Pull request by ebfe**
Depends on ~~#3976~~ ~~#3975~~ ~~#3974~~. Build tested everything on x86_64. ~~cegui currently  broken by the bump.~~

### CODE REVIEW

**Comment by ebfe** [comment]
Rebased. Disabled PyCEGUI as it doesn't build with with boost-1.60. Since currently nothing depends on cegui this shouldn't be a problem? (@pullmoll).

**Comment by ebfe** [comment]
Postponing for a while since 1.61 is just around the corner.

**Comment by pullmoll** [comment]
I just now saw the question regarding cegui: no, currently packages use cegui07 and won't (yet) work with the 0.8 branch.

**Comment by ebfe** [comment]
I reenabled it again since the build failure was fixed by a recent cegui update.

**Comment by ebfe** [comment]
kicad and swiften are currently broken with 1.61.

**Comment by ebfe** [comment]
Still waiting for a kicad fix.

**Comment by ebfe** [comment]
rebased, kicad builds now too

**Comment by ebfe** [comment]
Updated to 1.62.0

broken:

- [ ] facter
- [ ] kicad
- [ ] mongodb
- [ ] lyx

**Comment by asergi** [comment]
Patches:
- mongodb: http://cvsweb.netbsd.org/bsdweb.cgi/~checkout~/pkgsrc/databases/mongodb/patches/patch-src_mongo_db_fts_unicode_string.cpp?rev=1.1
- leatherman (that makes facter to fail): https://patch-diff.githubusercontent.com/raw/puppetlabs/leatherman/pull/210.patch

Only kicad left.

**Comment by ebfe** [comment]
Thanks @asergi. Updated.

**Comment by ebfe** [comment]
kicad maybe fixed too...

**Comment by ebfe** [comment]
index: added `kicad-4.0.4_3' (x86_64).

**Comment by kachsheev** [comment]
> `boost-1.62.0_1 (update) breaks installed pkg 'libreoffice-5.2.2.2_4'`

Is it normal?

**Comment by ebfe** [comment]
@kachsheev see #5012

**Comment by ebfe** [comment]
0cf2a7e827f36c7bc0a29ffcb540840365cbc1f6

**Pull request closed without merging**
