### PR TITLE
Rakudo

### PR DESCRIPTION
**Pull request by Vaelatern**
Fewer pieces of magic. `panda` and `rakudo-star` are not yet correct or building, can you help @xaduha ?

Makes the mess of changes in #3925 not necessary, and fixes the templates to comply more with the rest of the package repo.

Also features perl 6 on more platforms than before.

Review very welcome.

### CODE REVIEW

**Comment by xaduha** [comment]
I value practical things over doing everything perfectly, as long as it works it's fine with me. I'm happy with the way I did it, it builds, it works. I don't want to spend much time on it, but if anyone want to take over maintaining this package - I'll give it up.

**Comment by Vaelatern** [comment]
If you can suggest changes to this version of the panda and rakudo-star templates, that would be great.

**Comment by Vaelatern** [comment]
I mostly disagree that the changes introduced in 733e08f were correct or necessary.

**Comment by xaduha** [comment]
I'd be glad not make these changes, but that was the only solution that worked properly. Do you actually use Rakudo Star or you're just talking as a mantainer of void-packages repo? The hope is that proper changes would be made upstream and things would work as they were before, but until that happens this is what I came up with.

**Comment by Vaelatern** [comment]
What broke upstream that necessitated a wholly different installation method?

**Comment by xaduha** [comment]
I have a vague theory, but I don't really care what broke it upstream. I'm not interested in trying it again until a new version comes out. A previous PR (2016.02) with those changes is already included in void-packages, my 2016.03 PR of rakudo-star is just an increment with 3 dependencies included only once where they actually needed, which is MoarVM. I'm not against improving it later.

**Comment by Vaelatern** [comment]
Every single time you do `makedepends="${hostmakedepends}"` it is wrong by definition. Both hostmakedepends and makedepends are present on the system when the package is being built. One is there for the cross-compiled arch (and that brings in `-devel` packages) and the other is the programs that just need to be run, like `perl` or `git`.

**Comment by xaduha** [comment]
If it's a big deal, then I'll change it, no problem. Anything else?

**Comment by Vaelatern** [comment]
I think the first three sets of changes in this PR are correct, at the very least. Can you test that they work as you expect? I am willing to say panda and rakudo-star don't need the sweeping changes I made, but I believe the first three templates to be as necessary.

**Comment by xaduha** [comment]
I've updated my PR.

**Comment by xtraeme** [comment]
Already pushed

**Pull request closed without merging**
