### PR TITLE
New package: git-crypt-0.5.0

### PR DESCRIPTION
**Pull request by cobaugh**

### CODE REVIEW

**Comment by ebfe** [comment]
Please add the manpage/README to the package.

**Comment by cobaugh** [comment]
Added man page and other docs, and now the build is failing on some archs. Not sure what's up with that.

**Comment by ebfe** [comment]
> Added man page and other docs, and now the build is failing on some archs. Not sure what's up with that.

```make: xsltproc: Command not found```

This needs to go into `hostmakedepends` instead of `makepends`.

**Comment by cobaugh** [comment]
Aha. Got it.

**Pull request merged**
