### PR TITLE
gopass: update to 1.6.9.

### PR DESCRIPTION
**Pull request by SevereOverfl0w**

### CODE REVIEW

**Comment by newbluemoon** [comment]
Creating the cross-built packages has to fail because you use the target built `gopass` binary to create the completions. Maybe add `gopass` to `hostmakedepends` and make `post_build()` use the host `gopass`?

**Comment by newbluemoon** [comment]
The created completion scripts all have as a first line

    Warning: GPG not found: no gpg binary found

So I guess `gnupg2` should also be in `hostmakedepends`.

Just tested adding `gopass` to `hostmakedepends`: if it already exists for the hosts everything works fine, but if not xbps-src seems to be trapped in a circle when checking the dependencies.

**Comment by SevereOverfl0w** [comment]
The other option is to mark this as `nocross`.

**Comment by newbluemoon** [comment]
But wouldn’t `nocross` be a bit too much, because `gopass` itself can be cross-built without any problem; just generating the shell completion scripts poses a problem?

**Comment by SevereOverfl0w** [comment]
Perhaps.

I'm reluctant to perform this in INSTALL because we lose some benefits of being a packaged file to xbps.

The gopass team have decided that completion files are part of the distribution from their perspective, and that running gopass is the way to complete the distribution. In that sense, we are unable to create a full distribution in a cross-compatible way.

**Comment by newbluemoon** [comment]
> I'm reluctant to perform this in INSTALL because we lose some benefits of being a packaged file to xbps.

That’s what I was thinking, too; just mentioned it as an option.

But what about using a `$CROSS_BUILD` branch to only generate the completion scripts when compiling natively?

**Pull request closed without merging**
