### PR TITLE
boswars: fix cross compilation

### PR DESCRIPTION
**Pull request by newbluemoon**
The cross-compiler wasn’t respected.

### CODE REVIEW

**Comment by Vaelatern** [comment]
You added `glu-devel` and `python`, did that alter the build?

**Comment by Vaelatern** [comment]
`python` at least I can see being used.

**Comment by newbluemoon** [comment]
I don’t think so: `SDL` is built for i686*/x86_64* with option ‘opengl’ per default which pulls in `glu-devel`. On all other architectures `SDL` is built without that option (per default). When cross-compiling `boswars` an SDL include which includes `GL/glu.h` is used (but I don’t know if boswars makes use of glu at all). Adding `glu-devel` solves this. In my opinion that doesn’t alter the build.

As for `python`: the build system is a python script. It is pulled in via a dependency, but cannot be used when cross-compiling, of course. :)

And I thought a `$CROSS_BUILD` branch isn’t necessary, because in a native build those packages are there anyway (via dependencies).

**Comment by Vaelatern** [comment]
Excellent.

**Comment by newbluemoon** [comment]
I’ll be more verbose next time :)

**Pull request merged**
