### PR TITLE
gegl3: addition of lib package to support gimp 2.9.x

### PR DESCRIPTION
**Pull request by antonio-malcolm**
Added the lib package to gegl3 as a dependency for Gimp v2.9.x, for which I also have a template.

### CODE REVIEW

**Comment by Gottox** [comment]
* use the commit message format as described at https://github.com/voidlinux/void-packages/blob/master/CONTRIBUTING.md#committing-your-changes
* increase the revision of this package.

**Comment by antonio-malcolm** [comment]
Done.

**Comment by Gottox** [comment]
okay, after looking into the package: What's the reason for the split?

**Comment by Gottox** [comment]
Also note: this change will break all packages using gegl3, including gegl3-devel.

**Comment by antonio-malcolm** [comment]
Wait- how is this going to break all packages using gegl3?

**Comment by antonio-malcolm** [comment]
How does this not break with other packages which have lib subpackages?
What would be the preferred approach?

**Comment by Gottox** [comment]
A rebuild of all dependants would fix this situation. But I don't think this is worth the effort. Just depend on gegl3-devel in the template and you'll be fine.

**Comment by antonio-malcolm** [comment]
Ok, that would mean it will need it in both hostmakedepends and depends.
Otherwise, simple is my preferred approach to, thanks. 
Will close this pull request and delete the branch.

**Pull request closed without merging**
