### PR TITLE
New package: bs1770gain-0.4.12

### PR DESCRIPTION
**Pull request by autrimpo**
BS1770GAIN is a loudness scanner compliant with ITU-R BS.1770 and its flavors EBU R128, ATSC A/85, and ReplayGain 2.0. It helps normalizing the loudness of audio and video files to the same level.

### CODE REVIEW

**Comment by the-maldridge** [comment]
@autrimpo please remove or squash fab7d28 and mention me once you have done so.

**Comment by autrimpo** [comment]
@the-maldridge done, the commit was there just to show that rebuilding sox fixes the failing build

**Comment by autrimpo** [comment]
@the-maldridge could you have a look at this?

**Comment by the-maldridge** [comment]
Please rebase on top of an updated master to verify this builds correctly.  I'll take another look tonight (~7 hours) and merge then if all looks good.  The template is fine, I just need updated test results.

**Comment by autrimpo** [comment]
Done.

**Pull request closed without merging**
