### PR TITLE
New package: font-fontin-1

### PR DESCRIPTION
**Pull request by thypon**

### CODE REVIEW

**Comment by beefcurtains** [comment]
This isn't compatible with freedoms 2 and 3, look at the EULA.

**Comment by dominikh** [comment]
While "freedom 2" (the freedom to study and change the program) is irrelevant for the nonfree repo, freedom 3 is very relevant indeed.

Excerpt from the EULA for the sake of documentation:

> This font may not be distributed or sold -not online nor on any media- without my permission

**Comment by beefcurtains** [comment]
You are counting the freedoms wrong, the first freedom is 0.

**Comment by thypon** [comment]
Thanks, didn't saw them. Closing for now.

**Pull request closed without merging**
