### PR TITLE
linux4.9: update to 4.9.105.

### PR DESCRIPTION
**Pull request by cr6git**
[#13450](https://github.com/voidlinux/void-packages/issues/13450)

And this is new for aarch64:
````
Harden the branch predictor against aliasing attacks (HARDEN_BRANCH_PREDICTOR) [Y/n/?] (NEW) y
````

### CODE REVIEW

**Comment by cr6git** [comment]
New for aarch64:
````
Cortex-A55: 1024718: Update of DBM/AP bits without break before make might result in incorrect update (ARM64_ERRATUM_1024718) [Y/n/?] (NEW) y
````

**Comment by Piraty** [comment]
Maybe it's useful to contribute this config chage to all kernels supporting it, in a separate PR for example?

**Comment by cr6git** [comment]
Updated.

**Comment by cr6git** [comment]
Updated to 4.9.105.

**Comment by cr6git** [comment]
Because of commit [1e5bf8a](https://github.com/voidlinux/void-packages/commit/1e5bf8ac7fcce3e4a3e54867921a9a0cae558fe6) now my branch has conflicts. :disappointed:

**Pull request closed without merging**
