### PR TITLE
libgit2: update to 0.26.0. (soname bump)

### PR DESCRIPTION
**Pull request by ebfe**
ktexteditor (#6789), libgit2-glib broken

### CODE REVIEW

**Comment by Vaelatern** [comment]
`libgit2-glib` broke last time too, iirc

**Comment by ebfe** [comment]
It always brakes when there are API changes.

**Comment by chneukirchen** [comment]
IIRC we decided nothing uses libgit2-glib and it can be removed.

Else, good to merge.

**Comment by ebfe** [comment]
> IIRC we decided nothing uses libgit2-glib and it can be removed.

Unfortunately no longer true:
```
$ xrevshlib libgit2-glib
gitg
gnome-builder
```

**Comment by ebfe** [comment]
ktexteditor, libgit2-glib fixed. cargo broken...

**Comment by chneukirchen** [comment]
Merged manually.

**Pull request closed without merging**
