### PR TITLE
New package: ferm-2.3

### PR DESCRIPTION
**Pull request by jnbr**
I removed the systemd unit file from the installer but I did not include a runit script.
I don't think that a runit script makes sense, beacause people probably want to start their iptable rules before setting up the network, so adding it to the dhcpcd script should be sufficient.

### CODE REVIEW

**Comment by jnbr** [comment]
I missed to add perl as a dependency. Now fixed.

**Comment by Vaelatern** [comment]
I think perl should be added as a `hostmakedepends`

**Comment by jnbr** [comment]
You're right. I added perl to `hostmakepends` as well.

**Comment by jnbr** [comment]
I got the last commit wrong and missed to add the template file, so perl was still missing in `hostmakedepends`. 
@Vaelatern can you please check the package again?

**Comment by jnbr** [comment]
updated from 2.3 to 2.3.1

**Pull request merged**
