### PR TITLE
Libedit

### PR DESCRIPTION
**Pull request by thypon**
Shameless enable libedit instead of readline.

### CODE REVIEW

**Comment by pullmoll** [comment]
`s;SIGCLD;SIGCHLD;` for musl

**Comment by pullmoll** [comment]
BTW: SIGCHLD is ok for glibc as well, so no need to do it just for musl.
Ideally a patch to suggest for upstream would be fine :*)

**Comment by xtraeme** [comment]
And the reason to use libedit is?

**Comment by Gottox** [comment]
Maybe it's a war on GPL/GNU software?

**Comment by thypon** [comment]
no

**Comment by chneukirchen** [comment]
NACK on rc, it breaks filename completion iirc.

**Comment by xtraeme** [comment]
There's no need to change this for a gratuitous breakage just because readline has some issues.

**Pull request closed without merging**
