### PR TITLE
firefox-esr: update to 52.2.0

### PR DESCRIPTION
**Pull request by asergi**

### CODE REVIEW

**Comment by cr6git** [comment]
````
case "$XBPS_TARGET_MACHINE" in
	x86_64*) build_options_default+=" rust";;
esac
````

@asergi Please could you explain why you enabled rust only for x86_64* ? Not available for 32-bit ? Regards.

**Comment by asergi** [comment]
d08658e9105ad476925f29b0d769862e71bfa7cd

**Comment by cr6git** [comment]
ok. and what about @jnbr 's comment in [#13016](https://github.com/voidlinux/void-packages/pull/13016) ?

**Comment by cr6git** [comment]
I found the solution.

**Pull request merged**
